with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1023px;\" coordsize=\"950,1023\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:1023px;\">");
write("<img id=\"img1\" src=\"../img/SEA3E20R31100000000YDAD71.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1023px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:291px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR FRAME<br>STIFFENER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:669px;top:41px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>15 mm (0.6in.)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:822px;top:15px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR FLOOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:816px;top:181px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR FLOOR<br>CROSS-MEMBER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:651px;top:296px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR FLOOR<br>CROSS-MEMBER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:644px;top:349px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Cut line.<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:633px;top:445px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>JUCK-UP STIFFENER<br>SUPPORT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:633px;top:501px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR FLOOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:147px;top:36px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Cut line.<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:16px;top:405px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR FRAME<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:315px;top:301px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>[X]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:198px;top:647px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>[VIEW: X]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:371px;top:967px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR FLOOR<br>CROSS-MEMBER<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}