with(document) {
write("<v:group id=\"group14\" class=\"drag\" style=\"position:relative; width:950px; height:836px;\" coordsize=\"950,836\">");
write("<v:rect id=\"rect14\"class=\"drag\"  style=\"width:950px;height:836px;\">");
write("<img id=\"img14\" src=\"../img/SEA3ENBJ54230100000EAAD16.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:836px;border-color:#ffffff\">");
write("<p id=\"p14_1\" class=\"drag\" style=\"position:absolute;left:645px;top:542px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Power tailgate control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p14_2\" class=\"drag\" style=\"position:absolute;left:638px;top:303px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(With power tailgate)<br></b></nobr>");
write("</p>");
write("<p id=\"p14_3\" class=\"drag\" style=\"position:absolute;left:638px;top:332px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(With power tailgate)<br></b></nobr>");
write("</p>");
write("<p id=\"p14_4\" class=\"drag\" style=\"position:absolute;left:638px;top:256px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left rear fog light<br></b></nobr>");
write("</p>");
write("<p id=\"p14_5\" class=\"drag\" style=\"position:absolute;left:638px;top:239px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(With power tailgate)<br></b></nobr>");
write("</p>");
write("<p id=\"p14_6\" class=\"drag\" style=\"position:absolute;left:638px;top:267px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(With power tailgate)<br></b></nobr>");
write("</p>");
write("<p id=\"p14_7\" class=\"drag\" style=\"position:absolute;left:353px;top:598px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>AB<br></b></nobr>");
write("</p>");
write("<p id=\"p14_8\" class=\"drag\" style=\"position:absolute;left:327px;top:598px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p14_9\" class=\"drag\" style=\"position:absolute;left:353px;top:541px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>AB<br></b></nobr>");
write("</p>");
write("<p id=\"p14_10\" class=\"drag\" style=\"position:absolute;left:327px;top:541px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p14_11\" class=\"drag\" style=\"position:absolute;left:353px;top:484px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>AB<br></b></nobr>");
write("</p>");
write("<p id=\"p14_12\" class=\"drag\" style=\"position:absolute;left:327px;top:484px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p14_13\" class=\"drag\" style=\"position:absolute;left:353px;top:291px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>AB<br></b></nobr>");
write("</p>");
write("<p id=\"p14_14\" class=\"drag\" style=\"position:absolute;left:327px;top:291px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p14_15\" class=\"drag\" style=\"position:absolute;left:353px;top:198px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>AB<br></b></nobr>");
write("</p>");
write("<p id=\"p14_16\" class=\"drag\" style=\"position:absolute;left:327px;top:198px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p14_17\" class=\"drag\" style=\"position:absolute;left:353px;top:141px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>AB<br></b></nobr>");
write("</p>");
write("<p id=\"p14_18\" class=\"drag\" style=\"position:absolute;left:327px;top:141px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p14_19\" class=\"drag\" style=\"position:absolute;left:353px;top:84px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>AB<br></b></nobr>");
write("</p>");
write("<p id=\"p14_20\" class=\"drag\" style=\"position:absolute;left:327px;top:84px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p14_21\" class=\"drag\" style=\"position:absolute;left:47px;top:727px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G705<br></b></nobr>");
write("</p>");
write("<p id=\"p14_22\" class=\"drag\" style=\"position:absolute;left:638px;top:613px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Power tailgate buzzer<br></b></nobr>");
write("</p>");
write("<p id=\"p14_23\" class=\"drag\" style=\"position:absolute;left:638px;top:320px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Rear window deffoger<br></b></nobr>");
write("</p>");
write("<p id=\"p14_24\" class=\"drag\" style=\"position:absolute;left:638px;top:228px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left back−up light<br></b></nobr>");
write("</p>");
write("<p id=\"p14_25\" class=\"drag\" style=\"position:absolute;left:638px;top:42px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left taillight<br></b></nobr>");
write("</p>");
write("<p id=\"p14_26\" class=\"drag\" style=\"position:absolute;left:638px;top:292px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>License plate light<br></b></nobr>");
write("</p>");
write("<p id=\"p14_27\" class=\"drag\" style=\"position:absolute;left:638px;top:199px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Cargo light control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p14_28\" class=\"drag\" style=\"position:absolute;left:638px;top:142px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Data link connector (DLC)<br></b></nobr>");
write("</p>");
write("<p id=\"p14_29\" class=\"drag\" style=\"position:absolute;left:638px;top:85px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Tailgate closer unit<br></b></nobr>");
write("</p>");
write("<p id=\"p14_30\" class=\"drag\" style=\"position:absolute;left:60px;top:791px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>AB<br></b></nobr>");
write("</p>");
write("<p id=\"p14_31\" class=\"drag\" style=\"position:absolute;left:81px;top:790px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p14_32\" class=\"drag\" style=\"position:absolute;left:88px;top:791px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Power tailgate wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p14_33\" class=\"drag\" style=\"position:absolute;left:638px;top:28px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left rear turn signal light<br></b></nobr>");
write("</p>");
write("<p id=\"p14_34\" class=\"drag\" style=\"position:absolute;left:47px;top:420px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G704<br></b></nobr>");
write("</p>");
write("<p id=\"p14_35\" class=\"drag\" style=\"position:absolute;left:327px;top:27px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p14_36\" class=\"drag\" style=\"position:absolute;left:353px;top:27px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>AB<br></b></nobr>");
write("</p>");
write("<p id=\"p14_37\" class=\"drag\" style=\"position:absolute;left:638px;top:213px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left inner taillight<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}