with(document) {
write("<v:group id=\"group8\" class=\"drag\" style=\"position:relative; width:950px; height:1063px;\" coordsize=\"950,1063\">");
write("<v:rect id=\"rect8\"class=\"drag\"  style=\"width:950px;height:1063px;\">");
write("<img id=\"img8\" src=\"../img/SEA3ELBJ54230100000EAAD60.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1063px;border-color:#ffffff\">");
write("<p id=\"p8_1\" class=\"drag\" style=\"position:absolute;left:674px;top:369px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p8_2\" class=\"drag\" style=\"position:absolute;left:334px;top:369px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_3\" class=\"drag\" style=\"position:absolute;left:362px;top:369px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p8_4\" class=\"drag\" style=\"position:absolute;left:334px;top:312px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_5\" class=\"drag\" style=\"position:absolute;left:362px;top:312px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p8_6\" class=\"drag\" style=\"position:absolute;left:645px;top:312px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Seat heater relay<br></b></nobr>");
write("</p>");
write("<p id=\"p8_7\" class=\"drag\" style=\"position:absolute;left:334px;top:254px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_8\" class=\"drag\" style=\"position:absolute;left:362px;top:254px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p8_9\" class=\"drag\" style=\"position:absolute;left:645px;top:255px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Auto leveling unit<br></b></nobr>");
write("</p>");
write("<p id=\"p8_10\" class=\"drag\" style=\"position:absolute;left:645px;top:198px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Navigation unit<br></b></nobr>");
write("</p>");
write("<p id=\"p8_11\" class=\"drag\" style=\"position:absolute;left:362px;top:197px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p8_12\" class=\"drag\" style=\"position:absolute;left:334px;top:197px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_13\" class=\"drag\" style=\"position:absolute;left:645px;top:155px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Passenger's seat heater switch<br></b></nobr>");
write("</p>");
write("<p id=\"p8_14\" class=\"drag\" style=\"position:absolute;left:645px;top:141px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Driver's seat heater switch<br></b></nobr>");
write("</p>");
write("<p id=\"p8_15\" class=\"drag\" style=\"position:absolute;left:334px;top:140px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_16\" class=\"drag\" style=\"position:absolute;left:362px;top:140px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p8_17\" class=\"drag\" style=\"position:absolute;left:362px;top:83px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p8_18\" class=\"drag\" style=\"position:absolute;left:334px;top:83px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_19\" class=\"drag\" style=\"position:absolute;left:645px;top:84px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Ashtray light<br></b></nobr>");
write("</p>");
write("<p id=\"p8_20\" class=\"drag\" style=\"position:absolute;left:69px;top:569px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p8_21\" class=\"drag\" style=\"position:absolute;left:87px;top:567px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p8_22\" class=\"drag\" style=\"position:absolute;left:95px;top:569px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Dashboard wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p8_23\" class=\"drag\" style=\"position:absolute;left:645px;top:26px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Cigarette lighter<br></b></nobr>");
write("</p>");
write("<p id=\"p8_24\" class=\"drag\" style=\"position:absolute;left:54px;top:512px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G506<br></b></nobr>");
write("</p>");
write("<p id=\"p8_25\" class=\"drag\" style=\"position:absolute;left:334px;top:26px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_26\" class=\"drag\" style=\"position:absolute;left:362px;top:26px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}