with(document) {
write("<v:group id=\"group3\" class=\"drag\" style=\"position:relative; width:475px; height:465px;\" coordsize=\"475,465\">");
write("<v:rect id=\"rect3\"class=\"drag\"  style=\"width:475px;height:465px;\">");
write("<img id=\"img3\" src=\"../img/SEA3E00R00000000000YCAD03.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:465px;border-color:#ffffff\">");
write("<p id=\"p3_1\" class=\"drag\" style=\"position:absolute;left:159px;top:163px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Forward<br></b></nobr>");
write("</p>");
write("<p id=\"p3_2\" class=\"drag\" style=\"position:absolute;left:327px;top:162px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Forward<br></b></nobr>");
write("</p>");
write("<p id=\"p3_3\" class=\"drag\" style=\"position:absolute;left:39px;top:173px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Forward<br></b></nobr>");
write("</p>");
write("<p id=\"p3_4\" class=\"drag\" style=\"position:absolute;left:390px;top:43px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Black Dot<br></b></nobr>");
write("</p>");
write("<p id=\"p3_5\" class=\"drag\" style=\"position:absolute;left:39px;top:364px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Detail<br>Sketch<br></b></nobr>");
write("</p>");
write("<p id=\"p3_6\" class=\"drag\" style=\"position:absolute;left:38px;top:16px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Black dots: Measuring point<br></b></nobr>");
write("</p>");
write("<p id=\"p3_7\" class=\"drag\" style=\"position:absolute;left:266px;top:407px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p3_8\" class=\"drag\" style=\"position:absolute;left:355px;top:410px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}