with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:351px;\" coordsize=\"950,351\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:351px;\">");
write("<img id=\"img1\" src=\"../img/SEA3E00J34600000000CAAD61.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:351px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:164px;top:21px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Combination<br>Switch Control<br>Unit<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:348px;top:35px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:452px;top:29px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Relay Control<br>Module<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:592px;top:28px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Door Multiplex<br>Control Unit<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:728px;top:28px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Climate Control<br>Unit<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:100px;top:192px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Gauge Control<br>Module<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:260px;top:199px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ECM/PCM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:417px;top:199px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VSA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:534px;top:199px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Navigation<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:742px;top:158px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Rain Sensor<br>(With Auto<br>Wiper)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:377px;top:144px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>B-CAN 33.33 kbps<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:310px;top:306px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>F-CAN 500 kbps<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}