with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:952px; height:607px;\" coordsize=\"952,607\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:952px;height:607px;\">");
write("<img id=\"img1\" src=\"../img/SEA3EJ4J10311113151BBAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:952px;height:607px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:16px;top:19px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>No. 1 Display<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:496px;top:19px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>No. 2 Display<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:16px;top:115px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>No. 3 Display<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:496px;top:115px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>No. 4 Display<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:16px;top:210px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>No. 5 Display<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:496px;top:210px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>No. 6 Display<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:16px;top:306px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>No. 7 Display<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:496px;top:307px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>No. 8 Display<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:16px;top:402px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>No. 9 Display<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:496px;top:402px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>No. 10 Display<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:16px;top:498px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>No. 11 Display<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:496px;top:498px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>No. 12 Display<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}