with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\" coordsize=\"950,1103\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:1103px;\">");
write("<img id=\"img1\" src=\"../img/SEA3E20R51100000000YDAD09.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:358px;top:422px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SIDE SILL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:318px;top:525px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OUTRIGGER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:538px;top:407px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SIDE SILL<br>EXTENSION<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:500px;top:518px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SIDE SILL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:630px;top:398px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SIDE SILL<br>EXTENSION<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:752px;top:507px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR FRAME<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:806px;top:530px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR FLOOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:805px;top:593px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MIDDLE<br>CROSS-MEMBER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:806px;top:633px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MIDDLE<br>CROSS-MEMBER<br>STIFFENER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:707px;top:684px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT FLOOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:749px;top:730px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT FLOOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:711px;top:815px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FLOOR TUNNEL<br>STIFFENER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:683px;top:854px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CENTER ANCHOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:683px;top:927px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT FLOOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:583px;top:967px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CROSS-MEMBER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:591px;top:1060px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT FLOOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:458px;top:977px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT FLOOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:459px;top:1043px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT TUNNEL<br>STIFFENER B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:300px;top:980px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT FLOOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:396px;top:1030px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FLOOR<br>FRAME<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:290px;top:1074px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SIDE FRAME REAR END<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:157px;top:1073px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OUTRIGGER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:85px;top:947px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DASHBOARD LOWER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:65px;top:1053px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT FLOOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:48px;top:914px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DASHBOARD LOWER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:190px;top:596px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT<br>FLOOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:83px;top:801px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT FLOOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:101px;top:692px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DASHBOARD<br>LOWER PATCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:80px;top:597px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DASHBOARD<br>LOWER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:209px;top:478px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OUTRIGGER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:100px;top:451px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SIDE FRAME<br>REAR END<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}