with(document) {
write("<v:group id=\"group6\" class=\"drag\" style=\"position:relative; width:950px; height:543px;\" coordsize=\"950,543\">");
write("<v:rect id=\"rect6\"class=\"drag\"  style=\"width:950px;height:543px;\">");
write("<img id=\"img6\" src=\"../img/SEA3ENBA20300000000CAAD18.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:543px;border-color:#ffffff\">");
write("<p id=\"p6_1\" class=\"drag\" style=\"position:absolute;left:540px;top:15px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p6_2\" class=\"drag\" style=\"position:absolute;left:633px;top:46px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p6_3\" class=\"drag\" style=\"position:absolute;left:796px;top:174px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p6_4\" class=\"drag\" style=\"position:absolute;left:749px;top:129px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p6_5\" class=\"drag\" style=\"position:absolute;left:781px;top:375px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p6_6\" class=\"drag\" style=\"position:absolute;left:316px;top:493px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>26<br></b></nobr>");
write("</p>");
write("<p id=\"p6_7\" class=\"drag\" style=\"position:absolute;left:323px;top:453px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>27<br></b></nobr>");
write("</p>");
write("<p id=\"p6_8\" class=\"drag\" style=\"position:absolute;left:190px;top:433px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>29<br></b></nobr>");
write("</p>");
write("<p id=\"p6_9\" class=\"drag\" style=\"position:absolute;left:221px;top:464px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>28<br></b></nobr>");
write("</p>");
write("<p id=\"p6_10\" class=\"drag\" style=\"position:absolute;left:729px;top:451px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p6_11\" class=\"drag\" style=\"position:absolute;left:505px;top:518px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p6_12\" class=\"drag\" style=\"position:absolute;left:344px;top:503px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p6_13\" class=\"drag\" style=\"position:absolute;left:375px;top:482px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p6_14\" class=\"drag\" style=\"position:absolute;left:345px;top:470px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>25<br></b></nobr>");
write("</p>");
write("<p id=\"p6_15\" class=\"drag\" style=\"position:absolute;left:48px;top:331px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ENGINE<br>WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p6_16\" class=\"drag\" style=\"position:absolute;left:707px;top:497px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FLOOR WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p6_17\" class=\"drag\" style=\"position:absolute;left:735px;top:29px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DASHBOARD <br>WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p6_18\" class=\"drag\" style=\"position:absolute;left:791px;top:269px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>THROTTLE ACTUATOR<br>CONTROL MODULE<br>SUBHARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p6_19\" class=\"drag\" style=\"position:absolute;left:585px;top:32px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}