with(document) {
write("<v:group id=\"group2\" class=\"drag\" style=\"position:relative; width:950px; height:1068px;\" coordsize=\"950,1068\">");
write("<v:rect id=\"rect2\"class=\"drag\"  style=\"width:950px;height:1068px;\">");
write("<img id=\"img2\" src=\"../img/SEA3ENBA20300000000CAAD06.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1068px;border-color:#ffffff\">");
write("<p id=\"p2_1\" class=\"drag\" style=\"position:absolute;left:192px;top:62px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B11<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" class=\"drag\" style=\"position:absolute;left:252px;top:72px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" class=\"drag\" style=\"position:absolute;left:757px;top:90px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" class=\"drag\" style=\"position:absolute;left:844px;top:25px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>VTEC OIL <br>PRESSURE <br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" class=\"drag\" style=\"position:absolute;left:849px;top:390px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>MAP SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" class=\"drag\" style=\"position:absolute;left:192px;top:322px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A21<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" class=\"drag\" style=\"position:absolute;left:192px;top:376px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A30<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" class=\"drag\" style=\"position:absolute;left:192px;top:408px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A24<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" class=\"drag\" style=\"position:absolute;left:244px;top:333px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" class=\"drag\" style=\"position:absolute;left:245px;top:416px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" class=\"drag\" style=\"position:absolute;left:848px;top:575px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>TP SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" class=\"drag\" style=\"position:absolute;left:192px;top:553px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A29<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" class=\"drag\" style=\"position:absolute;left:757px;top:528px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" class=\"drag\" style=\"position:absolute;left:757px;top:558px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" class=\"drag\" style=\"position:absolute;left:245px;top:563px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" class=\"drag\" style=\"position:absolute;left:192px;top:810px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" class=\"drag\" style=\"position:absolute;left:252px;top:821px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" class=\"drag\" style=\"position:absolute;left:607px;top:396px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" class=\"drag\" style=\"position:absolute;left:192px;top:511px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A20<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" class=\"drag\" style=\"position:absolute;left:244px;top:522px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" class=\"drag\" style=\"position:absolute;left:192px;top:686px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_22\" class=\"drag\" style=\"position:absolute;left:253px;top:696px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_23\" class=\"drag\" style=\"position:absolute;left:815px;top:729px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>KNOCK SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_24\" class=\"drag\" style=\"position:absolute;left:757px;top:543px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_25\" class=\"drag\" style=\"position:absolute;left:824px;top:64px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_26\" class=\"drag\" style=\"position:absolute;left:836px;top:324px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_27\" class=\"drag\" style=\"position:absolute;left:835px;top:521px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_28\" class=\"drag\" style=\"position:absolute;left:245px;top:386px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_29\" class=\"drag\" style=\"position:absolute;left:757px;top:696px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_30\" class=\"drag\" style=\"position:absolute;left:642px;top:663px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>6P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_31\" class=\"drag\" style=\"position:absolute;left:818px;top:903px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>VTC OIL CONTROL<br>SOLENOID VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_32\" class=\"drag\" style=\"position:absolute;left:730px;top:610px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p2_33\" class=\"drag\" style=\"position:absolute;left:730px;top:254px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p2_34\" class=\"drag\" style=\"position:absolute;left:192px;top:167px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B6<br></b></nobr>");
write("</p>");
write("<p id=\"p2_35\" class=\"drag\" style=\"position:absolute;left:253px;top:177px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_36\" class=\"drag\" style=\"position:absolute;left:571px;top:387px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_37\" class=\"drag\" style=\"position:absolute;left:192px;top:82px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>VTPSW<br></b></nobr>");
write("</p>");
write("<p id=\"p2_38\" class=\"drag\" style=\"position:absolute;left:192px;top:188px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>VTS<br></b></nobr>");
write("</p>");
write("<p id=\"p2_39\" class=\"drag\" style=\"position:absolute;left:192px;top:342px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>VCC1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_40\" class=\"drag\" style=\"position:absolute;left:192px;top:393px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>MAP<br></b></nobr>");
write("</p>");
write("<p id=\"p2_41\" class=\"drag\" style=\"position:absolute;left:192px;top:425px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SG1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_42\" class=\"drag\" style=\"position:absolute;left:192px;top:530px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>VCC2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_43\" class=\"drag\" style=\"position:absolute;left:192px;top:572px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>TPS<br></b></nobr>");
write("</p>");
write("<p id=\"p2_44\" class=\"drag\" style=\"position:absolute;left:192px;top:707px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>KS<br></b></nobr>");
write("</p>");
write("<p id=\"p2_45\" class=\"drag\" style=\"position:absolute;left:192px;top:829px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>VTC<br></b></nobr>");
write("</p>");
write("<p id=\"p2_46\" class=\"drag\" style=\"position:absolute;left:757px;top:858px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_47\" class=\"drag\" style=\"position:absolute;left:822px;top:852px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_48\" class=\"drag\" style=\"position:absolute;left:823px;top:876px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_49\" class=\"drag\" style=\"position:absolute;left:757px;top:884px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_50\" class=\"drag\" style=\"position:absolute;left:702px;top:944px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p2_51\" class=\"drag\" style=\"position:absolute;left:824px;top:687px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_52\" class=\"drag\" style=\"position:absolute;left:697px;top:687px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_53\" class=\"drag\" style=\"position:absolute;left:757px;top:333px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_54\" class=\"drag\" style=\"position:absolute;left:756px;top:370px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_55\" class=\"drag\" style=\"position:absolute;left:757px;top:351px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_56\" class=\"drag\" style=\"position:absolute;left:386px;top:770px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p2_57\" class=\"drag\" style=\"position:absolute;left:835px;top:536px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_58\" class=\"drag\" style=\"position:absolute;left:835px;top:550px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_59\" class=\"drag\" style=\"position:absolute;left:591px;top:446px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>24P JUNCTION<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_60\" class=\"drag\" style=\"position:absolute;left:617px;top:593px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p2_61\" class=\"drag\" style=\"position:absolute;left:677px;top:593px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p2_62\" class=\"drag\" style=\"position:absolute;left:608px;top:621px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_63\" class=\"drag\" style=\"position:absolute;left:576px;top:516px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p2_64\" class=\"drag\" style=\"position:absolute;left:612px;top:515px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p2_65\" class=\"drag\" style=\"position:absolute;left:646px;top:515px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p2_66\" class=\"drag\" style=\"position:absolute;left:670px;top:514px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p2_67\" class=\"drag\" style=\"position:absolute;left:836px;top:343px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_68\" class=\"drag\" style=\"position:absolute;left:836px;top:362px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_69\" class=\"drag\" style=\"position:absolute;left:695px;top:254px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p2_70\" class=\"drag\" style=\"position:absolute;left:692px;top:125px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN/<br>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_71\" class=\"drag\" style=\"position:absolute;left:757px;top:72px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_72\" class=\"drag\" style=\"position:absolute;left:823px;top:221px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>VTEC SOLENOID<br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_73\" class=\"drag\" style=\"position:absolute;left:815px;top:163px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_74\" class=\"drag\" style=\"position:absolute;left:756px;top:193px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_75\" class=\"drag\" style=\"position:absolute;left:757px;top:177px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_76\" class=\"drag\" style=\"position:absolute;left:814px;top:186px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_77\" class=\"drag\" style=\"position:absolute;left:824px;top:82px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_78\" class=\"drag\" style=\"position:absolute;left:684px;top:388px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_79\" class=\"drag\" style=\"position:absolute;left:447px;top:430px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_80\" class=\"drag\" style=\"position:absolute;left:656px;top:397px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p2_81\" class=\"drag\" style=\"position:absolute;left:482px;top:435px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>W<br></b></nobr>");
write("</p>");
write("<p id=\"p2_82\" class=\"drag\" style=\"position:absolute;left:552px;top:611px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E<br></b></nobr>");
write("</p>");
write("<p id=\"p2_83\" class=\"drag\" style=\"position:absolute;left:669px;top:621px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>*7<br></b></nobr>");
write("</p>");
write("<p id=\"p2_84\" class=\"drag\" style=\"position:absolute;left:545px;top:639px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_85\" class=\"drag\" style=\"position:absolute;left:48px;top:565px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>*7<br></b></nobr>");
write("</p>");
write("<p id=\"p2_86\" class=\"drag\" style=\"position:absolute;left:199px;top:989px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>*1: A/T<br>*3: K24A3 engine<br>*7: K20A6 engine<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}