with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:447px;\" coordsize=\"950,447\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:447px;\">");
write("<img id=\"img1\" src=\"../img/SEA3E00J36100000000CAAD06.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:447px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:357px;top:225px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>Perception of<br>vehicle position<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:187px;top:277px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>YAW RATE SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:201px;top:297px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>Detection of<br>direction change<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:362px;top:296px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>Correction of<br>map matching<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:510px;top:227px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>Data process<br>concerning map<br>and vehicle position<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:510px;top:314px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>Map scroll<br>Change of reduced<br>scale of map<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:843px;top:242px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>LCD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:674px;top:251px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>Guide<br>processing<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:673px;top:397px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>Destination<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:836px;top:394px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:48px;top:91px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>GPS ANTENNA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:203px;top:92px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>GPS RECEIVER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:204px;top:112px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>Detection of<br>vehicle position<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:370px;top:117px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>GPS tuning<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:429px;top:70px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>NAVIGATION UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:813px;top:69px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>DISPLAY UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:37px;top:112px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>Reception of radio<br>wave from satellite<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:43px;top:185px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>PCM (VEHICLE<br>SPEED PULSE)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:49px;top:217px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>Detection of<br>travel distance<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:372px;top:387px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>DVD-ROM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:679px;top:42px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>Audio<br>guidance<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:667px;top:22px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>AUDIO UNIT<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}