with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:475px; height:320px;\" coordsize=\"475,320\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:475px;height:320px;\">");
write("<img id=\"img1\" src=\"../img/SEA3E00J36100000000FEAD13.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:320px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:344px;top:59px;font-weight:normal;font-size:10.9pt;\">");
write("<nobr><b>Return<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:100px;top:95px;font-weight:normal;font-size:10.9pt;\">");
write("<nobr><b>Disp<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:38px;top:58px;font-weight:normal;font-size:10.9pt;\">");
write("<nobr><b>Unit Check<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:78px;top:168px;font-weight:normal;font-size:10.9pt;\">");
write("<nobr><b>Navi ECU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:264px;top:95px;font-weight:normal;font-size:10.9pt;\">");
write("<nobr><b>System History<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:280px;top:169px;font-weight:normal;font-size:9.6pt;\">");
write("<nobr><b>Backup Clear<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:100px;top:131px;font-weight:normal;font-size:10.9pt;\">");
write("<nobr><b>GPS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:287px;top:131px;font-weight:normal;font-size:10.9pt;\">");
write("<nobr><b>Car Status<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:50px;top:240px;font-weight:normal;font-size:10.9pt;\">");
write("<nobr><b>Force Download<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}