with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:475px; height:690px;\" coordsize=\"475,690\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:475px;height:690px;\">");
write("<img id=\"img1\" src=\"../img/SEA3EK0J54400050461KBAD10.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:690px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:86px;top:17px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>: Apply glass primer here.<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:103px;top:481px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:270px;top:43px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:383px;top:93px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:103px;top:153px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:295px;top:444px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:137px;top:661px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:271px;top:497px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:150px;top:516px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Inside<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:267px;top:171px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Inside<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:201px;top:79px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>3 mm<br>(0.12 in.)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:200px;top:114px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>12 mm<br>(0.47 in.)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:86px;top:574px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>12 mm<br>(0.47 in.)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:386px;top:402px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>6 mm<br>(0.2 in.)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:434px;top:228px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}