with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:575px;\" coordsize=\"950,575\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:575px;\">");
write("<img id=\"img1\" src=\"../img/SEA3E20R11100000000YCAD08.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:575px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:841px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Unit: mm (in.)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:261px;top:502px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>2,680 (105.5)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:261px;top:533px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>4,665 (183.7)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:720px;top:501px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>1,525 (60.0)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:717px;top:245px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>1,515 (59.6)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:717px;top:274px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>1,760 (69.3)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("<v:line id=\"bl1_1\" class=\"drag\" from=\"891,202\" to=\"890,5\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_1\" class=\"drag\" on=\"true\" string=\"1,445 (56.9)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:8.6pt;\"/>");
write("</v:line>");
write("</v:group>");
}