with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1023px;\" coordsize=\"950,1023\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:1023px;\">");
write("<img id=\"img1\" src=\"../img/SEA3E20R31100000000YDAD66.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1023px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:624px;top:196px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>[VIEW: X]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:248px;top:983px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>[VIEW: Y]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:727px;top:36px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(2)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:361px;top:44px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR COMBINATION STIFFENER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:68px;top:74px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(4)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:53px;top:473px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(10)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:288px;top:553px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(3)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:350px;top:601px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(5)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:668px;top:642px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(24)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:447px;top:278px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(2)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:516px;top:877px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(4)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:458px;top:155px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR GUTTER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:490px;top:229px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR COMBINATION STIFFENER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:546px;top:266px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR PANEL GUSSET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:750px;top:262px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR PANEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:834px;top:371px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR FLOOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:397px;top:247px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>[X]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:157px;top:262px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>[Y]<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}