with(document) {
write("<v:group id=\"group4\" class=\"drag\" style=\"position:relative; width:950px; height:1121px;\" coordsize=\"950,1121\">");
write("<v:rect id=\"rect4\"class=\"drag\"  style=\"width:950px;height:1121px;\">");
write("<img id=\"img4\" src=\"../img/SEA3ENBJ22100000000EAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1121px;border-color:#ffffff\">");
write("<p id=\"p4_1\" class=\"drag\" style=\"position:absolute;left:739px;top:756px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>A8<br></b></nobr>");
write("</p>");
write("<p id=\"p4_2\" class=\"drag\" style=\"position:absolute;left:710px;top:928px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>TAILGATE<br></b></nobr>");
write("</p>");
write("<p id=\"p4_3\" class=\"drag\" style=\"position:absolute;left:228px;top:224px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p4_4\" class=\"drag\" style=\"position:absolute;left:214px;top:225px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_5\" class=\"drag\" style=\"position:absolute;left:214px;top:239px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_6\" class=\"drag\" style=\"position:absolute;left:228px;top:239px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p4_7\" class=\"drag\" style=\"position:absolute;left:293px;top:260px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p4_8\" class=\"drag\" style=\"position:absolute;left:279px;top:261px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_9\" class=\"drag\" style=\"position:absolute;left:279px;top:275px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_10\" class=\"drag\" style=\"position:absolute;left:293px;top:274px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p4_11\" class=\"drag\" style=\"position:absolute;left:293px;top:210px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p4_12\" class=\"drag\" style=\"position:absolute;left:279px;top:211px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_13\" class=\"drag\" style=\"position:absolute;left:279px;top:196px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_14\" class=\"drag\" style=\"position:absolute;left:293px;top:196px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p4_15\" class=\"drag\" style=\"position:absolute;left:446px;top:1079px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G506<br></b></nobr>");
write("</p>");
write("<p id=\"p4_16\" class=\"drag\" style=\"position:absolute;left:438px;top:1078px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p4_17\" class=\"drag\" style=\"position:absolute;left:421px;top:1079px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_18\" class=\"drag\" style=\"position:absolute;left:421px;top:1060px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_19\" class=\"drag\" style=\"position:absolute;left:438px;top:1059px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p4_20\" class=\"drag\" style=\"position:absolute;left:446px;top:1060px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p4_21\" class=\"drag\" style=\"position:absolute;left:874px;top:29px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LHD<br></b></nobr>");
write("</p>");
write("<p id=\"p4_22\" class=\"drag\" style=\"position:absolute;left:867px;top:27px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p4_23\" class=\"drag\" style=\"position:absolute;left:850px;top:29px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_24\" class=\"drag\" style=\"position:absolute;left:850px;top:50px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_25\" class=\"drag\" style=\"position:absolute;left:867px;top:49px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p4_26\" class=\"drag\" style=\"position:absolute;left:874px;top:50px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RHD<br></b></nobr>");
write("</p>");
write("<p id=\"p4_27\" class=\"drag\" style=\"position:absolute;left:596px;top:756px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>B29<br></b></nobr>");
write("</p>");
write("<p id=\"p4_28\" class=\"drag\" style=\"position:absolute;left:538px;top:292px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RIGHT TURN<br></b></nobr>");
write("</p>");
write("<p id=\"p4_29\" class=\"drag\" style=\"position:absolute;left:538px;top:304px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>SIGNAL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_30\" class=\"drag\" style=\"position:absolute;left:538px;top:315px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LIGHTS<br></b></nobr>");
write("</p>");
write("<p id=\"p4_31\" class=\"drag\" style=\"position:absolute;left:492px;top:232px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p4_32\" class=\"drag\" style=\"position:absolute;left:438px;top:196px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p4_33\" class=\"drag\" style=\"position:absolute;left:168px;top:315px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LIGHTS<br></b></nobr>");
write("</p>");
write("<p id=\"p4_34\" class=\"drag\" style=\"position:absolute;left:168px;top:304px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>SIGNAL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_35\" class=\"drag\" style=\"position:absolute;left:168px;top:293px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LEFT TURN<br></b></nobr>");
write("</p>");
write("<p id=\"p4_36\" class=\"drag\" style=\"position:absolute;left:438px;top:261px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p4_37\" class=\"drag\" style=\"position:absolute;left:310px;top:335px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>B15<br></b></nobr>");
write("</p>");
write("<p id=\"p4_38\" class=\"drag\" style=\"position:absolute;left:467px;top:478px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>SIGNAL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_39\" class=\"drag\" style=\"position:absolute;left:467px;top:501px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_40\" class=\"drag\" style=\"position:absolute;left:467px;top:489px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>INDICATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p4_41\" class=\"drag\" style=\"position:absolute;left:467px;top:466px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RIGHT TURN<br></b></nobr>");
write("</p>");
write("<p id=\"p4_42\" class=\"drag\" style=\"position:absolute;left:324px;top:466px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LEFT TURN<br></b></nobr>");
write("</p>");
write("<p id=\"p4_43\" class=\"drag\" style=\"position:absolute;left:324px;top:489px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>INDICATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p4_44\" class=\"drag\" style=\"position:absolute;left:324px;top:501px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_45\" class=\"drag\" style=\"position:absolute;left:324px;top:478px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>SIGNAL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_46\" class=\"drag\" style=\"position:absolute;left:453px;top:335px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>B26<br></b></nobr>");
write("</p>");
write("<p id=\"p4_47\" class=\"drag\" style=\"position:absolute;left:310px;top:121px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>TURN SIGNAL/HAZARD RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p4_48\" class=\"drag\" style=\"position:absolute;left:436px;top:818px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_49\" class=\"drag\" style=\"position:absolute;left:453px;top:756px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>B20<br></b></nobr>");
write("</p>");
write("<p id=\"p4_50\" class=\"drag\" style=\"position:absolute;left:151px;top:367px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p4_51\" class=\"drag\" style=\"position:absolute;left:150px;top:525px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>K<br></b></nobr>");
write("</p>");
write("<p id=\"p4_52\" class=\"drag\" style=\"position:absolute;left:741px;top:335px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GAUGE CONTROL MODULE<br></b></nobr>");
write("</p>");
write("<p id=\"p4_53\" class=\"drag\" style=\"position:absolute;left:234px;top:224px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_54\" class=\"drag\" style=\"position:absolute;left:234px;top:239px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p4_55\" class=\"drag\" style=\"position:absolute;left:298px;top:260px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_56\" class=\"drag\" style=\"position:absolute;left:298px;top:274px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p4_57\" class=\"drag\" style=\"position:absolute;left:298px;top:210px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p4_58\" class=\"drag\" style=\"position:absolute;left:298px;top:196px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_59\" class=\"drag\" style=\"position:absolute;left:753px;top:477px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>TAILGATE<br></b></nobr>");
write("</p>");
write("<p id=\"p4_60\" class=\"drag\" style=\"position:absolute;left:753px;top:465px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>POWER<br></b></nobr>");
write("</p>");
write("<p id=\"p4_61\" class=\"drag\" style=\"position:absolute;left:753px;top:500px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_62\" class=\"drag\" style=\"position:absolute;left:753px;top:488px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>INDICATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p4_63\" class=\"drag\" style=\"position:absolute;left:610px;top:494px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>INDICATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p4_64\" class=\"drag\" style=\"position:absolute;left:610px;top:505px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_65\" class=\"drag\" style=\"position:absolute;left:712px;top:817px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_66\" class=\"drag\" style=\"position:absolute;left:574px;top:940px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p4_67\" class=\"drag\" style=\"position:absolute;left:574px;top:928px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>OPDS<br></b></nobr>");
write("</p>");
write("<p id=\"p4_68\" class=\"drag\" style=\"position:absolute;left:579px;top:817px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_69\" class=\"drag\" style=\"position:absolute;left:610px;top:471px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>AIRBAG<br></b></nobr>");
write("</p>");
write("<p id=\"p4_70\" class=\"drag\" style=\"position:absolute;left:610px;top:483px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>CUTOFF<br></b></nobr>");
write("</p>");
write("<p id=\"p4_71\" class=\"drag\" style=\"position:absolute;left:610px;top:460px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>SIDE<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}