with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:799px;\" coordsize=\"950,799\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:799px;\">");
write("<img id=\"img1\" src=\"../img/SEA3E02E10411200000MEAD60.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:799px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:591px;top:15px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LOCKNUT (FLANGE NUT)<br>24 x 1.25 mm<br>226 N·m (23.0 kgf·m, 166 lbf·ft)→0→<br>167 N·m (17.0 kgf·m, 123 lbf·ft)<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:808px;top:97px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CONICAL SPRING<br>WASHER<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:790px;top:192px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>IDLER GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:736px;top:335px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TRANSMISSION<br>HOUSING BEARING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:234px;top:65px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>THRUST NEEDLE BEARING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:257px;top:129px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>4TH GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:210px;top:209px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>NEEDLE BEARING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:134px;top:255px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>THRUST NEEDLE BEARING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:198px;top:317px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>4TH GEAR COLLAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:181px;top:371px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>4TH/5TH CLUTCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:272px;top:451px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>O-RING<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:560px;top:499px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>THRUST WASHER, 41 x 68 mm<br></b>Selective part<br></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:504px;top:624px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>NEEDLE BEARING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:503px;top:585px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>THRUST NEEDLE BEARING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:504px;top:686px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>5TH GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:450px;top:741px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>THRUST NEEDLE BEARING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:172px;top:688px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SET RINGS,<br>29 mm<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:172px;top:733px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>NEEDLE BEARING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:172px;top:769px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SET RING<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}