with(document) {
write("<v:group id=\"group2\" class=\"drag\" style=\"position:relative; width:475px; height:481px;\" coordsize=\"475,481\">");
write("<v:rect id=\"rect2\"class=\"drag\"  style=\"width:475px;height:481px;\">");
write("<img id=\"img2\" src=\"../img/SEA3E20R31100000000YDAD73.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:481px;border-color:#ffffff\">");
write("<p id=\"p2_1\" class=\"drag\" style=\"position:absolute;left:159px;top:26px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>[A]<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" class=\"drag\" style=\"position:absolute;left:388px;top:13px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" class=\"drag\" style=\"position:absolute;left:156px;top:200px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>[B]<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" class=\"drag\" style=\"position:absolute;left:365px;top:198px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" class=\"drag\" style=\"position:absolute;left:223px;top:407px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" class=\"drag\" style=\"position:absolute;left:446px;top:300px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" class=\"drag\" style=\"position:absolute;left:81px;top:445px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>[VIEW: A]<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" class=\"drag\" style=\"position:absolute;left:271px;top:445px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>[VIEW: B]<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}