with(document) {
write("<v:group id=\"group12\" class=\"drag\" style=\"position:relative; width:950px; height:767px;\" coordsize=\"950,767\">");
write("<v:rect id=\"rect12\"class=\"drag\"  style=\"width:950px;height:767px;\">");
write("<img id=\"img12\" src=\"../img/SEA3ELBA20300000000CAAD45.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:767px;border-color:#ffffff\">");
write("<p id=\"p12_1\" class=\"drag\" style=\"position:absolute;left:553px;top:670px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p12_2\" class=\"drag\" style=\"position:absolute;left:285px;top:66px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p12_3\" class=\"drag\" style=\"position:absolute;left:334px;top:58px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p12_4\" class=\"drag\" style=\"position:absolute;left:373px;top:49px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p12_5\" class=\"drag\" style=\"position:absolute;left:889px;top:430px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p12_6\" class=\"drag\" style=\"position:absolute;left:425px;top:40px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p12_7\" class=\"drag\" style=\"position:absolute;left:871px;top:491px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p12_8\" class=\"drag\" style=\"position:absolute;left:709px;top:674px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p12_9\" class=\"drag\" style=\"position:absolute;left:604px;top:670px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p12_10\" class=\"drag\" style=\"position:absolute;left:107px;top:144px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p12_11\" class=\"drag\" style=\"position:absolute;left:181px;top:646px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p12_12\" class=\"drag\" style=\"position:absolute;left:141px;top:613px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p12_13\" class=\"drag\" style=\"position:absolute;left:486px;top:665px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p12_14\" class=\"drag\" style=\"position:absolute;left:441px;top:671px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p12_15\" class=\"drag\" style=\"position:absolute;left:311px;top:661px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p12_16\" class=\"drag\" style=\"position:absolute;left:377px;top:665px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p12_17\" class=\"drag\" style=\"position:absolute;left:229px;top:663px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p12_18\" class=\"drag\" style=\"position:absolute;left:3px;top:389px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ENGINE COMPARTMENT<br>WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p12_19\" class=\"drag\" style=\"position:absolute;left:506px;top:20px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ENGINE WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p12_20\" class=\"drag\" style=\"position:absolute;left:700px;top:60px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p12_21\" class=\"drag\" style=\"position:absolute;left:561px;top:729px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>STARTER SUBHARNESS<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}