with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1023px;\" coordsize=\"950,1023\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:1023px;\">");
write("<img id=\"img1\" src=\"../img/SEA3E40R11100000000YCAD08.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1023px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:16px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Mounting bolts/nuts torque:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:28px;top:31px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>6 x 1.0 mm: 9.8 N·m (1.0 kgf·m, 7.2 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:28px;top:47px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>8 x 1.25 mm: 22N·m (2.2 kgf·m, 16 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:84px;top:703px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL FILL DOOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:216px;top:726px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>6 x 1.0 mm<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:307px;top:745px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR BUMPER<br>BEAM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:451px;top:724px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>8 x 1.25 mm<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:504px;top:766px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>8 x 1.25 mm<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:751px;top:452px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>POWER TAILGATE DRIVE<br>UNIT BRACKET<br></b>(left side only)<br></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:834px;top:747px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TAILGATE<br>HINGE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:829px;top:805px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>8 x 1.25 mm<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:811px;top:885px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR PILLAR<br>GUSSET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:792px;top:994px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>8 x 1.25 mm<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:687px;top:66px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TAILGATE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:515px;top:803px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>Left side on the power<br>tailgate model only.<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}