with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1023px;\" coordsize=\"950,1023\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:1023px;\">");
write("<img id=\"img1\" src=\"../img/SEA3E00R31100000000YDAD26.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1023px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:72px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BACKPLATE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:405px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT SIDE<br>FRAME<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:617px;top:151px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DAMPER<br>HOUSING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:733px;top:222px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT<br>WHEELHOUSE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:794px;top:442px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT SIDE FRAME<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:65px;top:438px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT SUBFRAME<br>REAR SUPPORT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:273px;top:635px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SIDE FRAME<br>REAR END<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:260px;top:756px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT SIDE<br>FRAME<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:456px;top:757px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SIDE FRAME<br>REAR END<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:841px;top:994px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BACKPLATE<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}