with(document) {
write("<v:group id=\"group19\" class=\"drag\" style=\"position:relative; width:950px; height:836px;\" coordsize=\"950,836\">");
write("<v:rect id=\"rect19\"class=\"drag\"  style=\"width:950px;height:836px;\">");
write("<img id=\"img19\" src=\"../img/SEA3ELBJ54230100000EAAD19.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:836px;border-color:#ffffff\">");
write("<p id=\"p19_1\" class=\"drag\" style=\"position:absolute;left:407px;top:625px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p19_2\" class=\"drag\" style=\"position:absolute;left:377px;top:625px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p19_3\" class=\"drag\" style=\"position:absolute;left:674px;top:626px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left brake/taillight<br></b></nobr>");
write("</p>");
write("<p id=\"p19_4\" class=\"drag\" style=\"position:absolute;left:674px;top:576px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left back−up light<br></b></nobr>");
write("</p>");
write("<p id=\"p19_5\" class=\"drag\" style=\"position:absolute;left:377px;top:575px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p19_6\" class=\"drag\" style=\"position:absolute;left:407px;top:575px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p19_7\" class=\"drag\" style=\"position:absolute;left:674px;top:526px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left rear turn signal light<br></b></nobr>");
write("</p>");
write("<p id=\"p19_8\" class=\"drag\" style=\"position:absolute;left:377px;top:525px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p19_9\" class=\"drag\" style=\"position:absolute;left:407px;top:525px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p19_10\" class=\"drag\" style=\"position:absolute;left:674px;top:476px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right back−up light<br></b></nobr>");
write("</p>");
write("<p id=\"p19_11\" class=\"drag\" style=\"position:absolute;left:377px;top:475px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p19_12\" class=\"drag\" style=\"position:absolute;left:407px;top:475px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p19_13\" class=\"drag\" style=\"position:absolute;left:674px;top:426px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right taillight<br></b></nobr>");
write("</p>");
write("<p id=\"p19_14\" class=\"drag\" style=\"position:absolute;left:377px;top:425px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p19_15\" class=\"drag\" style=\"position:absolute;left:407px;top:425px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p19_16\" class=\"drag\" style=\"position:absolute;left:674px;top:376px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Trunk actuator<br></b></nobr>");
write("</p>");
write("<p id=\"p19_17\" class=\"drag\" style=\"position:absolute;left:377px;top:375px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p19_18\" class=\"drag\" style=\"position:absolute;left:407px;top:375px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p19_19\" class=\"drag\" style=\"position:absolute;left:674px;top:326px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Trunk handle switch<br></b></nobr>");
write("</p>");
write("<p id=\"p19_20\" class=\"drag\" style=\"position:absolute;left:377px;top:325px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p19_21\" class=\"drag\" style=\"position:absolute;left:407px;top:325px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p19_22\" class=\"drag\" style=\"position:absolute;left:674px;top:276px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Rear fog light (with rear fog light)<br></b></nobr>");
write("</p>");
write("<p id=\"p19_23\" class=\"drag\" style=\"position:absolute;left:377px;top:275px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p19_24\" class=\"drag\" style=\"position:absolute;left:407px;top:275px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p19_25\" class=\"drag\" style=\"position:absolute;left:674px;top:226px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left taillight<br></b></nobr>");
write("</p>");
write("<p id=\"p19_26\" class=\"drag\" style=\"position:absolute;left:377px;top:225px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p19_27\" class=\"drag\" style=\"position:absolute;left:407px;top:225px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p19_28\" class=\"drag\" style=\"position:absolute;left:407px;top:25px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p19_29\" class=\"drag\" style=\"position:absolute;left:377px;top:25px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p19_30\" class=\"drag\" style=\"position:absolute;left:377px;top:75px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p19_31\" class=\"drag\" style=\"position:absolute;left:407px;top:75px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p19_32\" class=\"drag\" style=\"position:absolute;left:407px;top:175px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p19_33\" class=\"drag\" style=\"position:absolute;left:377px;top:175px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p19_34\" class=\"drag\" style=\"position:absolute;left:674px;top:176px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right brake/taillight<br></b></nobr>");
write("</p>");
write("<p id=\"p19_35\" class=\"drag\" style=\"position:absolute;left:674px;top:126px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right rear turn signal light<br></b></nobr>");
write("</p>");
write("<p id=\"p19_36\" class=\"drag\" style=\"position:absolute;left:377px;top:125px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p19_37\" class=\"drag\" style=\"position:absolute;left:407px;top:125px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p19_38\" class=\"drag\" style=\"position:absolute;left:674px;top:76px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right license plate light<br></b></nobr>");
write("</p>");
write("<p id=\"p19_39\" class=\"drag\" style=\"position:absolute;left:71px;top:789px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p19_40\" class=\"drag\" style=\"position:absolute;left:88px;top:788px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p19_41\" class=\"drag\" style=\"position:absolute;left:95px;top:789px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Rear wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p19_42\" class=\"drag\" style=\"position:absolute;left:674px;top:26px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left license plate light<br></b></nobr>");
write("</p>");
write("<p id=\"p19_43\" class=\"drag\" style=\"position:absolute;left:54px;top:739px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G701<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}