with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:1900px; height:1132px;\" coordsize=\"1900,1132\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:1900px;height:1132px;\">");
write("<img id=\"img1\" src=\"../img/SEA3E40R41100000000YDAD90.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:1900px;height:1132px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:11px;top:23px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>Unit: mm (in.)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:663px;top:24px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>For front upper arm φ13 (0.51)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:663px;top:49px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>For front upper arm φ13 (0.51)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:11px;top:49px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>φ: Inner diameter<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:663px;top:73px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>For front subframe φ15 (0.59)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:663px;top:98px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>For front subframe φ16 (0.63)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:662px;top:123px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>Locating hole φ25 (0.98)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:662px;top:148px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>Locating hole φ25 (0.98)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:662px;top:173px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>Locating hole φ15 (0.59)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:187px;top:23px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>a<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:229px;top:73px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>For transmission mount φ15 (0.59) Left side  <br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:229px;top:24px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>For front subframe φ16 (0.63)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:229px;top:49px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>For transmission mount φ13 (0.51) Left side<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:187px;top:98px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>b3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:187px;top:123px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>c1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:229px;top:123px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>For engine side mount φ15 (0.59) Right side<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:187px;top:73px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>b2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:187px;top:48px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>b1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:187px;top:148px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>c2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:229px;top:149px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>For engine side mount φ15 (0.59) Right side<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:187px;top:173px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>d<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:229px;top:173px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>Front damper center φ50 (1.97)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:229px;top:98px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>For transmission mount φ13 (0.51) Left side  <br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:533px;top:1109px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>VERTICAL LINE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:620px;top:24px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>e<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:620px;top:98px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>h<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:620px;top:123px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>i<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:620px;top:73px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>g<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:620px;top:49px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>f<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:620px;top:148px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>j<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:620px;top:173px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>k<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:1059px;top:123px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>For rear cross beam φ17 (0.67)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" class=\"drag\" style=\"position:absolute;left:1493px;top:48px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>For rear cross beam φ17 (0.67)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" class=\"drag\" style=\"position:absolute;left:1493px;top:98px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>Locating hole φ25 (0.98)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" class=\"drag\" style=\"position:absolute;left:1018px;top:23px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>l<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" class=\"drag\" style=\"position:absolute;left:1059px;top:23px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>Locating hole φ25 (0.98)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" class=\"drag\" style=\"position:absolute;left:1059px;top:48px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>For suspension φ17 (0.67)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" class=\"drag\" style=\"position:absolute;left:1018px;top:98px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>o<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" class=\"drag\" style=\"position:absolute;left:1018px;top:73px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>n<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" class=\"drag\" style=\"position:absolute;left:1018px;top:48px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>m<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" class=\"drag\" style=\"position:absolute;left:1493px;top:73px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>Rear damper center φ24 (0.94)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" class=\"drag\" style=\"position:absolute;left:1019px;top:123px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>p<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" class=\"drag\" style=\"position:absolute;left:1452px;top:98px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>t<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" class=\"drag\" style=\"position:absolute;left:1452px;top:73px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>s<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" class=\"drag\" style=\"position:absolute;left:1452px;top:49px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>r<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" class=\"drag\" style=\"position:absolute;left:91px;top:598px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>CENTER LINE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" class=\"drag\" style=\"position:absolute;left:290px;top:313px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>POINT a<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" class=\"drag\" style=\"position:absolute;left:362px;top:694px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>POINT b1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" class=\"drag\" style=\"position:absolute;left:362px;top:669px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>POINT b2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" class=\"drag\" style=\"position:absolute;left:362px;top:642px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>POINT b3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" class=\"drag\" style=\"position:absolute;left:301px;top:284px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>POINT c1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" class=\"drag\" style=\"position:absolute;left:302px;top:252px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>POINT c2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" class=\"drag\" style=\"position:absolute;left:419px;top:281px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>POINT e<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" class=\"drag\" style=\"position:absolute;left:694px;top:232px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>POINT d<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" class=\"drag\" style=\"position:absolute;left:693px;top:263px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>POINT g<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" class=\"drag\" style=\"position:absolute;left:693px;top:294px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>POINT f<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" class=\"drag\" style=\"position:absolute;left:508px;top:544px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>367 (14.4)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" class=\"drag\" style=\"position:absolute;left:532px;top:516px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>252(9.9)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" class=\"drag\" style=\"position:absolute;left:516px;top:614px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>351 (13.8)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" class=\"drag\" style=\"position:absolute;left:521px;top:630px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>310 (12.2)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" class=\"drag\" style=\"position:absolute;left:529px;top:644px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>254 (10.0)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" class=\"drag\" style=\"position:absolute;left:533px;top:661px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>119 (4.9)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" class=\"drag\" style=\"position:absolute;left:541px;top:678px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>53 (2.1)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" class=\"drag\" style=\"position:absolute;left:538px;top:695px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>9 (0.35)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" class=\"drag\" style=\"position:absolute;left:597px;top:648px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>137<br>(5.4)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" class=\"drag\" style=\"position:absolute;left:485px;top:852px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>515 (20.3)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" class=\"drag\" style=\"position:absolute;left:613px;top:853px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>355 (14.0)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" class=\"drag\" style=\"position:absolute;left:620px;top:870px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>425 (16.7)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" class=\"drag\" style=\"position:absolute;left:628px;top:887px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>610 (24.0)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" class=\"drag\" style=\"position:absolute;left:635px;top:905px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>800 (31.5) Left side<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" class=\"drag\" style=\"position:absolute;left:820px;top:923px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>1445 (56.89)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" class=\"drag\" style=\"position:absolute;left:1025px;top:940px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>2046 (80.55)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" class=\"drag\" style=\"position:absolute;left:1032px;top:958px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>2100 (82.68)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" class=\"drag\" style=\"position:absolute;left:1040px;top:976px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>2260(88.98)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" class=\"drag\" style=\"position:absolute;left:1048px;top:993px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>2485 (97.83)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" class=\"drag\" style=\"position:absolute;left:1057px;top:1011px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>2806 (110.47)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" class=\"drag\" style=\"position:absolute;left:1065px;top:1028px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>2807 (110.51)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" class=\"drag\" style=\"position:absolute;left:1073px;top:1046px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>2816 (110.87)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" class=\"drag\" style=\"position:absolute;left:691px;top:354px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>Right side<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" class=\"drag\" style=\"position:absolute;left:832px;top:216px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>POINT i<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" class=\"drag\" style=\"position:absolute;left:833px;top:248px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>POINT h<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" class=\"drag\" style=\"position:absolute;left:833px;top:279px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>POINT j<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" class=\"drag\" style=\"position:absolute;left:833px;top:311px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>POINT k<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" class=\"drag\" style=\"position:absolute;left:1045px;top:318px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>POINT l<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" class=\"drag\" style=\"position:absolute;left:1066px;top:285px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>POINT m<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" class=\"drag\" style=\"position:absolute;left:1079px;top:247px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>POINT n<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" class=\"drag\" style=\"position:absolute;left:1122px;top:213px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>POINT o<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" class=\"drag\" style=\"position:absolute;left:1239px;top:322px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>POINT p<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" class=\"drag\" style=\"position:absolute;left:1254px;top:281px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>POINT q<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" class=\"drag\" style=\"position:absolute;left:1457px;top:316px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>POINT r<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" class=\"drag\" style=\"position:absolute;left:1268px;top:241px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>POINT s<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" class=\"drag\" style=\"position:absolute;left:691px;top:337px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>870 (34.3)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" class=\"drag\" style=\"position:absolute;left:1059px;top:73px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>Locating hole φ20 (0.79)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" class=\"drag\" style=\"position:absolute;left:1493px;top:23px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>Locating hole φ15 (0.59)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" class=\"drag\" style=\"position:absolute;left:1452px;top:22px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>q<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" class=\"drag\" style=\"position:absolute;left:1059px;top:98px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>For suspension φ17 (0.67)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" class=\"drag\" style=\"position:absolute;left:1546px;top:344px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>POINT t<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" class=\"drag\" style=\"position:absolute;left:1080px;top:1064px;font-weight:normal;font-size:7.2pt;\">");
write("<nobr><b>3200 (125.98)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("<v:line id=\"bl1_1\" class=\"drag\" from=\"880,636\" to=\"879,529\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_1\" class=\"drag\" on=\"true\" string=\"1110 (43.70)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_2\" class=\"drag\" from=\"827,629\" to=\"826,554\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_2\" class=\"drag\" on=\"true\" string=\"638 (25.1)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_3\" class=\"drag\" from=\"845,629\" to=\"844,542\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_3\" class=\"drag\" on=\"true\" string=\"888 (35.0)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_4\" class=\"drag\" from=\"863,636\" to=\"862,553\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_4\" class=\"drag\" on=\"true\" string=\"1100 (43.31)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_5\" class=\"drag\" from=\"254,590\" to=\"253,476\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_5\" class=\"drag\" on=\"true\" string=\"489 (19.3) c2\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_6\" class=\"drag\" from=\"272,630\" to=\"271,510\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_6\" class=\"drag\" on=\"true\" string=\"944 (37.2) d\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_7\" class=\"drag\" from=\"290,630\" to=\"289,508\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_7\" class=\"drag\" on=\"true\" string=\"916 (36.1) e\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_8\" class=\"drag\" from=\"308,726\" to=\"307,606\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_8\" class=\"drag\" on=\"true\" string=\"465 (18.3) b1\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_9\" class=\"drag\" from=\"325,726\" to=\"324,602\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_9\" class=\"drag\" on=\"true\" string=\"462 (18.2) b2\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_10\" class=\"drag\" from=\"342,726\" to=\"341,595\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_10\" class=\"drag\" on=\"true\" string=\"452 (17.8) b3\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_11\" class=\"drag\" from=\"639,630\" to=\"638,532\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_11\" class=\"drag\" on=\"true\" string=\"873 (34.4) g\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_12\" class=\"drag\" from=\"656,630\" to=\"655,532\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_12\" class=\"drag\" on=\"true\" string=\"934 (36.8) f\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_13\" class=\"drag\" from=\"1032,629\" to=\"1031,520\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_13\" class=\"drag\" on=\"true\" string=\"888 (35.0)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_14\" class=\"drag\" from=\"1131,636\" to=\"1130,519\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_14\" class=\"drag\" on=\"true\" string=\"1040 (40.94)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_15\" class=\"drag\" from=\"1212,635\" to=\"1211,530\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_15\" class=\"drag\" on=\"true\" string=\"1214 (47.80)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_16\" class=\"drag\" from=\"1254,636\" to=\"1253,533\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_16\" class=\"drag\" on=\"true\" string=\"1040 (40.94)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_17\" class=\"drag\" from=\"1335,629\" to=\"1334,555\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_17\" class=\"drag\" on=\"true\" string=\"908 (35.7)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_18\" class=\"drag\" from=\"1424,629\" to=\"1423,543\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_18\" class=\"drag\" on=\"true\" string=\"316 (12.4)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_19\" class=\"drag\" from=\"1473,629\" to=\"1472,540\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_19\" class=\"drag\" on=\"true\" string=\"894 (35.2)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_20\" class=\"drag\" from=\"1644,629\" to=\"1643,526\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_20\" class=\"drag\" on=\"true\" string=\"900 (35.4)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_21\" class=\"drag\" from=\"1693,636\" to=\"1692,527\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_21\" class=\"drag\" on=\"true\" string=\"1109 (43.66)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_22\" class=\"drag\" from=\"218,590\" to=\"217,473\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_22\" class=\"drag\" on=\"true\" string=\"526 (20.7) c1\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl1_23\" class=\"drag\" from=\"237,636\" to=\"236,508\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_23\" class=\"drag\" on=\"true\" string=\"1020 (40.16) a\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.2pt;\"/>");
write("</v:line>");
write("</v:group>");
}