with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1071px;\" coordsize=\"950,1071\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:1071px;\">");
write("<img id=\"img1\" src=\"../img/SEA3E40R21100000000YCAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1071px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:238px;top:50px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HOOD MOLDING<br></b>Chrome plated<br></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:43px;top:113px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT BUMPER GRILLE<br></b>Avantgarde gray<br>metallic (NH-655M)<br>20 SPOT: BP. Dark gray (NH-533)<br></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:16px;top:236px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT GRILLE MOLDING<br></b>Chrome plated<br></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:16px;top:341px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT BUMPER<br></b>Body color<br></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:85px;top:507px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT AIR SPOILER<br></b>Body color<br>(24TYPS only)<br></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:289px;top:521px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT AIR SPOILER<br></b>BP. Dark gray (NH-533)<br>(except 24TYPS)<br></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:454px;top:478px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FOG COVER<br></b>BP. Dark gray<br>(NH-533)<br></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:624px;top:466px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DOOR MIRROR BASE<br></b>BP. Dark gray (NH-533)<br></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:688px;top:419px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DOOR MIRROR HOUSING<br></b>Body color<br></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:737px;top:361px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DOOR MOLDINGS<br></b>Chrome plated or<br>Black (NH-70 Gloss 20)<br></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:768px;top:60px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CHANNEL TAPE<br></b>Black (NH-555 Gloss 80)<br></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:580px;top:17px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DOOR OUTER MOLDINGS<br></b>Chrome plated or<br>Black (NH-70 Gloss 20)<br></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:616px;top:530px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ROOF MOLDING<br></b>Black (NH-70 Gloss 20)<br></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:752px;top:893px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DOOR OUTER HANDLES<br></b>Chrome plated<br></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:688px;top:953px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SIDE SILL PANEL<br></b>Body color or<br>BP. Dark gray (NH-533)<br></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:315px;top:1026px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR BUMPER<br></b>Body color<br></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:55px;top:1012px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR AIR SPOILER<br></b>Body color<br>(24TYPS only)<br></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:33px;top:649px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TAILGATE LOWER TRIM<br></b>Body color<br></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:113px;top:570px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TAILGATE SPOILER<br></b>Body color<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}