with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:475px; height:320px;\" coordsize=\"475,320\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:475px;height:320px;\">");
write("<img id=\"img1\" src=\"../img/SEA3E00K732000Y1175FAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:320px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:75px;top:17px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>FUEL PUMP/FUEL GAUGE SENDING UNIT<br>5P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:119px;top:287px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b></b>Wire side of female terminals<br></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:105px;top:70px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:104px;top:104px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:166px;top:165px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>GAUGE CONTROL MODULE<br>CONNECTOR B (30P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:277px;top:117px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b></b>Wire side of<br>female terminals<br></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:23px;top:186px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:98px;top:186px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}