with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:475px; height:320px;\" coordsize=\"475,320\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:475px;height:320px;\">");
write("<img id=\"img1\" src=\"../img/SEA3E0BK711000Y1239FAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:320px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:64px;top:32px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>CLIMATE CONTROL UNIT CONNECTOR A (22P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:127px;top:274px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b></b>Wire side of female terminals<br></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:61px;top:146px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>RED: LHD<br>RED/BLK: RHD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:313px;top:57px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:250px;top:60px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:291px;top:150px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:254px;top:150px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:212px;top:150px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:179px;top:150px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}