with(document) {
write("<v:group id=\"group5\" class=\"drag\" style=\"position:relative; width:950px; height:859px;\" coordsize=\"950,859\">");
write("<v:rect id=\"rect5\"class=\"drag\"  style=\"width:950px;height:859px;\">");
write("<img id=\"img5\" src=\"../img/SEA4E0AJ54230100000EAAD05.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:859px;border-color:#ffffff\">");
write("<p id=\"p5_1\" class=\"drag\" style=\"position:absolute;left:136px;top:811px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ECM wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p5_2\" class=\"drag\" style=\"position:absolute;left:129px;top:809px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p5_3\" class=\"drag\" style=\"position:absolute;left:112px;top:810px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>V<br></b></nobr>");
write("</p>");
write("<p id=\"p5_4\" class=\"drag\" style=\"position:absolute;left:687px;top:611px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ECM<br></b></nobr>");
write("</p>");
write("<p id=\"p5_5\" class=\"drag\" style=\"position:absolute;left:437px;top:610px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_6\" class=\"drag\" style=\"position:absolute;left:462px;top:610px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>V<br></b></nobr>");
write("</p>");
write("<p id=\"p5_7\" class=\"drag\" style=\"position:absolute;left:462px;top:560px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p5_8\" class=\"drag\" style=\"position:absolute;left:437px;top:560px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_9\" class=\"drag\" style=\"position:absolute;left:580px;top:560px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_10\" class=\"drag\" style=\"position:absolute;left:605px;top:560px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p5_11\" class=\"drag\" style=\"position:absolute;left:687px;top:561px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Data link connector (DLC)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_12\" class=\"drag\" style=\"position:absolute;left:687px;top:497px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Imoes unit<br></b></nobr>");
write("</p>");
write("<p id=\"p5_13\" class=\"drag\" style=\"position:absolute;left:687px;top:483px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Immobilizer−receiver unit<br></b></nobr>");
write("</p>");
write("<p id=\"p5_14\" class=\"drag\" style=\"position:absolute;left:605px;top:482px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p5_15\" class=\"drag\" style=\"position:absolute;left:580px;top:482px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_16\" class=\"drag\" style=\"position:absolute;left:437px;top:482px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_17\" class=\"drag\" style=\"position:absolute;left:462px;top:482px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p5_18\" class=\"drag\" style=\"position:absolute;left:355px;top:482px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>V<br></b></nobr>");
write("</p>");
write("<p id=\"p5_19\" class=\"drag\" style=\"position:absolute;left:330px;top:482px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_20\" class=\"drag\" style=\"position:absolute;left:419px;top:403px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>V<br></b></nobr>");
write("</p>");
write("<p id=\"p5_21\" class=\"drag\" style=\"position:absolute;left:392px;top:404px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_22\" class=\"drag\" style=\"position:absolute;left:687px;top:168px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Climate control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p5_23\" class=\"drag\" style=\"position:absolute;left:687px;top:126px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Navigatioin unit<br></b></nobr>");
write("</p>");
write("<p id=\"p5_24\" class=\"drag\" style=\"position:absolute;left:687px;top:40px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Front passenger's seat heater switch<br></b></nobr>");
write("</p>");
write("<p id=\"p5_25\" class=\"drag\" style=\"position:absolute;left:222px;top:404px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_26\" class=\"drag\" style=\"position:absolute;left:419px;top:360px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>V<br></b></nobr>");
write("</p>");
write("<p id=\"p5_27\" class=\"drag\" style=\"position:absolute;left:392px;top:361px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_28\" class=\"drag\" style=\"position:absolute;left:96px;top:711px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G451<br></b></nobr>");
write("</p>");
write("<p id=\"p5_29\" class=\"drag\" style=\"position:absolute;left:687px;top:361px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ECM<br></b></nobr>");
write("</p>");
write("<p id=\"p5_30\" class=\"drag\" style=\"position:absolute;left:687px;top:404px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ECM<br></b></nobr>");
write("</p>");
write("<p id=\"p5_31\" class=\"drag\" style=\"position:absolute;left:222px;top:561px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_32\" class=\"drag\" style=\"position:absolute;left:248px;top:403px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>V<br></b></nobr>");
write("</p>");
write("<p id=\"p5_33\" class=\"drag\" style=\"position:absolute;left:248px;top:560px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>V<br></b></nobr>");
write("</p>");
write("<p id=\"p5_34\" class=\"drag\" style=\"position:absolute;left:418px;top:154px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p5_35\" class=\"drag\" style=\"position:absolute;left:418px;top:111px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p5_36\" class=\"drag\" style=\"position:absolute;left:418px;top:68px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p5_37\" class=\"drag\" style=\"position:absolute;left:111px;top:789px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p5_38\" class=\"drag\" style=\"position:absolute;left:129px;top:788px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p5_39\" class=\"drag\" style=\"position:absolute;left:136px;top:789px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Dashboard wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p5_40\" class=\"drag\" style=\"position:absolute;left:394px;top:154px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_41\" class=\"drag\" style=\"position:absolute;left:687px;top:154px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Climate contorl unit<br></b></nobr>");
write("</p>");
write("<p id=\"p5_42\" class=\"drag\" style=\"position:absolute;left:394px;top:111px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_43\" class=\"drag\" style=\"position:absolute;left:687px;top:111px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Navigation display unit<br></b></nobr>");
write("</p>");
write("<p id=\"p5_44\" class=\"drag\" style=\"position:absolute;left:687px;top:68px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Combination switch control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p5_45\" class=\"drag\" style=\"position:absolute;left:687px;top:26px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Driver's seat heater switch<br></b></nobr>");
write("</p>");
write("<p id=\"p5_46\" class=\"drag\" style=\"position:absolute;left:96px;top:289px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G506<br></b></nobr>");
write("</p>");
write("<p id=\"p5_47\" class=\"drag\" style=\"position:absolute;left:394px;top:25px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_48\" class=\"drag\" style=\"position:absolute;left:418px;top:25px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p5_49\" class=\"drag\" style=\"position:absolute;left:394px;top:68px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_50\" class=\"drag\" style=\"position:absolute;left:487px;top:422px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>JUNCTION <br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p5_51\" class=\"drag\" style=\"position:absolute;left:487px;top:501px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>JUNCTION <br>CONNECTOR<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}