with(document) {
write("<v:group id=\"group4\" class=\"drag\" style=\"position:relative; width:950px; height:1004px;\" coordsize=\"950,1004\">");
write("<v:rect id=\"rect4\"class=\"drag\"  style=\"width:950px;height:1004px;\">");
write("<img id=\"img4\" src=\"../img/SEA4E0AJ22100000000EAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1004px;border-color:#ffffff\">");
write("<p id=\"p4_1\" class=\"drag\" style=\"position:absolute;left:662px;top:757px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_2\" class=\"drag\" style=\"position:absolute;left:529px;top:964px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p4_3\" class=\"drag\" style=\"position:absolute;left:676px;top:831px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ECM<br></b></nobr>");
write("</p>");
write("<p id=\"p4_4\" class=\"drag\" style=\"position:absolute;left:690px;top:660px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>A10<br></b></nobr>");
write("</p>");
write("<p id=\"p4_5\" class=\"drag\" style=\"position:absolute;left:673px;top:685px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p4_6\" class=\"drag\" style=\"position:absolute;left:589px;top:135px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p4_7\" class=\"drag\" style=\"position:absolute;left:532px;top:107px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p4_8\" class=\"drag\" style=\"position:absolute;left:320px;top:135px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_9\" class=\"drag\" style=\"position:absolute;left:377px;top:107px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_10\" class=\"drag\" style=\"position:absolute;left:532px;top:164px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p4_11\" class=\"drag\" style=\"position:absolute;left:377px;top:164px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_12\" class=\"drag\" style=\"position:absolute;left:404px;top:238px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>B15<br></b></nobr>");
write("</p>");
write("<p id=\"p4_13\" class=\"drag\" style=\"position:absolute;left:547px;top:238px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>B26<br></b></nobr>");
write("</p>");
write("<p id=\"p4_14\" class=\"drag\" style=\"position:absolute;left:395px;top:24px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>TURN SIGNAL/HAZARD RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p4_15\" class=\"drag\" style=\"position:absolute;left:532px;top:720px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_16\" class=\"drag\" style=\"position:absolute;left:547px;top:660px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>B20<br></b></nobr>");
write("</p>");
write("<p id=\"p4_17\" class=\"drag\" style=\"position:absolute;left:152px;top:270px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p4_18\" class=\"drag\" style=\"position:absolute;left:152px;top:427px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>K<br></b></nobr>");
write("</p>");
write("<p id=\"p4_19\" class=\"drag\" style=\"position:absolute;left:736px;top:238px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GAUGE CONTROL MODULE<br></b></nobr>");
write("</p>");
write("<p id=\"p4_20\" class=\"drag\" style=\"position:absolute;left:261px;top:196px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LEFT TURN <br>SIGNAL <br>LIGHTS<br></b></nobr>");
write("</p>");
write("<p id=\"p4_21\" class=\"drag\" style=\"position:absolute;left:632px;top:196px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RIGHT TURN <br>SIGNAL <br>LIGHTS<br></b></nobr>");
write("</p>");
write("<p id=\"p4_22\" class=\"drag\" style=\"position:absolute;left:419px;top:368px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LEFT TURN <br>SIGNAL <br>INDICATOR <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_23\" class=\"drag\" style=\"position:absolute;left:562px;top:368px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RIGHT TURN <br>SIGNAL <br>INDICATOR <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_24\" class=\"drag\" style=\"position:absolute;left:705px;top:368px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GLOW PLUG <br>INDICATOR <br>(LED)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}