with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:475px; height:417px;\" coordsize=\"475,417\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:475px;height:417px;\">");
write("<img id=\"img1\" src=\"../img/SEA4E0AK80100081110FAAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:417px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:111px;top:17px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>VSA CONTROL UNIT 47P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:137px;top:383px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b></b>Wire side of female terminals<br></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:58px;top:134px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>FR-GND<br>(PNK)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:55px;top:180px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>FR +B<br>(GRN/BLK)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:97px;top:224px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>RL +B<br>(YEL/RED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:126px;top:267px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>RL-GND<br>(RED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:225px;top:133px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>RR-GND<br>(BLU/YEL)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:239px;top:180px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>RR +B<br>(GRN/YEL)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:277px;top:224px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>FL +B<br>(BLU/ORN)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:346px;top:267px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>FL-GND<br>(BRN/WHT)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}