with(document) {
write("<v:group id=\"group10\" class=\"drag\" style=\"position:relative; width:950px; height:1040px;\" coordsize=\"950,1040\">");
write("<v:rect id=\"rect10\"class=\"drag\"  style=\"width:950px;height:1040px;\">");
write("<img id=\"img10\" src=\"../img/SEA5ED3J54230100000EAAD03.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1040px;border-color:#ffffff\">");
write("<p id=\"p10_1\" class=\"drag\" style=\"position:absolute;left:406px;top:333px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_2\" class=\"drag\" style=\"position:absolute;left:435px;top:333px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p10_3\" class=\"drag\" style=\"position:absolute;left:710px;top:844px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>VSA modulator−control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p10_4\" class=\"drag\" style=\"position:absolute;left:702px;top:291px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Rear washer relay<br></b></nobr>");
write("</p>");
write("<p id=\"p10_5\" class=\"drag\" style=\"position:absolute;left:435px;top:290px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p10_6\" class=\"drag\" style=\"position:absolute;left:406px;top:290px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_7\" class=\"drag\" style=\"position:absolute;left:702px;top:126px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Super locking actuator (With super lock)<br></b></nobr>");
write("</p>");
write("<p id=\"p10_8\" class=\"drag\" style=\"position:absolute;left:702px;top:462px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Navigation unit<br></b></nobr>");
write("</p>");
write("<p id=\"p10_9\" class=\"drag\" style=\"position:absolute;left:449px;top:461px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p10_10\" class=\"drag\" style=\"position:absolute;left:420px;top:462px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_11\" class=\"drag\" style=\"position:absolute;left:345px;top:976px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Passenger's door wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p10_12\" class=\"drag\" style=\"position:absolute;left:338px;top:975px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p10_13\" class=\"drag\" style=\"position:absolute;left:320px;top:976px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>M<br></b></nobr>");
write("</p>");
write("<p id=\"p10_14\" class=\"drag\" style=\"position:absolute;left:71px;top:976px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p10_15\" class=\"drag\" style=\"position:absolute;left:88px;top:975px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p10_16\" class=\"drag\" style=\"position:absolute;left:95px;top:976px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Engine compartment wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p10_17\" class=\"drag\" style=\"position:absolute;left:342px;top:383px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p10_18\" class=\"drag\" style=\"position:absolute;left:311px;top:383px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_19\" class=\"drag\" style=\"position:absolute;left:402px;top:522px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ECM/PCM<br></b></nobr>");
write("</p>");
write("<p id=\"p10_20\" class=\"drag\" style=\"position:absolute;left:418px;top:576px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_21\" class=\"drag\" style=\"position:absolute;left:449px;top:575px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p10_22\" class=\"drag\" style=\"position:absolute;left:582px;top:540px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_23\" class=\"drag\" style=\"position:absolute;left:613px;top:540px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p10_24\" class=\"drag\" style=\"position:absolute;left:613px;top:504px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p10_25\" class=\"drag\" style=\"position:absolute;left:581px;top:504px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p10_26\" class=\"drag\" style=\"position:absolute;left:449px;top:683px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p10_27\" class=\"drag\" style=\"position:absolute;left:418px;top:683px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_28\" class=\"drag\" style=\"position:absolute;left:449px;top:790px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p10_29\" class=\"drag\" style=\"position:absolute;left:418px;top:790px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_30\" class=\"drag\" style=\"position:absolute;left:406px;top:247px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_31\" class=\"drag\" style=\"position:absolute;left:435px;top:247px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p10_32\" class=\"drag\" style=\"position:absolute;left:702px;top:248px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Clutch switch (M/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p10_33\" class=\"drag\" style=\"position:absolute;left:702px;top:205px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Seat heater relay<br></b></nobr>");
write("</p>");
write("<p id=\"p10_34\" class=\"drag\" style=\"position:absolute;left:435px;top:204px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p10_35\" class=\"drag\" style=\"position:absolute;left:406px;top:204px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_36\" class=\"drag\" style=\"position:absolute;left:702px;top:162px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Climate control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p10_37\" class=\"drag\" style=\"position:absolute;left:406px;top:162px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_38\" class=\"drag\" style=\"position:absolute;left:435px;top:161px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p10_39\" class=\"drag\" style=\"position:absolute;left:702px;top:112px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Passenger's door lock knob switch<br></b></nobr>");
write("</p>");
write("<p id=\"p10_40\" class=\"drag\" style=\"position:absolute;left:702px;top:98px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left power mirror defogger<br></b></nobr>");
write("</p>");
write("<p id=\"p10_41\" class=\"drag\" style=\"position:absolute;left:702px;top:84px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left power mirror<br></b></nobr>");
write("</p>");
write("<p id=\"p10_42\" class=\"drag\" style=\"position:absolute;left:702px;top:69px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Passenger's power window switch<br></b></nobr>");
write("</p>");
write("<p id=\"p10_43\" class=\"drag\" style=\"position:absolute;left:534px;top:69px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_44\" class=\"drag\" style=\"position:absolute;left:562px;top:69px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>M<br></b></nobr>");
write("</p>");
write("<p id=\"p10_45\" class=\"drag\" style=\"position:absolute;left:342px;top:68px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p10_46\" class=\"drag\" style=\"position:absolute;left:313px;top:69px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_47\" class=\"drag\" style=\"position:absolute;left:54px;top:926px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G503<br></b></nobr>");
write("</p>");
write("<p id=\"p10_48\" class=\"drag\" style=\"position:absolute;left:702px;top:26px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Power transistor<br></b></nobr>");
write("</p>");
write("<p id=\"p10_49\" class=\"drag\" style=\"position:absolute;left:406px;top:26px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_50\" class=\"drag\" style=\"position:absolute;left:435px;top:26px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p10_51\" class=\"drag\" style=\"position:absolute;left:95px;top:1004px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Dashboard wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p10_52\" class=\"drag\" style=\"position:absolute;left:88px;top:1003px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p10_53\" class=\"drag\" style=\"position:absolute;left:70px;top:1004px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p10_54\" class=\"drag\" style=\"position:absolute;left:582px;top:862px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_55\" class=\"drag\" style=\"position:absolute;left:614px;top:861px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p10_56\" class=\"drag\" style=\"position:absolute;left:614px;top:826px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p10_57\" class=\"drag\" style=\"position:absolute;left:581px;top:826px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p10_58\" class=\"drag\" style=\"position:absolute;left:614px;top:897px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p10_59\" class=\"drag\" style=\"position:absolute;left:582px;top:897px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_60\" class=\"drag\" style=\"position:absolute;left:418px;top:897px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_61\" class=\"drag\" style=\"position:absolute;left:449px;top:897px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p10_62\" class=\"drag\" style=\"position:absolute;left:416px;top:826px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p10_63\" class=\"drag\" style=\"position:absolute;left:449px;top:826px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p10_64\" class=\"drag\" style=\"position:absolute;left:449px;top:861px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p10_65\" class=\"drag\" style=\"position:absolute;left:418px;top:862px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_66\" class=\"drag\" style=\"position:absolute;left:710px;top:736px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ECM/PCM<br></b></nobr>");
write("</p>");
write("<p id=\"p10_67\" class=\"drag\" style=\"position:absolute;left:582px;top:754px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_68\" class=\"drag\" style=\"position:absolute;left:613px;top:754px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p10_69\" class=\"drag\" style=\"position:absolute;left:613px;top:718px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p10_70\" class=\"drag\" style=\"position:absolute;left:581px;top:719px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p10_71\" class=\"drag\" style=\"position:absolute;left:581px;top:612px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p10_72\" class=\"drag\" style=\"position:absolute;left:613px;top:611px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p10_73\" class=\"drag\" style=\"position:absolute;left:613px;top:647px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p10_74\" class=\"drag\" style=\"position:absolute;left:582px;top:647px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_75\" class=\"drag\" style=\"position:absolute;left:402px;top:1004px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>: Shielding<br></b></nobr>");
write("</p>");
write("<p id=\"p10_76\" class=\"drag\" style=\"position:absolute;left:702px;top:333px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Accessory power socket relay <br>('05 KE model)<br></b></nobr>");
write("</p>");
write("<p id=\"p10_77\" class=\"drag\" style=\"position:absolute;left:710px;top:510px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Gauge <br>control <br>module<br></b></nobr>");
write("</p>");
write("<p id=\"p10_78\" class=\"drag\" style=\"position:absolute;left:710px;top:617px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Gauge <br>control <br>module<br></b></nobr>");
write("</p>");
write("<p id=\"p10_79\" class=\"drag\" style=\"position:absolute;left:217px;top:710px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Junction <br>connector<br></b></nobr>");
write("</p>");
write("<p id=\"p10_80\" class=\"drag\" style=\"position:absolute;left:267px;top:439px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Junction <br>connector<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}