with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:495px;\" coordsize=\"950,495\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:495px;\">");
write("<img id=\"img1\" src=\"../img/SEA5E43D00060845111KBAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:495px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:756px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>8 x 1.25 mm<br>22 N·m<br>(2.2 kgf·m, 16 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:22px;top:432px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PARKING BRAKE<br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:126px;top:105px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PARKING BRAKE LEVER<br></b>Check for smooth<br>operation.<br></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:387px;top:401px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EQUALIZER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:247px;top:447px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(Multipurpose)<br>Sliding surface<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:453px;top:350px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ADJUSTING NUT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:652px;top:392px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PARKING BRAKE CABLE<br></b>Check for stiffness, binding, <br>and damage.<br></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:258px;top:149px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>8 x 1.25 mm<br>22 N·m<br>(2.2 kgf·m, 16 lbf·ft)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}