with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:863px;\" coordsize=\"950,863\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:863px;\">");
write("<img id=\"img1\" src=\"../img/SEA5E00J46127000000MFAD04.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:863px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:702px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HEADREST<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:753px;top:89px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SEAT-BACK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:307px;top:65px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>Release the seat cushion<br>cover from the cushion<br>frame spring.<br></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:644px;top:434px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CLAMP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:84px;top:160px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HOOKS<br>(Five places)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:128px;top:518px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CENTER COVER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:272px;top:775px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SEAT CUSHION<br>FRAME/SEAT TRACKS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:93px;top:720px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT COVER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:747px;top:174px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SEAT-BACK<br>HEATER HARNESS<br>(For some models)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:475px;top:821px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CLIP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:341px;top:384px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CLIP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:444px;top:435px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INNER COVERS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:43px;top:406px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SEAT CUSHION<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:495px;top:530px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>POWER <br>SEAT<br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:708px;top:681px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SWITCH KNOBS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:164px;top:92px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HOOKS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:768px;top:346px;font-weight:normal;font-size:9.1pt;\">");
write("<nobr><b>10 x 1.25 mm<br>47 N·m <br>(4.8 kgf·m, <br>35 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:564px;top:468px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RECLINE MOTOR<br>HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:746px;top:237px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SIDE AIRBAG<br>HARNESS<br>(For some models)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:613px;top:515px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HOOK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:693px;top:546px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CLIP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:686px;top:600px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RECLINE MOTOR HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:646px;top:798px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CLIPS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:556px;top:833px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HEIGHT OUTER COVER<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}