with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:640px; height:950px;\" coordsize=\"640,950\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:640px;height:950px;\">");
write("<img id=\"img1\" src=\"../img/SEA5E24000000000000EBA123.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:640px;height:950px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:71px;top:22px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>PGM−FI System, Immobilizer System<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:125px;top:145px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:275px;top:222px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:275px;top:231px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>(20A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:294px;top:230px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:436px;top:242px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:22px;top:35px;font-weight:normal;font-size:17.6pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:378px;top:201px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>PGM−FI <br>MAIN <br>RELAY 2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:277px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:122px;top:67px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BAT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:250px;top:54px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:189px;top:56px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.1 (GLOW)(70A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:127px;top:167px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:84px;top:168px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.18 (15A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:319px;top:243px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:433px;top:298px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:275px;top:418px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:275px;top:427px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>(20A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:295px;top:426px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:435px;top:383px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:378px;top:341px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>PGM−FI <br>MAIN <br>RELAY 1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:337px;top:409px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:433px;top:438px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:193px;top:655px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:157px;top:655px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:270px;top:655px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLU/ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:221px;top:764px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:156px;top:763px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN/ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:278px;top:763px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:169px;top:709px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>IMMOBILIZER CONTROL UNIT<br>− RECEIVER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:87px;top:695px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>KEY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:260px;top:571px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>IMMOBILIZER<br>INDICATOR <br>‹2−B›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" class=\"drag\" style=\"position:absolute;left:336px;top:655px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" class=\"drag\" style=\"position:absolute;left:335px;top:581px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>ECM<br>‹25−B›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" class=\"drag\" style=\"position:absolute;left:617px;top:470px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" class=\"drag\" style=\"position:absolute;left:585px;top:384px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" class=\"drag\" style=\"position:absolute;left:501px;top:540px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>INERTIA<br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" class=\"drag\" style=\"position:absolute;left:552px;top:470px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" class=\"drag\" style=\"position:absolute;left:618px;top:270px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" class=\"drag\" style=\"position:absolute;left:517px;top:213px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" class=\"drag\" style=\"position:absolute;left:519px;top:287px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" class=\"drag\" style=\"position:absolute;left:128px;top:99px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" class=\"drag\" style=\"position:absolute;left:69px;top:101px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.22(BAT)(100A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" class=\"drag\" style=\"position:absolute;left:88px;top:190px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.7 (10A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" class=\"drag\" style=\"position:absolute;left:126px;top:189px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" class=\"drag\" style=\"position:absolute;left:633px;top:781px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" class=\"drag\" style=\"position:absolute;left:589px;top:780px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" class=\"drag\" style=\"position:absolute;left:593px;top:741px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>DATA LINK CONNECTOR (DLC)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" class=\"drag\" style=\"position:absolute;left:623px;top:666px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RED/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" class=\"drag\" style=\"position:absolute;left:467px;top:735px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" class=\"drag\" style=\"position:absolute;left:159px;top:852px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>PARKING<br>BRAKE<br>SWITCH<br>‹4−C›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" class=\"drag\" style=\"position:absolute;left:629px;top:891px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>G451<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" class=\"drag\" style=\"position:absolute;left:473px;top:495px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" class=\"drag\" style=\"position:absolute;left:473px;top:588px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" class=\"drag\" style=\"position:absolute;left:309px;top:438px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" class=\"drag\" style=\"position:absolute;left:213px;top:338px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.19<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" class=\"drag\" style=\"position:absolute;left:213px;top:347px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>(15A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" class=\"drag\" style=\"position:absolute;left:234px;top:346px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" class=\"drag\" style=\"position:absolute;left:349px;top:762px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>IMOES UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" class=\"drag\" style=\"position:absolute;left:315px;top:729px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" class=\"drag\" style=\"position:absolute;left:383px;top:729px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" class=\"drag\" style=\"position:absolute;left:324px;top:812px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" class=\"drag\" style=\"position:absolute;left:169px;top:829px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" class=\"drag\" style=\"position:absolute;left:280px;top:602px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" class=\"drag\" style=\"position:absolute;left:347px;top:603px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>62<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" class=\"drag\" style=\"position:absolute;left:339px;top:479px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" class=\"drag\" style=\"position:absolute;left:512px;top:620px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" class=\"drag\" style=\"position:absolute;left:591px;top:665px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" class=\"drag\" style=\"position:absolute;left:381px;top:839px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RED/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" class=\"drag\" style=\"position:absolute;left:358px;top:887px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>MULTIPLEX INTEGRATED<br>CONTROL UNIT (MICU) <br>‹14−A›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" class=\"drag\" style=\"position:absolute;left:395px;top:874px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>54<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" class=\"drag\" style=\"position:absolute;left:320px;top:168px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" class=\"drag\" style=\"position:absolute;left:157px;top:239px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" class=\"drag\" style=\"position:absolute;left:613px;top:180px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.18 (15 A) <br>FUSE <br>‹1−C›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" class=\"drag\" style=\"position:absolute;left:630px;top:213px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}