with(document) {
write("<v:group id=\"group2\" class=\"drag\" style=\"position:relative; width:640px; height:950px;\" coordsize=\"640,950\">");
write("<v:rect id=\"rect2\"class=\"drag\"  style=\"width:640px;height:950px;\">");
write("<img id=\"img2\" src=\"../img/SEA5E24000000000000EBA207.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:640px;height:950px;border-color:#ffffff\">");
write("<p id=\"p2_1\" class=\"drag\" style=\"position:absolute;left:91px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" class=\"drag\" style=\"position:absolute;left:535px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" class=\"drag\" style=\"position:absolute;left:342px;top:422px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" class=\"drag\" style=\"position:absolute;left:352px;top:372px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>35<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" class=\"drag\" style=\"position:absolute;left:424px;top:422px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" class=\"drag\" style=\"position:absolute;left:430px;top:362px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>30<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" class=\"drag\" style=\"position:absolute;left:134px;top:610px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" class=\"drag\" style=\"position:absolute;left:162px;top:646px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>ON<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" class=\"drag\" style=\"position:absolute;left:199px;top:646px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LEFT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" class=\"drag\" style=\"position:absolute;left:250px;top:646px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" class=\"drag\" style=\"position:absolute;left:23px;top:641px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" class=\"drag\" style=\"position:absolute;left:1px;top:683px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>FOG<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" class=\"drag\" style=\"position:absolute;left:1px;top:674px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>REAR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" class=\"drag\" style=\"position:absolute;left:344px;top:652px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>PASSING<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" class=\"drag\" style=\"position:absolute;left:295px;top:657px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>DIMMER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" class=\"drag\" style=\"position:absolute;left:292px;top:640px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>HIGH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" class=\"drag\" style=\"position:absolute;left:333px;top:613px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LOW<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" class=\"drag\" style=\"position:absolute;left:374px;top:640px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" class=\"drag\" style=\"position:absolute;left:451px;top:638px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" class=\"drag\" style=\"position:absolute;left:429px;top:610px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" class=\"drag\" style=\"position:absolute;left:413px;top:610px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>(<br></b></nobr>");
write("</p>");
write("<p id=\"p2_22\" class=\"drag\" style=\"position:absolute;left:435px;top:638px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>(<br></b></nobr>");
write("</p>");
write("<p id=\"p2_23\" class=\"drag\" style=\"position:absolute;left:-33px;top:788px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_24\" class=\"drag\" style=\"position:absolute;left:-35px;top:877px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>G5O6<br></b></nobr>");
write("</p>");
write("<p id=\"p2_25\" class=\"drag\" style=\"position:absolute;left:-84px;top:469px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>COMBINATION LIGHTS and WIPER/WASHER SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_26\" class=\"drag\" style=\"position:absolute;left:-128px;top:422px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_27\" class=\"drag\" style=\"position:absolute;left:-45px;top:533px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>COMBINATION SWITCH  CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_28\" class=\"drag\" style=\"position:absolute;left:392px;top:696px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LIGHTING SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_29\" class=\"drag\" style=\"position:absolute;left:-431px;top:311px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>HEADLIGHT <br>WASHER <br>CONTROL <br>UNIT <br>‹5−B›<br></b></nobr>");
write("</p>");
write("<p id=\"p2_30\" class=\"drag\" style=\"position:absolute;left:-385px;top:330px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RELAY CONTROL<br>MODULE <br>‹5−A›<br></b></nobr>");
write("</p>");
write("<p id=\"p2_31\" class=\"drag\" style=\"position:absolute;left:-434px;top:525px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>HEADLIGHT <br>WASHER <br>CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_32\" class=\"drag\" style=\"position:absolute;left:-177px;top:639px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WASHER <br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_33\" class=\"drag\" style=\"position:absolute;left:82px;top:674px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>FRONT/<br>REAR <br>FOG<br></b></nobr>");
write("</p>");
write("<p id=\"p2_34\" class=\"drag\" style=\"position:absolute;left:31px;top:618px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>FRONT <br>FOG<br></b></nobr>");
write("</p>");
write("<p id=\"p2_35\" class=\"drag\" style=\"position:absolute;left:73px;top:707px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>FRONT/<br>REAR <br>FOG LIGHT <br>SWITCH*<sup>3</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p2_36\" class=\"drag\" style=\"position:absolute;left:151px;top:696px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>FRONT <br>FOG LIGHT <br>SWITCH*<sup>4</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p2_37\" class=\"drag\" style=\"position:absolute;left:239px;top:696px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>TURN <br>SIGNAL <br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_38\" class=\"drag\" style=\"position:absolute;left:332px;top:322px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>HEADLIGHTS <br>ADJUSTER <br>CONTROL UNIT <br>‹8−B›<br></b></nobr>");
write("</p>");
write("<p id=\"p2_39\" class=\"drag\" style=\"position:absolute;left:407px;top:330px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RELAY CONTROL<br>MODULE <br>‹5−D›<br></b></nobr>");
write("</p>");
write("<p id=\"p2_40\" class=\"drag\" style=\"position:absolute;left:358px;top:294px;font-weight:normal;font-size:5.3pt;\">");
write("<nobr><b>(With HID)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}