with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:475px; height:320px;\" coordsize=\"475,320\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:475px;height:320px;\">");
write("<img id=\"img1\" src=\"../img/SEA5E44K70100081110FAAD04.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:320px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:272px;top:88px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>RR +B (GRN/YEL)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:246px;top:65px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>RL-GND (RED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:54px;top:88px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>FR +B (GRN/BLK)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:16px;top:64px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>FL-GND (BRN/WHT)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:54px;top:245px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>FL +B (BLU/ORN)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:272px;top:244px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>RL +B (YEL/RED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:54px;top:214px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>FR-GND (PNK)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:273px;top:213px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>RR-GND (BLU/YEL)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:99px;top:15px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>ABS CONTROL UNIT 25P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:137px;top:288px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b></b>Wire side of female terminals<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}