with(document) {
write("<v:group id=\"group8\" class=\"drag\" style=\"position:relative; width:950px; height:1017px;\" coordsize=\"950,1017\">");
write("<v:rect id=\"rect8\"class=\"drag\"  style=\"width:950px;height:1017px;\">");
write("<img id=\"img8\" src=\"../img/SEA5EB3J54260400000EAAD08.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1017px;border-color:#ffffff\">");
write("<p id=\"p8_1\" class=\"drag\" style=\"position:absolute;left:76px;top:71px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p8_2\" class=\"drag\" style=\"position:absolute;left:74px;top:435px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p8_3\" class=\"drag\" style=\"position:absolute;left:172px;top:34px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p8_4\" class=\"drag\" style=\"position:absolute;left:193px;top:419px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.17 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_5\" class=\"drag\" style=\"position:absolute;left:456px;top:434px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_6\" class=\"drag\" style=\"position:absolute;left:686px;top:377px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Driver's power seat recline motor<br></b></nobr>");
write("</p>");
write("<p id=\"p8_7\" class=\"drag\" style=\"position:absolute;left:457px;top:377px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_8\" class=\"drag\" style=\"position:absolute;left:193px;top:362px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.16 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_9\" class=\"drag\" style=\"position:absolute;left:686px;top:160px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(for rear fog light)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_10\" class=\"drag\" style=\"position:absolute;left:193px;top:304px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.15 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_11\" class=\"drag\" style=\"position:absolute;left:458px;top:320px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_12\" class=\"drag\" style=\"position:absolute;left:686px;top:320px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Driver's seat heater and indicator<br></b></nobr>");
write("</p>");
write("<p id=\"p8_13\" class=\"drag\" style=\"position:absolute;left:193px;top:247px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.14 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_14\" class=\"drag\" style=\"position:absolute;left:686px;top:263px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Driver's power seat slide motor<br></b></nobr>");
write("</p>");
write("<p id=\"p8_15\" class=\"drag\" style=\"position:absolute;left:457px;top:263px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p8_16\" class=\"drag\" style=\"position:absolute;left:458px;top:206px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_17\" class=\"drag\" style=\"position:absolute;left:193px;top:190px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.13 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_18\" class=\"drag\" style=\"position:absolute;left:686px;top:513px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Starter solenoid<br></b></nobr>");
write("</p>");
write("<p id=\"p8_19\" class=\"drag\" style=\"position:absolute;left:686px;top:570px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Transmission range switch (A/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_20\" class=\"drag\" style=\"position:absolute;left:686px;top:584px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Clutch switch (M/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_21\" class=\"drag\" style=\"position:absolute;left:461px;top:570px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_22\" class=\"drag\" style=\"position:absolute;left:458px;top:513px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p8_23\" class=\"drag\" style=\"position:absolute;left:58px;top:484px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p8_24\" class=\"drag\" style=\"position:absolute;left:456px;top:663px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_25\" class=\"drag\" style=\"position:absolute;left:686px;top:663px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Door multiplex control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p8_26\" class=\"drag\" style=\"position:absolute;left:76px;top:585px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p8_27\" class=\"drag\" style=\"position:absolute;left:56px;top:634px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p8_28\" class=\"drag\" style=\"position:absolute;left:686px;top:720px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left power window motor<br></b></nobr>");
write("</p>");
write("<p id=\"p8_29\" class=\"drag\" style=\"position:absolute;left:458px;top:720px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_30\" class=\"drag\" style=\"position:absolute;left:293px;top:704px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.24 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_31\" class=\"drag\" style=\"position:absolute;left:293px;top:761px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.26 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_32\" class=\"drag\" style=\"position:absolute;left:458px;top:777px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_33\" class=\"drag\" style=\"position:absolute;left:686px;top:834px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right power window motor<br></b></nobr>");
write("</p>");
write("<p id=\"p8_34\" class=\"drag\" style=\"position:absolute;left:293px;top:819px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.25 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_35\" class=\"drag\" style=\"position:absolute;left:459px;top:834px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p8_36\" class=\"drag\" style=\"position:absolute;left:686px;top:891px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Driver's power window motor<br></b></nobr>");
write("</p>");
write("<p id=\"p8_37\" class=\"drag\" style=\"position:absolute;left:456px;top:891px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p8_38\" class=\"drag\" style=\"position:absolute;left:293px;top:876px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.27 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_39\" class=\"drag\" style=\"position:absolute;left:469px;top:948px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_40\" class=\"drag\" style=\"position:absolute;left:686px;top:948px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Sunroof motor<br></b></nobr>");
write("</p>");
write("<p id=\"p8_41\" class=\"drag\" style=\"position:absolute;left:293px;top:933px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.28 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_42\" class=\"drag\" style=\"position:absolute;left:70px;top:120px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p8_43\" class=\"drag\" style=\"position:absolute;left:686px;top:149px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Multiplex integrated control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p8_44\" class=\"drag\" style=\"position:absolute;left:469px;top:149px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_45\" class=\"drag\" style=\"position:absolute;left:192px;top:133px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.12 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_46\" class=\"drag\" style=\"position:absolute;left:686px;top:206px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Front passenger's power seat <br>recline motor<br></b></nobr>");
write("</p>");
write("<p id=\"p8_47\" class=\"drag\" style=\"position:absolute;left:686px;top:334px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Front passenger's seat heater <br>and indicator<br></b></nobr>");
write("</p>");
write("<p id=\"p8_48\" class=\"drag\" style=\"position:absolute;left:686px;top:434px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Front passenger's power seat <br>slide motor<br></b></nobr>");
write("</p>");
write("<p id=\"p8_49\" class=\"drag\" style=\"position:absolute;left:686px;top:777px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Front passenger's power <br>window motor<br></b></nobr>");
write("</p>");
write("<p id=\"p8_50\" class=\"drag\" style=\"position:absolute;left:193px;top:625px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>POWER <br>WINDOW RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p8_51\" class=\"drag\" style=\"position:absolute;left:45px;top:543px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.23 (P/W) (40 A) <br>UNDER−HOOD <br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p8_52\" class=\"drag\" style=\"position:absolute;left:193px;top:468px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>STARTER <br>CUT RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p8_53\" class=\"drag\" style=\"position:absolute;left:53px;top:404px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>IGNITION <br>SWITCH (ST)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_54\" class=\"drag\" style=\"position:absolute;left:45px;top:29px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.20 (40 A) <br>UNDER−HOOD <br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}