with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:475px; height:673px;\" coordsize=\"475,673\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:475px;height:673px;\">");
write("<img id=\"img1\" src=\"../img/SEA5E43J54400048101KBAD03.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:673px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:145px;top:162px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>2 mm<br>(0.08 in.)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:73px;top:17px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>2 mm<br>(0.08 in.)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:1px;top:62px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>13 mm<br>(0.51 in.)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:84px;top:103px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>8 mm<br>(0.31 in.)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:369px;top:175px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:198px;top:225px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:210px;top:265px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:236px;top:227px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Inside<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:275px;top:496px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Inside<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:185px;top:628px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>2 mm<br>(0.08 in.)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:284px;top:619px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>2 mm<br>(0.08 in.)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:263px;top:576px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:91px;top:423px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:290px;top:432px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:325px;top:576px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:346px;top:245px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:159px;top:58px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}