with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:847px;\" coordsize=\"950,847\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:847px;\">");
write("<img id=\"img1\" src=\"../img/SEA5EAPE10410600000CAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:847px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:324px;top:19px;font-weight:normal;font-size:7.3pt;\">");
write("<nobr><b>PCM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:23px;top:51px;font-weight:normal;font-size:7.3pt;\">");
write("<nobr><b>Engine RPM Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:23px;top:94px;font-weight:normal;font-size:7.3pt;\">");
write("<nobr><b>Throttle Position <br>Sensor Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:23px;top:141px;font-weight:normal;font-size:7.3pt;\">");
write("<nobr><b>Engine Coolant <br>Temperature Sensor Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:23px;top:188px;font-weight:normal;font-size:7.3pt;\">");
write("<nobr><b>Barometric Pressure <br>Sensor Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:23px;top:234px;font-weight:normal;font-size:7.3pt;\">");
write("<nobr><b>Manifold Absolute <br>Pressure Sensor Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:44px;top:405px;font-weight:normal;font-size:7.3pt;\">");
write("<nobr><b>Transmission<br>Range <br>Switch<br>Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:23px;top:559px;font-weight:normal;font-size:7.3pt;\">");
write("<nobr><b>Input shaft (mainshaft) <br>Speed Sensor Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:24px;top:606px;font-weight:normal;font-size:7.3pt;\">");
write("<nobr><b>Output shaft (countershaft) <br>Speed Sensor Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:23px;top:747px;font-weight:normal;font-size:7.3pt;\">");
write("<nobr><b>Brake Pedal Position <br>Switch Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:287px;top:128px;font-weight:normal;font-size:7.3pt;\">");
write("<nobr><b>PGM-FI Control <br>System<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:276px;top:255px;font-weight:normal;font-size:7.3pt;\">");
write("<nobr><b>A/T Control System<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:310px;top:337px;font-weight:normal;font-size:7.3pt;\">");
write("<nobr><b>Shift Control<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:288px;top:372px;font-weight:normal;font-size:7.3pt;\">");
write("<nobr><b>Grade Logic Control<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:288px;top:389px;font-weight:normal;font-size:7.3pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:299px;top:389px;font-weight:normal;font-size:7.3pt;\">");
write("<nobr><b>Ascending control<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:299px;top:406px;font-weight:normal;font-size:7.3pt;\">");
write("<nobr><b>Descending control<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:288px;top:406px;font-weight:normal;font-size:7.3pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:291px;top:524px;font-weight:normal;font-size:7.3pt;\">");
write("<nobr><b>Clutch Pressure <br>Control<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:290px;top:616px;font-weight:normal;font-size:7.3pt;\">");
write("<nobr><b>Lock-up Control<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:651px;top:115px;font-weight:normal;font-size:7.3pt;\">");
write("<nobr><b>Gauge Control Module<br>A/T Gear Position Indicator<br>Manual Mode <br>Shift Position Indicator<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:524px;top:298px;font-weight:normal;font-size:7.3pt;\">");
write("<nobr><b>Shift Solenoid Valve A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:523px;top:336px;font-weight:normal;font-size:7.3pt;\">");
write("<nobr><b>Shift Solenoid Valve B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:523px;top:486px;font-weight:normal;font-size:7.3pt;\">");
write("<nobr><b>A/T Clutch Pressure <br>Control Solenoid Valve A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:523px;top:524px;font-weight:normal;font-size:7.3pt;\">");
write("<nobr><b>A/T Clutch Pressure <br>Control Solenoid Valve B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:523px;top:671px;font-weight:normal;font-size:7.3pt;\">");
write("<nobr><b>Vehicle Speed Signal <br>Data Link Connector<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:522px;top:736px;font-weight:normal;font-size:7.3pt;\">");
write("<nobr><b>Shift Lock Solenoid<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:763px;top:425px;font-weight:normal;font-size:7.3pt;\">");
write("<nobr><b>Automatic<br>5-speed and <br>Reverse<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:777px;top:651px;font-weight:normal;font-size:7.3pt;\">");
write("<nobr><b>Lock-up<br>Conditions<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:776px;top:602px;font-weight:normal;font-size:7.3pt;\">");
write("<nobr><b>Lock-up <br>ON/OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:23px;top:332px;font-weight:normal;font-size:7.3pt;\">");
write("<nobr><b>Service Check Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:23px;top:280px;font-weight:normal;font-size:7.3pt;\">");
write("<nobr><b>ATF Temperature <br>Sensor Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" class=\"drag\" style=\"position:absolute;left:23px;top:513px;font-weight:normal;font-size:7.3pt;\">");
write("<nobr><b>Transmission Gear <br>Selection Switch Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" class=\"drag\" style=\"position:absolute;left:23px;top:654px;font-weight:normal;font-size:7.3pt;\">");
write("<nobr><b>2nd Clutch Pressure <br>Switch Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" class=\"drag\" style=\"position:absolute;left:23px;top:700px;font-weight:normal;font-size:7.3pt;\">");
write("<nobr><b>3rd Clutch Pressure <br>Switch Signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" class=\"drag\" style=\"position:absolute;left:282px;top:657px;font-weight:normal;font-size:7.3pt;\">");
write("<nobr><b>Self-diagnosis/<br>Fail-safe Function <br>Communication and <br>Output Function<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" class=\"drag\" style=\"position:absolute;left:283px;top:730px;font-weight:normal;font-size:7.3pt;\">");
write("<nobr><b>Shift Lock Control <br>Reverse Lock Control<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" class=\"drag\" style=\"position:absolute;left:523px;top:373px;font-weight:normal;font-size:7.3pt;\">");
write("<nobr><b>Shift Solenoid Valve C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" class=\"drag\" style=\"position:absolute;left:524px;top:563px;font-weight:normal;font-size:7.3pt;\">");
write("<nobr><b>A/T Clutch Pressure <br>Control Solenoid Valve C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" class=\"drag\" style=\"position:absolute;left:523px;top:409px;font-weight:normal;font-size:7.3pt;\">");
write("<nobr><b>Shift Solenoid Valve D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" class=\"drag\" style=\"position:absolute;left:523px;top:445px;font-weight:normal;font-size:7.3pt;\">");
write("<nobr><b>Shift Solenoid Valve E<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" class=\"drag\" style=\"position:absolute;left:508px;top:135px;font-weight:normal;font-size:7.3pt;\">");
write("<nobr><b>Multiplex<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" class=\"drag\" style=\"position:absolute;left:23px;top:794px;font-weight:normal;font-size:7.3pt;\">");
write("<nobr><b>Cruise Control Unit <br>Downshift Request Signal<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}