with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:863px;\" coordsize=\"950,863\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:863px;\">");
write("<img id=\"img1\" src=\"../img/SEA5E44J18533232001DAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:863px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:354px;top:625px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HOOD RELEASE HANDLE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:374px;top:18px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HOOD OPENER CABLE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:687px;top:39px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TAILGATE HANDLE<br>(With power tailgate)<br><a href=\"javascript:parent.Cts('000000000002230','i000')\"></b>Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:730px;top:93px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TAILGATE LATCH<br>(With power tailgate)<br><a href=\"javascript:parent.Cts('000000000002231','i000')\"></b>Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:729px;top:410px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL FILL DOOR LATCH<br><a href=\"javascript:parent.Cts('000000000002211','i040')\"></</a><br></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:450px;top:551px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL FILL DOOR OPENER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:601px;top:484px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL FILL DOOR OPENER CABLE<br><a href=\"javascript:parent.Cts('000000000002211','i000')\"></b>Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:18px;top:584px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HOOD LATCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:425px;top:729px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TAILGATE HANDLE<br>(Without power tailgate)<br><a href=\"javascript:parent.Cts('000000000002230','iR01')\"></b>Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:520px;top:801px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TAILGATE LATCH<br>(Without power tailgate)<br><a href=\"javascript:parent.Cts('000000000002231','iR02')\"></b>Replacement,</a><br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}