with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\" coordsize=\"950,1103\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:1103px;\">");
write("<img id=\"img1\" src=\"../img/SEA5E13A14600000000DAAD03.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:587px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CYLINDER HEAD BOLTS<br><a href=\"javascript:parent.Cts('000000000000533','i000')\"></b>Inspection,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:689px;top:140px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INTAKE VALVE SPRING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:697px;top:191px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INTAKE VALVE SEAL<br><a href=\"javascript:parent.Cts('000000000000546','i000')\"></b>Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:698px;top:255px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INTAKE VALVE GUIDE<br><a href=\"javascript:parent.Cts('000000000000549','i000')\"></b>Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:753px;top:570px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VTC STRAINER COVER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:734px;top:604px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VTC STRAINER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:681px;top:666px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CYLINDER HEAD<br><a href=\"javascript:parent.Cts('000000000002689','i000')\"></b>Removal,</a><br><a href=\"javascript:parent.Cts('000000000000535','i000')\">Inspection,</a><br><a href=\"javascript:parent.Cts('000000000000533','i000')\">Installation,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:682px;top:742px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EXHAUST VALVE<br><a href=\"javascript:parent.Cts('000000000000546','i000')\"></b>Removal,</a><br><a href=\"javascript:parent.Cts('000000000000547','i000')\">Installation,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:682px;top:804px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INTAKE VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:684px;top:867px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CYLINDER HEAD GASKET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:216px;top:1056px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VTEC SOLENOID<br>VALVE FILTER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:62px;top:271px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EXHAUST VALVE<br>SEAL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:63px;top:168px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EXHAUST VALVE<br>SPRING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:291px;top:102px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SPRING<br>RETAINER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:173px;top:103px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VALVE<br>COTTERS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:63px;top:419px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VALVE SPRING<br>SEAT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:62px;top:496px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EXHAUST VALVE<br>GUIDE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:68px;top:682px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HEAT SHIELD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:68px;top:781px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VTEC SOLENOID VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:620px;top:67px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LOST MOTION ASSEMBLY<br>(K24A3 engine)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:336px;top:152px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LOST MOTION<br>ASSEMBLY<br>(K24A3 engine)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}