with(document) {
write("<v:group id=\"group2\" class=\"drag\" style=\"position:relative; width:640px; height:950px;\" coordsize=\"640,950\">");
write("<v:rect id=\"rect2\"class=\"drag\"  style=\"width:640px;height:950px;\">");
write("<img id=\"img2\" src=\"../img/SEA5E44000000000000EBA213.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:640px;height:950px;border-color:#ffffff\">");
write("<p id=\"p2_1\" class=\"drag\" style=\"position:absolute;left:91px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" class=\"drag\" style=\"position:absolute;left:535px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" class=\"drag\" style=\"position:absolute;left:280px;top:879px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>(With super locking)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" class=\"drag\" style=\"position:absolute;left:636px;top:521px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>MULTIPLEX INTEGRATED CONTROL UNIT (MICU)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" class=\"drag\" style=\"position:absolute;left:623px;top:556px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LOCK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" class=\"drag\" style=\"position:absolute;left:215px;top:264px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>+B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" class=\"drag\" style=\"position:absolute;left:214px;top:353px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" class=\"drag\" style=\"position:absolute;left:215px;top:384px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" class=\"drag\" style=\"position:absolute;left:213px;top:428px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>G601<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" class=\"drag\" style=\"position:absolute;left:267px;top:214px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>(With ultrasonic)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" class=\"drag\" style=\"position:absolute;left:-99px;top:801px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LOCK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" class=\"drag\" style=\"position:absolute;left:-27px;top:801px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>UNLOCK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" class=\"drag\" style=\"position:absolute;left:-17px;top:722px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" class=\"drag\" style=\"position:absolute;left:-117px;top:666px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRY/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" class=\"drag\" style=\"position:absolute;left:-92px;top:722px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" class=\"drag\" style=\"position:absolute;left:272px;top:801px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>UNLOCK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" class=\"drag\" style=\"position:absolute;left:200px;top:801px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LOCK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" class=\"drag\" style=\"position:absolute;left:-117px;top:705px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRY/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" class=\"drag\" style=\"position:absolute;left:-128px;top:527px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>MULTIPLEX INTEGRATED CONTROL UNIT (MICU)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" class=\"drag\" style=\"position:absolute;left:-44px;top:234px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" class=\"drag\" style=\"position:absolute;left:-34px;top:312px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_22\" class=\"drag\" style=\"position:absolute;left:-558px;top:23px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>Keyless Entry/Security Alarm System<br></b></nobr>");
write("</p>");
write("<p id=\"p2_23\" class=\"drag\" style=\"position:absolute;left:-380px;top:829px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>DRIVER'S SUPER <br>LOCKING ACTUATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_24\" class=\"drag\" style=\"position:absolute;left:-245px;top:829px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RIGHT REAR <br>SUPER LOCKING <br>ACTUATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_25\" class=\"drag\" style=\"position:absolute;left:-110px;top:829px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>FRONT PASSENGER'S <br>SUPER LOCKING <br>ACTUATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_26\" class=\"drag\" style=\"position:absolute;left:189px;top:829px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>TAILGATE<br>LOCK<br>ACTUATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_27\" class=\"drag\" style=\"position:absolute;left:-175px;top:308px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>SENSOR <br>COM<br></b></nobr>");
write("</p>");
write("<p id=\"p2_28\" class=\"drag\" style=\"position:absolute;left:156px;top:308px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>SENSOR <br>COM<br></b></nobr>");
write("</p>");
write("<p id=\"p2_29\" class=\"drag\" style=\"position:absolute;left:251px;top:238px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>ULTRASONIC <br>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_30\" class=\"drag\" style=\"position:absolute;left:35px;top:801px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LOCK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_31\" class=\"drag\" style=\"position:absolute;left:107px;top:801px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>UNLOCK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_32\" class=\"drag\" style=\"position:absolute;left:116px;top:668px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_33\" class=\"drag\" style=\"position:absolute;left:42px;top:668px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_34\" class=\"drag\" style=\"position:absolute;left:17px;top:705px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRY/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_35\" class=\"drag\" style=\"position:absolute;left:23px;top:829px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LEFT REAR <br>SUPER LOCKING <br>ACTUATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_36\" class=\"drag\" style=\"position:absolute;left:250px;top:862px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>(Without power tailgate)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_37\" class=\"drag\" style=\"position:absolute;left:198px;top:720px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_38\" class=\"drag\" style=\"position:absolute;left:284px;top:720px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_39\" class=\"drag\" style=\"position:absolute;left:43px;top:721px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_40\" class=\"drag\" style=\"position:absolute;left:118px;top:721px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}