with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\" coordsize=\"950,1103\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:1103px;\">");
write("<img id=\"img1\" src=\"../img/SEA5EA0J32100000000DAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:768px;top:100px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MULTI-RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:4px;top:894px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HEADLIGHTS<br><a href=\"javascript:parent.Cts('000000000000198','i000')\"></b>HID Bulb Replacement,<br></a><br><a href=\"javascript:parent.Cts('000000000000196','i000')\">HID Lamp System Troubleshooting,<br></a><br><a href=\"javascript:parent.Cts('000000000000197','i000')\">Replacement,<br></a><br></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:405px;top:946px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT TURN SIGNAL LIGHTS<br><a href=\"javascript:parent.Cts('000000000000197','i000')\"></b>Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:178px;top:160px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT FOG LIGHT RELAY<br><a href=\"javascript:parent.Cts('000000000002908','i000')\"></b>Test,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:618px;top:848px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HEADLIGHT LEVELING MOTOR<br>(With HID Lamp)<br><a href=\"javascript:parent.Cts('000000000000202','i000')\"></b>Input Test,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:618px;top:897px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HEADLIGHT ADJUSTER UNIT<br>(Without HID Lamp)<br><a href=\"javascript:parent.Cts('000000000000205','i000')\"></b>Troubleshooting,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:782px;top:672px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SIDE TURN <br>SIGNAL LIGHT<br><a href=\"javascript:parent.Cts('000000000000206','i000')\"></b>Replacement,<br></a><br></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:673px;top:774px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT HEADLIGHTS ADJUSTER<br>LEVELING SENSOR (With HID Lamp)<br><a href=\"javascript:parent.Cts('000000000000204','i000')\"></b>Replacement,</a><br><a href=\"javascript:parent.Cts('000000000000203','i000')\">Troubleshooting,</a> <br></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:331px;top:997px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HID UNIT<br><a href=\"javascript:parent.Cts('000000000000199','i000')\"></b>Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:152px;top:1023px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT FOG LIGHT<br><a href=\"javascript:parent.Cts('000000000000193','i000')\"></b>Replacement,</a><br><a href=\"javascript:parent.Cts('000000000000194','i000')\">Adjustment,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:674px;top:333px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>UNDER-HOOD FUSE/<br>RELAY BOX<br>(Has built in the relay control module)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:0px;top:1081px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>LHD type is shown, RHD type is similar.<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}