with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1087px;\" coordsize=\"950,1087\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:1087px;\">");
write("<img id=\"img1\" src=\"../img/SEA5E44J16166200000DAAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1087px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:246px;top:263px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CENTER CHANNEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:590px;top:600px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INNER HANDLE CABLE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:690px;top:989px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>COVER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:789px;top:144px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>GLASS RUN CHANNEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:32px;top:676px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>STRIKER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:833px;top:854px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INNER HANDLE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:366px;top:563px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LOCK KNOB<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:437px;top:774px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LATCH PROTECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:438px;top:532px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SPACER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:108px;top:335px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PROTECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:713px;top:12px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>GLASS<br><a href=\"javascript:parent.Cts('000000000002295','i000')\"></b>Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:125px;top:558px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OUTER HANDLE<br><a href=\"javascript:parent.Cts('000000000002203','i000')\"></b>Replacement,<br></a><br></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:693px;top:381px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REGULATOR<br><a href=\"javascript:parent.Cts('000000000002295','i000')\"></b>Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:127px;top:840px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LATCH<br><a href=\"javascript:parent.Cts('000000000002202','i000')\"></b>Replacement,<br></a><br></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:196px;top:1003px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>POWER DOOR<br>LOCK ACTUATOR<br>(with Super Locking)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:458px;top:1019px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR DOOR LOCK<br>CONNECTOR PROTECTOR<br>(with Super Locking)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:403px;top:843px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>POWER DOOR<br>LOCK ACTUATOR<br>(without Super Locking)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:409px;top:706px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OUTER HANDLE ROD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:50px;top:778px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CHILD LOCK CAP<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}