with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:554px;\" coordsize=\"950,554\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:554px;\">");
write("<img id=\"img1\" src=\"../img/SEA5EE8J32100000000EAAD90.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:554px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:745px;top:179px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>27<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:786px;top:406px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>(<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:771px;top:387px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>(<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:781px;top:387px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:907px;top:531px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>G601<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:878px;top:531px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>G601<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:859px;top:179px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>P1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:851px;top:167px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:814px;top:138px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:880px;top:406px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:908px;top:406px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:851px;top:406px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:850px;top:531px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>G502<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:820px;top:336px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:779px;top:260px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:788px;top:290px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:733px;top:259px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:745px;top:290px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:708px;top:260px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:716px;top:290px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:688px;top:290px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:796px;top:406px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:746px;top:407px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:699px;top:390px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LOW<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:672px;top:407px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>HIGH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:674px;top:418px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>DIMMER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:709px;top:411px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>PASSING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:853px;top:138px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SG2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:853px;top:117px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>PG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:774px;top:160px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>B−CAN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:774px;top:138px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>IG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:774px;top:117px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>VBU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" class=\"drag\" style=\"position:absolute;left:719px;top:92px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>No.21<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" class=\"drag\" style=\"position:absolute;left:719px;top:98px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>(7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" class=\"drag\" style=\"position:absolute;left:638px;top:38px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" class=\"drag\" style=\"position:absolute;left:587px;top:18px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>IGNITION SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" class=\"drag\" style=\"position:absolute;left:597px;top:32px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BAT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" class=\"drag\" style=\"position:absolute;left:605px;top:44px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" class=\"drag\" style=\"position:absolute;left:670px;top:18px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" class=\"drag\" style=\"position:absolute;left:821px;top:531px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>G601<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" class=\"drag\" style=\"position:absolute;left:822px;top:406px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" class=\"drag\" style=\"position:absolute;left:682px;top:342px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>COMBINATION SWITCH CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" class=\"drag\" style=\"position:absolute;left:564px;top:38px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" class=\"drag\" style=\"position:absolute;left:565px;top:74px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" class=\"drag\" style=\"position:absolute;left:679px;top:260px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" class=\"drag\" style=\"position:absolute;left:666px;top:440px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>COMBINATION LIGHT SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" class=\"drag\" style=\"position:absolute;left:690px;top:98px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>(10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" class=\"drag\" style=\"position:absolute;left:690px;top:92px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>No.7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" class=\"drag\" style=\"position:absolute;left:422px;top:456px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" class=\"drag\" style=\"position:absolute;left:416px;top:374px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" class=\"drag\" style=\"position:absolute;left:422px;top:485px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" class=\"drag\" style=\"position:absolute;left:421px;top:531px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>G704<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" class=\"drag\" style=\"position:absolute;left:360px;top:531px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>G702<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" class=\"drag\" style=\"position:absolute;left:356px;top:374px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" class=\"drag\" style=\"position:absolute;left:362px;top:485px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" class=\"drag\" style=\"position:absolute;left:328px;top:531px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>G703<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" class=\"drag\" style=\"position:absolute;left:301px;top:456px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" class=\"drag\" style=\"position:absolute;left:295px;top:374px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" class=\"drag\" style=\"position:absolute;left:188px;top:321px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LOW (35 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" class=\"drag\" style=\"position:absolute;left:189px;top:288px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>HID UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" class=\"drag\" style=\"position:absolute;left:49px;top:321px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LOW (35 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" class=\"drag\" style=\"position:absolute;left:50px;top:288px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>HID UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" class=\"drag\" style=\"position:absolute;left:299px;top:531px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>G704<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" class=\"drag\" style=\"position:absolute;left:370px;top:182px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>IG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" class=\"drag\" style=\"position:absolute;left:148px;top:222px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>H10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" class=\"drag\" style=\"position:absolute;left:98px;top:222px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>H8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" class=\"drag\" style=\"position:absolute;left:184px;top:332px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" class=\"drag\" style=\"position:absolute;left:184px;top:268px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" class=\"drag\" style=\"position:absolute;left:148px;top:332px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" class=\"drag\" style=\"position:absolute;left:148px;top:268px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" class=\"drag\" style=\"position:absolute;left:98px;top:332px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" class=\"drag\" style=\"position:absolute;left:98px;top:268px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" class=\"drag\" style=\"position:absolute;left:45px;top:332px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" class=\"drag\" style=\"position:absolute;left:63px;top:268px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" class=\"drag\" style=\"position:absolute;left:90px;top:374px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" class=\"drag\" style=\"position:absolute;left:36px;top:374px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" class=\"drag\" style=\"position:absolute;left:140px;top:374px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" class=\"drag\" style=\"position:absolute;left:176px;top:374px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" class=\"drag\" style=\"position:absolute;left:403px;top:188px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" class=\"drag\" style=\"position:absolute;left:263px;top:245px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" class=\"drag\" style=\"position:absolute;left:404px;top:74px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" class=\"drag\" style=\"position:absolute;left:403px;top:38px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" class=\"drag\" style=\"position:absolute;left:155px;top:305px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>(60 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" class=\"drag\" style=\"position:absolute;left:155px;top:300px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>HIGH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" class=\"drag\" style=\"position:absolute;left:176px;top:485px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" class=\"drag\" style=\"position:absolute;left:174px;top:531px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>G201<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" class=\"drag\" style=\"position:absolute;left:89px;top:531px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>G301<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" class=\"drag\" style=\"position:absolute;left:90px;top:485px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" class=\"drag\" style=\"position:absolute;left:133px;top:245px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" class=\"drag\" style=\"position:absolute;left:169px;top:245px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RED/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" class=\"drag\" style=\"position:absolute;left:150px;top:189px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>No.5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" class=\"drag\" style=\"position:absolute;left:150px;top:195px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>(10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" class=\"drag\" style=\"position:absolute;left:48px;top:245px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RED/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" class=\"drag\" style=\"position:absolute;left:65px;top:195px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>(10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" class=\"drag\" style=\"position:absolute;left:65px;top:189px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>No.1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" class=\"drag\" style=\"position:absolute;left:324px;top:66px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>No.15 (40 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" class=\"drag\" style=\"position:absolute;left:251px;top:64px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>No.4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" class=\"drag\" style=\"position:absolute;left:251px;top:69px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>(15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" class=\"drag\" style=\"position:absolute;left:166px;top:75px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RELAY CONTROL MODULE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" class=\"drag\" style=\"position:absolute;left:184px;top:133px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>CONTROL BLOCK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" class=\"drag\" style=\"position:absolute;left:329px;top:485px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" class=\"drag\" style=\"position:absolute;left:323px;top:374px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" class=\"drag\" style=\"position:absolute;left:384px;top:374px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" class=\"drag\" style=\"position:absolute;left:263px;top:374px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" class=\"drag\" style=\"position:absolute;left:234px;top:374px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" class=\"drag\" style=\"position:absolute;left:206px;top:374px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" class=\"drag\" style=\"position:absolute;left:301px;top:485px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" class=\"drag\" style=\"position:absolute;left:269px;top:456px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" class=\"drag\" style=\"position:absolute;left:390px;top:456px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" class=\"drag\" style=\"position:absolute;left:210px;top:531px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>G301<br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" class=\"drag\" style=\"position:absolute;left:211px;top:485px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" class=\"drag\" style=\"position:absolute;left:319px;top:30px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>No.23 (IG) (50 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" class=\"drag\" style=\"position:absolute;left:240px;top:485px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" class=\"drag\" style=\"position:absolute;left:239px;top:531px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>G201<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" class=\"drag\" style=\"position:absolute;left:48px;top:18px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>UNDER−HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" class=\"drag\" style=\"position:absolute;left:84px;top:245px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>WHT/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" class=\"drag\" style=\"position:absolute;left:105px;top:305px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>(60 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" class=\"drag\" style=\"position:absolute;left:105px;top:300px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>HIGH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_119\" class=\"drag\" style=\"position:absolute;left:186px;top:195px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>(10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_120\" class=\"drag\" style=\"position:absolute;left:186px;top:189px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>No.6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_121\" class=\"drag\" style=\"position:absolute;left:100px;top:189px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>No.3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_122\" class=\"drag\" style=\"position:absolute;left:100px;top:195px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>(10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_123\" class=\"drag\" style=\"position:absolute;left:54px;top:30px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>No.22 (100 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_124\" class=\"drag\" style=\"position:absolute;left:25px;top:25px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BATTERY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_125\" class=\"drag\" style=\"position:absolute;left:105px;top:262px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LEFT <br>HEADLIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_126\" class=\"drag\" style=\"position:absolute;left:191px;top:262px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RIGHT <br>HEADLIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_127\" class=\"drag\" style=\"position:absolute;left:220px;top:422px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LEFT <br>FRONT <br>PARKING <br>LIGHT <br>(5 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_128\" class=\"drag\" style=\"position:absolute;left:248px;top:422px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RIGHT <br>FRONT <br>PARKING <br>LIGHT <br>(5 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_129\" class=\"drag\" style=\"position:absolute;left:277px;top:422px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LEFT <br>TAILLIGHT <br>(5 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_130\" class=\"drag\" style=\"position:absolute;left:309px;top:422px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LEFT <br>LID <br>LIGHT <br>(5 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_131\" class=\"drag\" style=\"position:absolute;left:338px;top:422px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RIGHT <br>TAILLIGHT <br>(5 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_132\" class=\"drag\" style=\"position:absolute;left:370px;top:422px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RIGHT <br>LID <br>LIGHT <br>(5 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_133\" class=\"drag\" style=\"position:absolute;left:398px;top:422px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LEFT<br>LICENSE<br>PLATE<br>LIGHT<br>(5 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_134\" class=\"drag\" style=\"position:absolute;left:431px;top:422px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RIGHT <br>LICENSE <br>PLATE <br>LIGHT <br>(5 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_135\" class=\"drag\" style=\"position:absolute;left:614px;top:237px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>HEADLIGHT ADJUSTER <br>CONTROL UNIT<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}