with(document) {
write("<v:group id=\"group5\" class=\"drag\" style=\"position:relative; width:950px; height:1058px;\" coordsize=\"950,1058\">");
write("<v:rect id=\"rect5\"class=\"drag\"  style=\"width:950px;height:1058px;\">");
write("<img id=\"img5\" src=\"../img/SEA5ED4J54260400000EAAD05.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1058px;border-color:#ffffff\">");
write("<p id=\"p5_1\" class=\"drag\" style=\"position:absolute;left:735px;top:678px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p5_2\" class=\"drag\" style=\"position:absolute;left:763px;top:678px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RELAY CONTROL MODULE<br></b></nobr>");
write("</p>");
write("<p id=\"p5_3\" class=\"drag\" style=\"position:absolute;left:551px;top:677px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p5_4\" class=\"drag\" style=\"position:absolute;left:636px;top:406px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p5_5\" class=\"drag\" style=\"position:absolute;left:635px;top:370px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p5_6\" class=\"drag\" style=\"position:absolute;left:636px;top:341px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p5_7\" class=\"drag\" style=\"position:absolute;left:735px;top:299px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Glow plug control module (IG1)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_8\" class=\"drag\" style=\"position:absolute;left:538px;top:298px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p5_9\" class=\"drag\" style=\"position:absolute;left:735px;top:271px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>VSA modulator−control unit (IG1)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_10\" class=\"drag\" style=\"position:absolute;left:735px;top:256px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ABS modulator−control unit (IG1)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_11\" class=\"drag\" style=\"position:absolute;left:735px;top:528px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Rain sensor<br></b></nobr>");
write("</p>");
write("<p id=\"p5_12\" class=\"drag\" style=\"position:absolute;left:735px;top:513px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Sunroof close relay<br></b></nobr>");
write("</p>");
write("<p id=\"p5_13\" class=\"drag\" style=\"position:absolute;left:735px;top:499px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Sunroof open relay<br></b></nobr>");
write("</p>");
write("<p id=\"p5_14\" class=\"drag\" style=\"position:absolute;left:536px;top:498px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p5_15\" class=\"drag\" style=\"position:absolute;left:537px;top:834px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p5_16\" class=\"drag\" style=\"position:absolute;left:347px;top:885px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.31 (Not used)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_17\" class=\"drag\" style=\"position:absolute;left:356px;top:821px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.29 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_18\" class=\"drag\" style=\"position:absolute;left:735px;top:721px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Door multiplex control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p5_19\" class=\"drag\" style=\"position:absolute;left:551px;top:720px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p5_20\" class=\"drag\" style=\"position:absolute;left:735px;top:635px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Multiplex integrated control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p5_21\" class=\"drag\" style=\"position:absolute;left:735px;top:606px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Combination switch control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p5_22\" class=\"drag\" style=\"position:absolute;left:735px;top:563px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Gauge control module<br></b></nobr>");
write("</p>");
write("<p id=\"p5_23\" class=\"drag\" style=\"position:absolute;left:551px;top:563px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p5_24\" class=\"drag\" style=\"position:absolute;left:356px;top:549px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.21 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_25\" class=\"drag\" style=\"position:absolute;left:735px;top:456px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Windshield washer motor<br></b></nobr>");
write("</p>");
write("<p id=\"p5_26\" class=\"drag\" style=\"position:absolute;left:536px;top:455px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p5_27\" class=\"drag\" style=\"position:absolute;left:356px;top:442px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.20 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_28\" class=\"drag\" style=\"position:absolute;left:735px;top:421px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Mass air flow sensor<br></b></nobr>");
write("</p>");
write("<p id=\"p5_29\" class=\"drag\" style=\"position:absolute;left:735px;top:406px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Alternator<br></b></nobr>");
write("</p>");
write("<p id=\"p5_30\" class=\"drag\" style=\"position:absolute;left:537px;top:406px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p5_31\" class=\"drag\" style=\"position:absolute;left:735px;top:342px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ECM (IG1)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_32\" class=\"drag\" style=\"position:absolute;left:537px;top:341px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p5_33\" class=\"drag\" style=\"position:absolute;left:538px;top:256px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p5_34\" class=\"drag\" style=\"position:absolute;left:358px;top:242px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.18 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_35\" class=\"drag\" style=\"position:absolute;left:548px;top:206px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p5_36\" class=\"drag\" style=\"position:absolute;left:735px;top:206px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Windshield wiper motor<br></b></nobr>");
write("</p>");
write("<p id=\"p5_37\" class=\"drag\" style=\"position:absolute;left:358px;top:192px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.11 (30 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_38\" class=\"drag\" style=\"position:absolute;left:238px;top:380px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p5_39\" class=\"drag\" style=\"position:absolute;left:220px;top:328px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p5_40\" class=\"drag\" style=\"position:absolute;left:88px;top:123px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>IGNITION SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p5_41\" class=\"drag\" style=\"position:absolute;left:89px;top:195px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BAT<br></b></nobr>");
write("</p>");
write("<p id=\"p5_42\" class=\"drag\" style=\"position:absolute;left:219px;top:64px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p5_43\" class=\"drag\" style=\"position:absolute;left:144px;top:145px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p5_44\" class=\"drag\" style=\"position:absolute;left:152px;top:172px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>IG2<br></b></nobr>");
write("</p>");
write("<p id=\"p5_45\" class=\"drag\" style=\"position:absolute;left:149px;top:215px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ACC<br></b></nobr>");
write("</p>");
write("<p id=\"p5_46\" class=\"drag\" style=\"position:absolute;left:142px;top:245px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ST<br></b></nobr>");
write("</p>");
write("<p id=\"p5_47\" class=\"drag\" style=\"position:absolute;left:219px;top:99px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p5_48\" class=\"drag\" style=\"position:absolute;left:165px;top:328px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p5_49\" class=\"drag\" style=\"position:absolute;left:210px;top:157px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p5_50\" class=\"drag\" style=\"position:absolute;left:356px;top:142px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.10 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_51\" class=\"drag\" style=\"position:absolute;left:170px;top:64px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p5_52\" class=\"drag\" style=\"position:absolute;left:184px;top:380px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p5_53\" class=\"drag\" style=\"position:absolute;left:307px;top:23px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p5_54\" class=\"drag\" style=\"position:absolute;left:735px;top:156px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>SRS unit<br></b></nobr>");
write("</p>");
write("<p id=\"p5_55\" class=\"drag\" style=\"position:absolute;left:131px;top:380px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p5_56\" class=\"drag\" style=\"position:absolute;left:112px;top:328px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p5_57\" class=\"drag\" style=\"position:absolute;left:298px;top:945px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p5_58\" class=\"drag\" style=\"position:absolute;left:547px;top:156px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p5_59\" class=\"drag\" style=\"position:absolute;left:533px;top:622px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(Fuse/relay box socket)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_60\" class=\"drag\" style=\"position:absolute;left:735px;top:771px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>SRS unit<br></b></nobr>");
write("</p>");
write("<p id=\"p5_61\" class=\"drag\" style=\"position:absolute;left:535px;top:770px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p5_62\" class=\"drag\" style=\"position:absolute;left:358px;top:756px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.22 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_63\" class=\"drag\" style=\"position:absolute;left:735px;top:370px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ECM <br>(Via brake pedal position switch)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_64\" class=\"drag\" style=\"position:absolute;left:735px;top:577px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Back−up lights <br>(Via back−up light switch)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_65\" class=\"drag\" style=\"position:absolute;left:735px;top:835px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Headlight adjuster unit <br>(Without HID)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_66\" class=\"drag\" style=\"position:absolute;left:735px;top:863px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Headlight adjuster switch light <br>(Without HID)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_67\" class=\"drag\" style=\"position:absolute;left:735px;top:892px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Headlight adjuster control unit <br>(With HID)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_68\" class=\"drag\" style=\"position:absolute;left:71px;top:52px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.23 (IG) (50 A)<br>UNDER−HOOD <br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}