with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:640px; height:950px;\" coordsize=\"640,950\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:640px;height:950px;\">");
write("<img id=\"img1\" src=\"../img/SEA5E13000000000000EBA126.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:640px;height:950px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:277px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:206px;top:-582px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b><br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:138px;top:189px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:98px;top:190px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.7 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:179px;top:190px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:172px;top:145px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:67px;top:101px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.22 (BAT) (100 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:138px;top:100px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:171px;top:167px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:169px;top:112px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:138px;top:166px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:131px;top:145px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:94px;top:167px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.18 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:138px;top:111px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:94px;top:112px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.19 (40 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:72px;top:54px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>K20A6, K24A3 engines (1/3) :<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:72px;top:23px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>PGM−FI System, Immobilizer System<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:632px;top:505px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:185px;top:710px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:185px;top:600px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:190px;top:778px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>90<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:468px;top:627px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:224px;top:570px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:202px;top:571px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>(15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:202px;top:562px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:519px;top:301px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:504px;top:361px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:636px;top:711px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:630px;top:672px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>A/F SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:600px;top:627px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:335px;top:571px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>(7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:359px;top:570px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" class=\"drag\" style=\"position:absolute;left:335px;top:562px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.23<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" class=\"drag\" style=\"position:absolute;left:247px;top:562px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" class=\"drag\" style=\"position:absolute;left:247px;top:571px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>(15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" class=\"drag\" style=\"position:absolute;left:268px;top:570px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" class=\"drag\" style=\"position:absolute;left:556px;top:627px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" class=\"drag\" style=\"position:absolute;left:637px;top:627px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RED/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" class=\"drag\" style=\"position:absolute;left:512px;top:627px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" class=\"drag\" style=\"position:absolute;left:511px;top:877px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>G201<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" class=\"drag\" style=\"position:absolute;left:513px;top:821px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" class=\"drag\" style=\"position:absolute;left:548px;top:505px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" class=\"drag\" style=\"position:absolute;left:505px;top:505px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" class=\"drag\" style=\"position:absolute;left:335px;top:213px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" class=\"drag\" style=\"position:absolute;left:335px;top:222px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>(15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" class=\"drag\" style=\"position:absolute;left:357px;top:221px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" class=\"drag\" style=\"position:absolute;left:308px;top:278px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" class=\"drag\" style=\"position:absolute;left:460px;top:361px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" class=\"drag\" style=\"position:absolute;left:404px;top:627px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" class=\"drag\" style=\"position:absolute;left:413px;top:821px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" class=\"drag\" style=\"position:absolute;left:411px;top:877px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>G603<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" class=\"drag\" style=\"position:absolute;left:427px;top:334px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" class=\"drag\" style=\"position:absolute;left:467px;top:505px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" class=\"drag\" style=\"position:absolute;left:549px;top:334px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" class=\"drag\" style=\"position:absolute;left:593px;top:505px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" class=\"drag\" style=\"position:absolute;left:312px;top:221px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" class=\"drag\" style=\"position:absolute;left:291px;top:222px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>(15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" class=\"drag\" style=\"position:absolute;left:291px;top:213px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.19<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" class=\"drag\" style=\"position:absolute;left:23px;top:35px;font-weight:normal;font-size:17.6pt;\">");
write("<nobr><b>26<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" class=\"drag\" style=\"position:absolute;left:504px;top:683px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" class=\"drag\" style=\"position:absolute;left:303px;top:727px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" class=\"drag\" style=\"position:absolute;left:125px;top:586px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>THROTTLE <br>ACTUATOR <br>CONTROL <br>MODULE RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" class=\"drag\" style=\"position:absolute;left:258px;top:604px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>A/F SENSOR <br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" class=\"drag\" style=\"position:absolute;left:171px;top:801px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>THROTTLE <br>ACTUATOR <br>CONTROL <br>MODULE <br>‹27−D›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" class=\"drag\" style=\"position:absolute;left:374px;top:557px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>PGM−FI <br>MAIN <br>RELAY 2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" class=\"drag\" style=\"position:absolute;left:368px;top:291px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>PGM−FI <br>MAIN <br>RELAY 1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" class=\"drag\" style=\"position:absolute;left:498px;top:268px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>IGNITION <br>COIL RELAY <br>‹2−B›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" class=\"drag\" style=\"position:absolute;left:537px;top:770px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>POWER <br>STEERING <br>PRESSURE <br>(PSP) <br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" class=\"drag\" style=\"position:absolute;left:437px;top:783px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>FUEL <br>PUMP<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}