with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:1900px; height:950px;\" coordsize=\"1900,950\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:1900px;height:950px;\">");
write("<img id=\"img1\" src=\"../img/SEA5E13000000000000EBAD21.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:1900px;height:950px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:132px;top:-579px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b><br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:277px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:721px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:1165px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:1608px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:1679px;top:214px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>*2 : UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:1679px;top:205px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>*1 : UNDER−HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:138px;top:188px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:98px;top:189px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.7 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:1790px;top:188px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:1751px;top:189px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.7 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:1691px;top:145px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:172px;top:145px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:67px;top:101px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.22 (BAT) (100 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:138px;top:100px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:1795px;top:111px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:1751px;top:112px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.19 (40 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:1751px;top:101px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.22 (BAT) (100 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:1821px;top:100px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:171px;top:167px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:169px;top:112px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:138px;top:166px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:131px;top:145px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:94px;top:167px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.18 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:128px;top:67px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BAT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:138px;top:111px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:94px;top:112px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.19 (40 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:1751px;top:67px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BAT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:1751px;top:145px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:1751px;top:167px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.18 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:1690px;top:167px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:1688px;top:112px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" class=\"drag\" style=\"position:absolute;left:1795px;top:166px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" class=\"drag\" style=\"position:absolute;left:1696px;top:238px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: RHD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" class=\"drag\" style=\"position:absolute;left:1684px;top:238px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" class=\"drag\" style=\"position:absolute;left:1684px;top:225px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" class=\"drag\" style=\"position:absolute;left:1696px;top:225px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: LHD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" class=\"drag\" style=\"position:absolute;left:71px;top:23px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>Cruise Control System<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" class=\"drag\" style=\"position:absolute;left:267px;top:594px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" class=\"drag\" style=\"position:absolute;left:190px;top:604px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>86<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" class=\"drag\" style=\"position:absolute;left:313px;top:239px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" class=\"drag\" style=\"position:absolute;left:267px;top:233px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.8 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" class=\"drag\" style=\"position:absolute;left:306px;top:232px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" class=\"drag\" style=\"position:absolute;left:572px;top:535px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>ECM/PCM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" class=\"drag\" style=\"position:absolute;left:1165px;top:700px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>58<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" class=\"drag\" style=\"position:absolute;left:1165px;top:639px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>56<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" class=\"drag\" style=\"position:absolute;left:1520px;top:816px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>‹26−C›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" class=\"drag\" style=\"position:absolute;left:1520px;top:807px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>ECM/PCM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" class=\"drag\" style=\"position:absolute;left:1536px;top:783px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>89<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" class=\"drag\" style=\"position:absolute;left:1337px;top:744px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>88<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" class=\"drag\" style=\"position:absolute;left:1298px;top:744px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>87<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" class=\"drag\" style=\"position:absolute;left:1531px;top:423px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>34<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" class=\"drag\" style=\"position:absolute;left:1476px;top:423px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>38<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" class=\"drag\" style=\"position:absolute;left:1165px;top:423px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>59<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" class=\"drag\" style=\"position:absolute;left:1608px;top:882px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" class=\"drag\" style=\"position:absolute;left:1161px;top:616px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" class=\"drag\" style=\"position:absolute;left:1333px;top:677px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" class=\"drag\" style=\"position:absolute;left:1383px;top:832px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" class=\"drag\" style=\"position:absolute;left:1610px;top:699px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" class=\"drag\" style=\"position:absolute;left:1160px;top:732px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" class=\"drag\" style=\"position:absolute;left:1334px;top:572px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>CRUISE CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" class=\"drag\" style=\"position:absolute;left:1151px;top:516px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" class=\"drag\" style=\"position:absolute;left:1221px;top:516px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" class=\"drag\" style=\"position:absolute;left:1527px;top:516px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" class=\"drag\" style=\"position:absolute;left:1299px;top:516px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" class=\"drag\" style=\"position:absolute;left:1344px;top:516px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" class=\"drag\" style=\"position:absolute;left:1161px;top:832px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" class=\"drag\" style=\"position:absolute;left:1159px;top:882px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>G202<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" class=\"drag\" style=\"position:absolute;left:1377px;top:677px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" class=\"drag\" style=\"position:absolute;left:1381px;top:882px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" class=\"drag\" style=\"position:absolute;left:1532px;top:699px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" class=\"drag\" style=\"position:absolute;left:1449px;top:618px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>(M/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" class=\"drag\" style=\"position:absolute;left:1551px;top:618px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>(A/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" class=\"drag\" style=\"position:absolute;left:875px;top:216px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>HORN SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" class=\"drag\" style=\"position:absolute;left:875px;top:225px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>‹7−C›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" class=\"drag\" style=\"position:absolute;left:894px;top:240px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>53<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" class=\"drag\" style=\"position:absolute;left:842px;top:516px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>‹4−C›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" class=\"drag\" style=\"position:absolute;left:842px;top:508px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GAUGE CONTROL MODULE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" class=\"drag\" style=\"position:absolute;left:982px;top:478px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>37<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" class=\"drag\" style=\"position:absolute;left:932px;top:478px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>28<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" class=\"drag\" style=\"position:absolute;left:849px;top:478px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>29<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" class=\"drag\" style=\"position:absolute;left:661px;top:265px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" class=\"drag\" style=\"position:absolute;left:517px;top:362px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" class=\"drag\" style=\"position:absolute;left:483px;top:362px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" class=\"drag\" style=\"position:absolute;left:262px;top:362px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>57<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" class=\"drag\" style=\"position:absolute;left:190px;top:362px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>59<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" class=\"drag\" style=\"position:absolute;left:576px;top:447px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>DBWRLY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" class=\"drag\" style=\"position:absolute;left:554px;top:417px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" class=\"drag\" style=\"position:absolute;left:616px;top:893px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" class=\"drag\" style=\"position:absolute;left:640px;top:257px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" class=\"drag\" style=\"position:absolute;left:1026px;top:882px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" class=\"drag\" style=\"position:absolute;left:248px;top:417px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" class=\"drag\" style=\"position:absolute;left:176px;top:417px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" class=\"drag\" style=\"position:absolute;left:315px;top:417px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" class=\"drag\" style=\"position:absolute;left:371px;top:417px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" class=\"drag\" style=\"position:absolute;left:177px;top:555px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" class=\"drag\" style=\"position:absolute;left:255px;top:555px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" class=\"drag\" style=\"position:absolute;left:554px;top:339px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" class=\"drag\" style=\"position:absolute;left:623px;top:339px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" class=\"drag\" style=\"position:absolute;left:623px;top:417px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" class=\"drag\" style=\"position:absolute;left:390px;top:555px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" class=\"drag\" style=\"position:absolute;left:324px;top:555px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" class=\"drag\" style=\"position:absolute;left:864px;top:657px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>CPU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" class=\"drag\" style=\"position:absolute;left:782px;top:622px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>5V<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" class=\"drag\" style=\"position:absolute;left:762px;top:630px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>REGULATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" class=\"drag\" style=\"position:absolute;left:662px;top:660px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" class=\"drag\" style=\"position:absolute;left:653px;top:710px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" class=\"drag\" style=\"position:absolute;left:652px;top:749px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RED/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" class=\"drag\" style=\"position:absolute;left:662px;top:793px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" class=\"drag\" style=\"position:absolute;left:661px;top:838px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" class=\"drag\" style=\"position:absolute;left:661px;top:771px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" class=\"drag\" style=\"position:absolute;left:663px;top:855px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" class=\"drag\" style=\"position:absolute;left:492px;top:785px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>TP SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" class=\"drag\" style=\"position:absolute;left:494px;top:884px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>THROTTLE BODY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" class=\"drag\" style=\"position:absolute;left:337px;top:535px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>SEDF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" class=\"drag\" style=\"position:absolute;left:404px;top:535px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>SEFD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" class=\"drag\" style=\"position:absolute;left:199px;top:447px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BKSW<br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" class=\"drag\" style=\"position:absolute;left:271px;top:447px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BKSWNC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_119\" class=\"drag\" style=\"position:absolute;left:716px;top:568px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>SEFD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_120\" class=\"drag\" style=\"position:absolute;left:716px;top:591px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>SEDF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_121\" class=\"drag\" style=\"position:absolute;left:720px;top:652px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>VCC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_122\" class=\"drag\" style=\"position:absolute;left:722px;top:701px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>TH1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_123\" class=\"drag\" style=\"position:absolute;left:722px;top:740px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>TH2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_124\" class=\"drag\" style=\"position:absolute;left:725px;top:762px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>SG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_125\" class=\"drag\" style=\"position:absolute;left:719px;top:846px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_126\" class=\"drag\" style=\"position:absolute;left:478px;top:417px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_127\" class=\"drag\" style=\"position:absolute;left:512px;top:417px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_128\" class=\"drag\" style=\"position:absolute;left:492px;top:447px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>CANH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_129\" class=\"drag\" style=\"position:absolute;left:526px;top:447px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>CANL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_130\" class=\"drag\" style=\"position:absolute;left:880px;top:273px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_131\" class=\"drag\" style=\"position:absolute;left:844px;top:444px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_132\" class=\"drag\" style=\"position:absolute;left:922px;top:444px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_133\" class=\"drag\" style=\"position:absolute;left:1028px;top:605px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_134\" class=\"drag\" style=\"position:absolute;left:1154px;top:197px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>(K20A6 engine)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_135\" class=\"drag\" style=\"position:absolute;left:1054px;top:197px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>(K24A3 engine)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_136\" class=\"drag\" style=\"position:absolute;left:130px;top:555px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_137\" class=\"drag\" style=\"position:absolute;left:134px;top:877px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p1_138\" class=\"drag\" style=\"position:absolute;left:136px;top:816px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_139\" class=\"drag\" style=\"position:absolute;left:203px;top:896px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>(M/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_140\" class=\"drag\" style=\"position:absolute;left:613px;top:295px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_141\" class=\"drag\" style=\"position:absolute;left:769px;top:489px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_142\" class=\"drag\" style=\"position:absolute;left:615px;top:228px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_143\" class=\"drag\" style=\"position:absolute;left:980px;top:452px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_144\" class=\"drag\" style=\"position:absolute;left:967px;top:452px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_145\" class=\"drag\" style=\"position:absolute;left:967px;top:439px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_146\" class=\"drag\" style=\"position:absolute;left:980px;top:439px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_147\" class=\"drag\" style=\"position:absolute;left:1385px;top:455px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_148\" class=\"drag\" style=\"position:absolute;left:1372px;top:455px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_149\" class=\"drag\" style=\"position:absolute;left:1372px;top:469px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_150\" class=\"drag\" style=\"position:absolute;left:1385px;top:469px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_151\" class=\"drag\" style=\"position:absolute;left:1385px;top:530px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_152\" class=\"drag\" style=\"position:absolute;left:1372px;top:530px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_153\" class=\"drag\" style=\"position:absolute;left:1372px;top:516px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_154\" class=\"drag\" style=\"position:absolute;left:1385px;top:516px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_155\" class=\"drag\" style=\"position:absolute;left:1474px;top:469px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_156\" class=\"drag\" style=\"position:absolute;left:1461px;top:469px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_157\" class=\"drag\" style=\"position:absolute;left:1461px;top:455px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_158\" class=\"drag\" style=\"position:absolute;left:1474px;top:455px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_159\" class=\"drag\" style=\"position:absolute;left:1612px;top:516px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_160\" class=\"drag\" style=\"position:absolute;left:1599px;top:516px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_161\" class=\"drag\" style=\"position:absolute;left:1599px;top:530px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_162\" class=\"drag\" style=\"position:absolute;left:1612px;top:530px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_163\" class=\"drag\" style=\"position:absolute;left:1207px;top:627px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_164\" class=\"drag\" style=\"position:absolute;left:1195px;top:627px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_165\" class=\"drag\" style=\"position:absolute;left:1195px;top:640px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_166\" class=\"drag\" style=\"position:absolute;left:1207px;top:641px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: BRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_167\" class=\"drag\" style=\"position:absolute;left:1252px;top:679px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: BRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_168\" class=\"drag\" style=\"position:absolute;left:1239px;top:679px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_169\" class=\"drag\" style=\"position:absolute;left:1239px;top:666px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_170\" class=\"drag\" style=\"position:absolute;left:1252px;top:666px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_171\" class=\"drag\" style=\"position:absolute;left:1296px;top:641px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_172\" class=\"drag\" style=\"position:absolute;left:1283px;top:640px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_173\" class=\"drag\" style=\"position:absolute;left:1283px;top:627px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_174\" class=\"drag\" style=\"position:absolute;left:1296px;top:627px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_175\" class=\"drag\" style=\"position:absolute;left:1257px;top:273px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_176\" class=\"drag\" style=\"position:absolute;left:1270px;top:240px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>53<br></b></nobr>");
write("</p>");
write("<p id=\"p1_177\" class=\"drag\" style=\"position:absolute;left:1252px;top:225px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>‹7−C›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_178\" class=\"drag\" style=\"position:absolute;left:1252px;top:216px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>HORN SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_179\" class=\"drag\" style=\"position:absolute;left:23px;top:35px;font-weight:normal;font-size:17.6pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p1_180\" class=\"drag\" style=\"position:absolute;left:1838px;top:36px;font-weight:normal;font-size:17.6pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p1_181\" class=\"drag\" style=\"position:absolute;left:1698px;top:189px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_182\" class=\"drag\" style=\"position:absolute;left:1699px;top:123px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_183\" class=\"drag\" style=\"position:absolute;left:1797px;top:122px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_184\" class=\"drag\" style=\"position:absolute;left:1751px;top:123px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.21 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_185\" class=\"drag\" style=\"position:absolute;left:179px;top:189px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_186\" class=\"drag\" style=\"position:absolute;left:180px;top:123px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_187\" class=\"drag\" style=\"position:absolute;left:92px;top:123px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.21 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_188\" class=\"drag\" style=\"position:absolute;left:138px;top:122px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_189\" class=\"drag\" style=\"position:absolute;left:292px;top:652px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>(A/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_190\" class=\"drag\" style=\"position:absolute;left:1195px;top:710px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_191\" class=\"drag\" style=\"position:absolute;left:1241px;top:727px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_192\" class=\"drag\" style=\"position:absolute;left:640px;top:266px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>(15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_193\" class=\"drag\" style=\"position:absolute;left:160px;top:742px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>CLUTCH <br>PEDAL <br>POSITION <br>SWITCH <br>(ON : <br>Pedal released)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_194\" class=\"drag\" style=\"position:absolute;left:1407px;top:742px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>CLUTCH <br>PEDAL <br>POSITION <br>SWITCH <br>(ON : <br>Pedal released)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_195\" class=\"drag\" style=\"position:absolute;left:199px;top:323px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BRAKE PEDAL <br>POSITION SWITCH <br>‹9−A›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_196\" class=\"drag\" style=\"position:absolute;left:177px;top:618px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>OUTPUT <br>SHAFT <br>(COUNTER−<br>SHAFT) <br>SPEED <br>SENSOR <br>‹28−C›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_197\" class=\"drag\" style=\"position:absolute;left:243px;top:618px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>TRANSMISSION <br>RANGE SWITCH <br>‹2−D›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_198\" class=\"drag\" style=\"position:absolute;left:470px;top:332px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GAUGE CONTROL <br>MODULE ‹3−B›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_199\" class=\"drag\" style=\"position:absolute;left:409px;top:280px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>PGM−FI <br>MAIN <br>RELAY 1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_200\" class=\"drag\" style=\"position:absolute;left:652px;top:359px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>THROTTLE <br>ACTUATOR <br>CONTROL <br>MODULE <br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_201\" class=\"drag\" style=\"position:absolute;left:775px;top:308px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>CRUISE <br>CONTROL <br>COMBINATION <br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_202\" class=\"drag\" style=\"position:absolute;left:858px;top:319px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>DECEL/<br>SET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_203\" class=\"drag\" style=\"position:absolute;left:903px;top:319px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>CAN−<br>CEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_204\" class=\"drag\" style=\"position:absolute;left:941px;top:319px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RES/<br>ACCEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_205\" class=\"drag\" style=\"position:absolute;left:1041px;top:313px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>CRUISE <br>CONTROL <br>MASTER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_206\" class=\"drag\" style=\"position:absolute;left:1063px;top:391px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>CABLE <br>REEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_207\" class=\"drag\" style=\"position:absolute;left:955px;top:502px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GAUGE CONTROL <br>MODULE ‹5−C›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_208\" class=\"drag\" style=\"position:absolute;left:1147px;top:381px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BRAKE PEDAL <br>POSITION <br>SWITCH <br>‹9−A›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_209\" class=\"drag\" style=\"position:absolute;left:1141px;top:665px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BRAKE PEDAL <br>POSITION <br>SWITCH ‹9−A›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_210\" class=\"drag\" style=\"position:absolute;left:1202px;top:818px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>CRUISE CONTROL <br>ACTUATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_211\" class=\"drag\" style=\"position:absolute;left:1293px;top:768px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>ECM/<br>PCM <br>‹26−C›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_212\" class=\"drag\" style=\"position:absolute;left:1332px;top:768px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>ECM/<br>PCM <br>‹26−C›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_213\" class=\"drag\" style=\"position:absolute;left:1418px;top:391px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>CABLE <br>REEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_214\" class=\"drag\" style=\"position:absolute;left:1463px;top:381px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GAUGE <br>CONTROL <br>MODULE <br>‹5−C›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_215\" class=\"drag\" style=\"position:absolute;left:1512px;top:381px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>CRUISE <br>CONTROL <br>INDICATOR <br>‹5−B›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_216\" class=\"drag\" style=\"position:absolute;left:1235px;top:319px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>DECEL/<br>SET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_217\" class=\"drag\" style=\"position:absolute;left:1280px;top:319px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>CAN−<br>CEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_218\" class=\"drag\" style=\"position:absolute;left:1318px;top:319px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RES/<br>ACCEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_219\" class=\"drag\" style=\"position:absolute;left:1396px;top:313px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>CRUISE <br>CONTROL <br>MASTER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_220\" class=\"drag\" style=\"position:absolute;left:1446px;top:313px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>CRUISE <br>CONTROL <br>COMBINATION <br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_221\" class=\"drag\" style=\"position:absolute;left:914px;top:884px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>THROTTLE ACTUATOR <br>CONTROL MODULE <br></b></nobr>");
write("</p>");
write("<p id=\"p1_222\" class=\"drag\" style=\"position:absolute;left:492px;top:845px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>THROTTLE <br>ACTUATOR<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}