with(document) {
write("<v:group id=\"group2\" class=\"drag\" style=\"position:relative; width:950px; height:1087px;\" coordsize=\"950,1087\">");
write("<v:rect id=\"rect2\"class=\"drag\"  style=\"width:950px;height:1087px;\">");
write("<img id=\"img2\" src=\"../img/SEA5EA0J22100000000DAAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1087px;border-color:#ffffff\">");
write("<p id=\"p2_1\" class=\"drag\" style=\"position:absolute;left:790px;top:692px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SAFETY INDICATOR<br><a href=\"javascript:parent.Cts('000000000000189','i000')\"></</a><br></nobr>");
write("</p>");
write("<p id=\"p2_2\" class=\"drag\" style=\"position:absolute;left:307px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" class=\"drag\" style=\"position:absolute;left:607px;top:15px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" class=\"drag\" style=\"position:absolute;left:264px;top:72px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>B1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" class=\"drag\" style=\"position:absolute;left:430px;top:71px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>B14<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" class=\"drag\" style=\"position:absolute;left:244px;top:222px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>B15<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" class=\"drag\" style=\"position:absolute;left:423px;top:222px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>B30<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" class=\"drag\" style=\"position:absolute;left:596px;top:77px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" class=\"drag\" style=\"position:absolute;left:689px;top:77px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A10<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" class=\"drag\" style=\"position:absolute;left:105px;top:1043px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A/T GEAR POSITION<br>INDICATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" class=\"drag\" style=\"position:absolute;left:364px;top:1043px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ODO/TRIP/OUTSIDE AIR<br>TEMPERATURE INDICATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" class=\"drag\" style=\"position:absolute;left:533px;top:1010px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL GAUGE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" class=\"drag\" style=\"position:absolute;left:696px;top:1056px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>COOLANT TEMPERATURE GAUGE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" class=\"drag\" style=\"position:absolute;left:105px;top:707px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TACHOMETER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" class=\"drag\" style=\"position:absolute;left:472px;top:667px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SPEEDOMETER<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}