with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:783px;\" coordsize=\"950,783\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:783px;\">");
write("<img id=\"img1\" src=\"../img/SEA5E43B44100036401KBAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:783px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:300px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>16 x 1.5 mm<br>140 N·m (14.3 kgf·m, 103 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:2px;top:18px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>10 x 1.25 mm<br>38 N·m<br>(3.9 kgf·m, 28 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:22px;top:356px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>KNUCKLE<br></b>Check for deformation<br>and damage.<br></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:280px;top:502px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HUB BEARING UNIT<br></b>Check for faulty movement<br>and wear.<br></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:476px;top:83px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PARKING BRAKE<br>SHOE ASSEMBLY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:543px;top:198px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BRAKE DISC/DRUM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:755px;top:236px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FLAT SCREW<br>6 x 1.0 mm<br>9.8 N·m<br>(1.0 kgf·m, 7.2 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:814px;top:594px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HUB CAP<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:599px;top:591px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SPINDLE NUT<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:599px;top:716px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>Apply a small amount<br>of engine oil to the seating<br>surface of the nut.<br></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:599px;top:623px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>24 x 1.5 mm<br>245 N·m<br>(25.0 kgf·m, 181 lbf·ft)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}