with(document) {
write("<v:group id=\"group8\" class=\"drag\" style=\"position:relative; width:950px; height:1085px;\" coordsize=\"950,1085\">");
write("<v:rect id=\"rect8\"class=\"drag\"  style=\"width:950px;height:1085px;\">");
write("<img id=\"img8\" src=\"../img/SEA5ED3J54260400000EAAD08.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1085px;border-color:#ffffff\">");
write("<p id=\"p8_1\" class=\"drag\" style=\"position:absolute;left:472px;top:446px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_2\" class=\"drag\" style=\"position:absolute;left:208px;top:281px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.32 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_3\" class=\"drag\" style=\"position:absolute;left:189px;top:46px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p8_4\" class=\"drag\" style=\"position:absolute;left:486px;top:296px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_5\" class=\"drag\" style=\"position:absolute;left:703px;top:296px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Audio unit (ACC)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_6\" class=\"drag\" style=\"position:absolute;left:73px;top:267px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_7\" class=\"drag\" style=\"position:absolute;left:487px;top:374px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_8\" class=\"drag\" style=\"position:absolute;left:597px;top:432px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G601<br></b></nobr>");
write("</p>");
write("<p id=\"p8_9\" class=\"drag\" style=\"position:absolute;left:703px;top:446px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Cigarette lighter<br></b></nobr>");
write("</p>");
write("<p id=\"p8_10\" class=\"drag\" style=\"position:absolute;left:212px;top:431px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.9 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_11\" class=\"drag\" style=\"position:absolute;left:87px;top:417px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p8_12\" class=\"drag\" style=\"position:absolute;left:212px;top:481px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.5 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_13\" class=\"drag\" style=\"position:absolute;left:473px;top:496px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p8_14\" class=\"drag\" style=\"position:absolute;left:703px;top:496px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Audio unit (+B)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_15\" class=\"drag\" style=\"position:absolute;left:212px;top:531px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.6 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_16\" class=\"drag\" style=\"position:absolute;left:703px;top:546px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Stereo amplifier (+B)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_17\" class=\"drag\" style=\"position:absolute;left:473px;top:617px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p8_18\" class=\"drag\" style=\"position:absolute;left:703px;top:617px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Front passenger's door courtesy light<br></b></nobr>");
write("</p>");
write("<p id=\"p8_19\" class=\"drag\" style=\"position:absolute;left:473px;top:653px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p8_20\" class=\"drag\" style=\"position:absolute;left:473px;top:703px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p8_21\" class=\"drag\" style=\"position:absolute;left:212px;top:759px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.7 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_22\" class=\"drag\" style=\"position:absolute;left:472px;top:775px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_23\" class=\"drag\" style=\"position:absolute;left:703px;top:818px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Combination switch control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p8_24\" class=\"drag\" style=\"position:absolute;left:703px;top:832px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Gauge control module<br></b></nobr>");
write("</p>");
write("<p id=\"p8_25\" class=\"drag\" style=\"position:absolute;left:703px;top:846px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Immobilizer control unit−receiver<br></b></nobr>");
write("</p>");
write("<p id=\"p8_26\" class=\"drag\" style=\"position:absolute;left:472px;top:933px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(Fuse/relay box socket)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_27\" class=\"drag\" style=\"position:absolute;left:703px;top:946px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Multiplex integrated control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p8_28\" class=\"drag\" style=\"position:absolute;left:212px;top:973px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.8 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_29\" class=\"drag\" style=\"position:absolute;left:90px;top:218px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p8_30\" class=\"drag\" style=\"position:absolute;left:93px;top:368px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p8_31\" class=\"drag\" style=\"position:absolute;left:90px;top:76px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p8_32\" class=\"drag\" style=\"position:absolute;left:700px;top:254px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p8_33\" class=\"drag\" style=\"position:absolute;left:731px;top:252px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNDER−HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p8_34\" class=\"drag\" style=\"position:absolute;left:475px;top:253px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p8_35\" class=\"drag\" style=\"position:absolute;left:703px;top:203px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Recirculation control motor<br></b></nobr>");
write("</p>");
write("<p id=\"p8_36\" class=\"drag\" style=\"position:absolute;left:703px;top:189px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Climate control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p8_37\" class=\"drag\" style=\"position:absolute;left:703px;top:218px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Seat heater relay<br></b></nobr>");
write("</p>");
write("<p id=\"p8_38\" class=\"drag\" style=\"position:absolute;left:491px;top:189px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>*<br></b></nobr>");
write("</p>");
write("<p id=\"p8_39\" class=\"drag\" style=\"position:absolute;left:703px;top:160px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Power mirror defogger<br></b></nobr>");
write("</p>");
write("<p id=\"p8_40\" class=\"drag\" style=\"position:absolute;left:703px;top:146px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Power mirror actuators<br></b></nobr>");
write("</p>");
write("<p id=\"p8_41\" class=\"drag\" style=\"position:absolute;left:208px;top:131px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.30 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_42\" class=\"drag\" style=\"position:absolute;left:75px;top:117px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_43\" class=\"drag\" style=\"position:absolute;left:730px;top:39px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RHD : BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p8_44\" class=\"drag\" style=\"position:absolute;left:730px;top:28px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LHD : WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p8_45\" class=\"drag\" style=\"position:absolute;left:715px;top:28px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>*<br></b></nobr>");
write("</p>");
write("<p id=\"p8_46\" class=\"drag\" style=\"position:absolute;left:703px;top:310px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Navigation display unit<br></b></nobr>");
write("</p>");
write("<p id=\"p8_47\" class=\"drag\" style=\"position:absolute;left:703px;top:325px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Navigation unit<br></b></nobr>");
write("</p>");
write("<p id=\"p8_48\" class=\"drag\" style=\"position:absolute;left:703px;top:860px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Immoes control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p8_49\" class=\"drag\" style=\"position:absolute;left:703px;top:875px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Navigation display unit<br></b></nobr>");
write("</p>");
write("<p id=\"p8_50\" class=\"drag\" style=\"position:absolute;left:703px;top:889px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Navigation unit<br></b></nobr>");
write("</p>");
write("<p id=\"p8_51\" class=\"drag\" style=\"position:absolute;left:703px;top:903px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Ultrasonic sensor<br></b></nobr>");
write("</p>");
write("<p id=\"p8_52\" class=\"drag\" style=\"position:absolute;left:703px;top:917px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Alarm control siren<br></b></nobr>");
write("</p>");
write("<p id=\"p8_53\" class=\"drag\" style=\"position:absolute;left:473px;top:582px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p8_54\" class=\"drag\" style=\"position:absolute;left:703px;top:582px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Driver's door courtesy light<br></b></nobr>");
write("</p>");
write("<p id=\"p8_55\" class=\"drag\" style=\"position:absolute;left:484px;top:546px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p8_56\" class=\"drag\" style=\"position:absolute;left:703px;top:653px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right cargo area light<br></b></nobr>");
write("</p>");
write("<p id=\"p8_57\" class=\"drag\" style=\"position:absolute;left:703px;top:668px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left cargo area light<br></b></nobr>");
write("</p>");
write("<p id=\"p8_58\" class=\"drag\" style=\"position:absolute;left:703px;top:682px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Power tailgate inner switch light<br></b></nobr>");
write("</p>");
write("<p id=\"p8_59\" class=\"drag\" style=\"position:absolute;left:703px;top:703px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Individual map lights<br></b></nobr>");
write("</p>");
write("<p id=\"p8_60\" class=\"drag\" style=\"position:absolute;left:703px;top:718px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Driver's vanity mirror light<br></b></nobr>");
write("</p>");
write("<p id=\"p8_61\" class=\"drag\" style=\"position:absolute;left:703px;top:732px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Passenger's vanity mirror light<br></b></nobr>");
write("</p>");
write("<p id=\"p8_62\" class=\"drag\" style=\"position:absolute;left:703px;top:746px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Ceiling light (With sunroof)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_63\" class=\"drag\" style=\"position:absolute;left:703px;top:775px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Power tailgate control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p8_64\" class=\"drag\" style=\"position:absolute;left:474px;top:989px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p8_65\" class=\"drag\" style=\"position:absolute;left:475px;top:146px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p8_66\" class=\"drag\" style=\"position:absolute;left:485px;top:817px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p8_67\" class=\"drag\" style=\"position:absolute;left:703px;top:339px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Rear accessory power socket relay<br></b></nobr>");
write("</p>");
write("<p id=\"p8_68\" class=\"drag\" style=\"position:absolute;left:703px;top:353px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Accessory power socket relay ('05 KE model)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_69\" class=\"drag\" style=\"position:absolute;left:66px;top:45px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>IGNITION <br>SWITCH (IG2)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_70\" class=\"drag\" style=\"position:absolute;left:66px;top:187px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>IGNITION <br>SWITCH (ACC)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_71\" class=\"drag\" style=\"position:absolute;left:59px;top:326px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.15 (40 A) <br>UNDER−HOOD <br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p8_72\" class=\"drag\" style=\"position:absolute;left:302px;top:326px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>CIGARETTE <br>LIGHTER <br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p8_73\" class=\"drag\" style=\"position:absolute;left:703px;top:989px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Multiplex integrated control unit <br>(+B : door lock)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}