with(document) {
write("<v:group id=\"group7\" class=\"drag\" style=\"position:relative; width:952px; height:1103px;\" coordsize=\"952,1103\">");
write("<v:rect id=\"rect7\"class=\"drag\"  style=\"width:952px;height:1103px;\">");
write("<img id=\"img7\" src=\"../img/SEA5ED3A20300000000DBAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:952px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p7_1\" class=\"drag\" style=\"position:absolute;left:204px;top:299px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>UNDER-DASH<br>FUSE/RELAY BOX (11)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_2\" class=\"drag\" style=\"position:absolute;left:395px;top:300px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>UNDER-DASH<br>FUSE/RELAY BOX (12)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_3\" class=\"drag\" style=\"position:absolute;left:575px;top:287px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>UNDER-DASH<br>FUSE/RELAY <br>BOX (13)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_4\" class=\"drag\" style=\"position:absolute;left:721px;top:287px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>UNDER-DASH<br>FUSE/RELAY <br>BOX (14)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_5\" class=\"drag\" style=\"position:absolute;left:71px;top:287px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>UNDER-DASH<br>FUSE/RELAY<br>BOX (10)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_6\" class=\"drag\" style=\"position:absolute;left:362px;top:415px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>28P JUNCTION<br>CONNECTOR (16)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_7\" class=\"drag\" style=\"position:absolute;left:206px;top:415px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>28P JUNCTION<br>CONNECTOR (15)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_8\" class=\"drag\" style=\"position:absolute;left:152px;top:175px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>GAUGE B (5)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_9\" class=\"drag\" style=\"position:absolute;left:364px;top:164px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>INERTIA <br>SWITCH (6)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_10\" class=\"drag\" style=\"position:absolute;left:480px;top:151px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>BRAKE PEDAL<br>POSITION <br>SWITCH (7)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_11\" class=\"drag\" style=\"position:absolute;left:591px;top:151px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>CLUTCH PEDAL<br>POSITION SWITCH<br>(8) <br></b></nobr>");
write("</p>");
write("<p id=\"p7_12\" class=\"drag\" style=\"position:absolute;left:735px;top:164px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>DATA LINK CONNECTOR<br>(9)**<br></b></nobr>");
write("</p>");
write("<p id=\"p7_13\" class=\"drag\" style=\"position:absolute;left:95px;top:856px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>ECM/PCM A (27)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_14\" class=\"drag\" style=\"position:absolute;left:363px;top:844px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>SHIFT LOCK<br>SOLENOID<br>(28) (A/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_15\" class=\"drag\" style=\"position:absolute;left:548px;top:857px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>SHIFT LEVER<br>(29) (A/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_16\" class=\"drag\" style=\"position:absolute;left:761px;top:694px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>ECM/PCM B (26)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_17\" class=\"drag\" style=\"position:absolute;left:326px;top:694px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>ECM/PCM D (24)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_18\" class=\"drag\" style=\"position:absolute;left:534px;top:694px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>PCM C (25)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_19\" class=\"drag\" style=\"position:absolute;left:81px;top:694px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>ECM/PCM E (23)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_20\" class=\"drag\" style=\"position:absolute;left:599px;top:576px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>13P CONNECTOR (21)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_21\" class=\"drag\" style=\"position:absolute;left:783px;top:564px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>SECONDARY HO2S<br>(SENSOR 2) (22)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_22\" class=\"drag\" style=\"position:absolute;left:423px;top:576px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>12P CONNECTOR (20)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_23\" class=\"drag\" style=\"position:absolute;left:47px;top:576px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>13P CONNECTOR (18)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_24\" class=\"drag\" style=\"position:absolute;left:234px;top:564px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>THROTTLE ACTUATOR<br>CONTROL MODULE (19)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_25\" class=\"drag\" style=\"position:absolute;left:517px;top:402px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>THROTTLE ACTUATOR<br>CONTROL MODULE <br>RELAY (17)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_26\" class=\"drag\" style=\"position:absolute;left:109px;top:15px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>28P JUNCTION<br>CONNECTOR (1)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_27\" class=\"drag\" style=\"position:absolute;left:283px;top:15px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>28P JUNCTION<br>CONNECTOR (2)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_28\" class=\"drag\" style=\"position:absolute;left:455px;top:15px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>28P JUNCTION<br>CONNECTOR (3)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_29\" class=\"drag\" style=\"position:absolute;left:660px;top:16px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>20P CONNECTOR <br>(4)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_30\" class=\"drag\" style=\"position:absolute;left:0px;top:1015px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b></b>NOTE:<br></nobr>");
write("</p>");
write("<p id=\"p7_31\" class=\"drag\" style=\"position:absolute;left:0px;top:1032px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b></b>· Connector with male terminals (double outline): view from terminal side<br>· Connector with female terminals (single outline): view from wire side<br>**: Connector with female terminals (single outline): view from terminal side<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}