with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1087px;\" coordsize=\"950,1087\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:1087px;\">");
write("<img id=\"img1\" src=\"../img/SEA5ED3J54200000000DEAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1087px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:68px;top:139px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MULTI-RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:156px;top:60px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT FOG LIGHT RELAY<br></b>Wire colors: BLU/YEL, BLU/ORN, <br>BLU/BLK and BLU/ORN<br></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:441px;top:106px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BLOWER MOTOR RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:399px;top:140px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ELD UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:685px;top:59px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A/C COMPRESSOR<br>CLUTCH RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:714px;top:106px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR WINDOW<br>DEFOGGER RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:751px;top:161px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RELAY CONTROL MODULE<br>(Built into the<br>under-hood fuse/relay box)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:775px;top:384px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RADIATOR FAN<br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:607px;top:417px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>UNDER-HOOD<br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:418px;top:388px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A/C CONDENSER <br>FAN RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:41px;top:1038px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>UNDER-HOOD SUBFUSE BOX<br>(Except '05 KE model)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:83px;top:388px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ABS MODULATOR-CONTROL UNIT or<br>VSA MODULATOR-CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:647px;top:1035px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MULTI-FUSE BOX<br>('05 KE model)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:0px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>NOTE: LHD type is shown, RHD type is similar.<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}