with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:895px;\" coordsize=\"950,895\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:895px;\">");
write("<img id=\"img1\" src=\"../img/SEA5E00J24200000000DAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:895px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:101px;top:128px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>UNDER-HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:351px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RELAY CONTROL MODULE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:16px;top:754px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HORNS<br><a href=\"javascript:parent.Cts('000000000000172','i000')\"></b>Test/Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:450px;top:789px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CABLE REEL<br><a href=\"javascript:parent.Cts('000000000000124','i000')\"></</a><br></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:737px;top:635px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HORN SWITCH<br><a href=\"javascript:parent.Cts('000000000000171','i000')\"></b>Test,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:594px;top:694px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HORN RELAY<br>(With security alarm system)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:594px;top:726px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b> Wire color: RED, BLU/RED,<br> GRN and RED<br></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:594px;top:757px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b><a href=\"javascript:parent.Cts('000000000002908','i000')\"></b>Test,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:0px;top:864px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>NOTE: LHD type is shown, RHD type is similar.<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}