with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:1900px; height:950px;\" coordsize=\"1900,950\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:1900px;height:950px;\">");
write("<img id=\"img1\" src=\"../img/SEA5E13000000000000EBAD24.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:1900px;height:950px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:277px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:721px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:1165px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:1608px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:205px;top:-582px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b><br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:1679px;top:214px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>*2 : UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:1679px;top:205px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>*1 : UNDER−HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:138px;top:189px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:98px;top:190px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.7 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:179px;top:190px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:1790px;top:189px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:1697px;top:190px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:1751px;top:190px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.7 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:1691px;top:145px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:172px;top:145px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:67px;top:101px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.22 (BAT) (100 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:138px;top:100px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:1795px;top:111px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:1751px;top:112px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.19 (40 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:1751px;top:101px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.22 (BAT) (100 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:1821px;top:100px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:171px;top:168px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:169px;top:112px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:138px;top:167px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:131px;top:145px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:94px;top:168px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.18 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:138px;top:111px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:94px;top:112px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.19 (40 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:1751px;top:145px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:1751px;top:168px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.18 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:1690px;top:168px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:1688px;top:112px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" class=\"drag\" style=\"position:absolute;left:1795px;top:167px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" class=\"drag\" style=\"position:absolute;left:71px;top:23px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>Fan Controls, HVAC (Heater, Ventilation, and Air Conditioning)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" class=\"drag\" style=\"position:absolute;left:1285px;top:328px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" class=\"drag\" style=\"position:absolute;left:1481px;top:511px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" class=\"drag\" style=\"position:absolute;left:1474px;top:450px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" class=\"drag\" style=\"position:absolute;left:1495px;top:389px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>PASSENGER'S AIR MIX CONTROL MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" class=\"drag\" style=\"position:absolute;left:1594px;top:450px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" class=\"drag\" style=\"position:absolute;left:1648px;top:450px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" class=\"drag\" style=\"position:absolute;left:1531px;top:450px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" class=\"drag\" style=\"position:absolute;left:1538px;top:511px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" class=\"drag\" style=\"position:absolute;left:1588px;top:511px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" class=\"drag\" style=\"position:absolute;left:1321px;top:511px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" class=\"drag\" style=\"position:absolute;left:1376px;top:511px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" class=\"drag\" style=\"position:absolute;left:1260px;top:511px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" class=\"drag\" style=\"position:absolute;left:1651px;top:716px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" class=\"drag\" style=\"position:absolute;left:1695px;top:716px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" class=\"drag\" style=\"position:absolute;left:1606px;top:716px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RED/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" class=\"drag\" style=\"position:absolute;left:1562px;top:716px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" class=\"drag\" style=\"position:absolute;left:1473px;top:716px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" class=\"drag\" style=\"position:absolute;left:1517px;top:716px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" class=\"drag\" style=\"position:absolute;left:1526px;top:655px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" class=\"drag\" style=\"position:absolute;left:1483px;top:655px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" class=\"drag\" style=\"position:absolute;left:1571px;top:655px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" class=\"drag\" style=\"position:absolute;left:750px;top:276px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" class=\"drag\" style=\"position:absolute;left:329px;top:276px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" class=\"drag\" style=\"position:absolute;left:152px;top:276px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" class=\"drag\" style=\"position:absolute;left:112px;top:877px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>G301<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" class=\"drag\" style=\"position:absolute;left:114px;top:777px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" class=\"drag\" style=\"position:absolute;left:190px;top:622px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" class=\"drag\" style=\"position:absolute;left:105px;top:622px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLU/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" class=\"drag\" style=\"position:absolute;left:282px;top:622px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" class=\"drag\" style=\"position:absolute;left:130px;top:268px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" class=\"drag\" style=\"position:absolute;left:130px;top:277px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>(20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" class=\"drag\" style=\"position:absolute;left:307px;top:277px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>(20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" class=\"drag\" style=\"position:absolute;left:307px;top:268px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" class=\"drag\" style=\"position:absolute;left:729px;top:268px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.21<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" class=\"drag\" style=\"position:absolute;left:729px;top:277px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>(40 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" class=\"drag\" style=\"position:absolute;left:457px;top:483px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" class=\"drag\" style=\"position:absolute;left:461px;top:517px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>99<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" class=\"drag\" style=\"position:absolute;left:448px;top:541px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>ECM/PCM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" class=\"drag\" style=\"position:absolute;left:526px;top:622px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" class=\"drag\" style=\"position:absolute;left:635px;top:777px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" class=\"drag\" style=\"position:absolute;left:712px;top:777px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" class=\"drag\" style=\"position:absolute;left:710px;top:877px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>G503<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" class=\"drag\" style=\"position:absolute;left:702px;top:483px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" class=\"drag\" style=\"position:absolute;left:736px;top:546px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLOWER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" class=\"drag\" style=\"position:absolute;left:736px;top:554px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" class=\"drag\" style=\"position:absolute;left:704px;top:622px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLU/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" class=\"drag\" style=\"position:absolute;left:801px;top:655px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" class=\"drag\" style=\"position:absolute;left:866px;top:655px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" class=\"drag\" style=\"position:absolute;left:995px;top:683px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" class=\"drag\" style=\"position:absolute;left:1377px;top:683px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" class=\"drag\" style=\"position:absolute;left:1210px;top:683px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" class=\"drag\" style=\"position:absolute;left:1615px;top:655px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" class=\"drag\" style=\"position:absolute;left:1703px;top:655px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" class=\"drag\" style=\"position:absolute;left:1659px;top:655px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" class=\"drag\" style=\"position:absolute;left:1548px;top:772px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>MODE CONTROL MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" class=\"drag\" style=\"position:absolute;left:1165px;top:578px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>HEATER CONTROL PANEL/CLIMATE CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" class=\"drag\" style=\"position:absolute;left:851px;top:456px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LT GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" class=\"drag\" style=\"position:absolute;left:790px;top:456px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" class=\"drag\" style=\"position:absolute;left:826px;top:323px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" class=\"drag\" style=\"position:absolute;left:1067px;top:483px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" class=\"drag\" style=\"position:absolute;left:1058px;top:411px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" class=\"drag\" style=\"position:absolute;left:1071px;top:373px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>48<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" class=\"drag\" style=\"position:absolute;left:1210px;top:483px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" class=\"drag\" style=\"position:absolute;left:1257px;top:450px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>PNK/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" class=\"drag\" style=\"position:absolute;left:1376px;top:450px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" class=\"drag\" style=\"position:absolute;left:1313px;top:450px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>PNK/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" class=\"drag\" style=\"position:absolute;left:191px;top:777px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" class=\"drag\" style=\"position:absolute;left:291px;top:777px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" class=\"drag\" style=\"position:absolute;left:934px;top:655px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" class=\"drag\" style=\"position:absolute;left:932px;top:877px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>G503<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" class=\"drag\" style=\"position:absolute;left:1128px;top:483px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" class=\"drag\" style=\"position:absolute;left:633px;top:877px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>G302<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" class=\"drag\" style=\"position:absolute;left:1232px;top:389px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>DRIVER'S AIR MIX CONTROL MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" class=\"drag\" style=\"position:absolute;left:1094px;top:683px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" class=\"drag\" style=\"position:absolute;left:448px;top:550px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>‹27−B›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" class=\"drag\" style=\"position:absolute;left:189px;top:877px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>G301<br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" class=\"drag\" style=\"position:absolute;left:289px;top:877px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>G201<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" class=\"drag\" style=\"position:absolute;left:1136px;top:383px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>100<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" class=\"drag\" style=\"position:absolute;left:1091px;top:454px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" class=\"drag\" style=\"position:absolute;left:1091px;top:445px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>PRESSURE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" class=\"drag\" style=\"position:absolute;left:1091px;top:436px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>A/C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" class=\"drag\" style=\"position:absolute;left:232px;top:550px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>‹27−B›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" class=\"drag\" style=\"position:absolute;left:232px;top:541px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>ECM/PCM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" class=\"drag\" style=\"position:absolute;left:245px;top:527px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>98<br></b></nobr>");
write("</p>");
write("<p id=\"p1_119\" class=\"drag\" style=\"position:absolute;left:980px;top:212px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>71<br></b></nobr>");
write("</p>");
write("<p id=\"p1_120\" class=\"drag\" style=\"position:absolute;left:800px;top:511px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_121\" class=\"drag\" style=\"position:absolute;left:866px;top:511px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_122\" class=\"drag\" style=\"position:absolute;left:1233px;top:885px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>(With Climate control)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_123\" class=\"drag\" style=\"position:absolute;left:1584px;top:822px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_124\" class=\"drag\" style=\"position:absolute;left:1557px;top:328px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_125\" class=\"drag\" style=\"position:absolute;left:1751px;top:328px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_126\" class=\"drag\" style=\"position:absolute;left:1451px;top:308px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>(With Climate control)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_127\" class=\"drag\" style=\"position:absolute;left:23px;top:35px;font-weight:normal;font-size:17.6pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p1_128\" class=\"drag\" style=\"position:absolute;left:1838px;top:36px;font-weight:normal;font-size:17.6pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p1_129\" class=\"drag\" style=\"position:absolute;left:1696px;top:225px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: LHD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_130\" class=\"drag\" style=\"position:absolute;left:1683px;top:225px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_131\" class=\"drag\" style=\"position:absolute;left:1683px;top:238px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_132\" class=\"drag\" style=\"position:absolute;left:1696px;top:238px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: RHD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_133\" class=\"drag\" style=\"position:absolute;left:240px;top:483px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_134\" class=\"drag\" style=\"position:absolute;left:1009px;top:832px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_135\" class=\"drag\" style=\"position:absolute;left:996px;top:831px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_136\" class=\"drag\" style=\"position:absolute;left:996px;top:818px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_137\" class=\"drag\" style=\"position:absolute;left:1009px;top:818px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_138\" class=\"drag\" style=\"position:absolute;left:1098px;top:818px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_139\" class=\"drag\" style=\"position:absolute;left:1085px;top:818px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_140\" class=\"drag\" style=\"position:absolute;left:1085px;top:831px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_141\" class=\"drag\" style=\"position:absolute;left:1098px;top:832px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_142\" class=\"drag\" style=\"position:absolute;left:1214px;top:818px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_143\" class=\"drag\" style=\"position:absolute;left:1201px;top:818px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_144\" class=\"drag\" style=\"position:absolute;left:1201px;top:831px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_145\" class=\"drag\" style=\"position:absolute;left:1214px;top:832px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_146\" class=\"drag\" style=\"position:absolute;left:1368px;top:822px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_147\" class=\"drag\" style=\"position:absolute;left:1148px;top:862px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_148\" class=\"drag\" style=\"position:absolute;left:1135px;top:861px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_149\" class=\"drag\" style=\"position:absolute;left:1135px;top:848px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_150\" class=\"drag\" style=\"position:absolute;left:1148px;top:848px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_151\" class=\"drag\" style=\"position:absolute;left:1258px;top:848px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_152\" class=\"drag\" style=\"position:absolute;left:1246px;top:848px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_153\" class=\"drag\" style=\"position:absolute;left:1246px;top:861px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_154\" class=\"drag\" style=\"position:absolute;left:1258px;top:862px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_155\" class=\"drag\" style=\"position:absolute;left:1330px;top:687px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_156\" class=\"drag\" style=\"position:absolute;left:1318px;top:687px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_157\" class=\"drag\" style=\"position:absolute;left:1318px;top:674px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_158\" class=\"drag\" style=\"position:absolute;left:1330px;top:674px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_159\" class=\"drag\" style=\"position:absolute;left:931px;top:497px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_160\" class=\"drag\" style=\"position:absolute;left:919px;top:497px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_161\" class=\"drag\" style=\"position:absolute;left:919px;top:510px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_162\" class=\"drag\" style=\"position:absolute;left:931px;top:510px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_163\" class=\"drag\" style=\"position:absolute;left:837px;top:255px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_164\" class=\"drag\" style=\"position:absolute;left:824px;top:255px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_165\" class=\"drag\" style=\"position:absolute;left:824px;top:242px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_166\" class=\"drag\" style=\"position:absolute;left:837px;top:242px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_167\" class=\"drag\" style=\"position:absolute;left:360px;top:273px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_168\" class=\"drag\" style=\"position:absolute;left:215px;top:691px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RADIATOR <br>FAN <br>SWITCH <br>(Closed : <br>Above 93 °C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_169\" class=\"drag\" style=\"position:absolute;left:137px;top:691px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RADIATOR <br>FAN <br>MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_170\" class=\"drag\" style=\"position:absolute;left:315px;top:686px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>A/C <br>CONDENSER <br>FAN <br>MOTOR <br></b></nobr>");
write("</p>");
write("<p id=\"p1_171\" class=\"drag\" style=\"position:absolute;left:215px;top:380px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RADIATOR <br>FAN <br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_172\" class=\"drag\" style=\"position:absolute;left:393px;top:376px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>A/C <br>CONDENSER <br>FAN <br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_173\" class=\"drag\" style=\"position:absolute;left:564px;top:376px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>A/C <br>COMPRESSOR <br>CLUTCH <br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_174\" class=\"drag\" style=\"position:absolute;left:742px;top:380px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLOWER <br>MOTOR <br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_175\" class=\"drag\" style=\"position:absolute;left:808px;top:380px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RECIRCULATION <br>CONTROL <br>MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_176\" class=\"drag\" style=\"position:absolute;left:559px;top:695px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>THERMAL <br>PROTECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_177\" class=\"drag\" style=\"position:absolute;left:559px;top:752px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>A/C <br>COMPRESSOR <br>CLUTCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_178\" class=\"drag\" style=\"position:absolute;left:725px;top:746px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>POWER <br>TRANSISTER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_179\" class=\"drag\" style=\"position:absolute;left:1024px;top:753px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>IN−CAR <br>TEMPERATURE <br>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_180\" class=\"drag\" style=\"position:absolute;left:1119px;top:753px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>OUTSIDE <br>AIR <br>TEMPERATURE <br>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_181\" class=\"drag\" style=\"position:absolute;left:1235px;top:745px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>SUNLIGHT <br>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_182\" class=\"drag\" style=\"position:absolute;left:1401px;top:750px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>EVAPORATOR <br>TEMPERATURE <br>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_183\" class=\"drag\" style=\"position:absolute;left:1047px;top:314px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RELAY <br>CONTROL <br>MODULE <br>(In the under−hood <br>fuse/relay box) <br>‹6−C›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_184\" class=\"drag\" style=\"position:absolute;left:1130px;top:340px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>MPCS <br>UNIT <br>‹15−A›<br></b></nobr>");
write("</p>");
write("<p id=\"p1_185\" class=\"drag\" style=\"position:absolute;left:997px;top:203px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.30 (7.5 A)*<sup>2</sup> <br>FUSE <br>‹11−B›<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}