with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1119px;\" coordsize=\"950,1119\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:1119px;\">");
write("<img id=\"img1\" src=\"../img/SEA5E44A20326428001MAAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1119px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:194px;top:600px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:194px;top:889px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>B:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:566px;top:887px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:580px;top:708px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>105 °<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:698px;top:688px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>10 °<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:374px;top:949px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>90 °<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:296px;top:873px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>There should be no<br>clearance.<br></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:127px;top:1072px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>When installing the fuel fill tube,<br>align the marks on the tube and the line.<br></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:686px;top:922px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>TOP<br></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:590px;top:930px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>Mark<br></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:517px;top:1072px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>Make sure that the clamp is in position<br>within the lever end of it the range shown.<br></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:537px;top:608px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>Make sure that the clamp is in position<br>within the lever end of it the range shown.<br></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:124px;top:364px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>To HAND PRIMER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:60px;top:419px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>To FUEL<br>RETURN HOSE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:544px;top:219px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BASE GASKET<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:619px;top:183px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:563px;top:171px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:506px;top:39px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:672px;top:953px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>90 °<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}