with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:475px; height:417px;\" coordsize=\"475,417\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:475px;height:417px;\">");
write("<img id=\"img1\" src=\"../img/SEA5E00K70400081040FAAD03.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:417px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:122px;top:388px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b></b>Wire side of female terminals<br></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:123px;top:186px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:80px;top:186px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:254px;top:99px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>RED: LHD<br>RED/BLK: RHD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:187px;top:97px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:161px;top:78px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:66px;top:114px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:96px;top:88px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:122px;top:47px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b></b>Wire side of female terminals<br></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:86px;top:372px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>MODE CONTROL MOTOR 7P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:98px;top:261px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:118px;top:308px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:230px;top:216px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:194px;top:189px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>YEL/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:257px;top:241px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:293px;top:307px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>RED/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:269px;top:349px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:151px;top:15px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>AUDIO-HVAC MODULE<br>22P CONNECTOR<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}