with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1007px;\" coordsize=\"950,1007\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:1007px;\">");
write("<img id=\"img1\" src=\"../img/SEA5ED3A20326900000DAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1007px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:418px;top:17px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INJECTORS<br><a href=\"javascript:parent.Cts('000000000000589','i000')\"></b>Replacement,</a><br> in the Shop Manual, P/N 62SEA02A<br></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:546px;top:73px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CAMSHAFT POSITION (CMP) SENSOR B (EXHAUST)<br><a href=\"javascript:parent.Cts('000000000000583','i000')\"></b>Replacement,</a><br> in the Shop Manual, P/N 62SEA02A<br></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:635px;top:138px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ELECTRICAL LOAD DETECTOR (ELD)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:716px;top:625px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ENGINE COOLANT <br>TEMPERATURE (ECT) SENSOR<br><a href=\"javascript:parent.Cts('000000000000586','i000')\"></b>Replacement,</a><br> in the Shop Manual, P/N 62SEA02A<br></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:607px;top:795px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OUTPUT SHAFT (COUNTERSHAFT)<br>SPEED SENSOR (M/T)<br><a href=\"javascript:parent.Cts('000000000000756','i000')\"></b>Replacement,</a><br> in the Shop Manual, P/N 62SEA02A<br></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:480px;top:914px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MANIFOLD ABSOLUTE PRESSURE (MAP) SENSOR <br><a href=\"javascript:parent.Cts('000000000002708','i000')\"></b>Replacement,</a><br> in the Shop Manual, P/N 62SEA02A<br></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:224px;top:842px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>KNOCK SENSOR <br><a href=\"javascript:parent.Cts('000000000000591','i000')\"></b>Replacement,</a><br> in the Shop Manual, P/N 62SEA02A<br></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:14px;top:762px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CRANKSHAFT POSITION (CKP) SENSOR<br><a href=\"javascript:parent.Cts('000000000000584','i000')\"></b>Replacement,</a><br> in the Shop Manual, P/N 62SEA02A<br></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:537px;top:876px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>THROTTLE POSITION (TP) SENSOR (K20A6 engine)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:16px;top:978px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>*: This illustration shows K20A6 engine.<br></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:659px;top:716px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INTAKE AIR TEMPERATURE <br>(IAT) SENSOR<br><a href=\"javascript:parent.Cts('000000000000590','i000')\"></b>Replacement,</a><br> in the Shop Manual, P/N 62SEA02A<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}