with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:475px;\" coordsize=\"950,475\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:475px;\">");
write("<img id=\"img1\" src=\"../img/SEA5ED3D52100000000EAAD90.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:475px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:12px;top:15px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BATTERY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:37px;top:29px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>UNDER-HOOD<br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:12px;top:36px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>+B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:54px;top:44px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>No. 13 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:54px;top:70px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>No. 22 (100 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:54px;top:99px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>No. 23 (50 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:42px;top:163px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>No. 18 (40 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:42px;top:176px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>No. 17 (30 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:194px;top:71px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>UNDER-DASH<br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:107px;top:165px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>C2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:107px;top:178px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>C1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:199px;top:86px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>No. 18 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:250px;top:87px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>C6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:104px;top:30px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BRAKE PEDAL POSITION SWITCH<br>Closed: Brake pedal pressed<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:134px;top:43px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:151px;top:43px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:139px;top:87px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:122px;top:78px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>IGNITION SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:112px;top:92px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:160px;top:92px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:159px;top:50px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:247px;top:202px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>LEFT-FRONT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:247px;top:228px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>RIGHT-FRONT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:247px;top:254px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>LEFT-REAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:247px;top:281px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>RIGHT-REAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:237px;top:230px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:237px;top:217px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:237px;top:204px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:237px;top:191px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:237px;top:256px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:237px;top:243px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:237px;top:283px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" class=\"drag\" style=\"position:absolute;left:237px;top:269px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" class=\"drag\" style=\"position:absolute;left:266px;top:37px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>GAUGE CONTROL MODULE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" class=\"drag\" style=\"position:absolute;left:341px;top:46px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>B13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" class=\"drag\" style=\"position:absolute;left:286px;top:82px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>ABS<br>INDICATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" class=\"drag\" style=\"position:absolute;left:280px;top:61px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BRAKE SYSTEM<br>INDICATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" class=\"drag\" style=\"position:absolute;left:280px;top:47px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>INDICATOR<br>DRIVER CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" class=\"drag\" style=\"position:absolute;left:341px;top:57px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>B12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" class=\"drag\" style=\"position:absolute;left:341px;top:95px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>B24<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" class=\"drag\" style=\"position:absolute;left:341px;top:106px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>B23<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" class=\"drag\" style=\"position:absolute;left:278px;top:124px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>VSA ACTIVATION<br>INDICATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" class=\"drag\" style=\"position:absolute;left:284px;top:103px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>VSA SYSTEM<br>INDICATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" class=\"drag\" style=\"position:absolute;left:341px;top:122px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>B7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" class=\"drag\" style=\"position:absolute;left:396px;top:122px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" class=\"drag\" style=\"position:absolute;left:438px;top:122px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" class=\"drag\" style=\"position:absolute;left:397px;top:115px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>VSA OFF SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" class=\"drag\" style=\"position:absolute;left:359px;top:221px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" class=\"drag\" style=\"position:absolute;left:368px;top:234px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" class=\"drag\" style=\"position:absolute;left:360px;top:248px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" class=\"drag\" style=\"position:absolute;left:368px;top:261px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" class=\"drag\" style=\"position:absolute;left:358px;top:196px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" class=\"drag\" style=\"position:absolute;left:360px;top:287px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" class=\"drag\" style=\"position:absolute;left:359px;top:274px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" class=\"drag\" style=\"position:absolute;left:368px;top:300px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" class=\"drag\" style=\"position:absolute;left:358px;top:209px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" class=\"drag\" style=\"position:absolute;left:437px;top:153px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" class=\"drag\" style=\"position:absolute;left:439px;top:136px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" class=\"drag\" style=\"position:absolute;left:366px;top:99px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" class=\"drag\" style=\"position:absolute;left:67px;top:270px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>DATA LINK<br>CONNECTOR (16P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" class=\"drag\" style=\"position:absolute;left:93px;top:283px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" class=\"drag\" style=\"position:absolute;left:132px;top:271px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>+B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" class=\"drag\" style=\"position:absolute;left:103px;top:287px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" class=\"drag\" style=\"position:absolute;left:95px;top:309px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" class=\"drag\" style=\"position:absolute;left:95px;top:321px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" class=\"drag\" style=\"position:absolute;left:130px;top:342px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" class=\"drag\" style=\"position:absolute;left:95px;top:296px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" class=\"drag\" style=\"position:absolute;left:110px;top:312px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" class=\"drag\" style=\"position:absolute;left:110px;top:325px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" class=\"drag\" style=\"position:absolute;left:149px;top:342px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>G503<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" class=\"drag\" style=\"position:absolute;left:107px;top:44px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>D9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" class=\"drag\" style=\"position:absolute;left:107px;top:86px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>G1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" class=\"drag\" style=\"position:absolute;left:366px;top:169px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" class=\"drag\" style=\"position:absolute;left:359px;top:182px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" class=\"drag\" style=\"position:absolute;left:367px;top:111px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" class=\"drag\" style=\"position:absolute;left:112px;top:50px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" class=\"drag\" style=\"position:absolute;left:108px;top:300px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" class=\"drag\" style=\"position:absolute;left:366px;top:126px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" class=\"drag\" style=\"position:absolute;left:367px;top:50px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" class=\"drag\" style=\"position:absolute;left:222px;top:48px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BRAKE LIGHT<br>MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" class=\"drag\" style=\"position:absolute;left:359px;top:26px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" class=\"drag\" style=\"position:absolute;left:434px;top:93px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>G202<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" class=\"drag\" style=\"position:absolute;left:379px;top:75px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BRAKE FLUID<br>LEVEL SWITCH<br>Closed: Low fluid<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" class=\"drag\" style=\"position:absolute;left:430px;top:66px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" class=\"drag\" style=\"position:absolute;left:430px;top:79px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" class=\"drag\" style=\"position:absolute;left:359px;top:157px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" class=\"drag\" style=\"position:absolute;left:398px;top:62px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" class=\"drag\" style=\"position:absolute;left:364px;top:61px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" class=\"drag\" style=\"position:absolute;left:636px;top:161px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" class=\"drag\" style=\"position:absolute;left:639px;top:154px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>38<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" class=\"drag\" style=\"position:absolute;left:629px;top:199px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>FL +B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" class=\"drag\" style=\"position:absolute;left:626px;top:212px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>FL-GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" class=\"drag\" style=\"position:absolute;left:629px;top:225px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>FR +B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" class=\"drag\" style=\"position:absolute;left:626px;top:238px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>FR-GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" class=\"drag\" style=\"position:absolute;left:628px;top:251px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RL +B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" class=\"drag\" style=\"position:absolute;left:626px;top:264px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RL-GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" class=\"drag\" style=\"position:absolute;left:628px;top:277px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RR +B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" class=\"drag\" style=\"position:absolute;left:625px;top:290px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RR-GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" class=\"drag\" style=\"position:absolute;left:641px;top:166px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" class=\"drag\" style=\"position:absolute;left:625px;top:173px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>+B-FSR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" class=\"drag\" style=\"position:absolute;left:639px;top:179px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" class=\"drag\" style=\"position:absolute;left:626px;top:186px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>+B-MR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" class=\"drag\" style=\"position:absolute;left:641px;top:192px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" class=\"drag\" style=\"position:absolute;left:639px;top:205px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" class=\"drag\" style=\"position:absolute;left:639px;top:218px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" class=\"drag\" style=\"position:absolute;left:639px;top:231px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" class=\"drag\" style=\"position:absolute;left:641px;top:245px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" class=\"drag\" style=\"position:absolute;left:641px;top:257px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" class=\"drag\" style=\"position:absolute;left:641px;top:271px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" class=\"drag\" style=\"position:absolute;left:641px;top:284px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" class=\"drag\" style=\"position:absolute;left:627px;top:303px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>DIAG-K<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" class=\"drag\" style=\"position:absolute;left:639px;top:296px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" class=\"drag\" style=\"position:absolute;left:628px;top:102px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>CAN-H<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" class=\"drag\" style=\"position:absolute;left:639px;top:96px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" class=\"drag\" style=\"position:absolute;left:629px;top:114px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>CAN-L<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" class=\"drag\" style=\"position:absolute;left:639px;top:108px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>30<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" class=\"drag\" style=\"position:absolute;left:672px;top:103px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>CAN <br>CONTROLLER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" class=\"drag\" style=\"position:absolute;left:694px;top:181px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>FAIL-SAFE<br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_119\" class=\"drag\" style=\"position:absolute;left:676px;top:208px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>PUMP MOTOR RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_120\" class=\"drag\" style=\"position:absolute;left:662px;top:242px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>+B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_121\" class=\"drag\" style=\"position:absolute;left:661px;top:256px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_122\" class=\"drag\" style=\"position:absolute;left:679px;top:155px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>5 V <br>REGULATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_123\" class=\"drag\" style=\"position:absolute;left:664px;top:140px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>CPU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_124\" class=\"drag\" style=\"position:absolute;left:666px;top:228px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>ELECTRIC<br>CURRENT<br>LIMITATION<br></b></nobr>");
write("</p>");
write("<p id=\"p1_125\" class=\"drag\" style=\"position:absolute;left:692px;top:244px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>VCC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_126\" class=\"drag\" style=\"position:absolute;left:572px;top:19px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>E11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_127\" class=\"drag\" style=\"position:absolute;left:540px;top:13px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>ECM/PCM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_128\" class=\"drag\" style=\"position:absolute;left:572px;top:26px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>E24<br></b></nobr>");
write("</p>");
write("<p id=\"p1_129\" class=\"drag\" style=\"position:absolute;left:524px;top:19px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>E22<br></b></nobr>");
write("</p>");
write("<p id=\"p1_130\" class=\"drag\" style=\"position:absolute;left:500px;top:26px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_131\" class=\"drag\" style=\"position:absolute;left:593px;top:182px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_132\" class=\"drag\" style=\"position:absolute;left:508px;top:50px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_133\" class=\"drag\" style=\"position:absolute;left:602px;top:234px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_134\" class=\"drag\" style=\"position:absolute;left:602px;top:260px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_135\" class=\"drag\" style=\"position:absolute;left:593px;top:195px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_136\" class=\"drag\" style=\"position:absolute;left:594px;top:287px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_137\" class=\"drag\" style=\"position:absolute;left:594px;top:273px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_138\" class=\"drag\" style=\"position:absolute;left:592px;top:209px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_139\" class=\"drag\" style=\"position:absolute;left:602px;top:299px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_140\" class=\"drag\" style=\"position:absolute;left:593px;top:221px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_141\" class=\"drag\" style=\"position:absolute;left:519px;top:58px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>PARKING<br>BRAKE SWITCH<br>Closed: Parking<br> brake applied<br></b></nobr>");
write("</p>");
write("<p id=\"p1_142\" class=\"drag\" style=\"position:absolute;left:682px;top:221px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_143\" class=\"drag\" style=\"position:absolute;left:602px;top:111px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_144\" class=\"drag\" style=\"position:absolute;left:601px;top:99px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_145\" class=\"drag\" style=\"position:absolute;left:594px;top:247px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_146\" class=\"drag\" style=\"position:absolute;left:601px;top:169px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_147\" class=\"drag\" style=\"position:absolute;left:593px;top:157px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_148\" class=\"drag\" style=\"position:absolute;left:682px;top:29px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>VSA  MODULATOR-CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_149\" class=\"drag\" style=\"position:absolute;left:698px;top:39px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>VSA CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_150\" class=\"drag\" style=\"position:absolute;left:714px;top:51px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>DTC <br>EEPROM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_151\" class=\"drag\" style=\"position:absolute;left:569px;top:390px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>G203<br></b></nobr>");
write("</p>");
write("<p id=\"p1_152\" class=\"drag\" style=\"position:absolute;left:633px;top:349px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_153\" class=\"drag\" style=\"position:absolute;left:639px;top:342px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>32<br></b></nobr>");
write("</p>");
write("<p id=\"p1_154\" class=\"drag\" style=\"position:absolute;left:623px;top:367px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>MR-GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_155\" class=\"drag\" style=\"position:absolute;left:638px;top:360px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>47<br></b></nobr>");
write("</p>");
write("<p id=\"p1_156\" class=\"drag\" style=\"position:absolute;left:713px;top:306px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>TXD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_157\" class=\"drag\" style=\"position:absolute;left:713px;top:325px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RXD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_158\" class=\"drag\" style=\"position:absolute;left:729px;top:179px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>VCC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_159\" class=\"drag\" style=\"position:absolute;left:602px;top:345px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_160\" class=\"drag\" style=\"position:absolute;left:602px;top:364px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_161\" class=\"drag\" style=\"position:absolute;left:696px;top:284px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_162\" class=\"drag\" style=\"position:absolute;left:760px;top:322px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>To SOLENOIDS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_163\" class=\"drag\" style=\"position:absolute;left:762px;top:301px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>PRESSURE<br>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_164\" class=\"drag\" style=\"position:absolute;left:757px;top:336px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>PUMP MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_165\" class=\"drag\" style=\"position:absolute;left:770px;top:354px;font-weight:normal;font-size:4.9pt;\">");
write("<nobr><b>M<br></b></nobr>");
write("</p>");
write("<p id=\"p1_166\" class=\"drag\" style=\"position:absolute;left:755px;top:291px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>MODULATOR UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_167\" class=\"drag\" style=\"position:absolute;left:808px;top:57px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>STR-A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_168\" class=\"drag\" style=\"position:absolute;left:902px;top:51px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_169\" class=\"drag\" style=\"position:absolute;left:808px;top:63px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>43<br></b></nobr>");
write("</p>");
write("<p id=\"p1_170\" class=\"drag\" style=\"position:absolute;left:808px;top:76px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>29<br></b></nobr>");
write("</p>");
write("<p id=\"p1_171\" class=\"drag\" style=\"position:absolute;left:808px;top:89px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>35<br></b></nobr>");
write("</p>");
write("<p id=\"p1_172\" class=\"drag\" style=\"position:absolute;left:808px;top:70px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>STR-B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_173\" class=\"drag\" style=\"position:absolute;left:808px;top:83px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>STR-D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_174\" class=\"drag\" style=\"position:absolute;left:808px;top:96px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>SVCC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_175\" class=\"drag\" style=\"position:absolute;left:808px;top:102px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>33<br></b></nobr>");
write("</p>");
write("<p id=\"p1_176\" class=\"drag\" style=\"position:absolute;left:808px;top:109px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>SGND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_177\" class=\"drag\" style=\"position:absolute;left:808px;top:176px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>YAW<br></b></nobr>");
write("</p>");
write("<p id=\"p1_178\" class=\"drag\" style=\"position:absolute;left:808px;top:169px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>34<br></b></nobr>");
write("</p>");
write("<p id=\"p1_179\" class=\"drag\" style=\"position:absolute;left:808px;top:182px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>37<br></b></nobr>");
write("</p>");
write("<p id=\"p1_180\" class=\"drag\" style=\"position:absolute;left:808px;top:188px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GLAT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_181\" class=\"drag\" style=\"position:absolute;left:910px;top:36px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>STEERING<br>ANGLE<br>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_182\" class=\"drag\" style=\"position:absolute;left:902px;top:63px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_183\" class=\"drag\" style=\"position:absolute;left:902px;top:76px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_184\" class=\"drag\" style=\"position:absolute;left:902px;top:89px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_185\" class=\"drag\" style=\"position:absolute;left:902px;top:102px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_186\" class=\"drag\" style=\"position:absolute;left:901px;top:142px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_187\" class=\"drag\" style=\"position:absolute;left:901px;top:155px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_188\" class=\"drag\" style=\"position:absolute;left:901px;top:169px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_189\" class=\"drag\" style=\"position:absolute;left:902px;top:181px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_190\" class=\"drag\" style=\"position:absolute;left:827px;top:173px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_191\" class=\"drag\" style=\"position:absolute;left:830px;top:185px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_192\" class=\"drag\" style=\"position:absolute;left:808px;top:51px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>28<br></b></nobr>");
write("</p>");
write("<p id=\"p1_193\" class=\"drag\" style=\"position:absolute;left:781px;top:46px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>VCC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_194\" class=\"drag\" style=\"position:absolute;left:790px;top:83px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>VCC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_195\" class=\"drag\" style=\"position:absolute;left:899px;top:122px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>YAW RATE/<br>LATERAL<br>ACCELERATION<br>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_196\" class=\"drag\" style=\"position:absolute;left:721px;top:188px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>5 V <br>REGULATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_197\" class=\"drag\" style=\"position:absolute;left:892px;top:212px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>*1: RHD model<br>*2: LHD model<br></b></nobr>");
write("</p>");
write("<p id=\"p1_198\" class=\"drag\" style=\"position:absolute;left:830px;top:54px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_199\" class=\"drag\" style=\"position:absolute;left:825px;top:67px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_200\" class=\"drag\" style=\"position:absolute;left:825px;top:80px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_201\" class=\"drag\" style=\"position:absolute;left:830px;top:92px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_202\" class=\"drag\" style=\"position:absolute;left:160px;top:199px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>WHEEL SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_203\" class=\"drag\" style=\"position:absolute;left:171px;top:215px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>IC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_204\" class=\"drag\" style=\"position:absolute;left:171px;top:267px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>IC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_205\" class=\"drag\" style=\"position:absolute;left:865px;top:77px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU/GRN *1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_206\" class=\"drag\" style=\"position:absolute;left:865px;top:82px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRY *2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_207\" class=\"drag\" style=\"position:absolute;left:824px;top:104px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRY/WHT *1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_208\" class=\"drag\" style=\"position:absolute;left:824px;top:109px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BRN *2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_209\" class=\"drag\" style=\"position:absolute;left:866px;top:106px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRY/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_210\" class=\"drag\" style=\"position:absolute;left:866px;top:65px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU/YEL *1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_211\" class=\"drag\" style=\"position:absolute;left:866px;top:70px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WHT *2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_212\" class=\"drag\" style=\"position:absolute;left:866px;top:159px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRY/WHT<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}