with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1023px;\" coordsize=\"950,1023\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:1023px;\">");
write("<img id=\"img1\" src=\"../img/SEA5E44A32200000000DAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1023px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:132px;top:929px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OIL PRESSURE SWITCH<br><a href=\"javascript:parent.Cts('000000000002052','i000')\"></b>Switch Test,</a><br><a href=\"javascript:parent.Cts('000000000002043','i000')\">Oil Pressure Test,</a><br><a href=\"javascript:parent.Cts('000000000002053','i000')\">Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:601px;top:842px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OIL FILTER<br><a href=\"javascript:parent.Cts('000000000002049','i000')\"></b>Replacement,<br></a><br></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:700px;top:212px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OIL PUMP<br><a href=\"javascript:parent.Cts('000000000002054','i000')\"></b>Overhaul,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:706px;top:15px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OIL PAN<br><a href=\"javascript:parent.Cts('000000000001976','i000')\"></b>Removal,</a><br><a href=\"javascript:parent.Cts('000000000001977','i000')\">Installation,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:59px;top:232px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BAFFLE PLATE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:771px;top:506px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OIL PUMP<br>CHAIN GUIDE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:739px;top:717px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CRANKSHAFT<br>SPROCKET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:728px;top:264px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OIL PUMP CHAIN<br>TENSIONER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:43px;top:746px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ENGINE OIL<br>COOLER<br><a href=\"javascript:parent.Cts('000000000002048','i000')\"></b>Replacement,<br></a><br></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:114px;top:504px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OIL JETS<br><a href=\"javascript:parent.Cts('000000000002051','i000')\"></b>Inspection,<br></a><br></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:69px;top:426px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OIL JET BOLTS<br><a href=\"javascript:parent.Cts('000000000002051','i000')\"></b>Inspection,<br></a><br></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:687px;top:773px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OIL PUMP CHAIN<br>TENSIONER ARM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:396px;top:958px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OIL FILTER HOUSING<br><a href=\"javascript:parent.Cts('000000000002050','i000')\"></b>Replacement,<br></a><br></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:750px;top:321px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OIL PUMP CHAIN<br><a href=\"javascript:parent.Cts('000000000002056','i000')\"></b>Inspection,<br></a><br><a href=\"javascript:parent.Cts('000000000002055','i000')\">Replacement,<br></a><br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}