with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:815px;\" coordsize=\"950,815\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:815px;\">");
write("<img id=\"img1\" src=\"../img/SEA5E13G10100000000FEAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:815px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:314px;top:716px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>0<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:130px;top:538px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INTAKE<br>PRESSURE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:451px;top:753px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(68)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:451px;top:735px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:531px;top:753px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(77)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:531px;top:735px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>25<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:612px;top:753px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(86)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:612px;top:735px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>30<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:692px;top:753px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(95)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:692px;top:735px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>35<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:830px;top:754px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(°F)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:830px;top:735px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>°C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:772px;top:752px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(104)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:772px;top:735px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>40<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:371px;top:426px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INTAKE<br>PRESSURE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:103px;top:18px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>kPa<br>(kgf/cm<sup>2</sup>)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:107px;top:52px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>[psi]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:208px;top:174px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>kPa<br>(kgf/cm<sup>2</sup>)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:211px;top:209px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>[psi]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:107px;top:150px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>2,000<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:107px;top:166px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(20)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:106px;top:183px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>[280]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:107px;top:71px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>2,500<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:107px;top:87px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(25)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:107px;top:104px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>[360]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:107px;top:230px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>1,500<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:107px;top:247px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(15)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:106px;top:263px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>[210]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:107px;top:309px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>1,000<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:107px;top:325px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(10)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:107px;top:342px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>[140]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:213px;top:309px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>300<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" class=\"drag\" style=\"position:absolute;left:212px;top:325px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(3)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" class=\"drag\" style=\"position:absolute;left:212px;top:341px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>[43]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" class=\"drag\" style=\"position:absolute;left:1px;top:289px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DELIVERY<br>PRESSURE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" class=\"drag\" style=\"position:absolute;left:366px;top:582px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DELIVERY<br>TEMPERATURE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" class=\"drag\" style=\"position:absolute;left:371px;top:294px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DELIVERY<br>PRESSURE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" class=\"drag\" style=\"position:absolute;left:213px;top:231px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>400<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" class=\"drag\" style=\"position:absolute;left:213px;top:247px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(4)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" class=\"drag\" style=\"position:absolute;left:213px;top:263px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>[57]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" class=\"drag\" style=\"position:absolute;left:316px;top:630px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" class=\"drag\" style=\"position:absolute;left:314px;top:647px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(41)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" class=\"drag\" style=\"position:absolute;left:312px;top:213px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(°F)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" class=\"drag\" style=\"position:absolute;left:312px;top:194px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>°C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" class=\"drag\" style=\"position:absolute;left:316px;top:548px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" class=\"drag\" style=\"position:absolute;left:316px;top:564px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(50)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" class=\"drag\" style=\"position:absolute;left:316px;top:468px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" class=\"drag\" style=\"position:absolute;left:315px;top:484px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(59)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" class=\"drag\" style=\"position:absolute;left:316px;top:390px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" class=\"drag\" style=\"position:absolute;left:315px;top:405px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(68)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" class=\"drag\" style=\"position:absolute;left:316px;top:311px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>25<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" class=\"drag\" style=\"position:absolute;left:315px;top:326px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(77)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" class=\"drag\" style=\"position:absolute;left:316px;top:232px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>30<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" class=\"drag\" style=\"position:absolute;left:315px;top:247px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(86)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" class=\"drag\" style=\"position:absolute;left:856px;top:134px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HUMIDITY<br>LEVEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" class=\"drag\" style=\"position:absolute;left:853px;top:329px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HUMIDITY<br>LEVEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" class=\"drag\" style=\"position:absolute;left:854px;top:457px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HUMIDITY<br>LEVEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" class=\"drag\" style=\"position:absolute;left:786px;top:106px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>80 %<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" class=\"drag\" style=\"position:absolute;left:787px;top:396px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>30 %<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" class=\"drag\" style=\"position:absolute;left:787px;top:295px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>80 %<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" class=\"drag\" style=\"position:absolute;left:786px;top:534px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>30 %<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" class=\"drag\" style=\"position:absolute;left:191px;top:688px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DELIVERY<br>TEMPERATURE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" class=\"drag\" style=\"position:absolute;left:469px;top:786px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INTAKE TEMPERATURE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" class=\"drag\" style=\"position:absolute;left:213px;top:390px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>200<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" class=\"drag\" style=\"position:absolute;left:212px;top:406px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(2)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" class=\"drag\" style=\"position:absolute;left:212px;top:422px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>[28]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" class=\"drag\" style=\"position:absolute;left:213px;top:469px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>100<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" class=\"drag\" style=\"position:absolute;left:212px;top:485px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(1)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" class=\"drag\" style=\"position:absolute;left:212px;top:501px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>[14]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" class=\"drag\" style=\"position:absolute;left:229px;top:550px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>0<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" class=\"drag\" style=\"position:absolute;left:787px;top:263px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>80 %<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" class=\"drag\" style=\"position:absolute;left:786px;top:173px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>30 %<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}