with(document) {
write("<v:group id=\"group3\" class=\"drag\" style=\"position:relative; width:640px; height:950px;\" coordsize=\"640,950\">");
write("<v:rect id=\"rect3\"class=\"drag\"  style=\"width:640px;height:950px;\">");
write("<img id=\"img3\" src=\"../img/SEA5E44000000000000EBA314.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:640px;height:950px;border-color:#ffffff\">");
write("<p id=\"p3_1\" class=\"drag\" style=\"position:absolute;left:-94px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p3_2\" class=\"drag\" style=\"position:absolute;left:348px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p3_3\" class=\"drag\" style=\"position:absolute;left:491px;top:101px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.22 (BAT) (100 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_4\" class=\"drag\" style=\"position:absolute;left:429px;top:190px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_5\" class=\"drag\" style=\"position:absolute;left:460px;top:667px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>64<br></b></nobr>");
write("</p>");
write("<p id=\"p3_6\" class=\"drag\" style=\"position:absolute;left:-1184px;top:23px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>Multiplex Integrated Control Unit, Exterior Lights(Rear Fog Light, Back−up Light)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_7\" class=\"drag\" style=\"position:absolute;left:367px;top:783px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_8\" class=\"drag\" style=\"position:absolute;left:366px;top:561px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_9\" class=\"drag\" style=\"position:absolute;left:356px;top:495px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_10\" class=\"drag\" style=\"position:absolute;left:367px;top:400px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_11\" class=\"drag\" style=\"position:absolute;left:259px;top:790px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_12\" class=\"drag\" style=\"position:absolute;left:203px;top:308px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_13\" class=\"drag\" style=\"position:absolute;left:219px;top:342px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.12<br></b></nobr>");
write("</p>");
write("<p id=\"p3_14\" class=\"drag\" style=\"position:absolute;left:217px;top:351px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>(7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_15\" class=\"drag\" style=\"position:absolute;left:238px;top:350px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_16\" class=\"drag\" style=\"position:absolute;left:195px;top:402px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RED/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_17\" class=\"drag\" style=\"position:absolute;left:578px;top:36px;font-weight:normal;font-size:17.6pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p3_18\" class=\"drag\" style=\"position:absolute;left:491px;top:134px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>ACC<br></b></nobr>");
write("</p>");
write("<p id=\"p3_19\" class=\"drag\" style=\"position:absolute;left:428px;top:134px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_20\" class=\"drag\" style=\"position:absolute;left:535px;top:167px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_21\" class=\"drag\" style=\"position:absolute;left:491px;top:168px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.18 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_22\" class=\"drag\" style=\"position:absolute;left:491px;top:145px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_23\" class=\"drag\" style=\"position:absolute;left:491px;top:68px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BAT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_24\" class=\"drag\" style=\"position:absolute;left:561px;top:100px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_25\" class=\"drag\" style=\"position:absolute;left:491px;top:112px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.21 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_26\" class=\"drag\" style=\"position:absolute;left:535px;top:111px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_27\" class=\"drag\" style=\"position:absolute;left:429px;top:145px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_28\" class=\"drag\" style=\"position:absolute;left:491px;top:179px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.15 (30 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_29\" class=\"drag\" style=\"position:absolute;left:535px;top:178px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_30\" class=\"drag\" style=\"position:absolute;left:439px;top:179px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_31\" class=\"drag\" style=\"position:absolute;left:491px;top:190px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.7 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_32\" class=\"drag\" style=\"position:absolute;left:530px;top:189px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_33\" class=\"drag\" style=\"position:absolute;left:248px;top:624px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RED/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_34\" class=\"drag\" style=\"position:absolute;left:-21px;top:280px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_35\" class=\"drag\" style=\"position:absolute;left:-29px;top:402px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_36\" class=\"drag\" style=\"position:absolute;left:420px;top:205px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>*1 : UNDER−HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_37\" class=\"drag\" style=\"position:absolute;left:420px;top:214px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>*2 : UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_38\" class=\"drag\" style=\"position:absolute;left:-450px;top:652px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>MULTIPLEX <br>CONTROL <br>INSPECTION <br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_39\" class=\"drag\" style=\"position:absolute;left:283px;top:692px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>REAR <br>FOG <br>LIGHT <br></b></nobr>");
write("</p>");
write("<p id=\"p3_40\" class=\"drag\" style=\"position:absolute;left:-723px;top:299px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GAUGE <br>CONTROL <br>MODULE <br>‹2−A› <br></b></nobr>");
write("</p>");
write("<p id=\"p3_41\" class=\"drag\" style=\"position:absolute;left:-668px;top:307px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>POWER WINDOW <br>MASTER SWITCH <br>‹12−A› <br></b></nobr>");
write("</p>");
write("<p id=\"p3_42\" class=\"drag\" style=\"position:absolute;left:-592px;top:289px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>COMBINATION <br>SWITCH <br>CONTROL <br>UNIT <br>‹7−B› <br></b></nobr>");
write("</p>");
write("<p id=\"p3_43\" class=\"drag\" style=\"position:absolute;left:-524px;top:307px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RAIN <br>SENSOR <br>‹6−A› <br></b></nobr>");
write("</p>");
write("<p id=\"p3_44\" class=\"drag\" style=\"position:absolute;left:-424px;top:307px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>CEILING <br>LIGHT <br>‹9−C› <br></b></nobr>");
write("</p>");
write("<p id=\"p3_45\" class=\"drag\" style=\"position:absolute;left:-346px;top:289px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>DRIVER'S <br>DOOR <br>COURTESY <br>LIGHT <br>‹9−D› <br></b></nobr>");
write("</p>");
write("<p id=\"p3_46\" class=\"drag\" style=\"position:absolute;left:-199px;top:299px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>REAR WINDOW<br>WIPER MOTOR RELAY<br>‹6−B, C› <br></b></nobr>");
write("</p>");
write("<p id=\"p3_47\" class=\"drag\" style=\"position:absolute;left:8px;top:326px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>IGNITION<br>KEY<br>LIGHT<br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_48\" class=\"drag\" style=\"position:absolute;left:391px;top:430px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BACK−UP <br>LIGHT SWITCH <br>(On the transmission <br>housing) <br>(Closed : In position R) <br></b></nobr>");
write("</p>");
write("<p id=\"p3_49\" class=\"drag\" style=\"position:absolute;left:441px;top:691px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>NAVIGATION <br>UNIT <br>‹23−C›<br></b></nobr>");
write("</p>");
write("<p id=\"p3_50\" class=\"drag\" style=\"position:absolute;left:391px;top:680px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RIGHT <br>(LEFT) <br>BACK−UP <br>LIGHT<br>(21 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_51\" class=\"drag\" style=\"position:absolute;left:432px;top:226px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: LHD<br></b></nobr>");
write("</p>");
write("<p id=\"p3_52\" class=\"drag\" style=\"position:absolute;left:432px;top:239px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: RHD<br></b></nobr>");
write("</p>");
write("<p id=\"p3_53\" class=\"drag\" style=\"position:absolute;left:419px;top:239px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_54\" class=\"drag\" style=\"position:absolute;left:419px;top:226px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_55\" class=\"drag\" style=\"position:absolute;left:431px;top:252px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: LHD With power tailgate <br></b></nobr>");
write("</p>");
write("<p id=\"p3_56\" class=\"drag\" style=\"position:absolute;left:419px;top:252px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_57\" class=\"drag\" style=\"position:absolute;left:431px;top:266px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: LHD Without power tailgate<br></b></nobr>");
write("</p>");
write("<p id=\"p3_58\" class=\"drag\" style=\"position:absolute;left:419px;top:266px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p3_59\" class=\"drag\" style=\"position:absolute;left:-627px;top:684px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>DRIVER'S<br>SEAT BELT<br>SWITCH<br>(Closed : Unbuckled)<br>(Open : Buckled)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_60\" class=\"drag\" style=\"position:absolute;left:-424px;top:278px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>INDIVIDUAL <br>MAP LIGHTS  <br>‹9−C› <br></b></nobr>");
write("</p>");
write("<p id=\"p3_61\" class=\"drag\" style=\"position:absolute;left:491px;top:156px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.20 (40 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_62\" class=\"drag\" style=\"position:absolute;left:535px;top:155px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_63\" class=\"drag\" style=\"position:absolute;left:439px;top:156px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_64\" class=\"drag\" style=\"position:absolute;left:457px;top:631px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_65\" class=\"drag\" style=\"position:absolute;left:-474px;top:289px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>POWER<br>TAILGATE<br>CONTROL<br>UNIT<br>‹16−B› <br></b></nobr>");
write("</p>");
write("<p id=\"p3_66\" class=\"drag\" style=\"position:absolute;left:-152px;top:401px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LT GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_67\" class=\"drag\" style=\"position:absolute;left:-77px;top:340px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>32<br></b></nobr>");
write("</p>");
write("<p id=\"p3_68\" class=\"drag\" style=\"position:absolute;left:-78px;top:401px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_69\" class=\"drag\" style=\"position:absolute;left:-78px;top:414px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_70\" class=\"drag\" style=\"position:absolute;left:-91px;top:414px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_71\" class=\"drag\" style=\"position:absolute;left:-91px;top:400px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_72\" class=\"drag\" style=\"position:absolute;left:367px;top:631px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_73\" class=\"drag\" style=\"position:absolute;left:289px;top:581px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_74\" class=\"drag\" style=\"position:absolute;left:101px;top:667px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>43<br></b></nobr>");
write("</p>");
write("<p id=\"p3_75\" class=\"drag\" style=\"position:absolute;left:167px;top:667px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>44<br></b></nobr>");
write("</p>");
write("<p id=\"p3_76\" class=\"drag\" style=\"position:absolute;left:88px;top:401px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_77\" class=\"drag\" style=\"position:absolute;left:100px;top:341px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>46<br></b></nobr>");
write("</p>");
write("<p id=\"p3_78\" class=\"drag\" style=\"position:absolute;left:87px;top:299px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>HAZARD <br>WARNING <br>SWITCH <br>‹9−B›<br></b></nobr>");
write("</p>");
write("<p id=\"p3_79\" class=\"drag\" style=\"position:absolute;left:112px;top:697px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>TURN SIGNAL/<br>HAZARD RELAY <br>‹9−A›<br></b></nobr>");
write("</p>");
write("<p id=\"p3_80\" class=\"drag\" style=\"position:absolute;left:256px;top:883px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: G702<br></b></nobr>");
write("</p>");
write("<p id=\"p3_81\" class=\"drag\" style=\"position:absolute;left:256px;top:896px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: G704<br></b></nobr>");
write("</p>");
write("<p id=\"p3_82\" class=\"drag\" style=\"position:absolute;left:244px;top:896px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_83\" class=\"drag\" style=\"position:absolute;left:244px;top:883px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_84\" class=\"drag\" style=\"position:absolute;left:365px;top:882px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: G702<br></b></nobr>");
write("</p>");
write("<p id=\"p3_85\" class=\"drag\" style=\"position:absolute;left:352px;top:882px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_86\" class=\"drag\" style=\"position:absolute;left:256px;top:910px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: G702<br></b></nobr>");
write("</p>");
write("<p id=\"p3_87\" class=\"drag\" style=\"position:absolute;left:244px;top:910px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p3_88\" class=\"drag\" style=\"position:absolute;left:364px;top:895px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: G704<br></b></nobr>");
write("</p>");
write("<p id=\"p3_89\" class=\"drag\" style=\"position:absolute;left:352px;top:895px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p3_90\" class=\"drag\" style=\"position:absolute;left:364px;top:909px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: G702<br></b></nobr>");
write("</p>");
write("<p id=\"p3_91\" class=\"drag\" style=\"position:absolute;left:352px;top:909px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p3_92\" class=\"drag\" style=\"position:absolute;left:431px;top:279px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: RHD With power tailgate <br></b></nobr>");
write("</p>");
write("<p id=\"p3_93\" class=\"drag\" style=\"position:absolute;left:419px;top:279px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p3_94\" class=\"drag\" style=\"position:absolute;left:431px;top:293px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: RHD Without power tailgate<br></b></nobr>");
write("</p>");
write("<p id=\"p3_95\" class=\"drag\" style=\"position:absolute;left:419px;top:293px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}