with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:847px;\" coordsize=\"950,847\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:847px;\">");
write("<img id=\"img1\" src=\"../img/SEA5E44B44100000000DAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:847px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:697px;top:72px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR DAMPER<br><a href=\"javascript:parent.Cts('000000000002072','i000')\"></b>Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:578px;top:735px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>KNUCKLE/<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:776px;top:152px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SPRING<br><a href=\"javascript:parent.Cts('000000000002077','i000')\"></b>Replacement,<br></a><br></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:577px;top:765px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b><a href=\"javascript:parent.Cts('000000000002073','iR01')\"></b>Hub Replacement,<br></a><br></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:577px;top:795px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b><a href=\"javascript:parent.Cts('000000000002073','iR02')\"></b>Knuckle Replacement,<br></a><br></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:183px;top:767px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TRAILING ARM<br><a href=\"javascript:parent.Cts('000000000002080','i000')\"></b>Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:65px;top:459px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LOWER ARM A<br><a href=\"javascript:parent.Cts('000000000002075','i000')\"></b>Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:479px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LOWER ARM B<br><a href=\"javascript:parent.Cts('000000000002076','i000')\"></b>Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:20px;top:347px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>UPPER ARM<br><a href=\"javascript:parent.Cts('000000000002081','i000')\"></b>Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:577px;top:750px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HUB<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}