with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:863px;\" coordsize=\"950,863\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:863px;\">");
write("<img id=\"img1\" src=\"../img/SEA5E1DE34150200000LDAD11.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:863px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:797px;top:780px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SYNCHRO SPRING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:329px;top:382px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>1ST GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:329px;top:765px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>COUNTERSHAFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:797px;top:88px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BALL BEARING<br></b>Check for wear<br>and operation.<br>Note the direction<br>of installation.<br></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:797px;top:468px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>2ND GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:797px;top:644px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRICTION DAMPER<br></b>Check for wear <br>and damage.<br></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:329px;top:224px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SYNCHRO SPRING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:329px;top:164px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>1ST/2ND <br>SYNCHRO HUB<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:329px;top:56px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REVERSE GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:329px;top:466px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>NEEDLE BEARING<br></b>Check for wear and <br>operation.<br></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:797px;top:545px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>NEEDLE BEARING<br></b>Check for wear and <br>operation.<br></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:797px;top:345px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>4TH GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:797px;top:293px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>5TH GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:797px;top:406px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>3RD GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:797px;top:608px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DISTANCE COLLAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:329px;top:316px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TRIPLE CONE SYNCHRO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:329px;top:543px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DISTANCE COLLAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:797px;top:708px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TRIPLE CONE <br>SYNCHRO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:747px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SPECIAL BOLT<br>118 N·m (12 kgf·m, 87 lbf·ft)<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:797px;top:198px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>35 mm SHIM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:797px;top:245px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DISTANCE COLLAR<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}