with(document) {
write("<v:group id=\"group2\" class=\"drag\" style=\"position:relative; width:475px; height:320px;\" coordsize=\"475,320\">");
write("<v:rect id=\"rect2\"class=\"drag\"  style=\"width:475px;height:320px;\">");
write("<img id=\"img2\" src=\"../img/SEA5E20H46200053401MAAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:320px;border-color:#ffffff\">");
write("<p id=\"p2_1\" class=\"drag\" style=\"position:absolute;left:159px;top:21px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>40 °<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" class=\"drag\" style=\"position:absolute;left:52px;top:23px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>40 °<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" class=\"drag\" style=\"position:absolute;left:88px;top:40px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>15 °<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" class=\"drag\" style=\"position:absolute;left:123px;top:41px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>15 °<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" class=\"drag\" style=\"position:absolute;left:203px;top:113px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>40 °<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" class=\"drag\" style=\"position:absolute;left:201px;top:209px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>40 °<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" class=\"drag\" style=\"position:absolute;left:231px;top:141px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>15 °<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" class=\"drag\" style=\"position:absolute;left:230px;top:177px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>15 °<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" class=\"drag\" style=\"position:absolute;left:27px;top:201px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" class=\"drag\" style=\"position:absolute;left:316px;top:284px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Forward<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" class=\"drag\" style=\"position:absolute;left:102px;top:284px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Inside<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}