with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:911px;\" coordsize=\"950,911\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:911px;\">");
write("<img id=\"img1\" src=\"../img/SEA5EA3A18400025501KDAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:911px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:494px;top:64px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>GASKET<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:173px;top:637px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>GASKET<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:708px;top:462px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>10 x 1.25 mm<br>44 N·m <br>(4.5 kgf·m, 33 lbf·ft)<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:708px;top:570px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>8 x 1.25 mm<br>22 N·m (2.2 kgf·m,16 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:708px;top:538px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HEAT SHIELD (K20A6 engine)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:708px;top:623px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EXHAUST MANIFOLD<br>BRACKET (K24A3 engine)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:406px;top:853px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>10 x 1.25 mm<br>44 N·m <br>(4.5 kgf·m, 33 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:179px;top:822px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>8 x 1.25 mm<br>22 N·m (2.2 kgf·m, 16 lbf·ft)<br></b>Replace.<br>Tighten the bolts in steps,<br>alternating side-to-side<br></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:18px;top:552px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SELF-LOCKING NUT<br>10 x 1.25 mm<br>44 N·m (4.5 kgf·m, 33 lbf·ft)<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:16px;top:460px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EXHAUST MANIFOLD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:55px;top:297px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>COVER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:15px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>8 x 1.25 mm<br>22 N·m <br>(2.2 kgf·m, 16 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:747px;top:848px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EXHAUST MANIFOLD<br>BRACKET (K20A6 engine)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}