with(document) {
write("<v:group id=\"group3\" class=\"drag\" style=\"position:relative; width:640px; height:950px;\" coordsize=\"640,950\">");
write("<v:rect id=\"rect3\"class=\"drag\"  style=\"width:640px;height:950px;\">");
write("<img id=\"img3\" src=\"../img/SEA5E24000000000000EBA301.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:640px;height:950px;border-color:#ffffff\">");
write("<p id=\"p3_1\" class=\"drag\" style=\"position:absolute;left:-94px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p3_2\" class=\"drag\" style=\"position:absolute;left:348px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p3_3\" class=\"drag\" style=\"position:absolute;left:403px;top:226px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>*2 : UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_4\" class=\"drag\" style=\"position:absolute;left:403px;top:217px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>*1 : UNDER−HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_5\" class=\"drag\" style=\"position:absolute;left:426px;top:168px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_6\" class=\"drag\" style=\"position:absolute;left:274px;top:339px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_7\" class=\"drag\" style=\"position:absolute;left:491px;top:101px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.22 (BAT) (100 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_8\" class=\"drag\" style=\"position:absolute;left:189px;top:462px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p3_9\" class=\"drag\" style=\"position:absolute;left:123px;top:462px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p3_10\" class=\"drag\" style=\"position:absolute;left:107px;top:528px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_11\" class=\"drag\" style=\"position:absolute;left:173px;top:528px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_12\" class=\"drag\" style=\"position:absolute;left:115px;top:594px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>VOLTAGE REGULATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_13\" class=\"drag\" style=\"position:absolute;left:-63px;top:657px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RECTIFIER<br></b></nobr>");
write("</p>");
write("<p id=\"p3_14\" class=\"drag\" style=\"position:absolute;left:-74px;top:552px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>ALTERNATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_15\" class=\"drag\" style=\"position:absolute;left:-15px;top:528px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_16\" class=\"drag\" style=\"position:absolute;left:275px;top:528px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_17\" class=\"drag\" style=\"position:absolute;left:428px;top:145px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_18\" class=\"drag\" style=\"position:absolute;left:561px;top:100px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_19\" class=\"drag\" style=\"position:absolute;left:488px;top:112px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.19 (30 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_20\" class=\"drag\" style=\"position:absolute;left:532px;top:111px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_21\" class=\"drag\" style=\"position:absolute;left:532px;top:167px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_22\" class=\"drag\" style=\"position:absolute;left:140px;top:441px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>ECM ‹24−B›<br></b></nobr>");
write("</p>");
write("<p id=\"p3_23\" class=\"drag\" style=\"position:absolute;left:578px;top:36px;font-weight:normal;font-size:17.6pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_24\" class=\"drag\" style=\"position:absolute;left:428px;top:112px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_25\" class=\"drag\" style=\"position:absolute;left:427px;top:156px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_26\" class=\"drag\" style=\"position:absolute;left:428px;top:134px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_27\" class=\"drag\" style=\"position:absolute;left:488px;top:168px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.18 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_28\" class=\"drag\" style=\"position:absolute;left:491px;top:156px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>IG2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_29\" class=\"drag\" style=\"position:absolute;left:491px;top:145px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_30\" class=\"drag\" style=\"position:absolute;left:491px;top:134px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>ACC<br></b></nobr>");
write("</p>");
write("<p id=\"p3_31\" class=\"drag\" style=\"position:absolute;left:491px;top:68px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BAT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_32\" class=\"drag\" style=\"position:absolute;left:-178px;top:246px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>VSA MODULATOR−CONTROL UNIT<br>‹18−C›<br></b></nobr>");
write("</p>");
write("<p id=\"p3_33\" class=\"drag\" style=\"position:absolute;left:-178px;top:274px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>ABS MODULATOR−CONTROL UNIT<br>‹19−C›<br></b></nobr>");
write("</p>");
write("<p id=\"p3_34\" class=\"drag\" style=\"position:absolute;left:-106px;top:189px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.15 (30 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_35\" class=\"drag\" style=\"position:absolute;left:-65px;top:186px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_36\" class=\"drag\" style=\"position:absolute;left:489px;top:179px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.15 (30 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_37\" class=\"drag\" style=\"position:absolute;left:533px;top:178px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_38\" class=\"drag\" style=\"position:absolute;left:33px;top:191px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_39\" class=\"drag\" style=\"position:absolute;left:94px;top:213px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.21 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_40\" class=\"drag\" style=\"position:absolute;left:136px;top:210px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_41\" class=\"drag\" style=\"position:absolute;left:33px;top:203px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_42\" class=\"drag\" style=\"position:absolute;left:164px;top:198px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.7 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_43\" class=\"drag\" style=\"position:absolute;left:200px;top:196px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_44\" class=\"drag\" style=\"position:absolute;left:489px;top:203px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.21 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_45\" class=\"drag\" style=\"position:absolute;left:531px;top:202px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_46\" class=\"drag\" style=\"position:absolute;left:488px;top:190px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.7 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_47\" class=\"drag\" style=\"position:absolute;left:527px;top:189px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_48\" class=\"drag\" style=\"position:absolute;left:-207px;top:574px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>ECM <br>‹23−B› <br></b></nobr>");
write("</p>");
write("<p id=\"p3_49\" class=\"drag\" style=\"position:absolute;left:-178px;top:302px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GLOW PLUG <br>CONTROL MODULE<br>‹23−B›<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}