with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:475px; height:401px;\" coordsize=\"475,401\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:475px;height:401px;\">");
write("<img id=\"img1\" src=\"../img/SEA5E1DE34116300000KBAD17.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:401px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:17px;top:74px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:172px;top:57px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:221px;top:359px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:54px;top:338px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>0.4−1.0 g<br>(0.01−0.04 oz)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:449px;top:255px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>E<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:309px;top:17px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>1.0−1.6 g<br>(0.04−0.06 oz)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:286px;top:354px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>0.4−1.0 g<br>(0.01−0.04 oz)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:110px;top:61px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}