with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1063px;\" coordsize=\"950,1063\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:1063px;\">");
write("<img id=\"img1\" src=\"../img/SEA5E43J32316800000EAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1063px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:262px;top:36px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BATTERY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:335px;top:46px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.22 (100 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:414px;top:47px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.23 (IG) (50 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:323px;top:22px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNDER−HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:529px;top:105px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:325px;top:1034px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G704<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:328px;top:919px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:549px;top:178px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:549px;top:189px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:515px;top:262px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:345px;top:472px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(5 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:345px;top:422px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:345px;top:594px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:315px;top:376px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:545px;top:422px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:545px;top:472px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(5 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:545px;top:594px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:317px;top:648px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:515px;top:376px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:345px;top:779px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:345px;top:872px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:317px;top:734px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:517px;top:648px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:595px;top:172px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNDER−DASH <br>FUSE/RELAY <br>BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:380px;top:491px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LEFT <br>CARGO <br>AREA <br>LIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:580px;top:491px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RIGHT <br>CARGO <br>AREA <br>LIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:423px;top:809px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>POWER <br>TAILGATE <br>CLOSER <br>UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:355px;top:821px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>TAILGATE <br>SWITCH<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}