with(document) {
write("<v:group id=\"group3\" class=\"drag\" style=\"position:relative; width:640px; height:950px;\" coordsize=\"640,950\">");
write("<v:rect id=\"rect3\"class=\"drag\"  style=\"width:640px;height:950px;\">");
write("<img id=\"img3\" src=\"../img/SEA5E24000000000000EBA320.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:640px;height:950px;border-color:#ffffff\">");
write("<p id=\"p3_1\" class=\"drag\" style=\"position:absolute;left:-94px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p3_2\" class=\"drag\" style=\"position:absolute;left:348px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p3_3\" class=\"drag\" style=\"position:absolute;left:-152px;top:499px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_4\" class=\"drag\" style=\"position:absolute;left:-96px;top:499px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_5\" class=\"drag\" style=\"position:absolute;left:-41px;top:499px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRY/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_6\" class=\"drag\" style=\"position:absolute;left:14px;top:499px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>PNK/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_7\" class=\"drag\" style=\"position:absolute;left:125px;top:499px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_8\" class=\"drag\" style=\"position:absolute;left:63px;top:499px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LT GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_9\" class=\"drag\" style=\"position:absolute;left:305px;top:655px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_10\" class=\"drag\" style=\"position:absolute;left:252px;top:655px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_11\" class=\"drag\" style=\"position:absolute;left:310px;top:705px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>38<br></b></nobr>");
write("</p>");
write("<p id=\"p3_12\" class=\"drag\" style=\"position:absolute;left:254px;top:705px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>56<br></b></nobr>");
write("</p>");
write("<p id=\"p3_13\" class=\"drag\" style=\"position:absolute;left:131px;top:324px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>(With side airbag)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_14\" class=\"drag\" style=\"position:absolute;left:131px;top:655px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_15\" class=\"drag\" style=\"position:absolute;left:19px;top:655px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_16\" class=\"drag\" style=\"position:absolute;left:84px;top:655px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_17\" class=\"drag\" style=\"position:absolute;left:-27px;top:655px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_18\" class=\"drag\" style=\"position:absolute;left:-96px;top:655px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RED/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_19\" class=\"drag\" style=\"position:absolute;left:94px;top:801px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>(With side curtain airbag)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_20\" class=\"drag\" style=\"position:absolute;left:578px;top:36px;font-weight:normal;font-size:17.6pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p3_21\" class=\"drag\" style=\"position:absolute;left:436px;top:256px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: LHD<br></b></nobr>");
write("</p>");
write("<p id=\"p3_22\" class=\"drag\" style=\"position:absolute;left:423px;top:256px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_23\" class=\"drag\" style=\"position:absolute;left:423px;top:269px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_24\" class=\"drag\" style=\"position:absolute;left:436px;top:269px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: RHD<br></b></nobr>");
write("</p>");
write("<p id=\"p3_25\" class=\"drag\" style=\"position:absolute;left:535px;top:166px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_26\" class=\"drag\" style=\"position:absolute;left:428px;top:112px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_27\" class=\"drag\" style=\"position:absolute;left:430px;top:167px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_28\" class=\"drag\" style=\"position:absolute;left:491px;top:167px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.18 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_29\" class=\"drag\" style=\"position:absolute;left:491px;top:145px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_30\" class=\"drag\" style=\"position:absolute;left:561px;top:100px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_31\" class=\"drag\" style=\"position:absolute;left:491px;top:101px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.22 (BAT) (100 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_32\" class=\"drag\" style=\"position:absolute;left:491px;top:112px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.19 (30 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_33\" class=\"drag\" style=\"position:absolute;left:535px;top:111px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_34\" class=\"drag\" style=\"position:absolute;left:431px;top:145px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_35\" class=\"drag\" style=\"position:absolute;left:491px;top:190px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.7 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_36\" class=\"drag\" style=\"position:absolute;left:430px;top:189px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_37\" class=\"drag\" style=\"position:absolute;left:530px;top:189px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_38\" class=\"drag\" style=\"position:absolute;left:419px;top:205px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>*1 : UNDER−HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_39\" class=\"drag\" style=\"position:absolute;left:419px;top:214px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>*2 : UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_40\" class=\"drag\" style=\"position:absolute;left:-550px;top:701px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RIGHT <br>FRONT <br>IMPACT <br>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_41\" class=\"drag\" style=\"position:absolute;left:-243px;top:748px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LEFT <br>SIDE CURTAIN <br>AIRBAG <br>INFLATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_42\" class=\"drag\" style=\"position:absolute;left:-132px;top:748px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RIGHT <br>SIDE CURTAIN <br>AIRBAG <br>INFLATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_43\" class=\"drag\" style=\"position:absolute;left:-16px;top:707px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LEFT <br>SIDE IMPACT <br>SENSOR (2ND)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_44\" class=\"drag\" style=\"position:absolute;left:94px;top:707px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RIGHT <br>SIDE IMPACT <br>SENSOR (2ND)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_45\" class=\"drag\" style=\"position:absolute;left:263px;top:735px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>DATA LINK <br>CONNECTOR <br>(DLC) <br>‹23−B› <br></b></nobr>");
write("</p>");
write("<p id=\"p3_46\" class=\"drag\" style=\"position:absolute;left:88px;top:429px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RIGHT <br>SIDE IMPACT <br>SENSOR (1ST)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_47\" class=\"drag\" style=\"position:absolute;left:-21px;top:429px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LEFT <br>SIDE IMPACT <br>SENSOR (1ST)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_48\" class=\"drag\" style=\"position:absolute;left:-132px;top:371px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RIGHT <br>SIDE AIRBAG <br>INFLATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_49\" class=\"drag\" style=\"position:absolute;left:-243px;top:371px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LEFT <br>SIDE AIRBAG <br>INFLATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_50\" class=\"drag\" style=\"position:absolute;left:-445px;top:370px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RIGHT SIDE <br>SEAT BELT <br>TENSIONER<br></b></nobr>");
write("</p>");
write("<p id=\"p3_51\" class=\"drag\" style=\"position:absolute;left:-667px;top:361px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>FRONT <br>PASSENGER'S <br>AIRBAG <br>INFLATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_52\" class=\"drag\" style=\"position:absolute;left:491px;top:67px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BAT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_53\" class=\"drag\" style=\"position:absolute;left:-67px;top:652px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_54\" class=\"drag\" style=\"position:absolute;left:-12px;top:652px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_55\" class=\"drag\" style=\"position:absolute;left:49px;top:652px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_56\" class=\"drag\" style=\"position:absolute;left:98px;top:652px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_57\" class=\"drag\" style=\"position:absolute;left:161px;top:652px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_58\" class=\"drag\" style=\"position:absolute;left:319px;top:652px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_59\" class=\"drag\" style=\"position:absolute;left:266px;top:652px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_60\" class=\"drag\" style=\"position:absolute;left:419px;top:223px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>*3 : BLUE or BROWN wire color can be<br>          used for the SRS circuits that<br>          have a *3 mark<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}