with(document) {
write("<v:group id=\"group2\" class=\"drag\" style=\"position:relative; width:950px; height:1023px;\" coordsize=\"950,1023\">");
write("<v:rect id=\"rect2\"class=\"drag\"  style=\"width:950px;height:1023px;\">");
write("<img id=\"img2\" src=\"../img/SEA5E44D10600000000EAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1023px;border-color:#ffffff\">");
write("<p id=\"p2_1\" class=\"drag\" style=\"position:absolute;left:57px;top:57px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>UNDER-HOOD FUSE/RELAY BOX<br>CONNECTOR C (2P)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" class=\"drag\" style=\"position:absolute;left:58px;top:210px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BRAKE PEDAL POSITION<br>SWITCH 4P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" class=\"drag\" style=\"position:absolute;left:59px;top:380px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>UNDER-DASH FUSE/RELAY BOX<br>CONNECTOR C (12P)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" class=\"drag\" style=\"position:absolute;left:393px;top:380px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>GAUGE CONTROL MODULE CONNECTOR B (30P)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" class=\"drag\" style=\"position:absolute;left:65px;top:550px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ABS CONTROL UNIT 25P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" class=\"drag\" style=\"position:absolute;left:338px;top:210px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BRAKE FLUID LEVEL SWITCH<br>2P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" class=\"drag\" style=\"position:absolute;left:343px;top:740px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>Wire side of female terminals<br></nobr>");
write("</p>");
write("<p id=\"p2_8\" class=\"drag\" style=\"position:absolute;left:121px;top:818px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DATA LINK CONNECTOR (16P)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" class=\"drag\" style=\"position:absolute;left:114px;top:965px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>Terminal side of female terminals<br></nobr>");
write("</p>");
write("<p id=\"p2_10\" class=\"drag\" style=\"position:absolute;left:497px;top:965px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>Terminal side of male terminals<br></nobr>");
write("</p>");
write("<p id=\"p2_11\" class=\"drag\" style=\"position:absolute;left:559px;top:843px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT/REAR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" class=\"drag\" style=\"position:absolute;left:494px;top:817px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>WHEEL SENSOR 2P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" class=\"drag\" style=\"position:absolute;left:320px;top:57px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>UNDER-HOOD FUSE/RELAY BOX<br>CONNECTOR G (2P)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" class=\"drag\" style=\"position:absolute;left:609px;top:57px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>UNDER-HOOD FUSE/RELAY BOX<br>CONNECTOR D (9P)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}