with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:799px;\" coordsize=\"950,799\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:799px;\">");
write("<img id=\"img1\" src=\"../img/SEA5E23D52100000000DAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:799px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:581px;top:713px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>UNDER-DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:237px;top:50px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DATA LINK CONNECTOR (16P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:16px;top:112px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>UNDER-HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:98px;top:661px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RIGHT-FRONT WHEEL SENSOR<br><a href=\"javascript:parent.Cts('000000000001016','i000')\"></b>Inspection,</a><br><a href=\"javascript:parent.Cts('000000000000034','i000')\">Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:447px;top:739px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LEFT-FRONT WHEEL SENSOR<br><a href=\"javascript:parent.Cts('000000000001016','i000')\"></b>Inspection,</a><br><a href=\"javascript:parent.Cts('000000000000034','i000')\">Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:710px;top:63px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RIGHT-REAR WHEEL SENSOR<br><a href=\"javascript:parent.Cts('000000000001016','i000')\"></b>Inspection,</a><br><a href=\"javascript:parent.Cts('000000000000034','i000')\">Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:727px;top:499px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LEFT-REAR<br>WHEEL SENSOR<br><a href=\"javascript:parent.Cts('000000000001016','i000')\"></b>Inspection,</a><br><a href=\"javascript:parent.Cts('000000000000034','i000')\">Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:15px;top:727px;font-weight:normal;font-size:9.1pt;\">");
write("<nobr><b>VSA MODULATOR-CONTROL UNIT<br><a href=\"javascript:parent.Cts('000000000000641','i000')\"></b>Removal and Installation,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:653px;top:670px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VSA OFF SWITCH<br><a href=\"javascript:parent.Cts('000000000000033','i000')\"></b>Test,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:665px;top:17px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>STEERING ANGLE SENSOR<br><a href=\"javascript:parent.Cts('000000000002593','i000')\"></b>Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:679px;top:611px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>YAW RATE/LATERAL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:679px;top:626px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ACCELERATION SENSOR<br><a href=\"javascript:parent.Cts('000000000000035','i000')\"></b>Replacement,</a><br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}