with(document) {
write("<v:group id=\"group10\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\" coordsize=\"950,1103\">");
write("<v:rect id=\"rect10\"class=\"drag\"  style=\"width:950px;height:1103px;\">");
write("<img id=\"img10\" src=\"../img/SEA5ED3A20300000000EAAD05.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p10_1\" class=\"drag\" style=\"position:absolute;left:628px;top:44px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>S<br></b></nobr>");
write("</p>");
write("<p id=\"p10_2\" class=\"drag\" style=\"position:absolute;left:323px;top:18px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>28P JUNCTION CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p10_3\" class=\"drag\" style=\"position:absolute;left:288px;top:75px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>12<br>(16)<br></b></nobr>");
write("</p>");
write("<p id=\"p10_4\" class=\"drag\" style=\"position:absolute;left:328px;top:75px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>14<br>(15)<br></b></nobr>");
write("</p>");
write("<p id=\"p10_5\" class=\"drag\" style=\"position:absolute;left:357px;top:75px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>19<br>(23)<br></b></nobr>");
write("</p>");
write("<p id=\"p10_6\" class=\"drag\" style=\"position:absolute;left:391px;top:75px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>21<br>(22)<br></b></nobr>");
write("</p>");
write("<p id=\"p10_7\" class=\"drag\" style=\"position:absolute;left:431px;top:71px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p10_8\" class=\"drag\" style=\"position:absolute;left:468px;top:71px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p10_9\" class=\"drag\" style=\"position:absolute;left:824px;top:977px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ELD<br></b></nobr>");
write("</p>");
write("<p id=\"p10_10\" class=\"drag\" style=\"position:absolute;left:777px;top:1073px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BATTERY<br></b></nobr>");
write("</p>");
write("<p id=\"p10_11\" class=\"drag\" style=\"position:absolute;left:739px;top:1089px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_12\" class=\"drag\" style=\"position:absolute;left:725px;top:913px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RADIATOR<br>FAN RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p10_13\" class=\"drag\" style=\"position:absolute;left:677px;top:951px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_14\" class=\"drag\" style=\"position:absolute;left:677px;top:969px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p10_15\" class=\"drag\" style=\"position:absolute;left:678px;top:988px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_16\" class=\"drag\" style=\"position:absolute;left:605px;top:976px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_17\" class=\"drag\" style=\"position:absolute;left:605px;top:958px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_18\" class=\"drag\" style=\"position:absolute;left:605px;top:995px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_19\" class=\"drag\" style=\"position:absolute;left:676px;top:883px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p10_20\" class=\"drag\" style=\"position:absolute;left:604px;top:890px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_21\" class=\"drag\" style=\"position:absolute;left:736px;top:553px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>(1)<br></b></nobr>");
write("</p>");
write("<p id=\"p10_22\" class=\"drag\" style=\"position:absolute;left:735px;top:602px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>(2)<br></b></nobr>");
write("</p>");
write("<p id=\"p10_23\" class=\"drag\" style=\"position:absolute;left:736px;top:645px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>(3)<br></b></nobr>");
write("</p>");
write("<p id=\"p10_24\" class=\"drag\" style=\"position:absolute;left:853px;top:648px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>(5)<br></b></nobr>");
write("</p>");
write("<p id=\"p10_25\" class=\"drag\" style=\"position:absolute;left:726px;top:742px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A/C CLUTCH<br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p10_26\" class=\"drag\" style=\"position:absolute;left:677px;top:712px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p10_27\" class=\"drag\" style=\"position:absolute;left:604px;top:719px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_28\" class=\"drag\" style=\"position:absolute;left:681px;top:658px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p10_29\" class=\"drag\" style=\"position:absolute;left:604px;top:665px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p10_30\" class=\"drag\" style=\"position:absolute;left:682px;top:629px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p10_31\" class=\"drag\" style=\"position:absolute;left:604px;top:637px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_32\" class=\"drag\" style=\"position:absolute;left:604px;top:614px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_33\" class=\"drag\" style=\"position:absolute;left:605px;top:591px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_34\" class=\"drag\" style=\"position:absolute;left:191px;top:113px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E29<br></b></nobr>");
write("</p>");
write("<p id=\"p10_35\" class=\"drag\" style=\"position:absolute;left:249px;top:122px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_36\" class=\"drag\" style=\"position:absolute;left:193px;top:177px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E23<br></b></nobr>");
write("</p>");
write("<p id=\"p10_37\" class=\"drag\" style=\"position:absolute;left:193px;top:240px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E30<br></b></nobr>");
write("</p>");
write("<p id=\"p10_38\" class=\"drag\" style=\"position:absolute;left:852px;top:624px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>(4)<br></b></nobr>");
write("</p>");
write("<p id=\"p10_39\" class=\"drag\" style=\"position:absolute;left:25px;top:886px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>UNDER-HOOD<br>FUSE/RELAY BOX:<br><br>(1) No. 23 +B IG MAIN (50 A)<br>(2) No. 19 OPTION (40 A)<br>(3) No. 8 FI ECU<br> (ECM/PCM) (15 A)<br>(4) No. 13 HORN, STOP (20 A)<br>(5) No. 22 BATTERY (100 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p10_40\" class=\"drag\" style=\"position:absolute;left:192px;top:131px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SCS<br></b></nobr>");
write("</p>");
write("<p id=\"p10_41\" class=\"drag\" style=\"position:absolute;left:193px;top:195px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>K-LINE<br></b></nobr>");
write("</p>");
write("<p id=\"p10_42\" class=\"drag\" style=\"position:absolute;left:193px;top:258px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WEN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_43\" class=\"drag\" style=\"position:absolute;left:575px;top:1055px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G201<br></b></nobr>");
write("</p>");
write("<p id=\"p10_44\" class=\"drag\" style=\"position:absolute;left:549px;top:1048px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>AK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_45\" class=\"drag\" style=\"position:absolute;left:514px;top:1048px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>AJ<br></b></nobr>");
write("</p>");
write("<p id=\"p10_46\" class=\"drag\" style=\"position:absolute;left:480px;top:1048px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>AI<br></b></nobr>");
write("</p>");
write("<p id=\"p10_47\" class=\"drag\" style=\"position:absolute;left:442px;top:1049px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>AH<br></b></nobr>");
write("</p>");
write("<p id=\"p10_48\" class=\"drag\" style=\"position:absolute;left:409px;top:1048px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>AG<br></b></nobr>");
write("</p>");
write("<p id=\"p10_49\" class=\"drag\" style=\"position:absolute;left:373px;top:1049px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>AF<br></b></nobr>");
write("</p>");
write("<p id=\"p10_50\" class=\"drag\" style=\"position:absolute;left:339px;top:1048px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>AE<br></b></nobr>");
write("</p>");
write("<p id=\"p10_51\" class=\"drag\" style=\"position:absolute;left:304px;top:1048px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>AD<br></b></nobr>");
write("</p>");
write("<p id=\"p10_52\" class=\"drag\" style=\"position:absolute;left:251px;top:186px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p10_53\" class=\"drag\" style=\"position:absolute;left:253px;top:249px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED<br>(RED/WHT)*2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_54\" class=\"drag\" style=\"position:absolute;left:290px;top:98px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_55\" class=\"drag\" style=\"position:absolute;left:330px;top:98px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_56\" class=\"drag\" style=\"position:absolute;left:360px;top:98px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_57\" class=\"drag\" style=\"position:absolute;left:394px;top:98px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_58\" class=\"drag\" style=\"position:absolute;left:487px;top:83px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>*9<br></b></nobr>");
write("</p>");
write("<p id=\"p10_59\" class=\"drag\" style=\"position:absolute;left:195px;top:298px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E22<br></b></nobr>");
write("</p>");
write("<p id=\"p10_60\" class=\"drag\" style=\"position:absolute;left:195px;top:314px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BKSW<br></b></nobr>");
write("</p>");
write("<p id=\"p10_61\" class=\"drag\" style=\"position:absolute;left:249px;top:307px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_62\" class=\"drag\" style=\"position:absolute;left:399px;top:322px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>28P JUNCTION <br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p10_63\" class=\"drag\" style=\"position:absolute;left:485px;top:333px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>*9<br></b></nobr>");
write("</p>");
write("<p id=\"p10_64\" class=\"drag\" style=\"position:absolute;left:399px;top:425px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>28P JUNCTION <br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p10_65\" class=\"drag\" style=\"position:absolute;left:408px;top:487px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>28<br></b></nobr>");
write("</p>");
write("<p id=\"p10_66\" class=\"drag\" style=\"position:absolute;left:446px;top:487px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p10_67\" class=\"drag\" style=\"position:absolute;left:485px;top:436px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>*9<br></b></nobr>");
write("</p>");
write("<p id=\"p10_68\" class=\"drag\" style=\"position:absolute;left:195px;top:397px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>D8<br></b></nobr>");
write("</p>");
write("<p id=\"p10_69\" class=\"drag\" style=\"position:absolute;left:195px;top:413px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BKSWNC<br></b></nobr>");
write("</p>");
write("<p id=\"p10_70\" class=\"drag\" style=\"position:absolute;left:273px;top:586px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>AA<br></b></nobr>");
write("</p>");
write("<p id=\"p10_71\" class=\"drag\" style=\"position:absolute;left:51px;top:366px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p10_72\" class=\"drag\" style=\"position:absolute;left:801px;top:114px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p10_73\" class=\"drag\" style=\"position:absolute;left:703px;top:122px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_74\" class=\"drag\" style=\"position:absolute;left:795px;top:133px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p10_75\" class=\"drag\" style=\"position:absolute;left:703px;top:140px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_76\" class=\"drag\" style=\"position:absolute;left:704px;top:167px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p10_77\" class=\"drag\" style=\"position:absolute;left:794px;top:185px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p10_78\" class=\"drag\" style=\"position:absolute;left:704px;top:194px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED<br>(RED/WHT)*2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_79\" class=\"drag\" style=\"position:absolute;left:799px;top:221px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_80\" class=\"drag\" style=\"position:absolute;left:702px;top:229px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_81\" class=\"drag\" style=\"position:absolute;left:707px;top:507px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>UNDER-HOOD<br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p10_82\" class=\"drag\" style=\"position:absolute;left:682px;top:607px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p10_83\" class=\"drag\" style=\"position:absolute;left:682px;top:583px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_84\" class=\"drag\" style=\"position:absolute;left:682px;top:537px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_85\" class=\"drag\" style=\"position:absolute;left:604px;top:544px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p10_86\" class=\"drag\" style=\"position:absolute;left:650px;top:288px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G451<br></b></nobr>");
write("</p>");
write("<p id=\"p10_87\" class=\"drag\" style=\"position:absolute;left:612px;top:259px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>Z<br></b></nobr>");
write("</p>");
write("<p id=\"p10_88\" class=\"drag\" style=\"position:absolute;left:840px;top:149px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>DATA LINK<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p10_89\" class=\"drag\" style=\"position:absolute;left:801px;top:79px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p10_90\" class=\"drag\" style=\"position:absolute;left:706px;top:87px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_91\" class=\"drag\" style=\"position:absolute;left:690px;top:272px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRAKE PEDAL<br>POSITION SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p10_92\" class=\"drag\" style=\"position:absolute;left:772px;top:306px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>Brake pedal pressed: closed<br>Brake pedal released: open<br></b></nobr>");
write("</p>");
write("<p id=\"p10_93\" class=\"drag\" style=\"position:absolute;left:569px;top:501px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>AB<br></b></nobr>");
write("</p>");
write("<p id=\"p10_94\" class=\"drag\" style=\"position:absolute;left:508px;top:232px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>28P JUNCTION <br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p10_95\" class=\"drag\" style=\"position:absolute;left:413px;top:383px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_96\" class=\"drag\" style=\"position:absolute;left:450px;top:383px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p10_97\" class=\"drag\" style=\"position:absolute;left:684px;top:299px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_98\" class=\"drag\" style=\"position:absolute;left:600px;top:306px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p10_99\" class=\"drag\" style=\"position:absolute;left:683px;top:316px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p10_100\" class=\"drag\" style=\"position:absolute;left:600px;top:324px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p10_101\" class=\"drag\" style=\"position:absolute;left:684px;top:337px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p10_102\" class=\"drag\" style=\"position:absolute;left:600px;top:362px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRY<br>(BLK/RED)*2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_103\" class=\"drag\" style=\"position:absolute;left:684px;top:355px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p10_104\" class=\"drag\" style=\"position:absolute;left:602px;top:407px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>20P CONNECTOR<br>(7P CONNECTOR)<br></b></nobr>");
write("</p>");
write("<p id=\"p10_105\" class=\"drag\" style=\"position:absolute;left:581px;top:426px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>12<br>(1)*2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_106\" class=\"drag\" style=\"position:absolute;left:772px;top:345px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>Brake pedal pressed: open<br>Brake pedal released: closed<br></b></nobr>");
write("</p>");
write("<p id=\"p10_107\" class=\"drag\" style=\"position:absolute;left:482px;top:250px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>*9<br></b></nobr>");
write("</p>");
write("<p id=\"p10_108\" class=\"drag\" style=\"position:absolute;left:515px;top:295px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p10_109\" class=\"drag\" style=\"position:absolute;left:552px;top:295px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p10_110\" class=\"drag\" style=\"position:absolute;left:265px;top:1048px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>AC<br></b></nobr>");
write("</p>");
write("<p id=\"p10_111\" class=\"drag\" style=\"position:absolute;left:145px;top:845px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>5P CONNECTOR<br>(20P CONNECTOR)*11<br></b></nobr>");
write("</p>");
write("<p id=\"p10_112\" class=\"drag\" style=\"position:absolute;left:699px;top:418px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p10_113\" class=\"drag\" style=\"position:absolute;left:28px;top:718px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>*2: RHD model<br>*3: K24A3 engine<br>*9: LHD model<br>*11: 2005 model (RHD model)<br></b></nobr>");
write("</p>");
write("<p id=\"p10_114\" class=\"drag\" style=\"position:absolute;left:251px;top:406px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_115\" class=\"drag\" style=\"position:absolute;left:601px;top:344px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p10_116\" class=\"drag\" style=\"position:absolute;left:798px;top:158px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p10_117\" class=\"drag\" style=\"position:absolute;left:220px;top:803px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br>(12)*11<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}