with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\" coordsize=\"950,1103\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:1103px;\">");
write("<img id=\"img1\" src=\"../img/SEA5E44E34116300000DAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:60px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RESERVOIR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:272px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RESERVOIR HOSE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:292px;top:122px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>O-RING<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:275px;top:215px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RETAINING CLIP<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:489px;top:85px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LOCK PIN<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:782px;top:65px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CLUTCH PEDAL <br>POSITION SWITCH<br><a href=\"javascript:parent.Cts('000000000002129','i000')\"></b>Adjustment,<br></a><br><a href=\"javascript:parent.Cts('000000000002130','i000')\">Test,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:743px;top:207px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CLUTCH PEDAL<br><a href=\"javascript:parent.Cts('000000000002129','i000')\"></b>Adjustment,<br></a><br><a href=\"javascript:parent.Cts('000000000002128','i000')\">Replacement,<br></a><br></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:538px;top:276px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PEDAL PIN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:401px;top:305px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CLUTCH MASTER CYLINDER<br><a href=\"javascript:parent.Cts('000000000002127','i000')\"></b>Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:359px;top:363px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PILOT BEARING<br><a href=\"javascript:parent.Cts('000000000002126','iR02')\"></b>Inspection,</a><br><a href=\"javascript:parent.Cts('000000000002126','iR03')\">Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:415px;top:414px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CLUTCH DISC<br><a href=\"javascript:parent.Cts('000000000002126','iR01')\"></b>Removal,</a><br><a href=\"javascript:parent.Cts('000000000002126','iR04')\">Installation,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:480px;top:467px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PRESSURE PLATE<br><a href=\"javascript:parent.Cts('000000000002126','iR01')\"></b>Removal,</a><br><a href=\"javascript:parent.Cts('000000000002126','iR04')\">Installation,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:767px;top:544px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RELEASE BEARING<br><a href=\"javascript:parent.Cts('000000000002126','iR05')\"></b>Replacement,<br></a><br></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:191px;top:684px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FLYWHEEL<br><a href=\"javascript:parent.Cts('000000000002126','iR02')\"></b>Inspection,</a><br><a href=\"javascript:parent.Cts('000000000002126','iR03')\">Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:614px;top:922px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CLUTCH HOSE CLIP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:562px;top:994px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CLUTCH HOSE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:162px;top:990px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SLAVE CYLINDER<br><a href=\"javascript:parent.Cts('000000000002131','i000')\"></b>Replacement,</a><br><a href=\"javascript:parent.Cts('000000000002132','i000')\">Overhaul,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:251px;top:946px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>O-RING<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:71px;top:801px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ROLL PIN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:1px;top:1072px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>LHD type is shown, RHD type is similar.<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}