with(document) {
write("<v:group id=\"group8\" class=\"drag\" style=\"position:relative; width:950px; height:1008px;\" coordsize=\"950,1008\">");
write("<v:rect id=\"rect8\"class=\"drag\"  style=\"width:950px;height:1008px;\">");
write("<img id=\"img8\" src=\"../img/SEA5E24J54260400000EAAD08.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1008px;border-color:#ffffff\">");
write("<p id=\"p8_1\" class=\"drag\" style=\"position:absolute;left:712px;top:551px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b> <br></b></nobr>");
write("</p>");
write("<p id=\"p8_2\" class=\"drag\" style=\"position:absolute;left:543px;top:631px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p8_3\" class=\"drag\" style=\"position:absolute;left:74px;top:68px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p8_4\" class=\"drag\" style=\"position:absolute;left:72px;top:432px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p8_5\" class=\"drag\" style=\"position:absolute;left:170px;top:31px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p8_6\" class=\"drag\" style=\"position:absolute;left:684px;top:443px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>slide motor<br></b></nobr>");
write("</p>");
write("<p id=\"p8_7\" class=\"drag\" style=\"position:absolute;left:191px;top:416px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.17 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_8\" class=\"drag\" style=\"position:absolute;left:455px;top:431px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_9\" class=\"drag\" style=\"position:absolute;left:684px;top:431px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Front passenger's power seat<br></b></nobr>");
write("</p>");
write("<p id=\"p8_10\" class=\"drag\" style=\"position:absolute;left:684px;top:374px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Driver's power seat recline motor<br></b></nobr>");
write("</p>");
write("<p id=\"p8_11\" class=\"drag\" style=\"position:absolute;left:455px;top:374px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_12\" class=\"drag\" style=\"position:absolute;left:191px;top:359px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.16 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_13\" class=\"drag\" style=\"position:absolute;left:191px;top:301px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.15 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_14\" class=\"drag\" style=\"position:absolute;left:457px;top:317px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_15\" class=\"drag\" style=\"position:absolute;left:684px;top:317px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Driver's seat heater and indicator<br></b></nobr>");
write("</p>");
write("<p id=\"p8_16\" class=\"drag\" style=\"position:absolute;left:191px;top:244px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.14 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_17\" class=\"drag\" style=\"position:absolute;left:684px;top:260px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Driver's power seat slide motor<br></b></nobr>");
write("</p>");
write("<p id=\"p8_18\" class=\"drag\" style=\"position:absolute;left:456px;top:260px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p8_19\" class=\"drag\" style=\"position:absolute;left:457px;top:146px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p8_20\" class=\"drag\" style=\"position:absolute;left:181px;top:187px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.13 (Not used)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_21\" class=\"drag\" style=\"position:absolute;left:684px;top:510px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Starter solenoid<br></b></nobr>");
write("</p>");
write("<p id=\"p8_22\" class=\"drag\" style=\"position:absolute;left:469px;top:567px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_23\" class=\"drag\" style=\"position:absolute;left:456px;top:510px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p8_24\" class=\"drag\" style=\"position:absolute;left:56px;top:481px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p8_25\" class=\"drag\" style=\"position:absolute;left:455px;top:660px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_26\" class=\"drag\" style=\"position:absolute;left:684px;top:660px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Door multiplex control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p8_27\" class=\"drag\" style=\"position:absolute;left:74px;top:582px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p8_28\" class=\"drag\" style=\"position:absolute;left:54px;top:631px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p8_29\" class=\"drag\" style=\"position:absolute;left:684px;top:717px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left rear power window motor<br></b></nobr>");
write("</p>");
write("<p id=\"p8_30\" class=\"drag\" style=\"position:absolute;left:457px;top:717px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_31\" class=\"drag\" style=\"position:absolute;left:291px;top:701px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.24 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_32\" class=\"drag\" style=\"position:absolute;left:291px;top:758px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.26 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_33\" class=\"drag\" style=\"position:absolute;left:457px;top:774px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_34\" class=\"drag\" style=\"position:absolute;left:684px;top:831px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right rear power window motor<br></b></nobr>");
write("</p>");
write("<p id=\"p8_35\" class=\"drag\" style=\"position:absolute;left:291px;top:816px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.25 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_36\" class=\"drag\" style=\"position:absolute;left:458px;top:831px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p8_37\" class=\"drag\" style=\"position:absolute;left:684px;top:888px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Driver's power window motor<br></b></nobr>");
write("</p>");
write("<p id=\"p8_38\" class=\"drag\" style=\"position:absolute;left:455px;top:888px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p8_39\" class=\"drag\" style=\"position:absolute;left:291px;top:873px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.27 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_40\" class=\"drag\" style=\"position:absolute;left:467px;top:945px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_41\" class=\"drag\" style=\"position:absolute;left:684px;top:945px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Sunroof motor<br></b></nobr>");
write("</p>");
write("<p id=\"p8_42\" class=\"drag\" style=\"position:absolute;left:291px;top:930px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.28 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_43\" class=\"drag\" style=\"position:absolute;left:68px;top:116px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p8_44\" class=\"drag\" style=\"position:absolute;left:189px;top:130px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.12 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_45\" class=\"drag\" style=\"position:absolute;left:38px;top:24px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.20 (40 A) FUSE <br>UNDER−HOOD <br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p8_46\" class=\"drag\" style=\"position:absolute;left:684px;top:145px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Multiplex integrated control unit <br>(for rear fog light)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_47\" class=\"drag\" style=\"position:absolute;left:684px;top:274px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Driver's power seat <br>front up−down motor<br></b></nobr>");
write("</p>");
write("<p id=\"p8_48\" class=\"drag\" style=\"position:absolute;left:684px;top:388px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Driver's power seat <br>rear up−down motor<br></b></nobr>");
write("</p>");
write("<p id=\"p8_49\" class=\"drag\" style=\"position:absolute;left:684px;top:331px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Front passenger's <br>seat heater and indicator<br></b></nobr>");
write("</p>");
write("<p id=\"p8_50\" class=\"drag\" style=\"position:absolute;left:52px;top:400px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>IGNITION <br>SWITCH (ST)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_51\" class=\"drag\" style=\"position:absolute;left:191px;top:464px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>STARTER <br>CUT RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p8_52\" class=\"drag\" style=\"position:absolute;left:191px;top:621px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>POWER <br>WINDOW RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p8_53\" class=\"drag\" style=\"position:absolute;left:41px;top:527px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.23 (P/W) (50 A) <br>FUSE  <br>UNDER−HOOD <br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p8_54\" class=\"drag\" style=\"position:absolute;left:684px;top:774px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Front passenger's power <br>window motor<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}