with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:863px;\" coordsize=\"950,863\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:863px;\">");
write("<img id=\"img1\" src=\"../img/SEA5E20B44100036401KBAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:863px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:363px;top:130px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>KNUCKLE<br></b>Check for deformation<br>and damage.<br></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:615px;top:230px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>6 x 1.0 mm<br>9.8 N·m<br>(1.0 kgf·m, 7.2 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:678px;top:338px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>O-RING<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:106px;top:590px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SPLASH GUARD<br></b>Check for corrosion,<br>deformation,<br>and damage.<br>Replace if rusted.<br></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:374px;top:716px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HUB BEARING UNIT<br></b>Check for faulty movement<br>and wear.<br></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:748px;top:785px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FLAT SCREW<br>6 x 1.0 mm<br>9.8 N·m<br>(1.0 kgf·m,7.2 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:837px;top:363px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BRAKE DISC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:172px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>10 x 1.25 mm<br>64 N·m<br>(6.5 kgf·m, 47 lbf·ft)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}