with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:511px;\" coordsize=\"950,511\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:511px;\">");
write("<img id=\"img1\" src=\"../img/SEA5E13D10600000000CAAD05.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:511px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:179px;top:28px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SPEED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:335px;top:17px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VEHICLE SPEED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:389px;top:41px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REFERENCE VEHICLE SPEED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:148px;top:217px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PRESSURE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:199px;top:317px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ON<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:143px;top:293px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OUTLET<br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:199px;top:344px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:145px;top:366px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INLET<br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:199px;top:390px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ON<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:200px;top:415px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:144px;top:439px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:199px;top:458px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ON<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:200px;top:483px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:714px;top:146px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>WHEEL SPEED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:695px;top:198px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TIME<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}