with(document) {
write("<v:group id=\"group2\" class=\"drag\" style=\"position:relative; width:950px; height:1039px;\" coordsize=\"950,1039\">");
write("<v:rect id=\"rect2\"class=\"drag\"  style=\"width:950px;height:1039px;\">");
write("<img id=\"img2\" src=\"../img/SEA5ED3A20300000000DBAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1039px;border-color:#ffffff\">");
write("<p id=\"p2_1\" class=\"drag\" style=\"position:absolute;left:758px;top:362px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>TRANSMISSION<br>RANGE SWITCH<br>(18) (A/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" class=\"drag\" style=\"position:absolute;left:18px;top:44px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>MAP SENSOR<br>(1)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" class=\"drag\" style=\"position:absolute;left:127px;top:30px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>TP SENSOR<br>(2) <br>(K20A6 engine)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" class=\"drag\" style=\"position:absolute;left:268px;top:31px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>IAT<br>SENSOR<br>(3)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" class=\"drag\" style=\"position:absolute;left:363px;top:16px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>OUTPUT SHAFT<br>(COUNTERSHAFT)<br>SPEED SENSOR<br>(4) (M/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" class=\"drag\" style=\"position:absolute;left:507px;top:31px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>A/F SENSOR<br>(SENSOR 1)<br>(5)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" class=\"drag\" style=\"position:absolute;left:816px;top:44px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>CMP SENSOR A<br>(7)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" class=\"drag\" style=\"position:absolute;left:38px;top:217px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>CMP SENSOR B<br>(8)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" class=\"drag\" style=\"position:absolute;left:169px;top:204px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>EVAP CANISTER<br>PURGE VALVE<br>(9)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" class=\"drag\" style=\"position:absolute;left:295px;top:204px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>ECT<br>SENSOR<br>(10)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" class=\"drag\" style=\"position:absolute;left:663px;top:44px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>EGR VALVE <br>(6)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" class=\"drag\" style=\"position:absolute;left:394px;top:230px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>24P JUNCTION CONNECTOR (11)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" class=\"drag\" style=\"position:absolute;left:663px;top:204px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>UNDER-HOOD<br>FUSE/RELAY<br>BOX (12)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" class=\"drag\" style=\"position:absolute;left:808px;top:230px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>ELD (13)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" class=\"drag\" style=\"position:absolute;left:53px;top:362px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>UNDER-HOOD<br>FUSE/RELAY<br>BOX (14)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" class=\"drag\" style=\"position:absolute;left:239px;top:362px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>UNDER-HOOD<br>FUSE/RELAY<br>BOX (15)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" class=\"drag\" style=\"position:absolute;left:439px;top:360px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>TEST<br>TACHOMETER<br>CONNECTOR<br>(16)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" class=\"drag\" style=\"position:absolute;left:604px;top:375px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>10P CONNECTOR <br>(17) (A/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" class=\"drag\" style=\"position:absolute;left:76px;top:668px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>SHIFT CONTROL<br>SOLENOID VALVE A<br>(25) (A/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" class=\"drag\" style=\"position:absolute;left:305px;top:520px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>SHIFT CONTROL<br>SOLENOID VALVE C<br>(21) (A/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" class=\"drag\" style=\"position:absolute;left:229px;top:667px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>SHIFT CONTROL<br>SOLENOID VALVE D<br>(26) (A/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_22\" class=\"drag\" style=\"position:absolute;left:382px;top:642px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>3RD CLUTCH<br>TRANSMISSION<br>FLUID<br>PRESSURE SWITCH<br>(27) (A/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_23\" class=\"drag\" style=\"position:absolute;left:60px;top:826px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>8P CONNECTOR<br>(30) (A/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_24\" class=\"drag\" style=\"position:absolute;left:540px;top:655px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>A/T CLUTCH<br>PRESSURE CONTROL<br>SOLENOID VALVE B<br>(28) (A/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_25\" class=\"drag\" style=\"position:absolute;left:712px;top:655px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>A/T CLUTCH<br>PRESSURE CONTROL<br>SOLENOID VALVE C<br>(29) (A/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_26\" class=\"drag\" style=\"position:absolute;left:412px;top:787px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>2ND CLUTCH<br>TRANSMISSION<br>FLUID<br>PRESSURE SWITCH<br>(32) (A/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_27\" class=\"drag\" style=\"position:absolute;left:569px;top:813px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>IAC VALVE <br>(33) <br>(K20A6 engine)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_28\" class=\"drag\" style=\"position:absolute;left:28px;top:507px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>INPUT SHAFT<br>(MAINSHAFT)<br>SPEED SENSOR<br>(19)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_29\" class=\"drag\" style=\"position:absolute;left:154px;top:507px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>OUTPUT SHAFT<br>(COUNTERSHAFT)<br>SPEED SENSOR<br>(20) (A/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_30\" class=\"drag\" style=\"position:absolute;left:625px;top:519px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>SHIFT CONTROL<br>SOLENOID VALVE E<br>(23) (A/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_31\" class=\"drag\" style=\"position:absolute;left:795px;top:507px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>ATF<br>TEMPERATURE<br>SENSOR <br>(24) (A/T) <br></b></nobr>");
write("</p>");
write("<p id=\"p2_32\" class=\"drag\" style=\"position:absolute;left:215px;top:800px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>A/T CLUTCH<br>PRESSURE CONTROL<br>SOLENOID VALVE A<br>(31) (A/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_33\" class=\"drag\" style=\"position:absolute;left:456px;top:520px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>SHIFT CONTROL<br>SOLENOID VALVE B<br>(22) (A/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_34\" class=\"drag\" style=\"position:absolute;left:751px;top:813px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>THROTTLE BODY<br>(34) <br>(K24A3 engine)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_35\" class=\"drag\" style=\"position:absolute;left:0px;top:975px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>NOTE:<br>· Connector with male terminals (double outline): view from terminal side<br>· Connector with female terminals (single outline): view from wire side<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}