with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1071px;\" coordsize=\"950,1071\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:1071px;\">");
write("<img id=\"img1\" src=\"../img/SEA5E20B44100019102KBAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1071px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:669px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SELF-LOCKING NUT<br>10 x 1.25 mm<br>29 N·m (3.0 kgf·m, 22 lbf·ft)<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:728px;top:134px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RUBBER BUSHING<br></b>Check for weakness<br>and damage.<br></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:738px;top:240px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DAMPER MOUNTING BASE<br></b>Check for deformation.<br></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:713px;top:370px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SPRING MOUNTING<br>CUSHION<br></b>Check for deterioration<br>and damage.<br></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:710px;top:708px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DUST COVER LOWER MOUNTING<br></b>Check for deterioration <br>and damage.<br></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:34px;top:575px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DUST COVER PLATE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:736px;top:565px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BUMP STOP PLATE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:738px;top:623px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BUMP STOP<br></b>Check for weakness <br>and damage.<br></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:55px;top:806px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DUST COVER<br></b>Check for bending and damage.<br></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:712px;top:984px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DAMPER UNIT<br></b>Check for oil leaks, gas leaks, <br>and smooth operation.<br></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:26px;top:208px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DAMPER SPRING<br></b>Check for free length.<br></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:709px;top:87px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>WASHER<br></b>Check for deformation.<br></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:745px;top:295px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RUBBER BUSHING<br></b>Check for weakness<br>and damage.<br></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:738px;top:199px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>COLLAR<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}