with(document) {
write("<v:group id=\"group5\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\" coordsize=\"950,1103\">");
write("<v:rect id=\"rect5\"class=\"drag\"  style=\"width:950px;height:1103px;\">");
write("<img id=\"img5\" src=\"../img/SEA5EB3A20300000000EAAD05.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p5_1\" class=\"drag\" style=\"position:absolute;left:789px;top:383px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SHIFT SOLENOID<br>VALVE D<br></b></nobr>");
write("</p>");
write("<p id=\"p5_2\" class=\"drag\" style=\"position:absolute;left:233px;top:491px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_3\" class=\"drag\" style=\"position:absolute;left:191px;top:482px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C1<br></b></nobr>");
write("</p>");
write("<p id=\"p5_4\" class=\"drag\" style=\"position:absolute;left:233px;top:573px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p5_5\" class=\"drag\" style=\"position:absolute;left:233px;top:655px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p5_6\" class=\"drag\" style=\"position:absolute;left:191px;top:564px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C15<br></b></nobr>");
write("</p>");
write("<p id=\"p5_7\" class=\"drag\" style=\"position:absolute;left:191px;top:646px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C7<br></b></nobr>");
write("</p>");
write("<p id=\"p5_8\" class=\"drag\" style=\"position:absolute;left:233px;top:799px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p5_9\" class=\"drag\" style=\"position:absolute;left:191px;top:789px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C19<br></b></nobr>");
write("</p>");
write("<p id=\"p5_10\" class=\"drag\" style=\"position:absolute;left:237px;top:967px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p5_11\" class=\"drag\" style=\"position:absolute;left:191px;top:958px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A18<br></b></nobr>");
write("</p>");
write("<p id=\"p5_12\" class=\"drag\" style=\"position:absolute;left:748px;top:539px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A/T CLUTCH PRESSURE<br>CONTROL SOLENOID VALVE A<br></b></nobr>");
write("</p>");
write("<p id=\"p5_13\" class=\"drag\" style=\"position:absolute;left:748px;top:622px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A/T CLUTCH PRESSURE<br>CONTROL SOLENOID VALVE B<br></b></nobr>");
write("</p>");
write("<p id=\"p5_14\" class=\"drag\" style=\"position:absolute;left:748px;top:706px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A/T CLUTCH PRESSURE<br>CONTROL SOLENOID VALVE C<br></b></nobr>");
write("</p>");
write("<p id=\"p5_15\" class=\"drag\" style=\"position:absolute;left:798px;top:851px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>INPUT SHAFT<br>(MAINSHAFT)<br>SPEED SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p5_16\" class=\"drag\" style=\"position:absolute;left:659px;top:879px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p5_17\" class=\"drag\" style=\"position:absolute;left:694px;top:831px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p5_18\" class=\"drag\" style=\"position:absolute;left:694px;top:765px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p5_19\" class=\"drag\" style=\"position:absolute;left:617px;top:719px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p5_20\" class=\"drag\" style=\"position:absolute;left:797px;top:1020px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>OUTPUT SHAFT<br>(COUNTERSHAFT)<br>SPEED SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p5_21\" class=\"drag\" style=\"position:absolute;left:694px;top:934px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p5_22\" class=\"drag\" style=\"position:absolute;left:617px;top:888px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p5_23\" class=\"drag\" style=\"position:absolute;left:694px;top:999px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p5_24\" class=\"drag\" style=\"position:absolute;left:27px;top:45px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p5_25\" class=\"drag\" style=\"position:absolute;left:191px;top:422px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C3<br></b></nobr>");
write("</p>");
write("<p id=\"p5_26\" class=\"drag\" style=\"position:absolute;left:237px;top:431px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p5_27\" class=\"drag\" style=\"position:absolute;left:789px;top:456px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SHIFT SOLENOID<br>VALVE E<br></b></nobr>");
write("</p>");
write("<p id=\"p5_28\" class=\"drag\" style=\"position:absolute;left:744px;top:430px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p5_29\" class=\"drag\" style=\"position:absolute;left:763px;top:927px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p5_30\" class=\"drag\" style=\"position:absolute;left:781px;top:483px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p5_31\" class=\"drag\" style=\"position:absolute;left:763px;top:959px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p5_32\" class=\"drag\" style=\"position:absolute;left:764px;top:991px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p5_33\" class=\"drag\" style=\"position:absolute;left:610px;top:1084px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p5_34\" class=\"drag\" style=\"position:absolute;left:190px;top:499px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LSA<br></b></nobr>");
write("</p>");
write("<p id=\"p5_35\" class=\"drag\" style=\"position:absolute;left:190px;top:581px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LSB<br></b></nobr>");
write("</p>");
write("<p id=\"p5_36\" class=\"drag\" style=\"position:absolute;left:190px;top:663px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LSC<br></b></nobr>");
write("</p>");
write("<p id=\"p5_37\" class=\"drag\" style=\"position:absolute;left:190px;top:807px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>NM<br></b></nobr>");
write("</p>");
write("<p id=\"p5_38\" class=\"drag\" style=\"position:absolute;left:190px;top:975px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>NC<br></b></nobr>");
write("</p>");
write("<p id=\"p5_39\" class=\"drag\" style=\"position:absolute;left:191px;top:439px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SHE<br></b></nobr>");
write("</p>");
write("<p id=\"p5_40\" class=\"drag\" style=\"position:absolute;left:191px;top:88px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C14<br></b></nobr>");
write("</p>");
write("<p id=\"p5_41\" class=\"drag\" style=\"position:absolute;left:233px;top:97px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p5_42\" class=\"drag\" style=\"position:absolute;left:191px;top:161px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C6<br></b></nobr>");
write("</p>");
write("<p id=\"p5_43\" class=\"drag\" style=\"position:absolute;left:233px;top:169px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_44\" class=\"drag\" style=\"position:absolute;left:191px;top:223px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C4<br></b></nobr>");
write("</p>");
write("<p id=\"p5_45\" class=\"drag\" style=\"position:absolute;left:233px;top:232px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p5_46\" class=\"drag\" style=\"position:absolute;left:783px;top:130px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ATF TEMPERATURE<br>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p5_47\" class=\"drag\" style=\"position:absolute;left:572px;top:53px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p5_48\" class=\"drag\" style=\"position:absolute;left:744px;top:96px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p5_49\" class=\"drag\" style=\"position:absolute;left:744px;top:113px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p5_50\" class=\"drag\" style=\"position:absolute;left:789px;top:195px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SHIFT SOLENOID<br>VALVE A<br></b></nobr>");
write("</p>");
write("<p id=\"p5_51\" class=\"drag\" style=\"position:absolute;left:744px;top:169px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p5_52\" class=\"drag\" style=\"position:absolute;left:789px;top:257px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SHIFT SOLENOID<br>VALVE B<br></b></nobr>");
write("</p>");
write("<p id=\"p5_53\" class=\"drag\" style=\"position:absolute;left:744px;top:232px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p5_54\" class=\"drag\" style=\"position:absolute;left:599px;top:114px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p5_55\" class=\"drag\" style=\"position:absolute;left:672px;top:67px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>8P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p5_56\" class=\"drag\" style=\"position:absolute;left:689px;top:88px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p5_57\" class=\"drag\" style=\"position:absolute;left:191px;top:105px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ATFT<br></b></nobr>");
write("</p>");
write("<p id=\"p5_58\" class=\"drag\" style=\"position:absolute;left:191px;top:178px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SHA<br></b></nobr>");
write("</p>");
write("<p id=\"p5_59\" class=\"drag\" style=\"position:absolute;left:191px;top:240px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SHB<br></b></nobr>");
write("</p>");
write("<p id=\"p5_60\" class=\"drag\" style=\"position:absolute;left:191px;top:286px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C2<br></b></nobr>");
write("</p>");
write("<p id=\"p5_61\" class=\"drag\" style=\"position:absolute;left:237px;top:295px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p5_62\" class=\"drag\" style=\"position:absolute;left:789px;top:320px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SHIFT SOLENOID<br>VALVE C<br></b></nobr>");
write("</p>");
write("<p id=\"p5_63\" class=\"drag\" style=\"position:absolute;left:744px;top:295px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p5_64\" class=\"drag\" style=\"position:absolute;left:191px;top:303px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SHC<br></b></nobr>");
write("</p>");
write("<p id=\"p5_65\" class=\"drag\" style=\"position:absolute;left:191px;top:349px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C5<br></b></nobr>");
write("</p>");
write("<p id=\"p5_66\" class=\"drag\" style=\"position:absolute;left:237px;top:357px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p5_67\" class=\"drag\" style=\"position:absolute;left:744px;top:357px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p5_68\" class=\"drag\" style=\"position:absolute;left:191px;top:366px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SHD<br></b></nobr>");
write("</p>");
write("<p id=\"p5_69\" class=\"drag\" style=\"position:absolute;left:781px;top:513px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p5_70\" class=\"drag\" style=\"position:absolute;left:781px;top:565px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p5_71\" class=\"drag\" style=\"position:absolute;left:781px;top:595px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p5_72\" class=\"drag\" style=\"position:absolute;left:781px;top:647px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p5_73\" class=\"drag\" style=\"position:absolute;left:781px;top:677px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p5_74\" class=\"drag\" style=\"position:absolute;left:744px;top:521px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_75\" class=\"drag\" style=\"position:absolute;left:744px;top:603px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_76\" class=\"drag\" style=\"position:absolute;left:744px;top:685px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p5_77\" class=\"drag\" style=\"position:absolute;left:697px;top:746px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p5_78\" class=\"drag\" style=\"position:absolute;left:689px;top:105px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p5_79\" class=\"drag\" style=\"position:absolute;left:689px;top:161px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p5_80\" class=\"drag\" style=\"position:absolute;left:689px;top:221px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p5_81\" class=\"drag\" style=\"position:absolute;left:689px;top:283px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p5_82\" class=\"drag\" style=\"position:absolute;left:690px;top:348px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p5_83\" class=\"drag\" style=\"position:absolute;left:689px;top:419px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p5_84\" class=\"drag\" style=\"position:absolute;left:763px;top:758px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p5_85\" class=\"drag\" style=\"position:absolute;left:763px;top:790px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p5_86\" class=\"drag\" style=\"position:absolute;left:764px;top:822px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p5_87\" class=\"drag\" style=\"position:absolute;left:237px;top:1024px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>*1: A/T<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}