with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1023px;\" coordsize=\"950,1023\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:1023px;\">");
write("<img id=\"img1\" src=\"../img/SEA5E00J20170700000KBAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1023px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:74px;top:631px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Bottom view<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:95px;top:786px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Forward<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:50px;top:828px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LOWER INSULATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:78px;top:874px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT SUSPENSION<br>FRAME FRONT<br>BRACKET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:141px;top:934px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SPECIAL BOLT<br>14 x 1.5 mm<br>103 N·m (10.5 kgf·m, <br>76 lbf·ft)<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:329px;top:963px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>12 x 1.25 mm<br>54 N·m <br>(5.5 kgf·m, 40 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:324px;top:887px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>8 x 1.25 mm<br>22 N·m <br>(2.2 kgf·m, 16 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:463px;top:790px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT SUSPENSION<br>SUBFRAME REAR BRACKET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:363px;top:850px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT SUSPENSION<br>SUBFRAME FRONT DAMPER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:587px;top:336px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT SUSPENSION<br>SUBFRAME REAR DAMPER<br>(A/T model)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:580px;top:950px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SPECIAL BOLT<br>14 x 1.5 mm<br>103 N·m (10.5 kgf·m, 76 lbf·ft)<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:722px;top:878px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>12 x 1.25 mm<br>93 N·m <br>(9.5 kgf·m, 69 lbf·ft)<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:274px;top:741px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>To body<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:793px;top:602px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Bottom view<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:802px;top:762px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Forward<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:769px;top:565px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LOWER INSULATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:765px;top:423px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>10 x 1.25 mm<br>59 N·m <br>(6.0 kgf·m, 43 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:648px;top:395px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>STEERING GEARBOX<br>STIFFENER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:392px;top:381px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>10 x 1.25 mm<br>22 N·m <br>(2.2 kgf·m, 16 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:166px;top:336px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT SUSPENSION<br>SUBFRAME MIDDLE<br>MOUTING RUBBER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:10px;top:371px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>10 x 1.25 mm<br>49 N·m <br>(5.0 kgf·m, 36 lbf·ft)<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:13px;top:475px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>12 x 1.25 mm<br>44 N·m <br>(4.5 kgf·m, 33 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:26px;top:561px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT SUSPENSION<br>SUBFRAME<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:228px;top:563px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>To body<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:680px;top:681px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>To body<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:665px;top:494px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>To body<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:303px;top:441px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>To body<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:184px;top:54px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT SUSPENSION<br>SUBFRAME<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}