with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1119px;\" coordsize=\"950,1119\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:1119px;\">");
write("<img id=\"img1\" src=\"../img/SEA5E43A20326428001MAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1119px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:644px;top:169px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:582px;top:211px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:430px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:230px;top:283px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>To FUEL<br>RAIL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:126px;top:457px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>To EVAPORATIVE<br>EMISSION (EVAP) <br>CANISTER<br>PURGE VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:194px;top:551px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:194px;top:841px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>B:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:566px;top:839px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:580px;top:708px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>105 °<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:698px;top:688px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>10 °<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:374px;top:949px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>90 °<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:296px;top:873px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>There should be no<br>clearance.<br></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:191px;top:1068px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>When installing the fuel fill tube,<br>align the marks on the tube and the line.<br></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:686px;top:922px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>TOP<br></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:573px;top:1038px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>Mark<br></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:158px;top:17px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BASE GASKET<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:669px;top:952px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>90 °<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:542px;top:569px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>Make sure that the<br>clamp is in position<br>within the lever<br>end of it the range<br>shown.<br></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:527px;top:1070px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>Make sure that the clamp is in position<br>within the lever end of it the range shown.<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}