with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1087px;\" coordsize=\"950,1087\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:1087px;\">");
write("<img id=\"img1\" src=\"../img/SEA5E44E16226600000LDAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1087px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:217px;top:972px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OUTBOARD BOOT (TPE)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:243px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SET RING<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:353px;top:34px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INBOARD JOINT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:381px;top:105px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CIRCLIP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:550px;top:33px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ROLLER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:569px;top:129px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SPIDER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:724px;top:191px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INBOARD BOOT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:385px;top:419px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DYNAMIC DAMPER<br></b>(Directional)<br></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:642px;top:512px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DRIVESHAFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:837px;top:573px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>STOP RING<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:575px;top:758px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EAR CLAMP BANDS<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:743px;top:850px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OUTBOARD JOINT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:724px;top:249px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>Use the grease included in the<br>inboard boot set.<br></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:574px;top:400px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DOUBLE LOOP BANDS<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:106px;top:313px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Right driveshaft<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:321px;top:344px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>Use the grease included in the<br>inboard boot set.<br></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:472px;top:467px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DOUBLE LOOP BAND<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:434px;top:1037px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>Use the grease included in the<br>outboard boot set.<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}