with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1007px;\" coordsize=\"950,1007\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:1007px;\">");
write("<img id=\"img1\" src=\"../img/SEA5E13A18224000000KBAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1007px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:463px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR MOUNT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:155px;top:111px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SIDE ENGINE MOUNT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:684px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>10 x 1.25 mm<br>54 N·m <br>(5.5 kgf·m, 40 lbf·ft)<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:17px;top:44px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>12 x 1.25 mm<br>64 N·m <br>(6.5 kgf·m, 47 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:776px;top:560px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>10 x 1.25 mm<br>44 N·m <br>(4.5 kgf·m, 33 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:593px;top:316px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TRANSMISSION LOWER<br>MOUNT (A/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:538px;top:683px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TRANSMISSION LOWER<br>MOUNT (M/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:761px;top:934px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>12 x 1.25 mm<br>59 N·m <br>(6.0 kgf·m, 43 lbf·ft)<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:198px;top:941px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT MOUNT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:45px;top:644px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>10 x 1.25 mm<br>54 N·m <br>(5.5 kgf·m, 40 lbf·ft)<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:762px;top:840px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>10 x 1.25 mm<br>44 N·m <br>(4.5 kgf·m, 33 lbf·ft)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}