with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:475px; height:320px;\" coordsize=\"475,320\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:475px;height:320px;\">");
write("<img id=\"img1\" src=\"../img/SEA5EAPK77100000000BBAD03.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:320px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:19px;top:287px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:138px;top:208px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Long blink<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:264px;top:208px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Short blinks (five times)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:16px;top:175px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Example: DTC 15-5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:15px;top:15px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Example: DTC 1-1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:130px;top:46px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Short blink (once)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:19px;top:121px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:74px;top:85px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>ON<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:73px;top:247px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>ON<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}