with(document) {
write("<v:group id=\"group2\" class=\"drag\" style=\"position:relative; width:640px; height:950px;\" coordsize=\"640,950\">");
write("<v:rect id=\"rect2\"class=\"drag\"  style=\"width:640px;height:950px;\">");
write("<img id=\"img2\" src=\"../img/SEA5E44000000000000EBA214.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:640px;height:950px;border-color:#ffffff\">");
write("<p id=\"p2_1\" class=\"drag\" style=\"position:absolute;left:91px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" class=\"drag\" style=\"position:absolute;left:535px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" class=\"drag\" style=\"position:absolute;left:361px;top:678px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>40<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" class=\"drag\" style=\"position:absolute;left:348px;top:623px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" class=\"drag\" style=\"position:absolute;left:158px;top:523px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>MULTIPLEX INTEGRATED CONTROL UNIT (MICU)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" class=\"drag\" style=\"position:absolute;left:269px;top:883px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>G601<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" class=\"drag\" style=\"position:absolute;left:271px;top:788px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" class=\"drag\" style=\"position:absolute;left:608px;top:280px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" class=\"drag\" style=\"position:absolute;left:600px;top:402px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" class=\"drag\" style=\"position:absolute;left:218px;top:340px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>48<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" class=\"drag\" style=\"position:absolute;left:204px;top:400px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" class=\"drag\" style=\"position:absolute;left:108px;top:400px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" class=\"drag\" style=\"position:absolute;left:118px;top:340px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>28<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" class=\"drag\" style=\"position:absolute;left:419px;top:400px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" class=\"drag\" style=\"position:absolute;left:426px;top:339px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>30<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" class=\"drag\" style=\"position:absolute;left:296px;top:340px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>49<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" class=\"drag\" style=\"position:absolute;left:283px;top:400px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" class=\"drag\" style=\"position:absolute;left:52px;top:340px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>37<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" class=\"drag\" style=\"position:absolute;left:42px;top:400px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" class=\"drag\" style=\"position:absolute;left:-28px;top:400px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" class=\"drag\" style=\"position:absolute;left:-14px;top:340px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>56<br></b></nobr>");
write("</p>");
write("<p id=\"p2_22\" class=\"drag\" style=\"position:absolute;left:-79px;top:340px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_23\" class=\"drag\" style=\"position:absolute;left:-161px;top:690px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>DATA LINK<br>CONNECTOR<br>(DLC)<br>‹26−C›<br></b></nobr>");
write("</p>");
write("<p id=\"p2_24\" class=\"drag\" style=\"position:absolute;left:179px;top:652px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>MULTIPLEX <br>CONTROL <br>INSPECTION <br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_25\" class=\"drag\" style=\"position:absolute;left:348px;top:691px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BRAKE <br>PEDAL <br>POSITION <br>SWITCH <br>‹8−A› <br></b></nobr>");
write("</p>");
write("<p id=\"p2_26\" class=\"drag\" style=\"position:absolute;left:-226px;top:298px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RELAY <br>CONTROL <br>MODULE <br>‹5−B› <br></b></nobr>");
write("</p>");
write("<p id=\"p2_27\" class=\"drag\" style=\"position:absolute;left:-163px;top:299px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>CLIMATE <br>CONTROL <br>UNIT <br>‹22−C› <br></b></nobr>");
write("</p>");
write("<p id=\"p2_28\" class=\"drag\" style=\"position:absolute;left:37px;top:289px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>COMBINATION <br>SWITCH <br>CONTROL <br>UNIT <br>‹7−B› <br></b></nobr>");
write("</p>");
write("<p id=\"p2_29\" class=\"drag\" style=\"position:absolute;left:105px;top:307px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RAIN <br>SENSOR <br>‹6−A› <br></b></nobr>");
write("</p>");
write("<p id=\"p2_30\" class=\"drag\" style=\"position:absolute;left:205px;top:307px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>CEILING <br>LIGHT <br>‹9−C› <br></b></nobr>");
write("</p>");
write("<p id=\"p2_31\" class=\"drag\" style=\"position:absolute;left:283px;top:289px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>DRIVER'S <br>DOOR <br>COURTESY <br>LIGHT <br>‹9−D› <br></b></nobr>");
write("</p>");
write("<p id=\"p2_32\" class=\"drag\" style=\"position:absolute;left:430px;top:299px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>REAR WINDOW<br>WIPER MOTOR RELAY<br>‹6−B, C› <br></b></nobr>");
write("</p>");
write("<p id=\"p2_33\" class=\"drag\" style=\"position:absolute;left:638px;top:326px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>IGNITION<br>KEY<br>LIGHT<br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_34\" class=\"drag\" style=\"position:absolute;left:2px;top:684px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>DRIVER'S<br>SEAT BELT<br>SWITCH<br>(Closed : Unbuckled)<br>(Open : Buckled)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_35\" class=\"drag\" style=\"position:absolute;left:-24px;top:886px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>G601<br></b></nobr>");
write("</p>");
write("<p id=\"p2_36\" class=\"drag\" style=\"position:absolute;left:-26px;top:622px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_37\" class=\"drag\" style=\"position:absolute;left:-93px;top:400px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_38\" class=\"drag\" style=\"position:absolute;left:205px;top:278px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>INDIVIDUAL <br>MAP LIGHTS  <br>‹9−C› <br></b></nobr>");
write("</p>");
write("<p id=\"p2_39\" class=\"drag\" style=\"position:absolute;left:-372px;top:412px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>Fuse/relay <br>box socket)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_40\" class=\"drag\" style=\"position:absolute;left:-229px;top:690px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>AUDIO UNIT <br>‹18−A›<br></b></nobr>");
write("</p>");
write("<p id=\"p2_41\" class=\"drag\" style=\"position:absolute;left:-19px;top:789px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_42\" class=\"drag\" style=\"position:absolute;left:156px;top:401px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_43\" class=\"drag\" style=\"position:absolute;left:167px;top:340px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>63<br></b></nobr>");
write("</p>");
write("<p id=\"p2_44\" class=\"drag\" style=\"position:absolute;left:155px;top:289px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>POWER<br>TAILGATE<br>CONTROL<br>UNIT<br>‹16−B› <br></b></nobr>");
write("</p>");
write("<p id=\"p2_45\" class=\"drag\" style=\"position:absolute;left:477px;top:401px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LT GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_46\" class=\"drag\" style=\"position:absolute;left:492px;top:340px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>31<br></b></nobr>");
write("</p>");
write("<p id=\"p2_47\" class=\"drag\" style=\"position:absolute;left:552px;top:340px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>32<br></b></nobr>");
write("</p>");
write("<p id=\"p2_48\" class=\"drag\" style=\"position:absolute;left:531px;top:298px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>REAR WINDOW<br>WASHER MOTOR<br>RELAY <br>‹6−C› <br></b></nobr>");
write("</p>");
write("<p id=\"p2_49\" class=\"drag\" style=\"position:absolute;left:362px;top:340px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>50<br></b></nobr>");
write("</p>");
write("<p id=\"p2_50\" class=\"drag\" style=\"position:absolute;left:359px;top:400px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p2_51\" class=\"drag\" style=\"position:absolute;left:352px;top:280px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>FRONT<br>PASSENGER'S<br>DOOR<br>COURTESY<br>LIGHT<br>‹9−D› <br></b></nobr>");
write("</p>");
write("<p id=\"p2_52\" class=\"drag\" style=\"position:absolute;left:551px;top:401px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_53\" class=\"drag\" style=\"position:absolute;left:551px;top:414px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>: WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_54\" class=\"drag\" style=\"position:absolute;left:538px;top:414px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_55\" class=\"drag\" style=\"position:absolute;left:538px;top:400px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_56\" class=\"drag\" style=\"position:absolute;left:-297px;top:298px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>No.32<br>(7.5A)<br>FUSE <br>‹17−D› <br></b></nobr>");
write("</p>");
write("<p id=\"p2_57\" class=\"drag\" style=\"position:absolute;left:-303px;top:411px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>Fuse/relay <br>box socket)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}