with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:831px;\" coordsize=\"950,831\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:831px;\">");
write("<img id=\"img1\" src=\"../img/SEA5EB4A20326400000DAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:831px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:18px;top:700px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL RAIL<br><a href=\"javascript:parent.Cts('000000000002977','i000')\"></b>Replacement,<br></a><br></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:436px;top:756px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL RETURN LINE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:113px;top:781px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL RAIL PRESSURE (FRP)<br>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:613px;top:635px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL FEED LINE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:683px;top:581px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL VAPOR LINE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:724px;top:464px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>QUICK-CONNECT<br>FITTING<br><a href=\"javascript:parent.Cts('000000000001327','i000')\"></b>Precaution,</a><br><a href=\"javascript:parent.Cts('000000000001328','i000')\">Removal,</a><br><a href=\"javascript:parent.Cts('000000000001329','i000')\">Installation,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:107px;top:183px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL RETURN HOSE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:220px;top:114px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HIGH PRESSURE PIPES<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:824px;top:94px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL FILL CAP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:700px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL TANK<br><a href=\"javascript:parent.Cts('000000000001335','i000')\"></b>Draining,</a><br><a href=\"javascript:parent.Cts('000000000001334','i000')\">Replacement,</a><br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}