with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1108px;\" coordsize=\"950,1108\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:1108px;\">");
write("<img id=\"img1\" src=\"../img/SEA5E44J26346100000EAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1108px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:91px;top:796px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:162px;top:796px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:162px;top:882px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN/ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:190px;top:592px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>B13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:216px;top:489px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>INTERFACE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:757px;top:1068px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:707px;top:1068px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:75px;top:189px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:275px;top:996px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:159px;top:116px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:159px;top:105px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:636px;top:839px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>: P2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:622px;top:839px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:622px;top:824px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:636px;top:824px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>: P13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:307px;top:839px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>: P14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:293px;top:839px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:293px;top:824px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:307px;top:824px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>: P1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:307px;top:727px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>: P7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:293px;top:727px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:293px;top:741px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:307px;top:742px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>: P8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:840px;top:99px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RHD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:833px;top:98px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:816px;top:99px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:816px;top:82px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:833px;top:80px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:840px;top:82px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LHD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:90px;top:492px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:90px;top:592px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:261px;top:689px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" class=\"drag\" style=\"position:absolute;left:271px;top:1068px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G502<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" class=\"drag\" style=\"position:absolute;left:334px;top:996px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" class=\"drag\" style=\"position:absolute;left:328px;top:1068px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G601<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" class=\"drag\" style=\"position:absolute;left:347px;top:856px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>E9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" class=\"drag\" style=\"position:absolute;left:436px;top:360px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>DRIVE CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" class=\"drag\" style=\"position:absolute;left:321px;top:360px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>DRIVE CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" class=\"drag\" style=\"position:absolute;left:216px;top:360px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>INTERFACE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" class=\"drag\" style=\"position:absolute;left:226px;top:438px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>AREA NETWORK CONTROLLER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" class=\"drag\" style=\"position:absolute;left:226px;top:426px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>POWER SUPPLY CIRCUIT/CONTROLLER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" class=\"drag\" style=\"position:absolute;left:385px;top:882px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" class=\"drag\" style=\"position:absolute;left:833px;top:52px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" class=\"drag\" style=\"position:absolute;left:816px;top:53px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" class=\"drag\" style=\"position:absolute;left:816px;top:25px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" class=\"drag\" style=\"position:absolute;left:833px;top:23px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" class=\"drag\" style=\"position:absolute;left:394px;top:979px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" class=\"drag\" style=\"position:absolute;left:387px;top:978px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" class=\"drag\" style=\"position:absolute;left:373px;top:979px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" class=\"drag\" style=\"position:absolute;left:373px;top:961px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" class=\"drag\" style=\"position:absolute;left:387px;top:959px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" class=\"drag\" style=\"position:absolute;left:394px;top:961px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" class=\"drag\" style=\"position:absolute;left:776px;top:592px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>B21<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" class=\"drag\" style=\"position:absolute;left:726px;top:592px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>B20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" class=\"drag\" style=\"position:absolute;left:762px;top:689px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" class=\"drag\" style=\"position:absolute;left:712px;top:689px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" class=\"drag\" style=\"position:absolute;left:412px;top:856px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>F14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" class=\"drag\" style=\"position:absolute;left:504px;top:689px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" class=\"drag\" style=\"position:absolute;left:526px;top:706px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>X27<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" class=\"drag\" style=\"position:absolute;left:412px;top:706px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>N28<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" class=\"drag\" style=\"position:absolute;left:384px;top:689px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" class=\"drag\" style=\"position:absolute;left:596px;top:292px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BEEPER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" class=\"drag\" style=\"position:absolute;left:126px;top:213px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GAUGE CONTROL MODULE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" class=\"drag\" style=\"position:absolute;left:776px;top:213px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>B6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" class=\"drag\" style=\"position:absolute;left:726px;top:213px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>B5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" class=\"drag\" style=\"position:absolute;left:412px;top:592px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>B25<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" class=\"drag\" style=\"position:absolute;left:641px;top:124px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.21 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" class=\"drag\" style=\"position:absolute;left:645px;top:66px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.7 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" class=\"drag\" style=\"position:absolute;left:747px;top:189px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" class=\"drag\" style=\"position:absolute;left:626px;top:42px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" class=\"drag\" style=\"position:absolute;left:242px;top:66px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.15 (30 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" class=\"drag\" style=\"position:absolute;left:139px;top:66px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.22 (BAT) (100 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" class=\"drag\" style=\"position:absolute;left:710px;top:189px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" class=\"drag\" style=\"position:absolute;left:359px;top:139px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" class=\"drag\" style=\"position:absolute;left:470px;top:150px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" class=\"drag\" style=\"position:absolute;left:453px;top:126px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BAT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" class=\"drag\" style=\"position:absolute;left:556px;top:139px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" class=\"drag\" style=\"position:absolute;left:361px;top:82px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" class=\"drag\" style=\"position:absolute;left:232px;top:124px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.23 (IG) (50 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" class=\"drag\" style=\"position:absolute;left:126px;top:42px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNDER−HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" class=\"drag\" style=\"position:absolute;left:65px;top:56px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BATTERY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" class=\"drag\" style=\"position:absolute;left:426px;top:99px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>IGNITION SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" class=\"drag\" style=\"position:absolute;left:394px;top:918px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" class=\"drag\" style=\"position:absolute;left:599px;top:1068px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" class=\"drag\" style=\"position:absolute;left:392px;top:1068px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G601<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" class=\"drag\" style=\"position:absolute;left:398px;top:996px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" class=\"drag\" style=\"position:absolute;left:592px;top:882px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" class=\"drag\" style=\"position:absolute;left:602px;top:996px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" class=\"drag\" style=\"position:absolute;left:616px;top:961px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" class=\"drag\" style=\"position:absolute;left:616px;top:918px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" class=\"drag\" style=\"position:absolute;left:840px;top:25px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>With 8−way <br>power seat<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" class=\"drag\" style=\"position:absolute;left:840px;top:53px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Without 8−way <br>power seat<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" class=\"drag\" style=\"position:absolute;left:433px;top:276px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LIGHTS ON <br>INDICATOR <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" class=\"drag\" style=\"position:absolute;left:326px;top:265px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>SEAT BELT <br>REMINDER <br>LIGHT <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" class=\"drag\" style=\"position:absolute;left:308px;top:485px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BODY−CONTROLLER <br>AREA NETWORK <br>TRANSCEIVER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" class=\"drag\" style=\"position:absolute;left:146px;top:396px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRAKE <br>SYSTEM <br>LIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" class=\"drag\" style=\"position:absolute;left:33px;top:593px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>IGNITION <br>KEY <br>LIGHT <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" class=\"drag\" style=\"position:absolute;left:447px;top:593px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>COMBINATION SWITCH <br>CONTROL UNIT <br>(in the WIPER/WASHER SWITCH <br>or COMBINATION LIGHT SWITCH)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" class=\"drag\" style=\"position:absolute;left:554px;top:733px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>MULTIPLEX INTEGRATED <br>CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" class=\"drag\" style=\"position:absolute;left:612px;top:696px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNDER−DASH <br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" class=\"drag\" style=\"position:absolute;left:633px;top:922px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>IGNITION <br>KEY <br>SWITCH <br>(Closed : <br>Key inserted)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" class=\"drag\" style=\"position:absolute;left:426px;top:922px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>DRIVER'S <br>SEAT BELT <br>SWITCH <br>(Closed : Unbuckled)<br>(Open : Buckled)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" class=\"drag\" style=\"position:absolute;left:204px;top:922px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>PARKING  <br>BRAKE <br>SWITCH<br>(Closed : <br>Lever up)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" class=\"drag\" style=\"position:absolute;left:83px;top:702px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>IMMOBILIZER <br>CONTROL UNIT−<br>RECEIVER<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}