with(document) {
write("<v:group id=\"group3\" class=\"drag\" style=\"position:relative; width:640px; height:950px;\" coordsize=\"640,950\">");
write("<v:rect id=\"rect3\"class=\"drag\"  style=\"width:640px;height:950px;\">");
write("<img id=\"img3\" src=\"../img/SEA5E44000000000000EBA326.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:640px;height:950px;border-color:#ffffff\">");
write("<p id=\"p3_1\" class=\"drag\" style=\"position:absolute;left:-94px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p3_2\" class=\"drag\" style=\"position:absolute;left:348px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p3_3\" class=\"drag\" style=\"position:absolute;left:-261px;top:750px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>DATA LINK CONNECTOR (DLC)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_4\" class=\"drag\" style=\"position:absolute;left:-27px;top:616px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_5\" class=\"drag\" style=\"position:absolute;left:-27px;top:694px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_6\" class=\"drag\" style=\"position:absolute;left:577px;top:36px;font-weight:normal;font-size:17.6pt;\">");
write("<nobr><b>26<br></b></nobr>");
write("</p>");
write("<p id=\"p3_7\" class=\"drag\" style=\"position:absolute;left:-139px;top:527px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>SRS UNIT <br>‹21−D›<br></b></nobr>");
write("</p>");
write("<p id=\"p3_8\" class=\"drag\" style=\"position:absolute;left:-369px;top:508px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>PARKING <br>BRAKE <br>SWITCH <br>‹4−C›<br></b></nobr>");
write("</p>");
write("<p id=\"p3_9\" class=\"drag\" style=\"position:absolute;left:-305px;top:246px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>IMMOBILIZER <br>INDICATOR <br>‹2−B›<br></b></nobr>");
write("</p>");
write("<p id=\"p3_10\" class=\"drag\" style=\"position:absolute;left:-968px;top:700px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>CLUTCH<br>PEDAL<br>POSITION<br>SWITCH A <br>(Closed : <br> Pedal pressed)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_11\" class=\"drag\" style=\"position:absolute;left:-837px;top:699px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>CLUTCH<br>PEDAL<br>POSITION<br>SWITCH B <br>(Closed : <br> Pedal pressed)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_12\" class=\"drag\" style=\"position:absolute;left:-24px;top:551px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>42<br></b></nobr>");
write("</p>");
write("<p id=\"p3_13\" class=\"drag\" style=\"position:absolute;left:-693px;top:227px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>MULTIPLEX<br>INTEGRATED<br>CONTROL<br>UNIT (MICU)<br>‹12−C›<br></b></nobr>");
write("</p>");
write("<p id=\"p3_14\" class=\"drag\" style=\"position:absolute;left:-138px;top:498px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>ABS MODULATOR−<br>CONTROL UNIT<br>‹20−D›<br></b></nobr>");
write("</p>");
write("<p id=\"p3_15\" class=\"drag\" style=\"position:absolute;left:-147px;top:423px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_16\" class=\"drag\" style=\"position:absolute;left:177px;top:421px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_17\" class=\"drag\" style=\"position:absolute;left:115px;top:610px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LT GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_18\" class=\"drag\" style=\"position:absolute;left:230px;top:610px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRY/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_19\" class=\"drag\" style=\"position:absolute;left:290px;top:610px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_20\" class=\"drag\" style=\"position:absolute;left:340px;top:610px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_21\" class=\"drag\" style=\"position:absolute;left:337px;top:876px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p3_22\" class=\"drag\" style=\"position:absolute;left:271px;top:539px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>MAIN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_23\" class=\"drag\" style=\"position:absolute;left:202px;top:539px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>RESUME<br></b></nobr>");
write("</p>");
write("<p id=\"p3_24\" class=\"drag\" style=\"position:absolute;left:148px;top:539px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>CANCEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_25\" class=\"drag\" style=\"position:absolute;left:109px;top:539px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>SET<br></b></nobr>");
write("</p>");
write("<p id=\"p3_26\" class=\"drag\" style=\"position:absolute;left:97px;top:475px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>CRUISE CONTROL<br>COMBINATION SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p3_27\" class=\"drag\" style=\"position:absolute;left:176px;top:351px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>HORN <br>RELAY <br>‹6−D›<br></b></nobr>");
write("</p>");
write("<p id=\"p3_28\" class=\"drag\" style=\"position:absolute;left:232px;top:686px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GRY/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_29\" class=\"drag\" style=\"position:absolute;left:290px;top:686px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_30\" class=\"drag\" style=\"position:absolute;left:340px;top:686px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_31\" class=\"drag\" style=\"position:absolute;left:153px;top:637px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>CABLE<br>REEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_32\" class=\"drag\" style=\"position:absolute;left:364px;top:637px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>CABLE<br>REEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_33\" class=\"drag\" style=\"position:absolute;left:187px;top:383px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>36<br></b></nobr>");
write("</p>");
write("<p id=\"p3_34\" class=\"drag\" style=\"position:absolute;left:115px;top:685px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>LT GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_35\" class=\"drag\" style=\"position:absolute;left:298px;top:734px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p3_36\" class=\"drag\" style=\"position:absolute;left:243px;top:735px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p3_37\" class=\"drag\" style=\"position:absolute;left:131px;top:734px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p3_38\" class=\"drag\" style=\"position:absolute;left:160px;top:765px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GAUGE CONTROL<br>MODULE <br>‹3−C›<br></b></nobr>");
write("</p>");
write("<p id=\"p3_39\" class=\"drag\" style=\"position:absolute;left:289px;top:757px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>GAUGE<br>CONTROL<br>MODULE<br>‹4−C›<br></b></nobr>");
write("</p>");
write("<p id=\"p3_40\" class=\"drag\" style=\"position:absolute;left:429px;top:189px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>*1 : UNDER−HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_41\" class=\"drag\" style=\"position:absolute;left:429px;top:198px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>*2 : UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_42\" class=\"drag\" style=\"position:absolute;left:-147px;top:470px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_43\" class=\"drag\" style=\"position:absolute;left:-147px;top:498px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_44\" class=\"drag\" style=\"position:absolute;left:-147px;top:527px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_45\" class=\"drag\" style=\"position:absolute;left:-43px;top:528px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>SRS UNIT <br>‹21−D›<br></b></nobr>");
write("</p>");
write("<p id=\"p3_46\" class=\"drag\" style=\"position:absolute;left:-51px;top:499px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_47\" class=\"drag\" style=\"position:absolute;left:-51px;top:528px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_48\" class=\"drag\" style=\"position:absolute;left:-52px;top:462px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_49\" class=\"drag\" style=\"position:absolute;left:466px;top:210px;font-weight:normal;font-size:5.2pt;\">");
write("<nobr><b>Shielding<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}