with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:989px; height:1119px;\" coordsize=\"989,1119\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:989px;height:1119px;\">");
write("<img id=\"img1\" src=\"../img/SEA5EB4J54200000000DEAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:989px;height:1119px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:0px;top:1086px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b></b>LHD type is shown, RHD type is similar.<br></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:2px;top:378px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>ABS MODULATOR-CONTROL UNIT or<br>VSA MODULATOR-CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:789px;top:207px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>MULTI-FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:716px;top:378px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>FAN CONTROL RELAY<br></b>Wire colors: WHT/RED, BLK,<br>BLK/YEL, BLU/BLK and BRN/WHT<br></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:580px;top:441px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>RADIATOR FAN RELAY<br></b>Wire colors: RED, BLU/BLK,<br>BLK/YEL and BRN/WHT<br></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:706px;top:125px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>FUEL HEATER RELAY<br></b>Wire colors: GRN, WHT/BLK,<br>RED/BLK *<sup>1</sup> (WHT/RED*<sup>2</sup>) <br>and RED<br></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:423px;top:46px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>REAR WINDOW DEFOGGER RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:0px;top:305px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>A/C CONDENSER <br>FAN RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:0px;top:85px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>ELD UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:23px;top:34px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>BLOWER MOTOR RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:520px;top:78px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>RELAY CONTORL MODULE<br>(built into the under-hood fuse/relay box)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:136px;top:336px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>UNDER-HOOD<br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:256px;top:16px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>A/C COMPRESSOR CLUTCH RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:811px;top:849px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>UNDER-HOOD<br>SUBFUSE BOX<br>('05 KE model)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:16px;top:995px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>*1: '04 model<br>*2: '05 model<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}