with(document) {
write("<v:group id=\"group2\" class=\"drag\" style=\"position:relative; width:475px; height:481px;\" coordsize=\"475,481\">");
write("<v:rect id=\"rect2\"class=\"drag\"  style=\"width:475px;height:481px;\">");
write("<img id=\"img2\" src=\"../img/SEA6EJ3A18316617502KBAD06.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:481px;border-color:#ffffff\">");
write("<p id=\"p2_1\" class=\"drag\" style=\"position:absolute;left:324px;top:16px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Larger crank bore<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" class=\"drag\" style=\"position:absolute;left:192px;top:42px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>1 or <br>A or I<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" class=\"drag\" style=\"position:absolute;left:263px;top:42px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>2 or <br>B or II<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" class=\"drag\" style=\"position:absolute;left:333px;top:42px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>3 or <br>C or III<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" class=\"drag\" style=\"position:absolute;left:404px;top:42px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>4 or <br>D or IIII<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" class=\"drag\" style=\"position:absolute;left:269px;top:83px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Smaller bearing (Thicker)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" class=\"drag\" style=\"position:absolute;left:402px;top:388px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Black<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" class=\"drag\" style=\"position:absolute;left:189px;top:131px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Red<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" class=\"drag\" style=\"position:absolute;left:189px;top:234px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Pink<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" class=\"drag\" style=\"position:absolute;left:189px;top:285px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Yellow<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" class=\"drag\" style=\"position:absolute;left:189px;top:327px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Yellow/<br>Green<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" class=\"drag\" style=\"position:absolute;left:189px;top:388px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Green<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" class=\"drag\" style=\"position:absolute;left:330px;top:183px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Yellow<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" class=\"drag\" style=\"position:absolute;left:330px;top:224px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Yellow/<br>Green<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" class=\"drag\" style=\"position:absolute;left:330px;top:285px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Green<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" class=\"drag\" style=\"position:absolute;left:401px;top:131px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Yellow<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" class=\"drag\" style=\"position:absolute;left:401px;top:284px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Brown<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" class=\"drag\" style=\"position:absolute;left:126px;top:25px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Crank <br>bore <br>code<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" class=\"drag\" style=\"position:absolute;left:32px;top:55px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Main <br>journal <br>code<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" class=\"drag\" style=\"position:absolute;left:77px;top:131px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" class=\"drag\" style=\"position:absolute;left:77px;top:183px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_22\" class=\"drag\" style=\"position:absolute;left:77px;top:234px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_23\" class=\"drag\" style=\"position:absolute;left:77px;top:285px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_24\" class=\"drag\" style=\"position:absolute;left:77px;top:337px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_25\" class=\"drag\" style=\"position:absolute;left:77px;top:388px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p2_26\" class=\"drag\" style=\"position:absolute;left:16px;top:423px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Smaller<br>main<br>journal<br></b></nobr>");
write("</p>");
write("<p id=\"p2_27\" class=\"drag\" style=\"position:absolute;left:119px;top:423px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Smaller<br>bearing<br>(Thicker)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_28\" class=\"drag\" style=\"position:absolute;left:331px;top:131px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Pink<br></b></nobr>");
write("</p>");
write("<p id=\"p2_29\" class=\"drag\" style=\"position:absolute;left:189px;top:173px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Red/<br>Pink<br></b></nobr>");
write("</p>");
write("<p id=\"p2_30\" class=\"drag\" style=\"position:absolute;left:330px;top:335px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Brown<br></b></nobr>");
write("</p>");
write("<p id=\"p2_31\" class=\"drag\" style=\"position:absolute;left:331px;top:379px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Brown/<br>Black<br></b></nobr>");
write("</p>");
write("<p id=\"p2_32\" class=\"drag\" style=\"position:absolute;left:259px;top:124px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Red/<br>Pink<br></b></nobr>");
write("</p>");
write("<p id=\"p2_33\" class=\"drag\" style=\"position:absolute;left:260px;top:181px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Pink<br></b></nobr>");
write("</p>");
write("<p id=\"p2_34\" class=\"drag\" style=\"position:absolute;left:260px;top:233px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Yellow<br></b></nobr>");
write("</p>");
write("<p id=\"p2_35\" class=\"drag\" style=\"position:absolute;left:259px;top:277px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Yellow/<br>Green<br></b></nobr>");
write("</p>");
write("<p id=\"p2_36\" class=\"drag\" style=\"position:absolute;left:262px;top:335px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Green<br></b></nobr>");
write("</p>");
write("<p id=\"p2_37\" class=\"drag\" style=\"position:absolute;left:260px;top:388px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Brown<br></b></nobr>");
write("</p>");
write("<p id=\"p2_38\" class=\"drag\" style=\"position:absolute;left:399px;top:177px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Yellow/<br>Green<br></b></nobr>");
write("</p>");
write("<p id=\"p2_39\" class=\"drag\" style=\"position:absolute;left:402px;top:234px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Green<br></b></nobr>");
write("</p>");
write("<p id=\"p2_40\" class=\"drag\" style=\"position:absolute;left:401px;top:330px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Brown/<br>Black<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}