with(document) {
write("<v:group id=\"group7\" class=\"drag\" style=\"position:relative; width:950px; height:879px;\" coordsize=\"950,879\">");
write("<v:rect id=\"rect7\"class=\"drag\"  style=\"width:950px;height:879px;\">");
write("<img id=\"img7\" src=\"../img/SEA6EJ4A20300000000DBAD07.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:879px;border-color:#ffffff\">");
write("<p id=\"p7_1\" class=\"drag\" style=\"position:absolute;left:115px;top:498px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>10P CONNECTOR<br>(7)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_2\" class=\"drag\" style=\"position:absolute;left:444px;top:501px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>21P CONNECTOR<br>(8)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_3\" class=\"drag\" style=\"position:absolute;left:747px;top:500px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>6P CONNECTOR<br>(9)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_4\" class=\"drag\" style=\"position:absolute;left:100px;top:644px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>8P CONNECTOR<br>(10)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_5\" class=\"drag\" style=\"position:absolute;left:416px;top:644px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>21P CONNECTOR<br>(11)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_6\" class=\"drag\" style=\"position:absolute;left:726px;top:644px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>17P CONNECTOR<br>(12)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_7\" class=\"drag\" style=\"position:absolute;left:383px;top:330px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ECM CONNECTOR No. 1 (96P) (6)**<br></b></nobr>");
write("</p>");
write("<p id=\"p7_8\" class=\"drag\" style=\"position:absolute;left:392px;top:174px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ECM CONNECTOR No. 2 (58P) (5)**<br></b></nobr>");
write("</p>");
write("<p id=\"p7_9\" class=\"drag\" style=\"position:absolute;left:78px;top:17px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>28P JUNCTION<br>CONNECTOR (1)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_10\" class=\"drag\" style=\"position:absolute;left:326px;top:17px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>28P JUNCTION<br>CONNECTOR (2)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_11\" class=\"drag\" style=\"position:absolute;left:760px;top:17px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PGM-FI MAIN <br>RELAY 2 (3)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_12\" class=\"drag\" style=\"position:absolute;left:601px;top:18px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PGM-FI MAIN <br>RELAY 1 (4)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_13\" class=\"drag\" style=\"position:absolute;left:1px;top:797px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>NOTE:<br>· Connector with male terminals (double outline): view from terminal side<br>· Connector with female terminals (single outline): view from wire side<br>**: Connector with female terminals (single outline): view from terminal side<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}