with(document) {
write("<v:group id=\"group2\" class=\"drag\" style=\"position:relative; width:950px; height:975px;\" coordsize=\"950,975\">");
write("<v:rect id=\"rect2\"class=\"drag\"  style=\"width:950px;height:975px;\">");
write("<img id=\"img2\" src=\"../img/SEA6EJ3D52100000000EAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:975px;border-color:#ffffff\">");
write("<p id=\"p2_1\" class=\"drag\" style=\"position:absolute;left:69px;top:22px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>UNDER-HOOD FUSE/RELAY BOX<br>CONNECTOR C (2P)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" class=\"drag\" style=\"position:absolute;left:68px;top:252px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>UNDER-DASH FUSE/RELAY BOX<br>CONNECTOR C (12P)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" class=\"drag\" style=\"position:absolute;left:445px;top:253px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>GAUGE CONTROL MODULE CONNECTOR (36P)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" class=\"drag\" style=\"position:absolute;left:379px;top:126px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BRAKE PEDAL POSITION SWITCH<br>4P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" class=\"drag\" style=\"position:absolute;left:285px;top:764px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>Wire side of female terminals<br></nobr>");
write("</p>");
write("<p id=\"p2_6\" class=\"drag\" style=\"position:absolute;left:97px;top:821px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DATA LINK CONNECTOR (16P)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" class=\"drag\" style=\"position:absolute;left:82px;top:932px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>Terminal side of female terminals<br></nobr>");
write("</p>");
write("<p id=\"p2_8\" class=\"drag\" style=\"position:absolute;left:463px;top:932px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>Terminal side of male terminals<br></nobr>");
write("</p>");
write("<p id=\"p2_9\" class=\"drag\" style=\"position:absolute;left:528px;top:830px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT/REAR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" class=\"drag\" style=\"position:absolute;left:460px;top:810px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>WHEEL SENSOR 2P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" class=\"drag\" style=\"position:absolute;left:69px;top:615px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VSA MODULATOR-CONTROL UNIT 47P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" class=\"drag\" style=\"position:absolute;left:69px;top:474px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PCM CONNECTOR E (31P)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" class=\"drag\" style=\"position:absolute;left:69px;top:369px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VSA OFF SWITCH 5P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" class=\"drag\" style=\"position:absolute;left:347px;top:369px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>STEERING ANGLE SENSOR<br>5P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" class=\"drag\" style=\"position:absolute;left:588px;top:369px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>YAW RATE/LATERAL<br>ACCELERATION SENSOR 5P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" class=\"drag\" style=\"position:absolute;left:377px;top:22px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>UNDER-HOOD FUSE/RELAY BOX<br>CONNECTOR G (2P)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" class=\"drag\" style=\"position:absolute;left:69px;top:126px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BRAKE FLUID LEVEL SWITCH<br>2P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" class=\"drag\" style=\"position:absolute;left:660px;top:22px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>UNDER-HOOD FUSE/RELAY BOX<br>CONNECTOR D (9P)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}