with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:475px; height:320px;\" coordsize=\"475,320\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:475px;height:320px;\">");
write("<img id=\"img1\" src=\"../img/SEA6EJ6J36200000000BBAD21.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:320px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:147px;top:64px;font-weight:normal;font-size:8.9pt;\">");
write("<nobr><b>Car Status<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:340px;top:64px;font-weight:normal;font-size:8.9pt;\">");
write("<nobr><b>Return<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:70px;top:122px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>VSP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:70px;top:162px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>BACK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:187px;top:122px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>[0]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:187px;top:162px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>[0]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:251px;top:122px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>ILL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:251px;top:162px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>DVD Lid<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:347px;top:122px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>[0]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:347px;top:162px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>[Open]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:70px;top:201px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>ILL CANCEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:187px;top:201px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>[0]<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}