with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:993px; height:959px;\" coordsize=\"993,959\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:993px;height:959px;\">");
write("<img id=\"img1\" src=\"../img/SEA6EL3J54200000000DEAD04.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:993px;height:959px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:560px;top:63px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>THROTTLE ACTUATOR CONTROL<br>MODULE RELAY<br></b>Wire colors: PNK, GRN,<br>BRN and YEL/BLK<br></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:560px;top:17px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>SEAT HEATER RELAY<br></b>Wire colors: RED/BLK, BRN,<br>BLK and WHT<br></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:805px;top:213px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>IMOES UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:386px;top:126px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>HANDSFREELINK UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:258px;top:77px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>ADAPTIVE CRUISE RELAY<br></b>Wire colors: YEL/BLU, RED,<br>BLK, YEL/BLU<br></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:38px;top:45px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>ADAPTIVE CRUISE<br>CONTROL UNIT<br>(KE model with adaptive<br>cruise control)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:831px;top:573px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>AUTOMATIC<br>LIGHTING<br>CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:629px;top:711px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>SECURITY HAZARD WARNING<br>LIGHT RELAY (Right)<br></b>Wire colors: WHT/BLK, BRN,<br>WHT and WHT/BLK<br></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:629px;top:775px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>SECURITY HAZARD WARNING<br>LIGHT RELAY (Left)<br></b>Wire colors: WHT/BLK, RED/BLU,<br>WHT and WHT/BLK<br></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:543px;top:851px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>ACCESSORY POWER SOCKET RELAY<br></b>Wire colors: GRN, RED/YEL,<br>BLK and YEL<br></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:448px;top:670px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>ECM/PCM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:299px;top:700px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>SRS UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:60px;top:575px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b>ADAPTIVE CRUISE<br>CONTROL UNIT<br>(KG model with adaptive<br>cruise control)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:16px;top:927px;font-weight:normal;font-size:9.0pt;\">");
write("<nobr><b></b>LHD type is shown, RHD type is similar.<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}