with(document) {
write("<v:group id=\"group4\" class=\"drag\" style=\"position:relative; width:950px; height:1119px;\" coordsize=\"950,1119\">");
write("<v:rect id=\"rect4\"class=\"drag\"  style=\"width:950px;height:1119px;\">");
write("<img id=\"img4\" src=\"../img/SEA6EL4A20300000000EAAD04.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1119px;border-color:#ffffff\">");
write("<p id=\"p4_1\" class=\"drag\" style=\"position:absolute;left:510px;top:39px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>5P JUNCTION<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p4_2\" class=\"drag\" style=\"position:absolute;left:709px;top:209px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_3\" class=\"drag\" style=\"position:absolute;left:810px;top:201px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_4\" class=\"drag\" style=\"position:absolute;left:810px;top:217px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_5\" class=\"drag\" style=\"position:absolute;left:620px;top:245px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>17P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p4_6\" class=\"drag\" style=\"position:absolute;left:668px;top:217px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p4_7\" class=\"drag\" style=\"position:absolute;left:709px;top:225px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p4_8\" class=\"drag\" style=\"position:absolute;left:709px;top:296px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_9\" class=\"drag\" style=\"position:absolute;left:810px;top:289px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_10\" class=\"drag\" style=\"position:absolute;left:810px;top:305px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_11\" class=\"drag\" style=\"position:absolute;left:620px;top:333px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>17P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p4_12\" class=\"drag\" style=\"position:absolute;left:668px;top:304px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p4_13\" class=\"drag\" style=\"position:absolute;left:709px;top:312px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_14\" class=\"drag\" style=\"position:absolute;left:827px;top:419px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>EGR CONTROL<br>SOLENOID VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p4_15\" class=\"drag\" style=\"position:absolute;left:709px;top:383px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_16\" class=\"drag\" style=\"position:absolute;left:810px;top:376px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_17\" class=\"drag\" style=\"position:absolute;left:809px;top:391px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_18\" class=\"drag\" style=\"position:absolute;left:619px;top:419px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>17P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p4_19\" class=\"drag\" style=\"position:absolute;left:708px;top:399px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p4_20\" class=\"drag\" style=\"position:absolute;left:401px;top:207px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p4_21\" class=\"drag\" style=\"position:absolute;left:434px;top:119px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_22\" class=\"drag\" style=\"position:absolute;left:529px;top:109px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p4_23\" class=\"drag\" style=\"position:absolute;left:547px;top:109px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p4_24\" class=\"drag\" style=\"position:absolute;left:564px;top:109px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_25\" class=\"drag\" style=\"position:absolute;left:582px;top:109px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_26\" class=\"drag\" style=\"position:absolute;left:212px;top:217px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>81<br></b></nobr>");
write("</p>");
write("<p id=\"p4_27\" class=\"drag\" style=\"position:absolute;left:203px;top:187px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 1 (96P)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_28\" class=\"drag\" style=\"position:absolute;left:212px;top:234px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IMRCS<br></b></nobr>");
write("</p>");
write("<p id=\"p4_29\" class=\"drag\" style=\"position:absolute;left:212px;top:304px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>78<br></b></nobr>");
write("</p>");
write("<p id=\"p4_30\" class=\"drag\" style=\"position:absolute;left:212px;top:321px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>T/CSOL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_31\" class=\"drag\" style=\"position:absolute;left:212px;top:391px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>48<br></b></nobr>");
write("</p>");
write("<p id=\"p4_32\" class=\"drag\" style=\"position:absolute;left:212px;top:407px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>EGR<br></b></nobr>");
write("</p>");
write("<p id=\"p4_33\" class=\"drag\" style=\"position:absolute;left:290px;top:225px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p4_34\" class=\"drag\" style=\"position:absolute;left:290px;top:313px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_35\" class=\"drag\" style=\"position:absolute;left:289px;top:399px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_36\" class=\"drag\" style=\"position:absolute;left:798px;top:332px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>TURBOCHARGER <br>BOOST CONTROL<br>SOLENOID VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p4_37\" class=\"drag\" style=\"position:absolute;left:829px;top:245px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IMRC SOLENOID<br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p4_38\" class=\"drag\" style=\"position:absolute;left:668px;top:391px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p4_39\" class=\"drag\" style=\"position:absolute;left:599px;top:109px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p4_40\" class=\"drag\" style=\"position:absolute;left:212px;top:492px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>51<br></b></nobr>");
write("</p>");
write("<p id=\"p4_41\" class=\"drag\" style=\"position:absolute;left:212px;top:509px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RVS<br></b></nobr>");
write("</p>");
write("<p id=\"p4_42\" class=\"drag\" style=\"position:absolute;left:288px;top:501px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_43\" class=\"drag\" style=\"position:absolute;left:707px;top:484px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_44\" class=\"drag\" style=\"position:absolute;left:706px;top:500px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_45\" class=\"drag\" style=\"position:absolute;left:470px;top:480px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>17P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p4_46\" class=\"drag\" style=\"position:absolute;left:519px;top:508px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p4_47\" class=\"drag\" style=\"position:absolute;left:805px;top:477px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_48\" class=\"drag\" style=\"position:absolute;left:805px;top:493px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_49\" class=\"drag\" style=\"position:absolute;left:829px;top:519px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>REVERSE LOCK<br>SOLENOID VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p4_50\" class=\"drag\" style=\"position:absolute;left:521px;top:677px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p4_51\" class=\"drag\" style=\"position:absolute;left:709px;top:614px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p4_52\" class=\"drag\" style=\"position:absolute;left:810px;top:606px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_53\" class=\"drag\" style=\"position:absolute;left:709px;top:650px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p4_54\" class=\"drag\" style=\"position:absolute;left:810px;top:643px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_55\" class=\"drag\" style=\"position:absolute;left:709px;top:686px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p4_56\" class=\"drag\" style=\"position:absolute;left:810px;top:679px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p4_57\" class=\"drag\" style=\"position:absolute;left:794px;top:717px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IMRC POSITION SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p4_58\" class=\"drag\" style=\"position:absolute;left:708px;top:742px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p4_59\" class=\"drag\" style=\"position:absolute;left:810px;top:735px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_60\" class=\"drag\" style=\"position:absolute;left:810px;top:771px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_61\" class=\"drag\" style=\"position:absolute;left:810px;top:807px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p4_62\" class=\"drag\" style=\"position:absolute;left:708px;top:778px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p4_63\" class=\"drag\" style=\"position:absolute;left:708px;top:814px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_64\" class=\"drag\" style=\"position:absolute;left:212px;top:606px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p4_65\" class=\"drag\" style=\"position:absolute;left:212px;top:623px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IMRCVCC<br></b></nobr>");
write("</p>");
write("<p id=\"p4_66\" class=\"drag\" style=\"position:absolute;left:212px;top:642px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p4_67\" class=\"drag\" style=\"position:absolute;left:212px;top:659px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IMRCP<br></b></nobr>");
write("</p>");
write("<p id=\"p4_68\" class=\"drag\" style=\"position:absolute;left:212px;top:678px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>57<br></b></nobr>");
write("</p>");
write("<p id=\"p4_69\" class=\"drag\" style=\"position:absolute;left:212px;top:695px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IMRCSG<br></b></nobr>");
write("</p>");
write("<p id=\"p4_70\" class=\"drag\" style=\"position:absolute;left:212px;top:734px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>30<br></b></nobr>");
write("</p>");
write("<p id=\"p4_71\" class=\"drag\" style=\"position:absolute;left:212px;top:751px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>VSSVCC<br></b></nobr>");
write("</p>");
write("<p id=\"p4_72\" class=\"drag\" style=\"position:absolute;left:212px;top:770px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>84<br></b></nobr>");
write("</p>");
write("<p id=\"p4_73\" class=\"drag\" style=\"position:absolute;left:212px;top:787px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>VSS<br></b></nobr>");
write("</p>");
write("<p id=\"p4_74\" class=\"drag\" style=\"position:absolute;left:212px;top:806px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>54<br></b></nobr>");
write("</p>");
write("<p id=\"p4_75\" class=\"drag\" style=\"position:absolute;left:212px;top:823px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>VSSSG<br></b></nobr>");
write("</p>");
write("<p id=\"p4_76\" class=\"drag\" style=\"position:absolute;left:468px;top:585px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>21P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p4_77\" class=\"drag\" style=\"position:absolute;left:825px;top:992px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>FUEL RAIL<br>PRESSURE<br>CONTROL VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p4_78\" class=\"drag\" style=\"position:absolute;left:709px;top:926px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_79\" class=\"drag\" style=\"position:absolute;left:810px;top:918px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_80\" class=\"drag\" style=\"position:absolute;left:212px;top:918px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>79<br></b></nobr>");
write("</p>");
write("<p id=\"p4_81\" class=\"drag\" style=\"position:absolute;left:212px;top:935px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>MPROP<br></b></nobr>");
write("</p>");
write("<p id=\"p4_82\" class=\"drag\" style=\"position:absolute;left:468px;top:897px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>17P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p4_83\" class=\"drag\" style=\"position:absolute;left:521px;top:917px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p4_84\" class=\"drag\" style=\"position:absolute;left:709px;top:962px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_85\" class=\"drag\" style=\"position:absolute;left:810px;top:955px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_86\" class=\"drag\" style=\"position:absolute;left:629px;top:989px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>6P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p4_87\" class=\"drag\" style=\"position:absolute;left:678px;top:954px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p4_88\" class=\"drag\" style=\"position:absolute;left:538px;top:1003px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p4_89\" class=\"drag\" style=\"position:absolute;left:590px;top:962px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_90\" class=\"drag\" style=\"position:absolute;left:290px;top:927px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_91\" class=\"drag\" style=\"position:absolute;left:287px;top:651px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p4_92\" class=\"drag\" style=\"position:absolute;left:287px;top:743px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p4_93\" class=\"drag\" style=\"position:absolute;left:520px;top:642px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p4_94\" class=\"drag\" style=\"position:absolute;left:520px;top:606px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p4_95\" class=\"drag\" style=\"position:absolute;left:520px;top:734px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p4_96\" class=\"drag\" style=\"position:absolute;left:520px;top:770px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p4_97\" class=\"drag\" style=\"position:absolute;left:520px;top:806px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p4_98\" class=\"drag\" style=\"position:absolute;left:288px;top:615px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p4_99\" class=\"drag\" style=\"position:absolute;left:288px;top:687px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p4_100\" class=\"drag\" style=\"position:absolute;left:287px;top:779px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p4_101\" class=\"drag\" style=\"position:absolute;left:287px;top:815px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_102\" class=\"drag\" style=\"position:absolute;left:815px;top:835px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>OUTPUT SHAFT<br>(COUNTERSHAFT)<br>SPEED SENSOR<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}