with(document) {
write("<v:group id=\"group2\" class=\"drag\" style=\"position:relative; width:950px; height:335px;\" coordsize=\"950,335\">");
write("<v:rect id=\"rect2\"class=\"drag\"  style=\"width:950px;height:335px;\">");
write("<img id=\"img2\" src=\"../img/SEA6EJPE10410600000CAAD06.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:335px;border-color:#ffffff\">");
write("<p id=\"p2_1\" class=\"drag\" style=\"position:absolute;left:109px;top:149px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>50<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" class=\"drag\" style=\"position:absolute;left:116px;top:271px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>0<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" class=\"drag\" style=\"position:absolute;left:147px;top:14px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DECENDING MODE: Downshift Schedule<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" class=\"drag\" style=\"position:absolute;left:608px;top:99px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>: FLAT ROAD MODE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" class=\"drag\" style=\"position:absolute;left:607px;top:129px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>: GRADUAL DESCENDING MODE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" class=\"drag\" style=\"position:absolute;left:607px;top:158px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>: MEDIUM DESCENDING MODE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" class=\"drag\" style=\"position:absolute;left:607px;top:187px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>: STEEP DESCENDING MODE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" class=\"drag\" style=\"position:absolute;left:296px;top:63px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>3RD<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" class=\"drag\" style=\"position:absolute;left:385px;top:63px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>4TH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" class=\"drag\" style=\"position:absolute;left:441px;top:289px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Vehicle speed<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" class=\"drag\" style=\"position:absolute;left:201px;top:63px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>2ND<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" class=\"drag\" style=\"position:absolute;left:147px;top:63px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>1ST<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" class=\"drag\" style=\"position:absolute;left:468px;top:63px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>5TH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" class=\"drag\" style=\"position:absolute;left:238px;top:63px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>2ND<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" class=\"drag\" style=\"position:absolute;left:329px;top:63px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>3RD<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" class=\"drag\" style=\"position:absolute;left:413px;top:63px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>4TH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" class=\"drag\" style=\"position:absolute;left:90px;top:27px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>100 %<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" class=\"drag\" style=\"position:absolute;left:295px;top:290px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>100 km/h <br>(62 mph)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("<v:line id=\"bl2_1\" class=\"drag\" from=\"68,226\" to=\"67,99\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_1\" class=\"drag\" on=\"true\" string=\"Throttle opening\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:8.6pt;\"/>");
write("</v:line>");
write("</v:group>");
}