with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\" coordsize=\"950,1103\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:1103px;\">");
write("<img id=\"img1\" src=\"../img/SEA6EJ3A32200000000DAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:302px;top:969px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OIL PRESSURE SWITCH<br><a href=\"javascript:parent.Cts('000000000003686','i000')\"></b>Circuit Diagram,</a><br><a href=\"javascript:parent.Cts('000000000000613','i000')\">Switch Test,</a><br> in the Shop Manual, P/N 62SEA02A<br><a href=\"javascript:parent.Cts('000000000000608','i000')\">Oil Pressure test,</a><br> in the Shop Manual, P/N 62SEA02A<br><a href=\"javascript:parent.Cts('000000000000614','i000')\">Replacement,</a><br> in the Shop Manual, P/N 62SEA02A<br></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:786px;top:869px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OIL FILTER<br><a href=\"javascript:parent.Cts('000000000000612','i000')\"></b>Replacement,<br></a><br> in the Shop Manual,<br> P/N 62SEA02A<br></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:633px;top:307px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OIL PUMP<br><a href=\"javascript:parent.Cts('000000000003635','i000')\"></b>Overhaul,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:665px;top:24px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DRAIN BOLT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:635px;top:124px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>WASHER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:558px;top:197px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OIL PAN<br><a href=\"javascript:parent.Cts('000000000000565','i000')\"></b>Removal,</a><br> in the Shop Manual, P/N 62SEA02A<br><a href=\"javascript:parent.Cts('000000000000566','i000')\">Installation,</a><br> in the Shop Manual, P/N 62SEA02A<br></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:640px;top:375px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BAFFLE PLATE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:786px;top:589px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OIL FILTER FEED <br>PIPE (K20Z2 engine)<br><a href=\"javascript:parent.Cts('000000000000470','i000')\"></b>Replacement,<br></a><br> in the Shop Manual,<br> P/N 62SEA02A<br></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:686px;top:506px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OIL CONTROL<br>ORIFICE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:165px;top:1008px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OIL PUMP<br>CHAIN GUIDE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:96px;top:942px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CRANKSHAFT<br>SPROCKET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:90px;top:310px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OIL PUMP CHAIN<br>TENSIONER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:686px;top:470px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>O-RING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:621px;top:969px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OIL COOLER CENTER BOLT<br>(K24A3 engine)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:592px;top:1029px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OIL COOLER<br>(K24A3 engine)<br><a href=\"javascript:parent.Cts('000000000000482','i000')\"></b>Replacement,</a><br> in the Shop Manual, P/N 62SEA02A<br></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:58px;top:824px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OIL JETS<br>(K24A3 engine)<br><a href=\"javascript:parent.Cts('000000000000483','i000')\"></b>Inspection,<br></a><br> in the Shop Manual,<br> P/N 62SEA02A<br></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:7px;top:682px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OIL JET BOLTS<br>(K24A3 engine)<br><a href=\"javascript:parent.Cts('000000000000483','i000')\"></b>Inspection,<br></a><br> in the Shop Manual,<br> P/N 62SEA02A<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}