with(document) {
write("<v:group id=\"group9\" class=\"drag\" style=\"position:relative; width:950px; height:1296px;\" coordsize=\"950,1296\">");
write("<v:rect id=\"rect9\"class=\"drag\"  style=\"width:950px;height:1296px;\">");
write("<img id=\"img9\" src=\"../img/SEA6EL3A20300000000EAAD09.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1296px;border-color:#ffffff\">");
write("<p id=\"p9_1\" class=\"drag\" style=\"position:absolute;left:194px;top:636px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p9_2\" class=\"drag\" style=\"position:absolute;left:718px;top:1027px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p9_3\" class=\"drag\" style=\"position:absolute;left:718px;top:1006px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p9_4\" class=\"drag\" style=\"position:absolute;left:718px;top:987px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p9_5\" class=\"drag\" style=\"position:absolute;left:196px;top:961px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>D2<br></b></nobr>");
write("</p>");
write("<p id=\"p9_6\" class=\"drag\" style=\"position:absolute;left:801px;top:920px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>THROTTLE ACTUATOR<br>CONTROL MODULE<br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p9_7\" class=\"drag\" style=\"position:absolute;left:657px;top:947px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>Z<br></b></nobr>");
write("</p>");
write("<p id=\"p9_8\" class=\"drag\" style=\"position:absolute;left:612px;top:947px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>Y<br></b></nobr>");
write("</p>");
write("<p id=\"p9_9\" class=\"drag\" style=\"position:absolute;left:820px;top:1067px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SHIFT LEVER<br></b></nobr>");
write("</p>");
write("<p id=\"p9_10\" class=\"drag\" style=\"position:absolute;left:718px;top:1045px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_11\" class=\"drag\" style=\"position:absolute;left:808px;top:979px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p9_12\" class=\"drag\" style=\"position:absolute;left:808px;top:999px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p9_13\" class=\"drag\" style=\"position:absolute;left:808px;top:1020px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p9_14\" class=\"drag\" style=\"position:absolute;left:808px;top:1038px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p9_15\" class=\"drag\" style=\"position:absolute;left:48px;top:953px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p9_16\" class=\"drag\" style=\"position:absolute;left:718px;top:163px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p9_17\" class=\"drag\" style=\"position:absolute;left:797px;top:153px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p9_18\" class=\"drag\" style=\"position:absolute;left:718px;top:142px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p9_19\" class=\"drag\" style=\"position:absolute;left:798px;top:132px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p9_20\" class=\"drag\" style=\"position:absolute;left:720px;top:184px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p9_21\" class=\"drag\" style=\"position:absolute;left:799px;top:174px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p9_22\" class=\"drag\" style=\"position:absolute;left:723px;top:205px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p9_23\" class=\"drag\" style=\"position:absolute;left:802px;top:195px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p9_24\" class=\"drag\" style=\"position:absolute;left:655px;top:44px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p9_25\" class=\"drag\" style=\"position:absolute;left:613px;top:44px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p9_26\" class=\"drag\" style=\"position:absolute;left:720px;top:113px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p9_27\" class=\"drag\" style=\"position:absolute;left:798px;top:109px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p9_28\" class=\"drag\" style=\"position:absolute;left:718px;top:84px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p9_29\" class=\"drag\" style=\"position:absolute;left:798px;top:76px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p9_30\" class=\"drag\" style=\"position:absolute;left:195px;top:107px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A26<br></b></nobr>");
write("</p>");
write("<p id=\"p9_31\" class=\"drag\" style=\"position:absolute;left:195px;top:124px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>APSA<br></b></nobr>");
write("</p>");
write("<p id=\"p9_32\" class=\"drag\" style=\"position:absolute;left:195px;top:174px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A25<br></b></nobr>");
write("</p>");
write("<p id=\"p9_33\" class=\"drag\" style=\"position:absolute;left:195px;top:191px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>APSB<br></b></nobr>");
write("</p>");
write("<p id=\"p9_34\" class=\"drag\" style=\"position:absolute;left:829px;top:239px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>APP SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p9_35\" class=\"drag\" style=\"position:absolute;left:799px;top:677px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p9_36\" class=\"drag\" style=\"position:absolute;left:800px;top:745px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p9_37\" class=\"drag\" style=\"position:absolute;left:800px;top:768px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p9_38\" class=\"drag\" style=\"position:absolute;left:801px;top:655px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p9_39\" class=\"drag\" style=\"position:absolute;left:721px;top:665px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p9_40\" class=\"drag\" style=\"position:absolute;left:719px;top:726px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p9_41\" class=\"drag\" style=\"position:absolute;left:719px;top:755px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p9_42\" class=\"drag\" style=\"position:absolute;left:720px;top:776px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p9_43\" class=\"drag\" style=\"position:absolute;left:808px;top:608px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>THROTTLE ACTUATOR<br>CONTROL MODULE<br></b></nobr>");
write("</p>");
write("<p id=\"p9_44\" class=\"drag\" style=\"position:absolute;left:237px;top:391px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>13P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p9_45\" class=\"drag\" style=\"position:absolute;left:221px;top:456px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p9_46\" class=\"drag\" style=\"position:absolute;left:216px;top:404px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p9_47\" class=\"drag\" style=\"position:absolute;left:194px;top:336px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B19<br></b></nobr>");
write("</p>");
write("<p id=\"p9_48\" class=\"drag\" style=\"position:absolute;left:194px;top:352px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SEFD<br></b></nobr>");
write("</p>");
write("<p id=\"p9_49\" class=\"drag\" style=\"position:absolute;left:194px;top:365px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B20<br></b></nobr>");
write("</p>");
write("<p id=\"p9_50\" class=\"drag\" style=\"position:absolute;left:194px;top:382px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SEDF<br></b></nobr>");
write("</p>");
write("<p id=\"p9_51\" class=\"drag\" style=\"position:absolute;left:667px;top:542px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p9_52\" class=\"drag\" style=\"position:absolute;left:665px;top:561px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p9_53\" class=\"drag\" style=\"position:absolute;left:667px;top:519px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p9_54\" class=\"drag\" style=\"position:absolute;left:602px;top:572px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_55\" class=\"drag\" style=\"position:absolute;left:490px;top:529px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p9_56\" class=\"drag\" style=\"position:absolute;left:490px;top:552px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p9_57\" class=\"drag\" style=\"position:absolute;left:488px;top:572px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_58\" class=\"drag\" style=\"position:absolute;left:554px;top:542px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p9_59\" class=\"drag\" style=\"position:absolute;left:552px;top:561px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p9_60\" class=\"drag\" style=\"position:absolute;left:554px;top:519px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p9_61\" class=\"drag\" style=\"position:absolute;left:543px;top:277px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>13P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p9_62\" class=\"drag\" style=\"position:absolute;left:665px;top:460px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p9_63\" class=\"drag\" style=\"position:absolute;left:665px;top:439px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p9_64\" class=\"drag\" style=\"position:absolute;left:667px;top:419px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p9_65\" class=\"drag\" style=\"position:absolute;left:668px;top:398px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p9_66\" class=\"drag\" style=\"position:absolute;left:604px;top:468px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_67\" class=\"drag\" style=\"position:absolute;left:604px;top:447px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p9_68\" class=\"drag\" style=\"position:absolute;left:605px;top:406px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p9_69\" class=\"drag\" style=\"position:absolute;left:604px;top:427px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p9_70\" class=\"drag\" style=\"position:absolute;left:491px;top:468px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_71\" class=\"drag\" style=\"position:absolute;left:491px;top:447px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p9_72\" class=\"drag\" style=\"position:absolute;left:491px;top:406px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p9_73\" class=\"drag\" style=\"position:absolute;left:493px;top:428px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p9_74\" class=\"drag\" style=\"position:absolute;left:555px;top:459px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p9_75\" class=\"drag\" style=\"position:absolute;left:555px;top:438px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p9_76\" class=\"drag\" style=\"position:absolute;left:557px;top:418px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p9_77\" class=\"drag\" style=\"position:absolute;left:558px;top:397px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p9_78\" class=\"drag\" style=\"position:absolute;left:665px;top:308px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p9_79\" class=\"drag\" style=\"position:absolute;left:604px;top:316px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p9_80\" class=\"drag\" style=\"position:absolute;left:490px;top:316px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p9_81\" class=\"drag\" style=\"position:absolute;left:555px;top:307px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p9_82\" class=\"drag\" style=\"position:absolute;left:670px;top:365px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p9_83\" class=\"drag\" style=\"position:absolute;left:669px;top:335px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p9_84\" class=\"drag\" style=\"position:absolute;left:608px;top:343px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p9_85\" class=\"drag\" style=\"position:absolute;left:607px;top:373px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p9_86\" class=\"drag\" style=\"position:absolute;left:494px;top:343px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p9_87\" class=\"drag\" style=\"position:absolute;left:493px;top:373px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p9_88\" class=\"drag\" style=\"position:absolute;left:560px;top:364px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p9_89\" class=\"drag\" style=\"position:absolute;left:558px;top:334px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p9_90\" class=\"drag\" style=\"position:absolute;left:798px;top:701px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p9_91\" class=\"drag\" style=\"position:absolute;left:719px;top:687px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_92\" class=\"drag\" style=\"position:absolute;left:799px;top:717px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p9_93\" class=\"drag\" style=\"position:absolute;left:718px;top:708px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p9_94\" class=\"drag\" style=\"position:absolute;left:845px;top:647px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>TP SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p9_95\" class=\"drag\" style=\"position:absolute;left:850px;top:791px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>THROTTLE<br>ACTUATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p9_96\" class=\"drag\" style=\"position:absolute;left:828px;top:827px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>THROTTLE BODY<br></b></nobr>");
write("</p>");
write("<p id=\"p9_97\" class=\"drag\" style=\"position:absolute;left:572px;top:44px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p9_98\" class=\"drag\" style=\"position:absolute;left:695px;top:43px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p9_99\" class=\"drag\" style=\"position:absolute;left:718px;top:843px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p9_100\" class=\"drag\" style=\"position:absolute;left:718px;top:862px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_101\" class=\"drag\" style=\"position:absolute;left:718px;top:881px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p9_102\" class=\"drag\" style=\"position:absolute;left:716px;top:899px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p9_103\" class=\"drag\" style=\"position:absolute;left:194px;top:874px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>D15<br></b></nobr>");
write("</p>");
write("<p id=\"p9_104\" class=\"drag\" style=\"position:absolute;left:194px;top:892px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>DBWRLY<br></b></nobr>");
write("</p>");
write("<p id=\"p9_105\" class=\"drag\" style=\"position:absolute;left:196px;top:978px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SMODE<br></b></nobr>");
write("</p>");
write("<p id=\"p9_106\" class=\"drag\" style=\"position:absolute;left:196px;top:993px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>D3<br></b></nobr>");
write("</p>");
write("<p id=\"p9_107\" class=\"drag\" style=\"position:absolute;left:196px;top:1005px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SUP<br></b></nobr>");
write("</p>");
write("<p id=\"p9_108\" class=\"drag\" style=\"position:absolute;left:196px;top:1020px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>D9<br></b></nobr>");
write("</p>");
write("<p id=\"p9_109\" class=\"drag\" style=\"position:absolute;left:196px;top:1038px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SDN<br></b></nobr>");
write("</p>");
write("<p id=\"p9_110\" class=\"drag\" style=\"position:absolute;left:807px;top:834px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p9_111\" class=\"drag\" style=\"position:absolute;left:808px;top:854px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p9_112\" class=\"drag\" style=\"position:absolute;left:807px;top:875px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p9_113\" class=\"drag\" style=\"position:absolute;left:808px;top:893px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p9_114\" class=\"drag\" style=\"position:absolute;left:648px;top:1088px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p9_115\" class=\"drag\" style=\"position:absolute;left:605px;top:530px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p9_116\" class=\"drag\" style=\"position:absolute;left:605px;top:553px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p9_117\" class=\"drag\" style=\"position:absolute;left:279px;top:1236px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>*1: A/T<br>*3: RHD model<br></b></nobr>");
write("</p>");
write("<p id=\"p9_118\" class=\"drag\" style=\"position:absolute;left:506px;top:1036px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p9_119\" class=\"drag\" style=\"position:absolute;left:896px;top:117px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p9_120\" class=\"drag\" style=\"position:absolute;left:897px;top:182px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p9_121\" class=\"drag\" style=\"position:absolute;left:446px;top:982px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p9_122\" class=\"drag\" style=\"position:absolute;left:469px;top:982px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p9_123\" class=\"drag\" style=\"position:absolute;left:487px;top:982px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p9_124\" class=\"drag\" style=\"position:absolute;left:510px;top:982px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p9_125\" class=\"drag\" style=\"position:absolute;left:532px;top:982px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p9_126\" class=\"drag\" style=\"position:absolute;left:555px;top:982px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p9_127\" class=\"drag\" style=\"position:absolute;left:460px;top:912px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>28 JUNCTION<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}