with(document) {
write("<v:group id=\"group3\" class=\"drag\" style=\"position:relative; width:950px; height:1119px;\" coordsize=\"950,1119\">");
write("<v:rect id=\"rect3\"class=\"drag\"  style=\"width:950px;height:1119px;\">");
write("<img id=\"img3\" src=\"../img/SEA6EJ4A20300000000EAAD03.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1119px;border-color:#ffffff\">");
write("<p id=\"p3_1\" class=\"drag\" style=\"position:absolute;left:658px;top:923px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_2\" class=\"drag\" style=\"position:absolute;left:835px;top:215px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ALTERNATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_3\" class=\"drag\" style=\"position:absolute;left:805px;top:118px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_4\" class=\"drag\" style=\"position:absolute;left:734px;top:125px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_5\" class=\"drag\" style=\"position:absolute;left:805px;top:167px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_6\" class=\"drag\" style=\"position:absolute;left:734px;top:174px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_7\" class=\"drag\" style=\"position:absolute;left:805px;top:93px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_8\" class=\"drag\" style=\"position:absolute;left:734px;top:100px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_9\" class=\"drag\" style=\"position:absolute;left:215px;top:93px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 1 (96P)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_10\" class=\"drag\" style=\"position:absolute;left:212px;top:118px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>35<br></b></nobr>");
write("</p>");
write("<p id=\"p3_11\" class=\"drag\" style=\"position:absolute;left:212px;top:134px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ACGL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_12\" class=\"drag\" style=\"position:absolute;left:286px;top:125px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_13\" class=\"drag\" style=\"position:absolute;left:212px;top:167px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>80<br></b></nobr>");
write("</p>");
write("<p id=\"p3_14\" class=\"drag\" style=\"position:absolute;left:212px;top:184px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ACGC<br></b></nobr>");
write("</p>");
write("<p id=\"p3_15\" class=\"drag\" style=\"position:absolute;left:286px;top:175px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_16\" class=\"drag\" style=\"position:absolute;left:332px;top:75px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>21P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_17\" class=\"drag\" style=\"position:absolute;left:384px;top:117px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p3_18\" class=\"drag\" style=\"position:absolute;left:384px;top:167px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p3_19\" class=\"drag\" style=\"position:absolute;left:805px;top:242px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p3_20\" class=\"drag\" style=\"position:absolute;left:734px;top:249px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_21\" class=\"drag\" style=\"position:absolute;left:805px;top:285px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_22\" class=\"drag\" style=\"position:absolute;left:734px;top:292px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_23\" class=\"drag\" style=\"position:absolute;left:212px;top:285px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p3_24\" class=\"drag\" style=\"position:absolute;left:212px;top:302px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>MAFVCC<br></b></nobr>");
write("</p>");
write("<p id=\"p3_25\" class=\"drag\" style=\"position:absolute;left:384px;top:285px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p3_26\" class=\"drag\" style=\"position:absolute;left:805px;top:328px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_27\" class=\"drag\" style=\"position:absolute;left:734px;top:335px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_28\" class=\"drag\" style=\"position:absolute;left:212px;top:328px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>90<br></b></nobr>");
write("</p>");
write("<p id=\"p3_29\" class=\"drag\" style=\"position:absolute;left:212px;top:345px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>MAF<br></b></nobr>");
write("</p>");
write("<p id=\"p3_30\" class=\"drag\" style=\"position:absolute;left:384px;top:328px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p3_31\" class=\"drag\" style=\"position:absolute;left:805px;top:371px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_32\" class=\"drag\" style=\"position:absolute;left:734px;top:378px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_33\" class=\"drag\" style=\"position:absolute;left:212px;top:371px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>69<br></b></nobr>");
write("</p>");
write("<p id=\"p3_34\" class=\"drag\" style=\"position:absolute;left:212px;top:388px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>MAFSG<br></b></nobr>");
write("</p>");
write("<p id=\"p3_35\" class=\"drag\" style=\"position:absolute;left:384px;top:371px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p3_36\" class=\"drag\" style=\"position:absolute;left:805px;top:414px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p3_37\" class=\"drag\" style=\"position:absolute;left:734px;top:421px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_38\" class=\"drag\" style=\"position:absolute;left:212px;top:414px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>88<br></b></nobr>");
write("</p>");
write("<p id=\"p3_39\" class=\"drag\" style=\"position:absolute;left:384px;top:414px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p3_40\" class=\"drag\" style=\"position:absolute;left:805px;top:741px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_41\" class=\"drag\" style=\"position:absolute;left:212px;top:741px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>33<br></b></nobr>");
write("</p>");
write("<p id=\"p3_42\" class=\"drag\" style=\"position:absolute;left:212px;top:758px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>MAP/IAT2VCC<br></b></nobr>");
write("</p>");
write("<p id=\"p3_43\" class=\"drag\" style=\"position:absolute;left:295px;top:749px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_44\" class=\"drag\" style=\"position:absolute;left:384px;top:741px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p3_45\" class=\"drag\" style=\"position:absolute;left:805px;top:784px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_46\" class=\"drag\" style=\"position:absolute;left:212px;top:784px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>89<br></b></nobr>");
write("</p>");
write("<p id=\"p3_47\" class=\"drag\" style=\"position:absolute;left:212px;top:801px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>MAP<br></b></nobr>");
write("</p>");
write("<p id=\"p3_48\" class=\"drag\" style=\"position:absolute;left:295px;top:792px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_49\" class=\"drag\" style=\"position:absolute;left:384px;top:784px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_50\" class=\"drag\" style=\"position:absolute;left:805px;top:827px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p3_51\" class=\"drag\" style=\"position:absolute;left:212px;top:827px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p3_52\" class=\"drag\" style=\"position:absolute;left:212px;top:844px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>MAP/IAT2SG<br></b></nobr>");
write("</p>");
write("<p id=\"p3_53\" class=\"drag\" style=\"position:absolute;left:295px;top:835px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_54\" class=\"drag\" style=\"position:absolute;left:384px;top:827px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_55\" class=\"drag\" style=\"position:absolute;left:805px;top:870px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_56\" class=\"drag\" style=\"position:absolute;left:212px;top:870px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p3_57\" class=\"drag\" style=\"position:absolute;left:212px;top:887px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IAT2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_58\" class=\"drag\" style=\"position:absolute;left:295px;top:878px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_59\" class=\"drag\" style=\"position:absolute;left:384px;top:870px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_60\" class=\"drag\" style=\"position:absolute;left:828px;top:1017px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ECT SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_61\" class=\"drag\" style=\"position:absolute;left:805px;top:487px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p3_62\" class=\"drag\" style=\"position:absolute;left:734px;top:494px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_63\" class=\"drag\" style=\"position:absolute;left:212px;top:487px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p3_64\" class=\"drag\" style=\"position:absolute;left:212px;top:504px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>TPSVCC1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_65\" class=\"drag\" style=\"position:absolute;left:384px;top:487px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p3_66\" class=\"drag\" style=\"position:absolute;left:805px;top:523px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p3_67\" class=\"drag\" style=\"position:absolute;left:734px;top:530px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_68\" class=\"drag\" style=\"position:absolute;left:212px;top:523px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p3_69\" class=\"drag\" style=\"position:absolute;left:212px;top:540px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>TPSD<br></b></nobr>");
write("</p>");
write("<p id=\"p3_70\" class=\"drag\" style=\"position:absolute;left:384px;top:523px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p3_71\" class=\"drag\" style=\"position:absolute;left:805px;top:559px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p3_72\" class=\"drag\" style=\"position:absolute;left:734px;top:567px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_73\" class=\"drag\" style=\"position:absolute;left:212px;top:559px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p3_74\" class=\"drag\" style=\"position:absolute;left:212px;top:576px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>TPSSG1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_75\" class=\"drag\" style=\"position:absolute;left:384px;top:559px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p3_76\" class=\"drag\" style=\"position:absolute;left:805px;top:595px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_77\" class=\"drag\" style=\"position:absolute;left:734px;top:603px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_78\" class=\"drag\" style=\"position:absolute;left:212px;top:595px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p3_79\" class=\"drag\" style=\"position:absolute;left:384px;top:595px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_80\" class=\"drag\" style=\"position:absolute;left:805px;top:632px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_81\" class=\"drag\" style=\"position:absolute;left:734px;top:639px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_82\" class=\"drag\" style=\"position:absolute;left:212px;top:631px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p3_83\" class=\"drag\" style=\"position:absolute;left:212px;top:648px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>TPSE<br></b></nobr>");
write("</p>");
write("<p id=\"p3_84\" class=\"drag\" style=\"position:absolute;left:384px;top:631px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_85\" class=\"drag\" style=\"position:absolute;left:805px;top:668px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_86\" class=\"drag\" style=\"position:absolute;left:734px;top:675px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_87\" class=\"drag\" style=\"position:absolute;left:212px;top:668px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p3_88\" class=\"drag\" style=\"position:absolute;left:212px;top:685px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>TPSSG2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_89\" class=\"drag\" style=\"position:absolute;left:384px;top:668px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_90\" class=\"drag\" style=\"position:absolute;left:734px;top:951px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_91\" class=\"drag\" style=\"position:absolute;left:212px;top:943px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>67<br></b></nobr>");
write("</p>");
write("<p id=\"p3_92\" class=\"drag\" style=\"position:absolute;left:212px;top:960px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ECT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_93\" class=\"drag\" style=\"position:absolute;left:286px;top:951px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_94\" class=\"drag\" style=\"position:absolute;left:384px;top:943px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p3_95\" class=\"drag\" style=\"position:absolute;left:734px;top:987px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_96\" class=\"drag\" style=\"position:absolute;left:212px;top:979px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>56<br></b></nobr>");
write("</p>");
write("<p id=\"p3_97\" class=\"drag\" style=\"position:absolute;left:212px;top:996px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ECTSG<br></b></nobr>");
write("</p>");
write("<p id=\"p3_98\" class=\"drag\" style=\"position:absolute;left:286px;top:987px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_99\" class=\"drag\" style=\"position:absolute;left:384px;top:979px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p3_100\" class=\"drag\" style=\"position:absolute;left:813px;top:908px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>MAP SENSOR/<br>IAT SENSOR 2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_101\" class=\"drag\" style=\"position:absolute;left:823px;top:452px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>MAF SENSOR/<br>IAT SENSOR 1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_102\" class=\"drag\" style=\"position:absolute;left:332px;top:722px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>17P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_103\" class=\"drag\" style=\"position:absolute;left:599px;top:275px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>M<br></b></nobr>");
write("</p>");
write("<p id=\"p3_104\" class=\"drag\" style=\"position:absolute;left:589px;top:228px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/<br>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_105\" class=\"drag\" style=\"position:absolute;left:511px;top:210px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>6P<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_106\" class=\"drag\" style=\"position:absolute;left:604px;top:190px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p3_107\" class=\"drag\" style=\"position:absolute;left:286px;top:293px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_108\" class=\"drag\" style=\"position:absolute;left:286px;top:336px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_109\" class=\"drag\" style=\"position:absolute;left:286px;top:379px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_110\" class=\"drag\" style=\"position:absolute;left:286px;top:422px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_111\" class=\"drag\" style=\"position:absolute;left:286px;top:495px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_112\" class=\"drag\" style=\"position:absolute;left:286px;top:531px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_113\" class=\"drag\" style=\"position:absolute;left:286px;top:567px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_114\" class=\"drag\" style=\"position:absolute;left:286px;top:603px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_115\" class=\"drag\" style=\"position:absolute;left:286px;top:639px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_116\" class=\"drag\" style=\"position:absolute;left:286px;top:676px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_117\" class=\"drag\" style=\"position:absolute;left:212px;top:612px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>TPSVCC2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_118\" class=\"drag\" style=\"position:absolute;left:734px;top:749px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_119\" class=\"drag\" style=\"position:absolute;left:734px;top:792px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_120\" class=\"drag\" style=\"position:absolute;left:734px;top:835px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_121\" class=\"drag\" style=\"position:absolute;left:734px;top:878px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_122\" class=\"drag\" style=\"position:absolute;left:805px;top:943px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_123\" class=\"drag\" style=\"position:absolute;left:805px;top:980px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_124\" class=\"drag\" style=\"position:absolute;left:215px;top:462px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 2 (58P)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_125\" class=\"drag\" style=\"position:absolute;left:215px;top:716px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 1 (96P)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_126\" class=\"drag\" style=\"position:absolute;left:593px;top:951px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_127\" class=\"drag\" style=\"position:absolute;left:593px;top:987px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_128\" class=\"drag\" style=\"position:absolute;left:686px;top:942px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_129\" class=\"drag\" style=\"position:absolute;left:686px;top:979px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_130\" class=\"drag\" style=\"position:absolute;left:898px;top:531px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p3_131\" class=\"drag\" style=\"position:absolute;left:898px;top:639px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p3_132\" class=\"drag\" style=\"position:absolute;left:822px;top:704px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>APP<br>SENSOR<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}