with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:475px; height:452px;\" coordsize=\"475,452\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:475px;height:452px;\">");
write("<img id=\"img1\" src=\"../img/SEA6EL4K734000Y1776FAAD05.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:452px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:127px;top:39px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b></b>Wire side of female terminals<br></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:93px;top:391px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>NAVIGATION UNIT CONNECTOR C (14P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:127px;top:412px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b></b>Wire side of female terminals<br></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:418px;top:159px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>MIC<br>OUT−<br>(PNK)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:406px;top:311px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>MIC<br>OUT−<br>(PNK)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:225px;top:159px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>MIC OUT+ (BLU)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:228px;top:206px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>MIC OUT+ (BLU)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:7px;top:18px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>HANDS FREE TELEPHONE CONTROL UNIT CONNECTOR (22P)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}