with(document) {
write("<v:group id=\"group17\" class=\"drag\" style=\"position:relative; width:950px; height:1085px;\" coordsize=\"950,1085\">");
write("<v:rect id=\"rect17\"class=\"drag\"  style=\"width:950px;height:1085px;\">");
write("<img id=\"img17\" src=\"../img/SEA6EJ3J54230100000EAAD17.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1085px;border-color:#ffffff\">");
write("<p id=\"p17_1\" class=\"drag\" style=\"position:absolute;left:259px;top:75px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p17_2\" class=\"drag\" style=\"position:absolute;left:230px;top:75px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p17_3\" class=\"drag\" style=\"position:absolute;left:57px;top:947px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G601<br></b></nobr>");
write("</p>");
write("<p id=\"p17_4\" class=\"drag\" style=\"position:absolute;left:229px;top:453px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p17_5\" class=\"drag\" style=\"position:absolute;left:258px;top:453px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p17_6\" class=\"drag\" style=\"position:absolute;left:676px;top:847px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right rear power window switch<br></b></nobr>");
write("</p>");
write("<p id=\"p17_7\" class=\"drag\" style=\"position:absolute;left:465px;top:632px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p17_8\" class=\"drag\" style=\"position:absolute;left:495px;top:632px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>T<br></b></nobr>");
write("</p>");
write("<p id=\"p17_9\" class=\"drag\" style=\"position:absolute;left:258px;top:632px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p17_10\" class=\"drag\" style=\"position:absolute;left:229px;top:632px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p17_11\" class=\"drag\" style=\"position:absolute;left:98px;top:990px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Engine compartment wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p17_12\" class=\"drag\" style=\"position:absolute;left:91px;top:988px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p17_13\" class=\"drag\" style=\"position:absolute;left:74px;top:989px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p17_14\" class=\"drag\" style=\"position:absolute;left:582px;top:989px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>T<br></b></nobr>");
write("</p>");
write("<p id=\"p17_15\" class=\"drag\" style=\"position:absolute;left:598px;top:988px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p17_16\" class=\"drag\" style=\"position:absolute;left:606px;top:990px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Driver's seat wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p17_17\" class=\"drag\" style=\"position:absolute;left:355px;top:1011px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Driver's door subharness<br></b></nobr>");
write("</p>");
write("<p id=\"p17_18\" class=\"drag\" style=\"position:absolute;left:348px;top:1010px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p17_19\" class=\"drag\" style=\"position:absolute;left:332px;top:1011px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>L<br></b></nobr>");
write("</p>");
write("<p id=\"p17_20\" class=\"drag\" style=\"position:absolute;left:73px;top:1010px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p17_21\" class=\"drag\" style=\"position:absolute;left:91px;top:1010px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p17_22\" class=\"drag\" style=\"position:absolute;left:98px;top:1011px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Dashboard wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p17_23\" class=\"drag\" style=\"position:absolute;left:331px;top:989px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>K<br></b></nobr>");
write("</p>");
write("<p id=\"p17_24\" class=\"drag\" style=\"position:absolute;left:348px;top:988px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p17_25\" class=\"drag\" style=\"position:absolute;left:355px;top:990px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Driver's door wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p17_26\" class=\"drag\" style=\"position:absolute;left:229px;top:382px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p17_27\" class=\"drag\" style=\"position:absolute;left:258px;top:382px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p17_28\" class=\"drag\" style=\"position:absolute;left:456px;top:64px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(Fuse/relay box socket)<br></b></nobr>");
write("</p>");
write("<p id=\"p17_29\" class=\"drag\" style=\"position:absolute;left:677px;top:76px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Cigarette lighter relay<br></b></nobr>");
write("</p>");
write("<p id=\"p17_30\" class=\"drag\" style=\"position:absolute;left:677px;top:126px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Driver's door lock knob switch<br></b></nobr>");
write("</p>");
write("<p id=\"p17_31\" class=\"drag\" style=\"position:absolute;left:482px;top:111px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>L<br></b></nobr>");
write("</p>");
write("<p id=\"p17_32\" class=\"drag\" style=\"position:absolute;left:452px;top:111px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p17_33\" class=\"drag\" style=\"position:absolute;left:677px;top:112px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Driver's key cylinder switch<br></b></nobr>");
write("</p>");
write("<p id=\"p17_34\" class=\"drag\" style=\"position:absolute;left:566px;top:111px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p17_35\" class=\"drag\" style=\"position:absolute;left:595px;top:111px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>K<br></b></nobr>");
write("</p>");
write("<p id=\"p17_36\" class=\"drag\" style=\"position:absolute;left:676px;top:632px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Driver's power seat switch (with power seat)<br></b></nobr>");
write("</p>");
write("<p id=\"p17_37\" class=\"drag\" style=\"position:absolute;left:229px;top:775px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p17_38\" class=\"drag\" style=\"position:absolute;left:258px;top:774px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p17_39\" class=\"drag\" style=\"position:absolute;left:495px;top:774px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>T<br></b></nobr>");
write("</p>");
write("<p id=\"p17_40\" class=\"drag\" style=\"position:absolute;left:465px;top:775px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p17_41\" class=\"drag\" style=\"position:absolute;left:676px;top:775px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Driver's seat heater (with power seat)<br></b></nobr>");
write("</p>");
write("<p id=\"p17_42\" class=\"drag\" style=\"position:absolute;left:229px;top:668px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p17_43\" class=\"drag\" style=\"position:absolute;left:258px;top:667px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p17_44\" class=\"drag\" style=\"position:absolute;left:495px;top:668px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>T<br></b></nobr>");
write("</p>");
write("<p id=\"p17_45\" class=\"drag\" style=\"position:absolute;left:465px;top:668px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p17_46\" class=\"drag\" style=\"position:absolute;left:676px;top:882px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right rear power door lock knob switch<br></b></nobr>");
write("</p>");
write("<p id=\"p17_47\" class=\"drag\" style=\"position:absolute;left:465px;top:882px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p17_48\" class=\"drag\" style=\"position:absolute;left:494px;top:882px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p17_49\" class=\"drag\" style=\"position:absolute;left:258px;top:882px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p17_50\" class=\"drag\" style=\"position:absolute;left:229px;top:882px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p17_51\" class=\"drag\" style=\"position:absolute;left:229px;top:846px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p17_52\" class=\"drag\" style=\"position:absolute;left:258px;top:846px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p17_53\" class=\"drag\" style=\"position:absolute;left:494px;top:846px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p17_54\" class=\"drag\" style=\"position:absolute;left:465px;top:846px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p17_55\" class=\"drag\" style=\"position:absolute;left:495px;top:147px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p17_56\" class=\"drag\" style=\"position:absolute;left:526px;top:147px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p17_57\" class=\"drag\" style=\"position:absolute;left:677px;top:147px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Driver's vanity mirror light<br></b></nobr>");
write("</p>");
write("<p id=\"p17_58\" class=\"drag\" style=\"position:absolute;left:677px;top:162px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Passenger's vanity mirror light<br></b></nobr>");
write("</p>");
write("<p id=\"p17_59\" class=\"drag\" style=\"position:absolute;left:523px;top:210px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p17_60\" class=\"drag\" style=\"position:absolute;left:494px;top:211px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p17_61\" class=\"drag\" style=\"position:absolute;left:676px;top:211px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Combination switch control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p17_62\" class=\"drag\" style=\"position:absolute;left:494px;top:246px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p17_63\" class=\"drag\" style=\"position:absolute;left:523px;top:246px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p17_64\" class=\"drag\" style=\"position:absolute;left:562px;top:328px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(Fuse/relay box socket)<br></b></nobr>");
write("</p>");
write("<p id=\"p17_65\" class=\"drag\" style=\"position:absolute;left:676px;top:340px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Relay module<br></b></nobr>");
write("</p>");
write("<p id=\"p17_66\" class=\"drag\" style=\"position:absolute;left:433px;top:383px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>MICU service check connector<br></b></nobr>");
write("</p>");
write("<p id=\"p17_67\" class=\"drag\" style=\"position:absolute;left:454px;top:406px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(Fuse/relay box socket)<br></b></nobr>");
write("</p>");
write("<p id=\"p17_68\" class=\"drag\" style=\"position:absolute;left:454px;top:442px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(Fuse/relay box socket)<br></b></nobr>");
write("</p>");
write("<p id=\"p17_69\" class=\"drag\" style=\"position:absolute;left:676px;top:418px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Multiplex integrated control unit (MICU)<br></b></nobr>");
write("</p>");
write("<p id=\"p17_70\" class=\"drag\" style=\"position:absolute;left:594px;top:496px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>K<br></b></nobr>");
write("</p>");
write("<p id=\"p17_71\" class=\"drag\" style=\"position:absolute;left:565px;top:496px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p17_72\" class=\"drag\" style=\"position:absolute;left:676px;top:497px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Power mirror switch<br></b></nobr>");
write("</p>");
write("<p id=\"p17_73\" class=\"drag\" style=\"position:absolute;left:451px;top:496px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p17_74\" class=\"drag\" style=\"position:absolute;left:480px;top:496px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>L<br></b></nobr>");
write("</p>");
write("<p id=\"p17_75\" class=\"drag\" style=\"position:absolute;left:676px;top:510px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right mirror<br></b></nobr>");
write("</p>");
write("<p id=\"p17_76\" class=\"drag\" style=\"position:absolute;left:676px;top:540px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Power window master switch<br></b></nobr>");
write("</p>");
write("<p id=\"p17_77\" class=\"drag\" style=\"position:absolute;left:98px;top:1033px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Floor wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p17_78\" class=\"drag\" style=\"position:absolute;left:91px;top:1031px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p17_79\" class=\"drag\" style=\"position:absolute;left:74px;top:1032px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p17_80\" class=\"drag\" style=\"position:absolute;left:355px;top:1033px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right rear door wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p17_81\" class=\"drag\" style=\"position:absolute;left:348px;top:1031px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p17_82\" class=\"drag\" style=\"position:absolute;left:331px;top:1032px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p17_83\" class=\"drag\" style=\"position:absolute;left:465px;top:703px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p17_84\" class=\"drag\" style=\"position:absolute;left:495px;top:703px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>T<br></b></nobr>");
write("</p>");
write("<p id=\"p17_85\" class=\"drag\" style=\"position:absolute;left:258px;top:703px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p17_86\" class=\"drag\" style=\"position:absolute;left:229px;top:703px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p17_87\" class=\"drag\" style=\"position:absolute;left:676px;top:704px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Driver's seat belt switch (with power seat)<br></b></nobr>");
write("</p>");
write("<p id=\"p17_88\" class=\"drag\" style=\"position:absolute;left:676px;top:740px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Driver's seat belt switch (without power seat)<br></b></nobr>");
write("</p>");
write("<p id=\"p17_89\" class=\"drag\" style=\"position:absolute;left:494px;top:739px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p17_90\" class=\"drag\" style=\"position:absolute;left:465px;top:739px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p17_91\" class=\"drag\" style=\"position:absolute;left:494px;top:810px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p17_92\" class=\"drag\" style=\"position:absolute;left:465px;top:810px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p17_93\" class=\"drag\" style=\"position:absolute;left:676px;top:811px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Driver's seat heater (without power seat)<br></b></nobr>");
write("</p>");
write("<p id=\"p17_94\" class=\"drag\" style=\"position:absolute;left:677px;top:176px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Sunroof switch<br></b></nobr>");
write("</p>");
write("<p id=\"p17_95\" class=\"drag\" style=\"position:absolute;left:454px;top:556px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(Fuse/relay box socket)<br></b></nobr>");
write("</p>");
write("<p id=\"p17_96\" class=\"drag\" style=\"position:absolute;left:676px;top:568px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Turn signal/Hazard relay<br></b></nobr>");
write("</p>");
write("<p id=\"p17_97\" class=\"drag\" style=\"position:absolute;left:676px;top:525px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right mirror<br></b></nobr>");
write("</p>");
write("<p id=\"p17_98\" class=\"drag\" style=\"position:absolute;left:676px;top:668px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Driver's power seat switch (without power seat)<br></b></nobr>");
write("</p>");
write("<p id=\"p17_99\" class=\"drag\" style=\"position:absolute;left:676px;top:453px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Multiplex integrated control unit (MICU)<br></b></nobr>");
write("</p>");
write("<p id=\"p17_100\" class=\"drag\" style=\"position:absolute;left:320px;top:24px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNDER−DASH <br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p17_101\" class=\"drag\" style=\"position:absolute;left:462px;top:287px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNDER−DASH <br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p17_102\" class=\"drag\" style=\"position:absolute;left:677px;top:190px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Automatic Dimming Inside Mirror<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}