with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\" coordsize=\"950,1103\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:1103px;\">");
write("<img id=\"img1\" src=\"../img/SEA6EJ4E34150100000LCAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:622px;top:806px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(32)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:622px;top:856px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(34)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:622px;top:891px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(35)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:622px;top:907px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(36)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:622px;top:924px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(37)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:367px;top:1077px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SHIFT PIECE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:622px;top:840px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(33)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:644px;top:806px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>5 x 22 mm, 3 x 22 mm SPRING PIN<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:367px;top:1094px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SELECT RETURN SPRING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:644px;top:840px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SELECT ARM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:622px;top:941px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(38)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:644px;top:890px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SELECT LEVER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:644px;top:856px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>14 x 20 x 5 mm DUST SEAL<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:622px;top:958px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(39)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:644px;top:907px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OIL GUTTER PLATE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:622px;top:992px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(40)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:644px;top:924px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>45 x 80 x 21 mm BEARING OUTER RACE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:622px;top:1009px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(41)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:644px;top:941px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>46 x 80 x 1 mm SPACER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:622px;top:1026px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(42)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:644px;top:958px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>35 x 54 x 8 mm OIL SEAL<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:644px;top:992px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CLUTCH HOUSING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:644px;top:1009px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BREATHER PLATE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:644px;top:1026px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>6 mm FLANGE BOLT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:644px;top:1043px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>12 N·m (1.2 kgf·m, 8.7 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:37px;top:823px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SHIFT FORK ASSEMBLY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:37px;top:856px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MAINSHAFT ASSEMBLY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:37px;top:873px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>6 mm FLANGE BOLT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:17px;top:1009px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(11)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:17px;top:806px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(1)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:17px;top:823px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(2)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:17px;top:840px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(3)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" class=\"drag\" style=\"position:absolute;left:17px;top:856px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(4)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" class=\"drag\" style=\"position:absolute;left:17px;top:873px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(5)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" class=\"drag\" style=\"position:absolute;left:17px;top:907px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(6)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" class=\"drag\" style=\"position:absolute;left:17px;top:924px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(7)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" class=\"drag\" style=\"position:absolute;left:17px;top:941px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(8)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" class=\"drag\" style=\"position:absolute;left:17px;top:958px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(9)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" class=\"drag\" style=\"position:absolute;left:37px;top:1026px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>14 x 20 mm DOWEL PIN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" class=\"drag\" style=\"position:absolute;left:37px;top:992px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OIL GUIDE PIPE A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" class=\"drag\" style=\"position:absolute;left:37px;top:806px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DIFFERENTIAL ASSEMBLY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" class=\"drag\" style=\"position:absolute;left:37px;top:941px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>64 mm SPRING WASHER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" class=\"drag\" style=\"position:absolute;left:37px;top:924px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>NEEDLE BEARING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" class=\"drag\" style=\"position:absolute;left:37px;top:840px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>COUNTERSHAFT ASSEMBLY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" class=\"drag\" style=\"position:absolute;left:17px;top:992px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(10)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" class=\"drag\" style=\"position:absolute;left:37px;top:907px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BEARING SET PLATE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" class=\"drag\" style=\"position:absolute;left:37px;top:958px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>28 x 43 x 7 mm OIL SEAL<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_48\" class=\"drag\" style=\"position:absolute;left:37px;top:1009px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OIL GUIDE PIPE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" class=\"drag\" style=\"position:absolute;left:37px;top:890px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>13 N·m (1.3 kgf·m, 9.4 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" class=\"drag\" style=\"position:absolute;left:17px;top:1026px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(12)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" class=\"drag\" style=\"position:absolute;left:37px;top:1043px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>20 mm THRUST WASHER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" class=\"drag\" style=\"position:absolute;left:17px;top:1043px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(13)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" class=\"drag\" style=\"position:absolute;left:17px;top:1060px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(14)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" class=\"drag\" style=\"position:absolute;left:17px;top:1077px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(15)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" class=\"drag\" style=\"position:absolute;left:37px;top:1060px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>20 mm THRUST NEEDLE BEARING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" class=\"drag\" style=\"position:absolute;left:37px;top:1077px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REVERSE IDLER GEAR SHAFT ASSEMBLY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" class=\"drag\" style=\"position:absolute;left:17px;top:1094px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(16)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" class=\"drag\" style=\"position:absolute;left:37px;top:1094px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>33 mm SPRING WASHER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" class=\"drag\" style=\"position:absolute;left:347px;top:958px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(25)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" class=\"drag\" style=\"position:absolute;left:347px;top:806px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(17)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" class=\"drag\" style=\"position:absolute;left:347px;top:823px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(18)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" class=\"drag\" style=\"position:absolute;left:347px;top:840px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(19)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" class=\"drag\" style=\"position:absolute;left:347px;top:857px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(20)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" class=\"drag\" style=\"position:absolute;left:347px;top:874px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(21)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" class=\"drag\" style=\"position:absolute;left:347px;top:890px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(22)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" class=\"drag\" style=\"position:absolute;left:367px;top:874px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OIL PUMP SHAFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" class=\"drag\" style=\"position:absolute;left:347px;top:941px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(24)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" class=\"drag\" style=\"position:absolute;left:367px;top:924px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OIL PUMP PLATE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" class=\"drag\" style=\"position:absolute;left:367px;top:857px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MAGNET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" class=\"drag\" style=\"position:absolute;left:367px;top:806px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REVERSE SHIFT FORK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" class=\"drag\" style=\"position:absolute;left:367px;top:823px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REVERSE SHIFT LEVER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" class=\"drag\" style=\"position:absolute;left:367px;top:840px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>8 x 50 mm PIN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" class=\"drag\" style=\"position:absolute;left:367px;top:890px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>6 mm FLANGE BOLT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" class=\"drag\" style=\"position:absolute;left:367px;top:907px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>12 N·m (1.2 kgf·m, 8.7 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" class=\"drag\" style=\"position:absolute;left:367px;top:941px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OIL PUMP OUTER ROTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" class=\"drag\" style=\"position:absolute;left:367px;top:958px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OIL PUMP INNER ROTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" class=\"drag\" style=\"position:absolute;left:347px;top:975px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(26)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" class=\"drag\" style=\"position:absolute;left:347px;top:1009px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(27)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" class=\"drag\" style=\"position:absolute;left:347px;top:1043px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(28)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" class=\"drag\" style=\"position:absolute;left:367px;top:975px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>14 mm WASHER<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_81\" class=\"drag\" style=\"position:absolute;left:347px;top:1060px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(29)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" class=\"drag\" style=\"position:absolute;left:367px;top:1009px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DRAIN PLUG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" class=\"drag\" style=\"position:absolute;left:367px;top:1026px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>39 N·m (4.0 kgf·m, 29 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" class=\"drag\" style=\"position:absolute;left:347px;top:1077px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(30)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" class=\"drag\" style=\"position:absolute;left:367px;top:1043px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SHIFT PIECE SHAFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" class=\"drag\" style=\"position:absolute;left:347px;top:1094px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(31)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" class=\"drag\" style=\"position:absolute;left:367px;top:1060px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INTERLOCK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" class=\"drag\" style=\"position:absolute;left:212px;top:232px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(1)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" class=\"drag\" style=\"position:absolute;left:230px;top:86px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(2)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" class=\"drag\" style=\"position:absolute;left:358px;top:17px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(3)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" class=\"drag\" style=\"position:absolute;left:473px;top:24px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(4)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" class=\"drag\" style=\"position:absolute;left:352px;top:213px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(5)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" class=\"drag\" style=\"position:absolute;left:344px;top:250px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(6)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" class=\"drag\" style=\"position:absolute;left:492px;top:233px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(7)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" class=\"drag\" style=\"position:absolute;left:557px;top:235px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(8)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" class=\"drag\" style=\"position:absolute;left:448px;top:307px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(9)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" class=\"drag\" style=\"position:absolute;left:529px;top:23px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(10)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" class=\"drag\" style=\"position:absolute;left:646px;top:33px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(11)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" class=\"drag\" style=\"position:absolute;left:354px;top:713px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(12)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" class=\"drag\" style=\"position:absolute;left:685px;top:228px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(13)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" class=\"drag\" style=\"position:absolute;left:712px;top:246px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(14)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" class=\"drag\" style=\"position:absolute;left:727px;top:277px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(15)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" class=\"drag\" style=\"position:absolute;left:589px;top:355px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(16)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" class=\"drag\" style=\"position:absolute;left:773px;top:337px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(17)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" class=\"drag\" style=\"position:absolute;left:774px;top:411px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(18)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" class=\"drag\" style=\"position:absolute;left:756px;top:494px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(19)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" class=\"drag\" style=\"position:absolute;left:632px;top:481px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(20)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" class=\"drag\" style=\"position:absolute;left:490px;top:341px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(21)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" class=\"drag\" style=\"position:absolute;left:584px;top:303px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(22)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" class=\"drag\" style=\"position:absolute;left:474px;top:351px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(23)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" class=\"drag\" style=\"position:absolute;left:469px;top:371px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(24)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" class=\"drag\" style=\"position:absolute;left:473px;top:398px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(25)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" class=\"drag\" style=\"position:absolute;left:663px;top:599px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(26)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" class=\"drag\" style=\"position:absolute;left:706px;top:594px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(27)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" class=\"drag\" style=\"position:absolute;left:223px;top:427px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(28)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" class=\"drag\" style=\"position:absolute;left:331px;top:479px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(29)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" class=\"drag\" style=\"position:absolute;left:197px;top:527px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(30)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" class=\"drag\" style=\"position:absolute;left:192px;top:570px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(31)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_119\" class=\"drag\" style=\"position:absolute;left:341px;top:593px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(32)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_120\" class=\"drag\" style=\"position:absolute;left:366px;top:468px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(33)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_121\" class=\"drag\" style=\"position:absolute;left:252px;top:706px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(35)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_122\" class=\"drag\" style=\"position:absolute;left:165px;top:300px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(36)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_123\" class=\"drag\" style=\"position:absolute;left:403px;top:354px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(37)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_124\" class=\"drag\" style=\"position:absolute;left:250px;top:388px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(38)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_125\" class=\"drag\" style=\"position:absolute;left:423px;top:760px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(39)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_126\" class=\"drag\" style=\"position:absolute;left:671px;top:708px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(40)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_127\" class=\"drag\" style=\"position:absolute;left:580px;top:720px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(41)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_128\" class=\"drag\" style=\"position:absolute;left:579px;top:754px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(42)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_129\" class=\"drag\" style=\"position:absolute;left:741px;top:309px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(14)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_130\" class=\"drag\" style=\"position:absolute;left:441px;top:435px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(12)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_131\" class=\"drag\" style=\"position:absolute;left:447px;top:394px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(12)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_132\" class=\"drag\" style=\"position:absolute;left:203px;top:477px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(19)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_133\" class=\"drag\" style=\"position:absolute;left:598px;top:335px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(13)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_134\" class=\"drag\" style=\"position:absolute;left:308px;top:716px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(34)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_135\" class=\"drag\" style=\"position:absolute;left:347px;top:924px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(23)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}