with(document) {
write("<v:group id=\"group16\" class=\"drag\" style=\"position:relative; width:950px; height:791px;\" coordsize=\"950,791\">");
write("<v:rect id=\"rect16\"class=\"drag\"  style=\"width:950px;height:791px;\">");
write("<img id=\"img16\" src=\"../img/SEA6EJ3J54230100000EAAD16.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:791px;border-color:#ffffff\">");
write("<p id=\"p16_1\" class=\"drag\" style=\"position:absolute;left:364px;top:540px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p16_2\" class=\"drag\" style=\"position:absolute;left:393px;top:539px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p16_3\" class=\"drag\" style=\"position:absolute;left:675px;top:540px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Accessory power socket<br></b></nobr>");
write("</p>");
write("<p id=\"p16_4\" class=\"drag\" style=\"position:absolute;left:675px;top:426px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Headlight washer unit<br></b></nobr>");
write("</p>");
write("<p id=\"p16_5\" class=\"drag\" style=\"position:absolute;left:393px;top:425px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p16_6\" class=\"drag\" style=\"position:absolute;left:364px;top:425px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p16_7\" class=\"drag\" style=\"position:absolute;left:675px;top:483px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>EPS unit<br></b></nobr>");
write("</p>");
write("<p id=\"p16_8\" class=\"drag\" style=\"position:absolute;left:393px;top:482px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p16_9\" class=\"drag\" style=\"position:absolute;left:364px;top:482px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p16_10\" class=\"drag\" style=\"position:absolute;left:675px;top:369px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>VSA off switch<br></b></nobr>");
write("</p>");
write("<p id=\"p16_11\" class=\"drag\" style=\"position:absolute;left:364px;top:368px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p16_12\" class=\"drag\" style=\"position:absolute;left:393px;top:368px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p16_13\" class=\"drag\" style=\"position:absolute;left:364px;top:311px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p16_14\" class=\"drag\" style=\"position:absolute;left:393px;top:311px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p16_15\" class=\"drag\" style=\"position:absolute;left:675px;top:312px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Navigation unit<br></b></nobr>");
write("</p>");
write("<p id=\"p16_16\" class=\"drag\" style=\"position:absolute;left:364px;top:254px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p16_17\" class=\"drag\" style=\"position:absolute;left:393px;top:254px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p16_18\" class=\"drag\" style=\"position:absolute;left:675px;top:255px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Gauge control module<br></b></nobr>");
write("</p>");
write("<p id=\"p16_19\" class=\"drag\" style=\"position:absolute;left:675px;top:197px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Glove box light<br></b></nobr>");
write("</p>");
write("<p id=\"p16_20\" class=\"drag\" style=\"position:absolute;left:393px;top:196px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p16_21\" class=\"drag\" style=\"position:absolute;left:364px;top:197px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p16_22\" class=\"drag\" style=\"position:absolute;left:675px;top:155px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Passenger's seat heater switch<br></b></nobr>");
write("</p>");
write("<p id=\"p16_23\" class=\"drag\" style=\"position:absolute;left:675px;top:140px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Driver's seat heater switch<br></b></nobr>");
write("</p>");
write("<p id=\"p16_24\" class=\"drag\" style=\"position:absolute;left:364px;top:140px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p16_25\" class=\"drag\" style=\"position:absolute;left:393px;top:139px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p16_26\" class=\"drag\" style=\"position:absolute;left:393px;top:82px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p16_27\" class=\"drag\" style=\"position:absolute;left:364px;top:83px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p16_28\" class=\"drag\" style=\"position:absolute;left:675px;top:83px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Ashtray light<br></b></nobr>");
write("</p>");
write("<p id=\"p16_29\" class=\"drag\" style=\"position:absolute;left:100px;top:739px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p16_30\" class=\"drag\" style=\"position:absolute;left:117px;top:738px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p16_31\" class=\"drag\" style=\"position:absolute;left:124px;top:740px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Dashboard wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p16_32\" class=\"drag\" style=\"position:absolute;left:675px;top:26px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Cigarette lighter<br></b></nobr>");
write("</p>");
write("<p id=\"p16_33\" class=\"drag\" style=\"position:absolute;left:84px;top:682px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G506<br></b></nobr>");
write("</p>");
write("<p id=\"p16_34\" class=\"drag\" style=\"position:absolute;left:364px;top:25px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p16_35\" class=\"drag\" style=\"position:absolute;left:393px;top:25px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p16_36\" class=\"drag\" style=\"position:absolute;left:364px;top:596px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p16_37\" class=\"drag\" style=\"position:absolute;left:393px;top:596px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p16_38\" class=\"drag\" style=\"position:absolute;left:675px;top:596px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Adaptive cruise control unit<br>(KE model with Adaptive cruise control)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}