with(document) {
write("<v:group id=\"group12\" class=\"drag\" style=\"position:relative; width:950px; height:1023px;\" coordsize=\"950,1023\">");
write("<v:rect id=\"rect12\"class=\"drag\"  style=\"width:950px;height:1023px;\">");
write("<img id=\"img12\" src=\"../img/SEA6EL4A20300000000DBAD12.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1023px;border-color:#ffffff\">");
write("<p id=\"p12_1\" class=\"drag\" style=\"position:absolute;left:475px;top:341px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>UNDER-DASH<br>FUSE/RELAY BOX (8)<br></b></nobr>");
write("</p>");
write("<p id=\"p12_2\" class=\"drag\" style=\"position:absolute;left:709px;top:341px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>UNDER-DASH<br>FUSE/RELAY BOX (9)<br></b></nobr>");
write("</p>");
write("<p id=\"p12_3\" class=\"drag\" style=\"position:absolute;left:102px;top:383px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>28P JUNCTION<br>CONNECTOR (6)<br></b></nobr>");
write("</p>");
write("<p id=\"p12_4\" class=\"drag\" style=\"position:absolute;left:290px;top:383px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>28P JUNCTION<br>CONNECTOR (7)<br></b></nobr>");
write("</p>");
write("<p id=\"p12_5\" class=\"drag\" style=\"position:absolute;left:119px;top:636px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>UNDER-DASH<br>FUSE/RELAY BOX (10)<br></b></nobr>");
write("</p>");
write("<p id=\"p12_6\" class=\"drag\" style=\"position:absolute;left:539px;top:636px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>DATA LINK<br>CONNECTOR (12)**<br></b></nobr>");
write("</p>");
write("<p id=\"p12_7\" class=\"drag\" style=\"position:absolute;left:319px;top:636px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>UNDER-DASH<br>FUSE/RELAY BOX (11)<br></b></nobr>");
write("</p>");
write("<p id=\"p12_8\" class=\"drag\" style=\"position:absolute;left:739px;top:625px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRAKE PEDAL<br>POSITION SWITCH<br>A/B (13)<br></b></nobr>");
write("</p>");
write("<p id=\"p12_9\" class=\"drag\" style=\"position:absolute;left:239px;top:798px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>CLUTCH PEDAL<br>POSITION SWITCH A<br>(15)<br></b></nobr>");
write("</p>");
write("<p id=\"p12_10\" class=\"drag\" style=\"position:absolute;left:421px;top:809px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>INERTIA<br>SWITCH (16)<br></b></nobr>");
write("</p>");
write("<p id=\"p12_11\" class=\"drag\" style=\"position:absolute;left:581px;top:809px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>4P CONNECTOR<br>(17)<br></b></nobr>");
write("</p>");
write("<p id=\"p12_12\" class=\"drag\" style=\"position:absolute;left:67px;top:798px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>CLUTCH PEDAL<br>POSITION SWITCH B<br>(14)<br></b></nobr>");
write("</p>");
write("<p id=\"p12_13\" class=\"drag\" style=\"position:absolute;left:265px;top:37px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GAUGE B (1)<br></b></nobr>");
write("</p>");
write("<p id=\"p12_14\" class=\"drag\" style=\"position:absolute;left:118px;top:174px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>7P CONNECTOR<br>(3)<br></b></nobr>");
write("</p>");
write("<p id=\"p12_15\" class=\"drag\" style=\"position:absolute;left:395px;top:181px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>13P CONNECTOR (4)<br></b></nobr>");
write("</p>");
write("<p id=\"p12_16\" class=\"drag\" style=\"position:absolute;left:758px;top:171px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>28P JUNCTION<br>CONNECTOR (5)<br></b></nobr>");
write("</p>");
write("<p id=\"p12_17\" class=\"drag\" style=\"position:absolute;left:654px;top:16px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>20P CONNECTOR<br>(2)<br></b></nobr>");
write("</p>");
write("<p id=\"p12_18\" class=\"drag\" style=\"position:absolute;left:0px;top:946px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>NOTE:<br>· Connector with male terminals (double outline): view from terminal side<br>· Connector with female terminals (single outline): view from wire side<br>**: Connector with female terminals (single outline): view from terminal side<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}