with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:475px; height:320px;\" coordsize=\"475,320\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:475px;height:320px;\">");
write("<img id=\"img1\" src=\"../img/SEA6EJ7J36200000000BBAD25.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:320px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:137px;top:77px;font-weight:normal;font-size:10.9pt;\">");
write("<nobr><b>GPS Detail<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:55px;top:106px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>TS:xx<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:55px;top:121px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>AS:xx<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:110px;top:106px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>HDop:xx.x<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:110px;top:121px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>VDop:xx.x<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:196px;top:106px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>Speed: x.xKm/h<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:195px;top:122px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>Direction:   x °<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:337px;top:76px;font-weight:normal;font-size:9.6pt;\">");
write("<nobr><b>Return<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:319px;top:106px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>Date :xxxx.xx.xx<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:319px;top:122px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>Time:xx:xx:xx<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:93px;top:158px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>xx<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:90px;top:142px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>PRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:93px;top:174px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>xx<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:93px;top:189px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>xx<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:93px;top:204px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>xx<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:93px;top:220px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>xx<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:93px;top:235px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>xx<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:144px;top:158px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>xx<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:143px;top:142px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>ST<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:144px;top:174px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>xx<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:144px;top:189px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>xx<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:144px;top:204px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>xx<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:144px;top:220px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>xx<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:144px;top:234px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>xx<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:193px;top:158px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>xxx<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:193px;top:174px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>xxx<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:193px;top:189px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>xxx<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:193px;top:204px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>xxx<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:193px;top:220px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>xxx<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:193px;top:235px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>xxx<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:191px;top:142px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>AZI<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:250px;top:159px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>xx<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" class=\"drag\" style=\"position:absolute;left:249px;top:143px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>EL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" class=\"drag\" style=\"position:absolute;left:250px;top:174px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>xx<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" class=\"drag\" style=\"position:absolute;left:250px;top:190px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>xx<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" class=\"drag\" style=\"position:absolute;left:250px;top:205px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>xx<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" class=\"drag\" style=\"position:absolute;left:250px;top:220px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>xx<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" class=\"drag\" style=\"position:absolute;left:250px;top:235px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>xx<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" class=\"drag\" style=\"position:absolute;left:300px;top:159px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>xxx<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" class=\"drag\" style=\"position:absolute;left:300px;top:142px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>C/N<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" class=\"drag\" style=\"position:absolute;left:300px;top:174px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>xxx<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" class=\"drag\" style=\"position:absolute;left:300px;top:189px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>xxx<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" class=\"drag\" style=\"position:absolute;left:300px;top:205px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>xxx<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" class=\"drag\" style=\"position:absolute;left:300px;top:220px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>xxx<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" class=\"drag\" style=\"position:absolute;left:300px;top:235px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>xxx<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" class=\"drag\" style=\"position:absolute;left:358px;top:158px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>xx<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" class=\"drag\" style=\"position:absolute;left:353px;top:142px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>ACC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" class=\"drag\" style=\"position:absolute;left:358px;top:174px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>xx<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" class=\"drag\" style=\"position:absolute;left:358px;top:189px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>xx<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" class=\"drag\" style=\"position:absolute;left:358px;top:204px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>xx<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" class=\"drag\" style=\"position:absolute;left:358px;top:220px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>xx<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" class=\"drag\" style=\"position:absolute;left:358px;top:235px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>xx<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" class=\"drag\" style=\"position:absolute;left:399px;top:188px;font-weight:normal;font-size:7.7pt;\">");
write("<nobr><b>1/2<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}