with(document) {
write("<v:group id=\"group12\" class=\"drag\" style=\"position:relative; width:950px; height:927px;\" coordsize=\"950,927\">");
write("<v:rect id=\"rect12\"class=\"drag\"  style=\"width:950px;height:927px;\">");
write("<img id=\"img12\" src=\"../img/SEA6EJ3J54230100000EAAD12.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:927px;border-color:#ffffff\">");
write("<p id=\"p12_1\" class=\"drag\" style=\"position:absolute;left:380px;top:70px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_2\" class=\"drag\" style=\"position:absolute;left:410px;top:34px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p12_3\" class=\"drag\" style=\"position:absolute;left:380px;top:35px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_4\" class=\"drag\" style=\"position:absolute;left:100px;top:542px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G701<br></b></nobr>");
write("</p>");
write("<p id=\"p12_5\" class=\"drag\" style=\"position:absolute;left:691px;top:35px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left license plate light<br></b></nobr>");
write("</p>");
write("<p id=\"p12_6\" class=\"drag\" style=\"position:absolute;left:691px;top:71px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right license plate light<br></b></nobr>");
write("</p>");
write("<p id=\"p12_7\" class=\"drag\" style=\"position:absolute;left:691px;top:107px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right rear turn signal light<br></b></nobr>");
write("</p>");
write("<p id=\"p12_8\" class=\"drag\" style=\"position:absolute;left:380px;top:106px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_9\" class=\"drag\" style=\"position:absolute;left:691px;top:143px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right brake/taillight<br></b></nobr>");
write("</p>");
write("<p id=\"p12_10\" class=\"drag\" style=\"position:absolute;left:380px;top:142px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_11\" class=\"drag\" style=\"position:absolute;left:380px;top:178px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_12\" class=\"drag\" style=\"position:absolute;left:691px;top:178px;font-weight:normal;font-size:6.7pt;\">");
write("<nobr><b>Left taillight<br></b></nobr>");
write("</p>");
write("<p id=\"p12_13\" class=\"drag\" style=\"position:absolute;left:380px;top:213px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_14\" class=\"drag\" style=\"position:absolute;left:691px;top:214px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Rear fog light (with rear fog light)<br></b></nobr>");
write("</p>");
write("<p id=\"p12_15\" class=\"drag\" style=\"position:absolute;left:380px;top:249px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_16\" class=\"drag\" style=\"position:absolute;left:691px;top:250px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Trunk handle switch<br></b></nobr>");
write("</p>");
write("<p id=\"p12_17\" class=\"drag\" style=\"position:absolute;left:380px;top:285px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_18\" class=\"drag\" style=\"position:absolute;left:691px;top:285px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Trunk actuator<br></b></nobr>");
write("</p>");
write("<p id=\"p12_19\" class=\"drag\" style=\"position:absolute;left:137px;top:628px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Rear wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p12_20\" class=\"drag\" style=\"position:absolute;left:130px;top:627px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p12_21\" class=\"drag\" style=\"position:absolute;left:116px;top:628px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p12_22\" class=\"drag\" style=\"position:absolute;left:410px;top:70px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p12_23\" class=\"drag\" style=\"position:absolute;left:410px;top:106px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p12_24\" class=\"drag\" style=\"position:absolute;left:410px;top:141px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p12_25\" class=\"drag\" style=\"position:absolute;left:410px;top:177px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p12_26\" class=\"drag\" style=\"position:absolute;left:410px;top:213px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p12_27\" class=\"drag\" style=\"position:absolute;left:410px;top:249px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p12_28\" class=\"drag\" style=\"position:absolute;left:410px;top:284px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p12_29\" class=\"drag\" style=\"position:absolute;left:381px;top:321px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_30\" class=\"drag\" style=\"position:absolute;left:692px;top:321px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right taillight<br></b></nobr>");
write("</p>");
write("<p id=\"p12_31\" class=\"drag\" style=\"position:absolute;left:409px;top:320px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p12_32\" class=\"drag\" style=\"position:absolute;left:381px;top:357px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_33\" class=\"drag\" style=\"position:absolute;left:692px;top:357px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right back−up light<br></b></nobr>");
write("</p>");
write("<p id=\"p12_34\" class=\"drag\" style=\"position:absolute;left:409px;top:356px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p12_35\" class=\"drag\" style=\"position:absolute;left:382px;top:393px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_36\" class=\"drag\" style=\"position:absolute;left:693px;top:393px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left rear turn signal light<br></b></nobr>");
write("</p>");
write("<p id=\"p12_37\" class=\"drag\" style=\"position:absolute;left:409px;top:392px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p12_38\" class=\"drag\" style=\"position:absolute;left:382px;top:428px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p12_39\" class=\"drag\" style=\"position:absolute;left:693px;top:429px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left brake/taillight<br></b></nobr>");
write("</p>");
write("<p id=\"p12_40\" class=\"drag\" style=\"position:absolute;left:410px;top:427px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}