with(document) {
write("<v:group id=\"group4\" class=\"drag\" style=\"position:relative; width:950px; height:415px;\" coordsize=\"950,415\">");
write("<v:rect id=\"rect4\"class=\"drag\"  style=\"width:950px;height:415px;\">");
write("<img id=\"img4\" src=\"../img/SEA6EJ7J36200000000CAAD05.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:415px;border-color:#ffffff\">");
write("<p id=\"p4_1\" class=\"drag\" style=\"position:absolute;left:130px;top:19px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Enlarged view of sensor element<br></b></nobr>");
write("</p>");
write("<p id=\"p4_2\" class=\"drag\" style=\"position:absolute;left:356px;top:70px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DETECTING PIEZOELECTRIC<br>PARTS<br></b></nobr>");
write("</p>");
write("<p id=\"p4_3\" class=\"drag\" style=\"position:absolute;left:355px;top:127px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OSCILLATORS<br></b></nobr>");
write("</p>");
write("<p id=\"p4_4\" class=\"drag\" style=\"position:absolute;left:37px;top:135px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SUPPORT PIN<br></b></nobr>");
write("</p>");
write("<p id=\"p4_5\" class=\"drag\" style=\"position:absolute;left:8px;top:247px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DRIVING PIEZOELECTRIC<br>PART<br></b></nobr>");
write("</p>");
write("<p id=\"p4_6\" class=\"drag\" style=\"position:absolute;left:54px;top:377px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>METAL BLOCK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_7\" class=\"drag\" style=\"position:absolute;left:349px;top:359px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MONITORING PIEZOELECTRIC<br>PART<br></b></nobr>");
write("</p>");
write("<p id=\"p4_8\" class=\"drag\" style=\"position:absolute;left:426px;top:285px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Bend<br></b></nobr>");
write("</p>");
write("<p id=\"p4_9\" class=\"drag\" style=\"position:absolute;left:331px;top:196px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Oscillation<br></b></nobr>");
write("</p>");
write("<p id=\"p4_10\" class=\"drag\" style=\"position:absolute;left:542px;top:226px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Coriolis force<br></b></nobr>");
write("</p>");
write("<p id=\"p4_11\" class=\"drag\" style=\"position:absolute;left:618px;top:141px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Turn to<br>right<br></b></nobr>");
write("</p>");
write("<p id=\"p4_12\" class=\"drag\" style=\"position:absolute;left:751px;top:174px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Coriolis force<br></b></nobr>");
write("</p>");
write("<p id=\"p4_13\" class=\"drag\" style=\"position:absolute;left:867px;top:195px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Oscillation<br></b></nobr>");
write("</p>");
write("<p id=\"p4_14\" class=\"drag\" style=\"position:absolute;left:614px;top:20px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Sensor element top view<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}