with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:475px; height:192px;\" coordsize=\"475,192\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:475px;height:192px;\">");
write("<img id=\"img1\" src=\"../img/SEA6EL4J34200057284FEAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:192px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:113px;top:24px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Terminal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:48px;top:55px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Position<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:90px;top:88px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>CLOSE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:102px;top:120px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>TILT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:95px;top:152px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>OPEN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:207px;top:40px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:284px;top:40px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:322px;top:40px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:361px;top:40px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:399px;top:40px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:438px;top:40px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}