with(document) {
write("<v:group id=\"group4\" class=\"drag\" style=\"position:relative; width:950px; height:1058px;\" coordsize=\"950,1058\">");
write("<v:rect id=\"rect4\"class=\"drag\"  style=\"width:950px;height:1058px;\">");
write("<img id=\"img4\" src=\"../img/SEA6EL4J54260400000EAAD04.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1058px;border-color:#ffffff\">");
write("<p id=\"p4_1\" class=\"drag\" style=\"position:absolute;left:745px;top:984px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p4_2\" class=\"drag\" style=\"position:absolute;left:748px;top:949px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p4_3\" class=\"drag\" style=\"position:absolute;left:777px;top:584px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>MULTI−FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p4_4\" class=\"drag\" style=\"position:absolute;left:745px;top:584px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p4_5\" class=\"drag\" style=\"position:absolute;left:748px;top:534px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p4_6\" class=\"drag\" style=\"position:absolute;left:777px;top:983px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>MULTI−FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p4_7\" class=\"drag\" style=\"position:absolute;left:533px;top:698px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p4_8\" class=\"drag\" style=\"position:absolute;left:533px;top:669px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p4_9\" class=\"drag\" style=\"position:absolute;left:748px;top:612px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Magnet valve<br></b></nobr>");
write("</p>");
write("<p id=\"p4_10\" class=\"drag\" style=\"position:absolute;left:523px;top:584px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_11\" class=\"drag\" style=\"position:absolute;left:522px;top:948px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p4_12\" class=\"drag\" style=\"position:absolute;left:344px;top:329px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>CONTROL BLOCK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_13\" class=\"drag\" style=\"position:absolute;left:395px;top:256px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_14\" class=\"drag\" style=\"position:absolute;left:395px;top:268px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(30 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_15\" class=\"drag\" style=\"position:absolute;left:195px;top:86px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p4_16\" class=\"drag\" style=\"position:absolute;left:110px;top:150px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p4_17\" class=\"drag\" style=\"position:absolute;left:92px;top:198px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_18\" class=\"drag\" style=\"position:absolute;left:214px;top:139px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.14 (40 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_19\" class=\"drag\" style=\"position:absolute;left:521px;top:155px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_20\" class=\"drag\" style=\"position:absolute;left:532px;top:462px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_21\" class=\"drag\" style=\"position:absolute;left:214px;top:375px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.21 (40 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_22\" class=\"drag\" style=\"position:absolute;left:703px;top:511px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G302<br></b></nobr>");
write("</p>");
write("<p id=\"p4_23\" class=\"drag\" style=\"position:absolute;left:214px;top:518px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.11 (30 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_24\" class=\"drag\" style=\"position:absolute;left:521px;top:533px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_25\" class=\"drag\" style=\"position:absolute;left:777px;top:533px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>FUEL HEATER RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p4_26\" class=\"drag\" style=\"position:absolute;left:533px;top:641px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p4_27\" class=\"drag\" style=\"position:absolute;left:217px;top:725px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.9 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_28\" class=\"drag\" style=\"position:absolute;left:748px;top:741px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Condenser fan motor<br></b></nobr>");
write("</p>");
write("<p id=\"p4_29\" class=\"drag\" style=\"position:absolute;left:522px;top:741px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_30\" class=\"drag\" style=\"position:absolute;left:748px;top:155px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Rear window defogger<br></b></nobr>");
write("</p>");
write("<p id=\"p4_31\" class=\"drag\" style=\"position:absolute;left:748px;top:391px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Blower motor<br></b></nobr>");
write("</p>");
write("<p id=\"p4_32\" class=\"drag\" style=\"position:absolute;left:521px;top:898px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p4_33\" class=\"drag\" style=\"position:absolute;left:748px;top:826px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ECM (ACC)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_34\" class=\"drag\" style=\"position:absolute;left:534px;top:826px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p4_35\" class=\"drag\" style=\"position:absolute;left:748px;top:898px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>A/C compressor clutch<br></b></nobr>");
write("</p>");
write("<p id=\"p4_36\" class=\"drag\" style=\"position:absolute;left:219px;top:23px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNDER−HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p4_37\" class=\"drag\" style=\"position:absolute;left:214px;top:932px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.12 (30 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_38\" class=\"drag\" style=\"position:absolute;left:519px;top:391px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_39\" class=\"drag\" style=\"position:absolute;left:382px;top:300px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>d<br></b></nobr>");
write("</p>");
write("<p id=\"p4_40\" class=\"drag\" style=\"position:absolute;left:748px;top:169px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Antenna coil<br></b></nobr>");
write("</p>");
write("<p id=\"p4_41\" class=\"drag\" style=\"position:absolute;left:74px;top:105px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.30 (7.5 A) FUSE <br>UNDER−DASH <br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p4_42\" class=\"drag\" style=\"position:absolute;left:311px;top:99px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>REAR WINDOW <br>DEFOGGER <br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p4_43\" class=\"drag\" style=\"position:absolute;left:312px;top:346px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLOWER <br>MOTOR RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p4_44\" class=\"drag\" style=\"position:absolute;left:312px;top:603px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>CONDENSER <br>FAN RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p4_45\" class=\"drag\" style=\"position:absolute;left:312px;top:776px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>A/C <br>COMPRESSOR <br>CLUTCH RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p4_46\" class=\"drag\" style=\"position:absolute;left:777px;top:942px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNDER−DASH <br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p4_47\" class=\"drag\" style=\"position:absolute;left:748px;top:698px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Radiator fan low <br>temperature switch<br></b></nobr>");
write("</p>");
write("<p id=\"p4_48\" class=\"drag\" style=\"position:absolute;left:748px;top:669px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Climate control unit <br>(Via fan low diode)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_49\" class=\"drag\" style=\"position:absolute;left:748px;top:640px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Climate control unit <br>(Via condenser fan diode)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}