with(document) {
write("<v:group id=\"group2\" class=\"drag\" style=\"position:relative; width:950px; height:223px;\" coordsize=\"950,223\">");
write("<v:rect id=\"rect2\"class=\"drag\"  style=\"width:950px;height:223px;\">");
write("<img id=\"img2\" src=\"../img/SEA6EL8H10900036861MBAD31.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:223px;border-color:#ffffff\">");
write("<p id=\"p2_1\" class=\"drag\" style=\"position:absolute;left:187px;top:24px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DISPLAY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" class=\"drag\" style=\"position:absolute;left:54px;top:56px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>STATE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" class=\"drag\" style=\"position:absolute;left:567px;top:39px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(2) LKAS<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" class=\"drag\" style=\"position:absolute;left:719px;top:25px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ADAPTIVE CRUISE CONTROL<br>(ACC)/LKAS INDICATOR<br>(ORANGE)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" class=\"drag\" style=\"position:absolute;left:87px;top:119px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Aiming is completed<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" class=\"drag\" style=\"position:absolute;left:96px;top:151px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Aiming is failure<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" class=\"drag\" style=\"position:absolute;left:358px;top:87px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Blink<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" class=\"drag\" style=\"position:absolute;left:360px;top:119px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" class=\"drag\" style=\"position:absolute;left:364px;top:151px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ON<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" class=\"drag\" style=\"position:absolute;left:583px;top:87px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ON*<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" class=\"drag\" style=\"position:absolute;left:583px;top:120px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" class=\"drag\" style=\"position:absolute;left:582px;top:151px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" class=\"drag\" style=\"position:absolute;left:811px;top:88px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ON<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" class=\"drag\" style=\"position:absolute;left:809px;top:119px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" class=\"drag\" style=\"position:absolute;left:811px;top:152px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ON<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" class=\"drag\" style=\"position:absolute;left:50px;top:181px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>: The ''LKAS'' display disappears when the lane cannot be recognized.<br></nobr>");
write("</p>");
write("<p id=\"p2_17\" class=\"drag\" style=\"position:absolute;left:38px;top:181px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>*<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" class=\"drag\" style=\"position:absolute;left:328px;top:39px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(1) CAMERA<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" class=\"drag\" style=\"position:absolute;left:95px;top:88px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Starting of aiming<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}