with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:979px; height:959px;\" coordsize=\"979,959\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:979px;height:959px;\">");
write("<img id=\"img1\" src=\"../img/SEA6EJ4J54200000000DEAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:979px;height:959px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:279px;top:719px;font-weight:normal;font-size:8.9pt;\">");
write("<nobr><b>SRS UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:890px;top:705px;font-weight:normal;font-size:8.9pt;\">");
write("<nobr><b>ECM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:855px;top:246px;font-weight:normal;font-size:8.9pt;\">");
write("<nobr><b>IMOES UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:665px;top:53px;font-weight:normal;font-size:8.9pt;\">");
write("<nobr><b>PGM-FI MAIN RELAY 1<br></b>Wire colors: WHT/GRN, YEL/BLK,<br>WHT/GRN and RED/BLK<br></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:664px;top:104px;font-weight:normal;font-size:8.9pt;\">");
write("<nobr><b>PGM-FI MAIN RELAY 2<br></b>Wire colors: WHT/BLK, WHT/RED,<br>WHT/GRN and RED/BLK<br></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:593px;top:746px;font-weight:normal;font-size:8.9pt;\">");
write("<nobr><b>SECURITY HAZARD WARNING LIGHT RELAY (Right)<br></b>Wire colors: WHT/BLK, BRN,<br>WHT and WHT/BLK<br></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:593px;top:796px;font-weight:normal;font-size:8.9pt;\">");
write("<nobr><b>SECURITY HAZARD WARNING LIGHT RELAY (Left)<br></b>Wire colors: WHT/BLK, RED/BLU,<br>WHT and WHT/BLK<br></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:760px;top:176px;font-weight:normal;font-size:8.9pt;\">");
write("<nobr><b>SEAT HEATER RELAY*<br></b>Wire colors: RED/BLK, BRN,<br>BLU and BLK/YEL<br></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:381px;top:861px;font-weight:normal;font-size:8.9pt;\">");
write("<nobr><b>ACCESSORY POWER SOCKET RELAY<br></b>Wire colors: GRN, RED/YEL,<br>BLK and RED<br></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:877px;top:16px;font-weight:normal;font-size:8.9pt;\">");
write("<nobr><b>*: RHD type<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:16px;top:927px;font-weight:normal;font-size:8.9pt;\">");
write("<nobr><b></b>LHD type is shown, RHD type is similar.<br></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:870px;top:447px;font-weight:normal;font-size:8.9pt;\">");
write("<nobr><b>AUTOMATIC<br>LIGHTING<br>CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:387px;top:103px;font-weight:normal;font-size:8.9pt;\">");
write("<nobr><b>HANDS FREE TELEPHONE<br>CONTROL UNIT<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}