with(document) {
write("<v:group id=\"group7\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\" coordsize=\"950,1103\">");
write("<v:rect id=\"rect7\"class=\"drag\"  style=\"width:950px;height:1103px;\">");
write("<img id=\"img7\" src=\"../img/SEA6EJ4A20300000000EAAD07.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p7_1\" class=\"drag\" style=\"position:absolute;left:206px;top:219px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 2 (58P)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_2\" class=\"drag\" style=\"position:absolute;left:721px;top:449px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>UNDER-DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p7_3\" class=\"drag\" style=\"position:absolute;left:839px;top:504px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(8)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_4\" class=\"drag\" style=\"position:absolute;left:839px;top:549px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(9)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_5\" class=\"drag\" style=\"position:absolute;left:684px;top:474px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p7_6\" class=\"drag\" style=\"position:absolute;left:684px;top:510px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p7_7\" class=\"drag\" style=\"position:absolute;left:684px;top:528px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>29<br></b></nobr>");
write("</p>");
write("<p id=\"p7_8\" class=\"drag\" style=\"position:absolute;left:684px;top:545px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>41<br></b></nobr>");
write("</p>");
write("<p id=\"p7_9\" class=\"drag\" style=\"position:absolute;left:684px;top:581px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>33<br></b></nobr>");
write("</p>");
write("<p id=\"p7_10\" class=\"drag\" style=\"position:absolute;left:684px;top:599px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p7_11\" class=\"drag\" style=\"position:absolute;left:684px;top:617px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p7_12\" class=\"drag\" style=\"position:absolute;left:684px;top:635px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p7_13\" class=\"drag\" style=\"position:absolute;left:684px;top:652px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>35<br></b></nobr>");
write("</p>");
write("<p id=\"p7_14\" class=\"drag\" style=\"position:absolute;left:684px;top:706px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p7_15\" class=\"drag\" style=\"position:absolute;left:684px;top:724px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p7_16\" class=\"drag\" style=\"position:absolute;left:684px;top:741px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p7_17\" class=\"drag\" style=\"position:absolute;left:684px;top:759px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p7_18\" class=\"drag\" style=\"position:absolute;left:684px;top:777px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p7_19\" class=\"drag\" style=\"position:absolute;left:613px;top:483px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p7_20\" class=\"drag\" style=\"position:absolute;left:613px;top:518px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p7_21\" class=\"drag\" style=\"position:absolute;left:613px;top:536px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p7_22\" class=\"drag\" style=\"position:absolute;left:613px;top:554px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p7_23\" class=\"drag\" style=\"position:absolute;left:613px;top:590px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p7_24\" class=\"drag\" style=\"position:absolute;left:613px;top:608px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p7_25\" class=\"drag\" style=\"position:absolute;left:611px;top:750px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p7_26\" class=\"drag\" style=\"position:absolute;left:613px;top:643px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p7_27\" class=\"drag\" style=\"position:absolute;left:613px;top:661px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p7_28\" class=\"drag\" style=\"position:absolute;left:613px;top:714px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p7_29\" class=\"drag\" style=\"position:absolute;left:613px;top:732px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p7_30\" class=\"drag\" style=\"position:absolute;left:612px;top:626px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU (PNK)*<br></b></nobr>");
write("</p>");
write("<p id=\"p7_31\" class=\"drag\" style=\"position:absolute;left:613px;top:768px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p7_32\" class=\"drag\" style=\"position:absolute;left:613px;top:786px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p7_33\" class=\"drag\" style=\"position:absolute;left:839px;top:602px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(10)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_34\" class=\"drag\" style=\"position:absolute;left:590px;top:444px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p7_35\" class=\"drag\" style=\"position:absolute;left:594px;top:90px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>28P JUNCTION<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p7_36\" class=\"drag\" style=\"position:absolute;left:686px;top:396px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRAKE PEDAL<br>POSITION SWITCH B<br></b></nobr>");
write("</p>");
write("<p id=\"p7_37\" class=\"drag\" style=\"position:absolute;left:777px;top:324px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>Brake pedal pressed: closed<br>Brake pedal released: open<br></b></nobr>");
write("</p>");
write("<p id=\"p7_38\" class=\"drag\" style=\"position:absolute;left:778px;top:358px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>Brake pedal pressed: open<br>Brake pedal released: closed<br></b></nobr>");
write("</p>");
write("<p id=\"p7_39\" class=\"drag\" style=\"position:absolute;left:680px;top:365px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p7_40\" class=\"drag\" style=\"position:absolute;left:604px;top:372px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p7_41\" class=\"drag\" style=\"position:absolute;left:680px;top:348px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p7_42\" class=\"drag\" style=\"position:absolute;left:604px;top:355px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p7_43\" class=\"drag\" style=\"position:absolute;left:680px;top:330px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p7_44\" class=\"drag\" style=\"position:absolute;left:604px;top:338px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p7_45\" class=\"drag\" style=\"position:absolute;left:680px;top:313px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p7_46\" class=\"drag\" style=\"position:absolute;left:604px;top:321px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p7_47\" class=\"drag\" style=\"position:absolute;left:644px;top:159px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p7_48\" class=\"drag\" style=\"position:absolute;left:626px;top:159px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p7_49\" class=\"drag\" style=\"position:absolute;left:574px;top:159px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p7_50\" class=\"drag\" style=\"position:absolute;left:521px;top:159px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>26<br></b></nobr>");
write("</p>");
write("<p id=\"p7_51\" class=\"drag\" style=\"position:absolute;left:556px;top:159px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p7_52\" class=\"drag\" style=\"position:absolute;left:504px;top:159px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>24<br></b></nobr>");
write("</p>");
write("<p id=\"p7_53\" class=\"drag\" style=\"position:absolute;left:486px;top:159px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>25<br></b></nobr>");
write("</p>");
write("<p id=\"p7_54\" class=\"drag\" style=\"position:absolute;left:462px;top:448px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p7_55\" class=\"drag\" style=\"position:absolute;left:444px;top:448px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p7_56\" class=\"drag\" style=\"position:absolute;left:411px;top:383px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>28P JUNCTION<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p7_57\" class=\"drag\" style=\"position:absolute;left:571px;top:493px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>Q<br></b></nobr>");
write("</p>");
write("<p id=\"p7_58\" class=\"drag\" style=\"position:absolute;left:497px;top:572px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>21P<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p7_59\" class=\"drag\" style=\"position:absolute;left:549px;top:600px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p7_60\" class=\"drag\" style=\"position:absolute;left:549px;top:617px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p7_61\" class=\"drag\" style=\"position:absolute;left:549px;top:635px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p7_62\" class=\"drag\" style=\"position:absolute;left:471px;top:608px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p7_63\" class=\"drag\" style=\"position:absolute;left:471px;top:626px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p7_64\" class=\"drag\" style=\"position:absolute;left:471px;top:644px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p7_65\" class=\"drag\" style=\"position:absolute;left:449px;top:575px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p7_66\" class=\"drag\" style=\"position:absolute;left:402px;top:72px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>M<br></b></nobr>");
write("</p>");
write("<p id=\"p7_67\" class=\"drag\" style=\"position:absolute;left:684px;top:831px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p7_68\" class=\"drag\" style=\"position:absolute;left:684px;top:866px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p7_69\" class=\"drag\" style=\"position:absolute;left:684px;top:884px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p7_70\" class=\"drag\" style=\"position:absolute;left:507px;top:807px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IGNITION SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p7_71\" class=\"drag\" style=\"position:absolute;left:607px;top:831px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p7_72\" class=\"drag\" style=\"position:absolute;left:515px;top:876px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>+B<br></b></nobr>");
write("</p>");
write("<p id=\"p7_73\" class=\"drag\" style=\"position:absolute;left:607px;top:867px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IG2<br></b></nobr>");
write("</p>");
write("<p id=\"p7_74\" class=\"drag\" style=\"position:absolute;left:519px;top:924px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IGNITION SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p7_75\" class=\"drag\" style=\"position:absolute;left:213px;top:979px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>UNDER-DASH FUSE/RELAY BOX:<br><br>(8)No. 30 IG HAC (A/C) (7.5 A)<br>(9)No. 18 IG ACG (15 A)<br>(10)No. 21 IG METER (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_76\" class=\"drag\" style=\"position:absolute;left:258px;top:702px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p7_77\" class=\"drag\" style=\"position:absolute;left:286px;top:702px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p7_78\" class=\"drag\" style=\"position:absolute;left:315px;top:702px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E<br></b></nobr>");
write("</p>");
write("<p id=\"p7_79\" class=\"drag\" style=\"position:absolute;left:344px;top:657px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p7_80\" class=\"drag\" style=\"position:absolute;left:371px;top:658px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>L<br></b></nobr>");
write("</p>");
write("<p id=\"p7_81\" class=\"drag\" style=\"position:absolute;left:212px;top:617px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p7_82\" class=\"drag\" style=\"position:absolute;left:212px;top:634px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ELDGND<br></b></nobr>");
write("</p>");
write("<p id=\"p7_83\" class=\"drag\" style=\"position:absolute;left:212px;top:585px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p7_84\" class=\"drag\" style=\"position:absolute;left:212px;top:601px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ELD<br></b></nobr>");
write("</p>");
write("<p id=\"p7_85\" class=\"drag\" style=\"position:absolute;left:212px;top:534px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>45<br></b></nobr>");
write("</p>");
write("<p id=\"p7_86\" class=\"drag\" style=\"position:absolute;left:212px;top:551px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ACC<br></b></nobr>");
write("</p>");
write("<p id=\"p7_87\" class=\"drag\" style=\"position:absolute;left:212px;top:484px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>27<br></b></nobr>");
write("</p>");
write("<p id=\"p7_88\" class=\"drag\" style=\"position:absolute;left:212px;top:500px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IG2<br></b></nobr>");
write("</p>");
write("<p id=\"p7_89\" class=\"drag\" style=\"position:absolute;left:286px;top:457px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>21P<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p7_90\" class=\"drag\" style=\"position:absolute;left:338px;top:484px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p7_91\" class=\"drag\" style=\"position:absolute;left:252px;top:491px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p7_92\" class=\"drag\" style=\"position:absolute;left:386px;top:492px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p7_93\" class=\"drag\" style=\"position:absolute;left:212px;top:347px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>35<br></b></nobr>");
write("</p>");
write("<p id=\"p7_94\" class=\"drag\" style=\"position:absolute;left:212px;top:364px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p7_95\" class=\"drag\" style=\"position:absolute;left:352px;top:348px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p7_96\" class=\"drag\" style=\"position:absolute;left:266px;top:355px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p7_97\" class=\"drag\" style=\"position:absolute;left:212px;top:297px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>36<br></b></nobr>");
write("</p>");
write("<p id=\"p7_98\" class=\"drag\" style=\"position:absolute;left:212px;top:313px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BKSWNC<br></b></nobr>");
write("</p>");
write("<p id=\"p7_99\" class=\"drag\" style=\"position:absolute;left:301px;top:270px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>21P<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p7_100\" class=\"drag\" style=\"position:absolute;left:352px;top:297px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p7_101\" class=\"drag\" style=\"position:absolute;left:266px;top:304px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p7_102\" class=\"drag\" style=\"position:absolute;left:212px;top:247px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>38<br></b></nobr>");
write("</p>");
write("<p id=\"p7_103\" class=\"drag\" style=\"position:absolute;left:212px;top:263px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BKSWNO<br></b></nobr>");
write("</p>");
write("<p id=\"p7_104\" class=\"drag\" style=\"position:absolute;left:301px;top:220px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>10P<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p7_105\" class=\"drag\" style=\"position:absolute;left:352px;top:247px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p7_106\" class=\"drag\" style=\"position:absolute;left:266px;top:254px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p7_107\" class=\"drag\" style=\"position:absolute;left:394px;top:355px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p7_108\" class=\"drag\" style=\"position:absolute;left:394px;top:305px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p7_109\" class=\"drag\" style=\"position:absolute;left:394px;top:255px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p7_110\" class=\"drag\" style=\"position:absolute;left:688px;top:285px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRAKE PEDAL<br>POSITION SWITCH A<br></b></nobr>");
write("</p>");
write("<p id=\"p7_111\" class=\"drag\" style=\"position:absolute;left:221px;top:853px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>R<br></b></nobr>");
write("</p>");
write("<p id=\"p7_112\" class=\"drag\" style=\"position:absolute;left:213px;top:1065px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>*: RHD model<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}