with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:1071px;\" coordsize=\"950,1071\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:1071px;\">");
write("<img id=\"img1\" src=\"../img/SEA6EJ4A20336335001KDAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1071px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:38px;top:130px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>6 x 1.0 mm<br>12 N·m <br>(1.2 kgf·m, 8.7 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:328px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INTAKE MANIFOLD<br>RUNNER CONTROL<br>(IMRC) SOLENOID<br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:138px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FILTER ASSEMBLY<br>SOLENOID VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:636px;top:771px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>GASKET<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:359px;top:561px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>IMRC VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:706px;top:989px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>8 x 1.25 mm<br>22 N·m <br>(2.2 kgf·m, 16 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:795px;top:505px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>AIR INTAKE<br>PASSAGE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:173px;top:883px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>GASKET<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:635px;top:711px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INTAKE MANIFOLD<br>BRACKET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:99px;top:508px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>8 x 1.25 mm<br>22 N·m <br>(2.2 kgf·m, 16 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:807px;top:696px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>8 x 1.25 mm<br>22 N·m <br>(2.2 kgf·m, 16 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:30px;top:242px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INTAKE MANIFOLD<br></b>Replace if cracked or if<br>mating surface is<br>damaged.<br></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:332px;top:807px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>8 x 1.25 mm<br>22 N·m <br>(2.2 kgf·m, 16 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:110px;top:608px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EGR VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:462px;top:1013px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EGR PIPE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:201px;top:1009px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>8 x 1.25 mm<br>22 N·m <br>(2.2 kgf·m, 16 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:43px;top:815px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>8 x 1.25 mm<br>22 N·m <br>(2.2 kgf·m, 16 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:367px;top:750px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>GASKET<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:456px;top:728px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>8 x 1.25 mm<br>22 N·m <br>(2.2 kgf·m, 16 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:280px;top:507px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>GASKET<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:751px;top:459px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>GASKET<br></b>Replace.<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}