with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:607px;\" coordsize=\"950,607\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:607px;\">");
write("<img id=\"img1\" src=\"../img/SEA6EJPE10480150701MEAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:607px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:599px;top:20px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>6 x 1.0 mm<br>12 N·m (1.2 kgf·m, 8.7 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:569px;top:183px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:654px;top:201px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:662px;top:261px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:684px;top:309px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>3RD ACCUMULATOR<br>PISTON<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:654px;top:374px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>O-RING<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:561px;top:495px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REGULATOR VALVE BODY<br></b>Inspect for scoring and damage.<br></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:246px;top:462px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LOCK-UP SHIFT VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:291px;top:500px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>E<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:359px;top:578px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VALVE CAP CLIP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:175px;top:521px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VALVE CAP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:246px;top:429px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REGULATOR VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:140px;top:396px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TORQUE CONVERTER<br>CHECK VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:320px;top:301px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:153px;top:310px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SPRING SEAT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:195px;top:230px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:245px;top:268px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:353px;top:330px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:614px;top:107px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ACCUMULATOR COVER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:633px;top:175px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>1ST ACCUMULATOR PISTON<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:95px;top:113px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REGULATOR<br>SPRING CAP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:352px;top:189px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>STOP BOLT<br>6 x 1.0 mm<br>12 N·m (1.2 kgf·m,<br>8.7 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:618px;top:72px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BAFFLE PLATE<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}