with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:742px;\" coordsize=\"950,742\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:742px;\">");
write("<img id=\"img1\" src=\"../img/SEA6EJPE10410800000CAAD07.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:742px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:300px;top:19px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>3RD<br>CLUTCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:90px;top:80px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>TORQUE<br>CONVERTER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:126px;top:31px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>3RD CLUTCH<br>TRANSMISSION FLUID<br>PRESSURE<br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:222px;top:20px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>3RD<br>ACCUMULATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:365px;top:19px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>1ST<br>CLUTCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:410px;top:27px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>1ST<br>ACCUMULATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:456px;top:16px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>4TH<br>ACCUMULATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:538px;top:22px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>4TH<br>CLUTCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:588px;top:22px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>5TH<br>CLUTCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:631px;top:27px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>5TH<br>ACCUMULATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:676px;top:15px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>2ND<br>ACCUMULATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" class=\"drag\" style=\"position:absolute;left:755px;top:20px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>2ND<br>CLUTCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" class=\"drag\" style=\"position:absolute;left:826px;top:27px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>2ND CLUTCH<br>TRANSMISSION FLUID<br>PRESSURE<br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" class=\"drag\" style=\"position:absolute;left:868px;top:149px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>SHIFT<br>SOLENOID<br>VALVES<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" class=\"drag\" style=\"position:absolute;left:874px;top:193px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>A: OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" class=\"drag\" style=\"position:absolute;left:874px;top:236px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>B: OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" class=\"drag\" style=\"position:absolute;left:874px;top:279px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>C: ON<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" class=\"drag\" style=\"position:absolute;left:873px;top:322px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>D: OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" class=\"drag\" style=\"position:absolute;left:873px;top:365px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>E: OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" class=\"drag\" style=\"position:absolute;left:91px;top:339px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>LOCK-UP<br>SHIFT<br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" class=\"drag\" style=\"position:absolute;left:189px;top:409px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>SHIFT<br>VALVE<br>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" class=\"drag\" style=\"position:absolute;left:168px;top:555px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>LOCK-UP<br>CONTROL<br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" class=\"drag\" style=\"position:absolute;left:114px;top:652px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>RELIEF VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" class=\"drag\" style=\"position:absolute;left:57px;top:632px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>ATF<br>COOLER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" class=\"drag\" style=\"position:absolute;left:50px;top:558px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>COOLER<br>CHECK<br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" class=\"drag\" style=\"position:absolute;left:9px;top:481px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>TORQUE<br>CONVERTER<br>CHECK<br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" class=\"drag\" style=\"position:absolute;left:207px;top:680px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>REGULATOR VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" class=\"drag\" style=\"position:absolute;left:498px;top:682px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>ATF PUMP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" class=\"drag\" style=\"position:absolute;left:364px;top:628px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>SERVO VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" class=\"drag\" style=\"position:absolute;left:578px;top:557px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>MANUAL VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" class=\"drag\" style=\"position:absolute;left:763px;top:565px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>A/T CLUTCH PRESSURE<br>CONTROL SOLENOID VALVES<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" class=\"drag\" style=\"position:absolute;left:894px;top:429px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" class=\"drag\" style=\"position:absolute;left:888px;top:478px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" class=\"drag\" style=\"position:absolute;left:887px;top:526px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" class=\"drag\" style=\"position:absolute;left:596px;top:408px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>SHIFT<br>VALVE<br>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" class=\"drag\" style=\"position:absolute;left:615px;top:271px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>SHIFT VALVE E<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" class=\"drag\" style=\"position:absolute;left:662px;top:200px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>SERVO CONTROL VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" class=\"drag\" style=\"position:absolute;left:212px;top:226px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>SHIFT<br>VALVE<br>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" class=\"drag\" style=\"position:absolute;left:211px;top:271px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>SHIFT<br>VALVE<br>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" class=\"drag\" style=\"position:absolute;left:300px;top:545px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>IDLER<br>SHAFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" class=\"drag\" style=\"position:absolute;left:300px;top:558px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>IDLER GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" class=\"drag\" style=\"position:absolute;left:300px;top:568px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>MAINSHAFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" class=\"drag\" style=\"position:absolute;left:300px;top:578px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>COUNTERSHAFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" class=\"drag\" style=\"position:absolute;left:300px;top:585px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>FINAL DRIVE<br>GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" class=\"drag\" style=\"position:absolute;left:300px;top:597px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>SECONDARY<br>SHAFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" class=\"drag\" style=\"position:absolute;left:88px;top:264px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>94<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" class=\"drag\" style=\"position:absolute;left:138px;top:265px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>90<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" class=\"drag\" style=\"position:absolute;left:161px;top:224px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>91<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" class=\"drag\" style=\"position:absolute;left:69px;top:392px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" class=\"drag\" style=\"position:absolute;left:61px;top:426px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" class=\"drag\" style=\"position:absolute;left:76px;top:426px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>55<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" class=\"drag\" style=\"position:absolute;left:101px;top:426px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>96<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" class=\"drag\" style=\"position:absolute;left:119px;top:426px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>92<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" class=\"drag\" style=\"position:absolute;left:143px;top:426px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>93<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" class=\"drag\" style=\"position:absolute;left:158px;top:426px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>SE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" class=\"drag\" style=\"position:absolute;left:131px;top:395px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>91<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" class=\"drag\" style=\"position:absolute;left:110px;top:395px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>94<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" class=\"drag\" style=\"position:absolute;left:84px;top:395px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>55'<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" class=\"drag\" style=\"position:absolute;left:202px;top:508px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>97<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" class=\"drag\" style=\"position:absolute;left:186px;top:508px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>55<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" class=\"drag\" style=\"position:absolute;left:163px;top:508px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>96<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" class=\"drag\" style=\"position:absolute;left:136px;top:508px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>90<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" class=\"drag\" style=\"position:absolute;left:91px;top:511px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>90<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" class=\"drag\" style=\"position:absolute;left:114px;top:542px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" class=\"drag\" style=\"position:absolute;left:129px;top:540px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>93<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" class=\"drag\" style=\"position:absolute;left:149px;top:546px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" class=\"drag\" style=\"position:absolute;left:172px;top:539px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>92<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" class=\"drag\" style=\"position:absolute;left:74px;top:511px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>90<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" class=\"drag\" style=\"position:absolute;left:30px;top:543px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" class=\"drag\" style=\"position:absolute;left:62px;top:540px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>93<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" class=\"drag\" style=\"position:absolute;left:98px;top:548px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" class=\"drag\" style=\"position:absolute;left:118px;top:581px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>93<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" class=\"drag\" style=\"position:absolute;left:144px;top:606px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>95<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" class=\"drag\" style=\"position:absolute;left:179px;top:607px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" class=\"drag\" style=\"position:absolute;left:123px;top:640px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" class=\"drag\" style=\"position:absolute;left:142px;top:637px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" class=\"drag\" style=\"position:absolute;left:148px;top:668px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>99<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" class=\"drag\" style=\"position:absolute;left:228px;top:620px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>92<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" class=\"drag\" style=\"position:absolute;left:251px;top:620px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>95<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" class=\"drag\" style=\"position:absolute;left:212px;top:665px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" class=\"drag\" style=\"position:absolute;left:239px;top:661px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" class=\"drag\" style=\"position:absolute;left:299px;top:506px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>AX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" class=\"drag\" style=\"position:absolute;left:292px;top:520px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>HX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" class=\"drag\" style=\"position:absolute;left:300px;top:527px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>AX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" class=\"drag\" style=\"position:absolute;left:300px;top:537px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>HX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" class=\"drag\" style=\"position:absolute;left:356px;top:586px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>3'<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" class=\"drag\" style=\"position:absolute;left:382px;top:563px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>4'<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" class=\"drag\" style=\"position:absolute;left:409px;top:563px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>4''<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" class=\"drag\" style=\"position:absolute;left:416px;top:569px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" class=\"drag\" style=\"position:absolute;left:436px;top:573px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>3B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" class=\"drag\" style=\"position:absolute;left:450px;top:573px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>3A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" class=\"drag\" style=\"position:absolute;left:504px;top:490px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" class=\"drag\" style=\"position:absolute;left:525px;top:490px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" class=\"drag\" style=\"position:absolute;left:485px;top:490px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>5A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" class=\"drag\" style=\"position:absolute;left:456px;top:490px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>5A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" class=\"drag\" style=\"position:absolute;left:435px;top:490px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>1B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" class=\"drag\" style=\"position:absolute;left:414px;top:519px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>3A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" class=\"drag\" style=\"position:absolute;left:400px;top:522px;font-weight:normal;font-size:3.8pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" class=\"drag\" style=\"position:absolute;left:392px;top:533px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>3A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" class=\"drag\" style=\"position:absolute;left:588px;top:492px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" class=\"drag\" style=\"position:absolute;left:557px;top:519px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" class=\"drag\" style=\"position:absolute;left:481px;top:405px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>SD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" class=\"drag\" style=\"position:absolute;left:508px;top:405px;font-weight:normal;font-size:3.8pt;\">");
write("<nobr><b>5L<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" class=\"drag\" style=\"position:absolute;left:526px;top:405px;font-weight:normal;font-size:3.8pt;\">");
write("<nobr><b>5J<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" class=\"drag\" style=\"position:absolute;left:551px;top:405px;font-weight:normal;font-size:3.8pt;\">");
write("<nobr><b>1A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" class=\"drag\" style=\"position:absolute;left:574px;top:402px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>55'<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" class=\"drag\" style=\"position:absolute;left:583px;top:435px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" class=\"drag\" style=\"position:absolute;left:557px;top:433px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" class=\"drag\" style=\"position:absolute;left:543px;top:434px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" class=\"drag\" style=\"position:absolute;left:531px;top:434px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>57<br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" class=\"drag\" style=\"position:absolute;left:508px;top:434px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" class=\"drag\" style=\"position:absolute;left:553px;top:317px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>SE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" class=\"drag\" style=\"position:absolute;left:581px;top:319px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" class=\"drag\" style=\"position:absolute;left:588px;top:317px;font-weight:normal;font-size:4.7pt;\">");
write("<nobr><b>3B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" class=\"drag\" style=\"position:absolute;left:607px;top:317px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>3'<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" class=\"drag\" style=\"position:absolute;left:630px;top:318px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" class=\"drag\" style=\"position:absolute;left:644px;top:318px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" class=\"drag\" style=\"position:absolute;left:606px;top:286px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p1_119\" class=\"drag\" style=\"position:absolute;left:595px;top:280px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>3C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_120\" class=\"drag\" style=\"position:absolute;left:629px;top:183px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_121\" class=\"drag\" style=\"position:absolute;left:646px;top:217px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_122\" class=\"drag\" style=\"position:absolute;left:619px;top:217px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_123\" class=\"drag\" style=\"position:absolute;left:609px;top:217px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>4'<br></b></nobr>");
write("</p>");
write("<p id=\"p1_124\" class=\"drag\" style=\"position:absolute;left:594px;top:216px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p1_125\" class=\"drag\" style=\"position:absolute;left:568px;top:216px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>57<br></b></nobr>");
write("</p>");
write("<p id=\"p1_126\" class=\"drag\" style=\"position:absolute;left:266px;top:435px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p1_127\" class=\"drag\" style=\"position:absolute;left:275px;top:435px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p1_128\" class=\"drag\" style=\"position:absolute;left:315px;top:433px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>1B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_129\" class=\"drag\" style=\"position:absolute;left:327px;top:435px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p1_130\" class=\"drag\" style=\"position:absolute;left:365px;top:405px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>SA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_131\" class=\"drag\" style=\"position:absolute;left:350px;top:405px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>5F<br></b></nobr>");
write("</p>");
write("<p id=\"p1_132\" class=\"drag\" style=\"position:absolute;left:324px;top:405px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>55'<br></b></nobr>");
write("</p>");
write("<p id=\"p1_133\" class=\"drag\" style=\"position:absolute;left:306px;top:405px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>1A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_134\" class=\"drag\" style=\"position:absolute;left:275px;top:405px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>30<br></b></nobr>");
write("</p>");
write("<p id=\"p1_135\" class=\"drag\" style=\"position:absolute;left:262px;top:405px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>50<br></b></nobr>");
write("</p>");
write("<p id=\"p1_136\" class=\"drag\" style=\"position:absolute;left:240px;top:406px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>5N<br></b></nobr>");
write("</p>");
write("<p id=\"p1_137\" class=\"drag\" style=\"position:absolute;left:233px;top:401px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p1_138\" class=\"drag\" style=\"position:absolute;left:297px;top:382px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>5K<br></b></nobr>");
write("</p>");
write("<p id=\"p1_139\" class=\"drag\" style=\"position:absolute;left:324px;top:382px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_140\" class=\"drag\" style=\"position:absolute;left:263px;top:355px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>5K<br></b></nobr>");
write("</p>");
write("<p id=\"p1_141\" class=\"drag\" style=\"position:absolute;left:228px;top:333px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p1_142\" class=\"drag\" style=\"position:absolute;left:237px;top:331px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>5N<br></b></nobr>");
write("</p>");
write("<p id=\"p1_143\" class=\"drag\" style=\"position:absolute;left:263px;top:331px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>5L<br></b></nobr>");
write("</p>");
write("<p id=\"p1_144\" class=\"drag\" style=\"position:absolute;left:289px;top:331px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>5J<br></b></nobr>");
write("</p>");
write("<p id=\"p1_145\" class=\"drag\" style=\"position:absolute;left:306px;top:342px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_146\" class=\"drag\" style=\"position:absolute;left:310px;top:332px;font-weight:normal;font-size:4.4pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p1_147\" class=\"drag\" style=\"position:absolute;left:332px;top:331px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>40<br></b></nobr>");
write("</p>");
write("<p id=\"p1_148\" class=\"drag\" style=\"position:absolute;left:359px;top:331px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>5F<br></b></nobr>");
write("</p>");
write("<p id=\"p1_149\" class=\"drag\" style=\"position:absolute;left:240px;top:299px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p1_150\" class=\"drag\" style=\"position:absolute;left:272px;top:300px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>5H<br></b></nobr>");
write("</p>");
write("<p id=\"p1_151\" class=\"drag\" style=\"position:absolute;left:298px;top:300px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>5B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_152\" class=\"drag\" style=\"position:absolute;left:316px;top:276px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>5G<br></b></nobr>");
write("</p>");
write("<p id=\"p1_153\" class=\"drag\" style=\"position:absolute;left:324px;top:300px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>3C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_154\" class=\"drag\" style=\"position:absolute;left:350px;top:300px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>5E<br></b></nobr>");
write("</p>");
write("<p id=\"p1_155\" class=\"drag\" style=\"position:absolute;left:368px;top:300px;font-weight:normal;font-size:4.1pt;\">");
write("<nobr><b>5C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_156\" class=\"drag\" style=\"position:absolute;left:382px;top:300px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>SB<br></b></nobr>");
write("</p>");
write("<p id=\"p1_157\" class=\"drag\" style=\"position:absolute;left:234px;top:179px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p1_158\" class=\"drag\" style=\"position:absolute;left:266px;top:179px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p1_159\" class=\"drag\" style=\"position:absolute;left:275px;top:179px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p1_160\" class=\"drag\" style=\"position:absolute;left:293px;top:179px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>5A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_161\" class=\"drag\" style=\"position:absolute;left:309px;top:179px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p1_162\" class=\"drag\" style=\"position:absolute;left:318px;top:179px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p1_163\" class=\"drag\" style=\"position:absolute;left:327px;top:179px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>56<br></b></nobr>");
write("</p>");
write("<p id=\"p1_164\" class=\"drag\" style=\"position:absolute;left:344px;top:179px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>5E<br></b></nobr>");
write("</p>");
write("<p id=\"p1_165\" class=\"drag\" style=\"position:absolute;left:237px;top:211px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>57<br></b></nobr>");
write("</p>");
write("<p id=\"p1_166\" class=\"drag\" style=\"position:absolute;left:263px;top:211px;font-weight:normal;font-size:4.0pt;\">");
write("<nobr><b>5H<br></b></nobr>");
write("</p>");
write("<p id=\"p1_167\" class=\"drag\" style=\"position:absolute;left:275px;top:211px;font-weight:normal;font-size:4.0pt;\">");
write("<nobr><b>5C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_168\" class=\"drag\" style=\"position:absolute;left:307px;top:211px;font-weight:normal;font-size:4.0pt;\">");
write("<nobr><b>5B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_169\" class=\"drag\" style=\"position:absolute;left:319px;top:211px;font-weight:normal;font-size:4.0pt;\">");
write("<nobr><b>5G<br></b></nobr>");
write("</p>");
write("<p id=\"p1_170\" class=\"drag\" style=\"position:absolute;left:359px;top:212px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_171\" class=\"drag\" style=\"position:absolute;left:373px;top:212px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>SC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_172\" class=\"drag\" style=\"position:absolute;left:210px;top:129px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>30<br></b></nobr>");
write("</p>");
write("<p id=\"p1_173\" class=\"drag\" style=\"position:absolute;left:268px;top:111px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>30<br></b></nobr>");
write("</p>");
write("<p id=\"p1_174\" class=\"drag\" style=\"position:absolute;left:316px;top:111px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>95<br></b></nobr>");
write("</p>");
write("<p id=\"p1_175\" class=\"drag\" style=\"position:absolute;left:328px;top:101px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>30<br></b></nobr>");
write("</p>");
write("<p id=\"p1_176\" class=\"drag\" style=\"position:absolute;left:360px;top:101px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_177\" class=\"drag\" style=\"position:absolute;left:379px;top:109px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>95<br></b></nobr>");
write("</p>");
write("<p id=\"p1_178\" class=\"drag\" style=\"position:absolute;left:424px;top:110px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_179\" class=\"drag\" style=\"position:absolute;left:491px;top:111px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>40<br></b></nobr>");
write("</p>");
write("<p id=\"p1_180\" class=\"drag\" style=\"position:absolute;left:558px;top:102px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>40<br></b></nobr>");
write("</p>");
write("<p id=\"p1_181\" class=\"drag\" style=\"position:absolute;left:599px;top:103px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>50<br></b></nobr>");
write("</p>");
write("<p id=\"p1_182\" class=\"drag\" style=\"position:absolute;left:647px;top:110px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>50<br></b></nobr>");
write("</p>");
write("<p id=\"p1_183\" class=\"drag\" style=\"position:absolute;left:720px;top:111px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_184\" class=\"drag\" style=\"position:absolute;left:778px;top:113px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>95<br></b></nobr>");
write("</p>");
write("<p id=\"p1_185\" class=\"drag\" style=\"position:absolute;left:803px;top:104px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_186\" class=\"drag\" style=\"position:absolute;left:849px;top:131px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_187\" class=\"drag\" style=\"position:absolute;left:848px;top:177px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>SA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_188\" class=\"drag\" style=\"position:absolute;left:817px;top:294px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_189\" class=\"drag\" style=\"position:absolute;left:848px;top:338px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>SD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_190\" class=\"drag\" style=\"position:absolute;left:848px;top:351px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>SE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_191\" class=\"drag\" style=\"position:absolute;left:861px;top:386px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p1_192\" class=\"drag\" style=\"position:absolute;left:818px;top:382px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_193\" class=\"drag\" style=\"position:absolute;left:831px;top:412px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>55<br></b></nobr>");
write("</p>");
write("<p id=\"p1_194\" class=\"drag\" style=\"position:absolute;left:781px;top:435px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p1_195\" class=\"drag\" style=\"position:absolute;left:817px;top:448px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_196\" class=\"drag\" style=\"position:absolute;left:837px;top:449px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p1_197\" class=\"drag\" style=\"position:absolute;left:847px;top:449px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>AX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_198\" class=\"drag\" style=\"position:absolute;left:825px;top:460px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>56<br></b></nobr>");
write("</p>");
write("<p id=\"p1_199\" class=\"drag\" style=\"position:absolute;left:776px;top:483px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p1_200\" class=\"drag\" style=\"position:absolute;left:831px;top:497px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p1_201\" class=\"drag\" style=\"position:absolute;left:841px;top:497px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>AX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_202\" class=\"drag\" style=\"position:absolute;left:812px;top:497px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>4''<br></b></nobr>");
write("</p>");
write("<p id=\"p1_203\" class=\"drag\" style=\"position:absolute;left:825px;top:509px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>57<br></b></nobr>");
write("</p>");
write("<p id=\"p1_204\" class=\"drag\" style=\"position:absolute;left:776px;top:532px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p1_205\" class=\"drag\" style=\"position:absolute;left:831px;top:546px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p1_206\" class=\"drag\" style=\"position:absolute;left:841px;top:546px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>AX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_207\" class=\"drag\" style=\"position:absolute;left:812px;top:546px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_208\" class=\"drag\" style=\"position:absolute;left:848px;top:251px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>SB<br></b></nobr>");
write("</p>");
write("<p id=\"p1_209\" class=\"drag\" style=\"position:absolute;left:848px;top:265px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>SC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_210\" class=\"drag\" style=\"position:absolute;left:817px;top:208px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_211\" class=\"drag\" style=\"position:absolute;left:861px;top:343px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p1_212\" class=\"drag\" style=\"position:absolute;left:860px;top:300px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p1_213\" class=\"drag\" style=\"position:absolute;left:861px;top:214px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p1_214\" class=\"drag\" style=\"position:absolute;left:861px;top:257px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}