with(document) {
write("<v:group id=\"group3\" class=\"drag\" style=\"position:relative; width:950px; height:1094px;\" coordsize=\"950,1094\">");
write("<v:rect id=\"rect3\"class=\"drag\"  style=\"width:950px;height:1094px;\">");
write("<img id=\"img3\" src=\"../img/SEA6EL3J54260400000EAAD03.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1094px;border-color:#ffffff\">");
write("<p id=\"p3_1\" class=\"drag\" style=\"position:absolute;left:168px;top:104px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p3_2\" class=\"drag\" style=\"position:absolute;left:192px;top:43px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNDER−HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_3\" class=\"drag\" style=\"position:absolute;left:320px;top:845px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.1 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_4\" class=\"drag\" style=\"position:absolute;left:494px;top:860px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_5\" class=\"drag\" style=\"position:absolute;left:693px;top:860px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left headlights (low beam)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_6\" class=\"drag\" style=\"position:absolute;left:320px;top:888px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.6 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_7\" class=\"drag\" style=\"position:absolute;left:492px;top:903px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_8\" class=\"drag\" style=\"position:absolute;left:693px;top:903px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right headlights (low beam)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_9\" class=\"drag\" style=\"position:absolute;left:320px;top:973px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.5 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_10\" class=\"drag\" style=\"position:absolute;left:320px;top:931px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.3 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_11\" class=\"drag\" style=\"position:absolute;left:491px;top:988px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_12\" class=\"drag\" style=\"position:absolute;left:493px;top:945px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_13\" class=\"drag\" style=\"position:absolute;left:223px;top:618px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>CONTROL BLOCK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_14\" class=\"drag\" style=\"position:absolute;left:693px;top:989px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right headlights (high beam)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_15\" class=\"drag\" style=\"position:absolute;left:693px;top:946px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left headlights (high beam)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_16\" class=\"drag\" style=\"position:absolute;left:283px;top:733px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>d<br></b></nobr>");
write("</p>");
write("<p id=\"p3_17\" class=\"drag\" style=\"position:absolute;left:168px;top:975px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p3_18\" class=\"drag\" style=\"position:absolute;left:721px;top:28px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>* : Without security alarm system<br></b></nobr>");
write("</p>");
write("<p id=\"p3_19\" class=\"drag\" style=\"position:absolute;left:493px;top:281px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_20\" class=\"drag\" style=\"position:absolute;left:693px;top:282px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Low horn*<br></b></nobr>");
write("</p>");
write("<p id=\"p3_21\" class=\"drag\" style=\"position:absolute;left:693px;top:310px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>High horn*<br></b></nobr>");
write("</p>");
write("<p id=\"p3_22\" class=\"drag\" style=\"position:absolute;left:493px;top:310px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_23\" class=\"drag\" style=\"position:absolute;left:693px;top:610px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>VSA OFF switch light<br></b></nobr>");
write("</p>");
write("<p id=\"p3_24\" class=\"drag\" style=\"position:absolute;left:693px;top:596px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Sunroof switch light<br></b></nobr>");
write("</p>");
write("<p id=\"p3_25\" class=\"drag\" style=\"position:absolute;left:494px;top:424px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_26\" class=\"drag\" style=\"position:absolute;left:693px;top:425px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left parking lights<br></b></nobr>");
write("</p>");
write("<p id=\"p3_27\" class=\"drag\" style=\"position:absolute;left:693px;top:439px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right parking lights<br></b></nobr>");
write("</p>");
write("<p id=\"p3_28\" class=\"drag\" style=\"position:absolute;left:693px;top:453px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left taillights<br></b></nobr>");
write("</p>");
write("<p id=\"p3_29\" class=\"drag\" style=\"position:absolute;left:693px;top:468px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right taillights<br></b></nobr>");
write("</p>");
write("<p id=\"p3_30\" class=\"drag\" style=\"position:absolute;left:693px;top:482px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>License plate light(s)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_31\" class=\"drag\" style=\"position:absolute;left:693px;top:496px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>A/T gear position console light<br></b></nobr>");
write("</p>");
write("<p id=\"p3_32\" class=\"drag\" style=\"position:absolute;left:693px;top:525px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Audio−HVAC−display module<br></b></nobr>");
write("</p>");
write("<p id=\"p3_33\" class=\"drag\" style=\"position:absolute;left:693px;top:510px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Ashtray light<br></b></nobr>");
write("</p>");
write("<p id=\"p3_34\" class=\"drag\" style=\"position:absolute;left:693px;top:568px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Hazard warning switch light<br></b></nobr>");
write("</p>");
write("<p id=\"p3_35\" class=\"drag\" style=\"position:absolute;left:693px;top:582px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Headlight adjuster switch light<br></b></nobr>");
write("</p>");
write("<p id=\"p3_36\" class=\"drag\" style=\"position:absolute;left:693px;top:553px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Glove box light<br></b></nobr>");
write("</p>");
write("<p id=\"p3_37\" class=\"drag\" style=\"position:absolute;left:693px;top:539px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Cigarette lighter light<br></b></nobr>");
write("</p>");
write("<p id=\"p3_38\" class=\"drag\" style=\"position:absolute;left:263px;top:299px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.4 (15 A) FUSE<br></b></nobr>");
write("</p>");
write("<p id=\"p3_39\" class=\"drag\" style=\"position:absolute;left:297px;top:318px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>c<br></b></nobr>");
write("</p>");
write("<p id=\"p3_40\" class=\"drag\" style=\"position:absolute;left:219px;top:733px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>b<br></b></nobr>");
write("</p>");
write("<p id=\"p3_41\" class=\"drag\" style=\"position:absolute;left:213px;top:128px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RELAY CONTROL MODULE<br></b></nobr>");
write("</p>");
write("<p id=\"p3_42\" class=\"drag\" style=\"position:absolute;left:276px;top:175px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>a<br></b></nobr>");
write("</p>");
write("<p id=\"p3_43\" class=\"drag\" style=\"position:absolute;left:238px;top:156px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.13 (20 A) FUSE<br></b></nobr>");
write("</p>");
write("<p id=\"p3_44\" class=\"drag\" style=\"position:absolute;left:493px;top:338px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_45\" class=\"drag\" style=\"position:absolute;left:693px;top:339px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Security horn<br></b></nobr>");
write("</p>");
write("<p id=\"p3_46\" class=\"drag\" style=\"position:absolute;left:693px;top:625px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Driver's seat heater switch light<br></b></nobr>");
write("</p>");
write("<p id=\"p3_47\" class=\"drag\" style=\"position:absolute;left:693px;top:639px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Passenger's seat heater swtich light<br></b></nobr>");
write("</p>");
write("<p id=\"p3_48\" class=\"drag\" style=\"position:absolute;left:693px;top:653px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Navigation unit illumination<br></b></nobr>");
write("</p>");
write("<p id=\"p3_49\" class=\"drag\" style=\"position:absolute;left:80px;top:540px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p3_50\" class=\"drag\" style=\"position:absolute;left:76px;top:589px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_51\" class=\"drag\" style=\"position:absolute;left:297px;top:680px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(30 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_52\" class=\"drag\" style=\"position:absolute;left:297px;top:669px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_53\" class=\"drag\" style=\"position:absolute;left:693px;top:682px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Cruise control switch light<br></b></nobr>");
write("</p>");
write("<p id=\"p3_54\" class=\"drag\" style=\"position:absolute;left:693px;top:668px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Radio remote switch light<br></b></nobr>");
write("</p>");
write("<p id=\"p3_55\" class=\"drag\" style=\"position:absolute;left:693px;top:696px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Navigation remote switch light<br></b></nobr>");
write("</p>");
write("<p id=\"p3_56\" class=\"drag\" style=\"position:absolute;left:265px;top:749px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>REAR <br>WINDOW <br>DEFOGGER <br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_57\" class=\"drag\" style=\"position:absolute;left:196px;top:749px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.7 (7.5 A) <br>FUSE<br></b></nobr>");
write("</p>");
write("<p id=\"p3_58\" class=\"drag\" style=\"position:absolute;left:49px;top:497px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.21 (7.5 A) <br>UNDER−DASH <br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}