with(document) {
write("<v:group id=\"group8\" class=\"drag\" style=\"position:relative; width:950px; height:1063px;\" coordsize=\"950,1063\">");
write("<v:rect id=\"rect8\"class=\"drag\"  style=\"width:950px;height:1063px;\">");
write("<img id=\"img8\" src=\"../img/SEA6EJ3J54230100000EAAD08.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1063px;border-color:#ffffff\">");
write("<p id=\"p8_1\" class=\"drag\" style=\"position:absolute;left:345px;top:976px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Passenger's door wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p8_2\" class=\"drag\" style=\"position:absolute;left:338px;top:975px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p8_3\" class=\"drag\" style=\"position:absolute;left:319px;top:976px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>M<br></b></nobr>");
write("</p>");
write("<p id=\"p8_4\" class=\"drag\" style=\"position:absolute;left:70px;top:976px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p8_5\" class=\"drag\" style=\"position:absolute;left:88px;top:975px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p8_6\" class=\"drag\" style=\"position:absolute;left:95px;top:976px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Engine compartment wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p8_7\" class=\"drag\" style=\"position:absolute;left:312px;top:526px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p8_8\" class=\"drag\" style=\"position:absolute;left:284px;top:525px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_9\" class=\"drag\" style=\"position:absolute;left:423px;top:507px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ECM/PCM<br></b></nobr>");
write("</p>");
write("<p id=\"p8_10\" class=\"drag\" style=\"position:absolute;left:439px;top:562px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_11\" class=\"drag\" style=\"position:absolute;left:470px;top:562px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p8_12\" class=\"drag\" style=\"position:absolute;left:604px;top:526px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_13\" class=\"drag\" style=\"position:absolute;left:634px;top:526px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p8_14\" class=\"drag\" style=\"position:absolute;left:634px;top:490px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p8_15\" class=\"drag\" style=\"position:absolute;left:602px;top:490px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p8_16\" class=\"drag\" style=\"position:absolute;left:470px;top:669px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p8_17\" class=\"drag\" style=\"position:absolute;left:439px;top:669px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_18\" class=\"drag\" style=\"position:absolute;left:470px;top:783px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p8_19\" class=\"drag\" style=\"position:absolute;left:439px;top:783px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_20\" class=\"drag\" style=\"position:absolute;left:406px;top:440px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_21\" class=\"drag\" style=\"position:absolute;left:434px;top:440px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p8_22\" class=\"drag\" style=\"position:absolute;left:724px;top:441px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Navigation subdisplay unit<br></b></nobr>");
write("</p>");
write("<p id=\"p8_23\" class=\"drag\" style=\"position:absolute;left:406px;top:404px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_24\" class=\"drag\" style=\"position:absolute;left:434px;top:404px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p8_25\" class=\"drag\" style=\"position:absolute;left:724px;top:405px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Headlight washer unit<br></b></nobr>");
write("</p>");
write("<p id=\"p8_26\" class=\"drag\" style=\"position:absolute;left:724px;top:369px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Navigation display<br></b></nobr>");
write("</p>");
write("<p id=\"p8_27\" class=\"drag\" style=\"position:absolute;left:434px;top:369px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p8_28\" class=\"drag\" style=\"position:absolute;left:406px;top:369px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_29\" class=\"drag\" style=\"position:absolute;left:724px;top:326px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Gauge control module<br></b></nobr>");
write("</p>");
write("<p id=\"p8_30\" class=\"drag\" style=\"position:absolute;left:506px;top:326px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_31\" class=\"drag\" style=\"position:absolute;left:534px;top:326px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p8_32\" class=\"drag\" style=\"position:absolute;left:724px;top:298px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Glove box light<br></b></nobr>");
write("</p>");
write("<p id=\"p8_33\" class=\"drag\" style=\"position:absolute;left:731px;top:269px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>A/T lever (A/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_34\" class=\"drag\" style=\"position:absolute;left:724px;top:233px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Memory erase signal (MES) connector<br></b></nobr>");
write("</p>");
write("<p id=\"p8_35\" class=\"drag\" style=\"position:absolute;left:534px;top:297px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p8_36\" class=\"drag\" style=\"position:absolute;left:506px;top:297px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_37\" class=\"drag\" style=\"position:absolute;left:534px;top:261px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p8_38\" class=\"drag\" style=\"position:absolute;left:506px;top:261px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_39\" class=\"drag\" style=\"position:absolute;left:534px;top:233px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p8_40\" class=\"drag\" style=\"position:absolute;left:506px;top:233px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_41\" class=\"drag\" style=\"position:absolute;left:724px;top:205px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Climate control unit/heater control panel<br></b></nobr>");
write("</p>");
write("<p id=\"p8_42\" class=\"drag\" style=\"position:absolute;left:506px;top:204px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_43\" class=\"drag\" style=\"position:absolute;left:534px;top:204px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p8_44\" class=\"drag\" style=\"position:absolute;left:274px;top:239px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Junction<br></b></nobr>");
write("</p>");
write("<p id=\"p8_45\" class=\"drag\" style=\"position:absolute;left:274px;top:250px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>connector<br></b></nobr>");
write("</p>");
write("<p id=\"p8_46\" class=\"drag\" style=\"position:absolute;left:724px;top:141px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Data link connector (DLC)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_47\" class=\"drag\" style=\"position:absolute;left:534px;top:140px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p8_48\" class=\"drag\" style=\"position:absolute;left:506px;top:140px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_49\" class=\"drag\" style=\"position:absolute;left:284px;top:140px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_50\" class=\"drag\" style=\"position:absolute;left:312px;top:140px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p8_51\" class=\"drag\" style=\"position:absolute;left:724px;top:112px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Passenger's door lock knob switch<br></b></nobr>");
write("</p>");
write("<p id=\"p8_52\" class=\"drag\" style=\"position:absolute;left:724px;top:98px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right power mirror (with heater mirror)<br></b></nobr>");
write("</p>");
write("<p id=\"p8_53\" class=\"drag\" style=\"position:absolute;left:724px;top:83px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right power mirror<br></b></nobr>");
write("</p>");
write("<p id=\"p8_54\" class=\"drag\" style=\"position:absolute;left:724px;top:69px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Passenger's power window switch<br></b></nobr>");
write("</p>");
write("<p id=\"p8_55\" class=\"drag\" style=\"position:absolute;left:506px;top:68px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_56\" class=\"drag\" style=\"position:absolute;left:534px;top:68px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>M<br></b></nobr>");
write("</p>");
write("<p id=\"p8_57\" class=\"drag\" style=\"position:absolute;left:312px;top:68px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p8_58\" class=\"drag\" style=\"position:absolute;left:284px;top:68px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_59\" class=\"drag\" style=\"position:absolute;left:54px;top:926px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G503<br></b></nobr>");
write("</p>");
write("<p id=\"p8_60\" class=\"drag\" style=\"position:absolute;left:724px;top:26px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Power transistor<br></b></nobr>");
write("</p>");
write("<p id=\"p8_61\" class=\"drag\" style=\"position:absolute;left:406px;top:26px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p8_62\" class=\"drag\" style=\"position:absolute;left:434px;top:26px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p8_63\" class=\"drag\" style=\"position:absolute;left:95px;top:1005px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Dashboard wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p8_64\" class=\"drag\" style=\"position:absolute;left:88px;top:1003px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p8_65\" class=\"drag\" style=\"position:absolute;left:69px;top:1005px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p8_66\" class=\"drag\" style=\"position:absolute;left:604px;top:862px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_67\" class=\"drag\" style=\"position:absolute;left:635px;top:862px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p8_68\" class=\"drag\" style=\"position:absolute;left:635px;top:826px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p8_69\" class=\"drag\" style=\"position:absolute;left:602px;top:826px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p8_70\" class=\"drag\" style=\"position:absolute;left:635px;top:898px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p8_71\" class=\"drag\" style=\"position:absolute;left:604px;top:897px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_72\" class=\"drag\" style=\"position:absolute;left:439px;top:897px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p8_73\" class=\"drag\" style=\"position:absolute;left:470px;top:897px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p8_74\" class=\"drag\" style=\"position:absolute;left:438px;top:826px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p8_75\" class=\"drag\" style=\"position:absolute;left:470px;top:826px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p8_76\" class=\"drag\" style=\"position:absolute;left:470px;top:862px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p8_77\" class=\"drag\" style=\"position:absolute;left:439px;top:862px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_78\" class=\"drag\" style=\"position:absolute;left:738px;top:843px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>VSA unit<br></b></nobr>");
write("</p>");
write("<p id=\"p8_79\" class=\"drag\" style=\"position:absolute;left:738px;top:729px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ECM/PCM<br></b></nobr>");
write("</p>");
write("<p id=\"p8_80\" class=\"drag\" style=\"position:absolute;left:604px;top:747px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_81\" class=\"drag\" style=\"position:absolute;left:634px;top:747px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p8_82\" class=\"drag\" style=\"position:absolute;left:634px;top:712px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p8_83\" class=\"drag\" style=\"position:absolute;left:602px;top:712px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p8_84\" class=\"drag\" style=\"position:absolute;left:602px;top:597px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p8_85\" class=\"drag\" style=\"position:absolute;left:634px;top:597px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p8_86\" class=\"drag\" style=\"position:absolute;left:634px;top:633px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p8_87\" class=\"drag\" style=\"position:absolute;left:604px;top:633px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p8_88\" class=\"drag\" style=\"position:absolute;left:402px;top:1005px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>: Shielding<br></b></nobr>");
write("</p>");
write("<p id=\"p8_89\" class=\"drag\" style=\"position:absolute;left:738px;top:495px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Gauge <br>control <br>module<br></b></nobr>");
write("</p>");
write("<p id=\"p8_90\" class=\"drag\" style=\"position:absolute;left:738px;top:602px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Gauge <br>control <br>module<br></b></nobr>");
write("</p>");
write("<p id=\"p8_91\" class=\"drag\" style=\"position:absolute;left:246px;top:682px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Junction <br>switch<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}