with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:950px; height:863px;\" coordsize=\"950,863\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:950px;height:863px;\">");
write("<img id=\"img1\" src=\"../img/SEA6EL3A18223800000KCAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:863px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:599px;top:17px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR MOUNT<br>BRACKET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:235px;top:41px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ENGINE MOUNT<br>BRACKET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:587px;top:565px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT MOUNT<br>BRACKET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:202px;top:562px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A/C COMPRESSOR<br>BRACKET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:415px;top:32px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>12 x 1.25 mm<br>88 N·m <br>(9.0 kgf·m, 65 lbf·ft)<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:65px;top:261px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>10 x 1.25 mm<br>44 N·m <br>(4.5 kgf·m, 33 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:370px;top:802px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>10 x 1.25 mm<br>44 N·m <br>(4.5 kgf·m, 33 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:745px;top:772px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>12 x 1.25 mm<br>64 N·m <br>(6.5 kgf·m, 47 lbf·ft)<br></b>Replace.<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}