with(document) {
write("<v:group id=\"group1\" class=\"drag\" style=\"position:relative; width:475px; height:320px;\" coordsize=\"475,320\">");
write("<v:rect id=\"rect1\"class=\"drag\"  style=\"width:475px;height:320px;\">");
write("<img id=\"img1\" src=\"../img/SEA6EJ7J36200000000BBAD04.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:320px;border-color:#ffffff\">");
write("<p id=\"p1_1\" class=\"drag\" style=\"position:absolute;left:122px;top:64px;font-weight:normal;font-size:8.9pt;\">");
write("<nobr><b>Navi System Link<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" class=\"drag\" style=\"position:absolute;left:343px;top:64px;font-weight:normal;font-size:8.9pt;\">");
write("<nobr><b>Return<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" class=\"drag\" style=\"position:absolute;left:361px;top:105px;font-weight:normal;font-size:8.9pt;\">");
write("<nobr><b>O K<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" class=\"drag\" style=\"position:absolute;left:360px;top:236px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>Exit Diag<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" class=\"drag\" style=\"position:absolute;left:72px;top:193px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>Radio<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" class=\"drag\" style=\"position:absolute;left:67px;top:150px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>Display<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" class=\"drag\" style=\"position:absolute;left:280px;top:108px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>GPS Ant.<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" class=\"drag\" style=\"position:absolute;left:66px;top:108px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>Air-Con.<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" class=\"drag\" style=\"position:absolute;left:214px;top:108px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>Meter<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" class=\"drag\" style=\"position:absolute;left:153px;top:169px;font-weight:normal;font-size:8.9pt;\">");
write("<nobr><b>Navi.ECU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" class=\"drag\" style=\"position:absolute;left:142px;top:108px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>FI-ECU<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}